'use client'
import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,upload} from '@/lib/api'
import {Alert,ImagePicker,Loading,Switch} from '@/components/ui'
import SettingsNav from '@/components/settings-nav'
import PhoneInput from '@/components/phone-input'
import StoreThemePreview from '@/components/store-theme-preview'
import StoreDomainsSettings from '@/components/store-domains-settings'
import {FONT_OPTIONS,STORE_THEMES,freshThemeConfig,resolvedTheme,type StoreThemeConfig} from '@/lib/store-themes'
import {resolveBusinessCapabilities} from '@/lib/business-capabilities'
import {CheckCircle2,Code2,ExternalLink,Grid2X2,Image as ImageIcon,LayoutTemplate,Palette,Plus,RotateCcw,Save,Smartphone,Sparkles,Trash2,Type,Truck,UtensilsCrossed} from 'lucide-react'

const days=[['mon','Lunes'],['tue','Martes'],['wed','Miércoles'],['thu','Jueves'],['fri','Viernes'],['sat','Sábado'],['sun','Domingo']] as const
const defaultHours=Object.fromEntries(days.map(([k])=>[k,{enabled:k!=='sun',open:'08:00',close:'18:00'}]))
type Tab='general'|'design'|'sales'|'hours'|'domains'
type DesignTab='theme'|'colors'|'type'|'layout'|'products'|'background'|'advanced'

const PALETTES=[
 {id:'wamercio',name:'Verde negocio',detail:'Fresco y confiable',colors:{primary:'#36b385',secondary:'#82d6b7',accent:'#2e3154',background:'#f7f9fc',surface:'#ffffff',text:'#2e3154',muted:'#858aa7',border:'#e7eaf0',buttonText:'#ffffff'}},
 {id:'caribe',name:'Caribe',detail:'Azul y turquesa',colors:{primary:'#147d92',secondary:'#5fd0c2',accent:'#123a4a',background:'#f4fbfb',surface:'#ffffff',text:'#173747',muted:'#738994',border:'#dcebed',buttonText:'#ffffff'}},
 {id:'confianza',name:'Azul confianza',detail:'Formal y comercial',colors:{primary:'#3563e9',secondary:'#9ab4ff',accent:'#17223b',background:'#f4f7fc',surface:'#ffffff',text:'#17223b',muted:'#71809c',border:'#dde4ef',buttonText:'#ffffff'}},
 {id:'sabor',name:'Sabor',detail:'Comida y promociones',colors:{primary:'#e14a2b',secondary:'#f7b32b',accent:'#31211d',background:'#fff7f1',surface:'#ffffff',text:'#2b201d',muted:'#806e68',border:'#f1ded4',buttonText:'#ffffff'}},
 {id:'belleza',name:'Belleza',detail:'Suave y delicado',colors:{primary:'#c45f79',secondary:'#efc8d0',accent:'#74515b',background:'#fff8fa',surface:'#ffffff',text:'#3f3034',muted:'#927b81',border:'#f0dfe4',buttonText:'#ffffff'}},
 {id:'premium',name:'Premium',detail:'Negro y dorado',colors:{primary:'#171717',secondary:'#c4a15a',accent:'#8a6d35',background:'#f4f1e9',surface:'#fffdf8',text:'#1c1b18',muted:'#77736b',border:'#ddd7ca',buttonText:'#ffffff'}},
]

export default function StoreSettings(){
 const[store,setStore]=useState(''),[form,setForm]=useState<any>(null),[tab,setTab]=useState<Tab>('general'),[designTab,setDesignTab]=useState<DesignTab>('theme'),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[err,setErr]=useState(''),[ok,setOk]=useState(''),[up,setUp]=useState('')
 const[tables,setTables]=useState<any[]>([]),[newTable,setNewTable]=useState({name:'',capacity:4}),[tableBusy,setTableBusy]=useState(false)
 const capabilities=useMemo(()=>resolveBusinessCapabilities(form),[form])
 useEffect(()=>{if(typeof window==='undefined')return;const t=new URLSearchParams(window.location.search).get('tab');if(t==='general'||t==='design'||t==='sales'||t==='hours'||t==='domains')setTab(t)},[])
 useEffect(()=>{if(!store){setForm(null);setTables([]);return};setLoading(true);setErr('');Promise.all([api(`/stores/${store}/settings`),api<any[]>(`/tables?store_id=${store}`)]).then(([x,t])=>{const resolved=resolvedTheme(x.visual_theme,x.theme_config,x.primary_color).config;const caps=resolveBusinessCapabilities(x);setForm({...x,dine_in_enabled:caps.supportsDineIn?!!x.dine_in_enabled:false,visual_theme:x.visual_theme||'minimal-shop',theme_config:resolved,business_hours:{...defaultHours,...(x.business_hours||{})}});setTables(caps.supportsDineIn?(t||[]):[])}).catch((e:any)=>setErr(e.message)).finally(()=>setLoading(false))},[store])
 const reloadTables=async()=>{if(!store)return;setTables(await api<any[]>(`/tables?store_id=${store}`))}
 const addTable=async()=>{if(!newTable.name.trim())return;setTableBusy(true);setErr('');try{await api('/tables',{method:'POST',body:JSON.stringify({store_id:store,name:newTable.name.trim(),capacity:Number(newTable.capacity)||4})});setNewTable({name:'',capacity:4});await reloadTables()}catch(e:any){setErr(e.message)}finally{setTableBusy(false)}}
 const saveTable=async(t:any)=>{setTableBusy(true);setErr('');try{await api(`/tables/${t.id}`,{method:'PUT',body:JSON.stringify({store_id:store,name:t.name,capacity:Number(t.capacity)||1,sort_order:Number(t.sort_order)||100,is_active:t.is_active!==false})});await reloadTables()}catch(e:any){setErr(e.message)}finally{setTableBusy(false)}}
 const removeTable=async(t:any)=>{if(!confirm(`¿Archivar ${t.name}?`))return;setTableBusy(true);try{await api(`/tables/${t.id}`,{method:'DELETE'});await reloadTables()}catch(e:any){setErr(e.message)}finally{setTableBusy(false)}}
 const save=async()=>{if(!form)return;setSaving(true);setErr('');setOk('');try{const payload={...form,currency:form.currency||'DOP',primary_color:form.theme_config?.colors?.primary||form.primary_color||'#36b385',is_active:form.is_active!==false,accepting_orders:form.accepting_orders!==false};await api(`/stores/${store}/settings`,{method:'PUT',body:JSON.stringify(payload)});setForm((v:any)=>({...v,primary_color:payload.primary_color}));setOk('Cambios guardados correctamente.')}catch(e:any){setErr(e.message)}finally{setSaving(false)}}
 const pick=async(kind:'logo_url'|'banner_url',f:File)=>{setUp(kind);setErr('');try{const url=await upload(f);setForm((v:any)=>({...v,[kind]:url}))}catch(e:any){setErr(e.message)}finally{setUp('')}}
 const setThemeConfig=(path:string,value:any)=>setForm((v:any)=>{const cfg=JSON.parse(JSON.stringify(v.theme_config||{}));const parts=path.split('.');let o=cfg;parts.slice(0,-1).forEach(k=>{o[k]??={};o=o[k]});o[parts.at(-1)!]=value;const extra=path==='colors.primary'?{primary_color:value}:{};return{...v,theme_config:cfg,...extra}})
 const applyTheme=(id:string)=>{const cfg=freshThemeConfig(id);setForm((v:any)=>({...v,visual_theme:id,theme_config:cfg,primary_color:cfg.colors.primary}))}
 const applyPalette=(colors:any)=>setForm((v:any)=>{const cfg=JSON.parse(JSON.stringify(v.theme_config||freshThemeConfig(v.visual_theme||'minimal-shop')));cfg.colors={...cfg.colors,...colors};if(cfg.background?.type==='solid')cfg.background.value=colors.background;return{...v,theme_config:cfg,primary_color:colors.primary}})
 const cfg:StoreThemeConfig=form?.theme_config||freshThemeConfig('minimal-shop')
 const previewTip=useMemo(()=>tab==='design'?'Todo lo que cambies aquí se refleja al instante en la vista del celular.':tab==='general'?'Revisa cómo se verá tu nombre, logo y portada antes de guardar.':tab==='sales'?'Configura cómo recibes pedidos y realizas entregas sin cambiar la apariencia del catálogo.':tab==='domains'?'Publica tu tienda en su subdominio de ltd.do o conecta un dominio propio.':'Tus horarios controlan cuándo el cliente puede completar pedidos.',[tab])
 const designTabs:[DesignTab,string,any][]=[['theme','Diseños',Sparkles],['colors','Colores',Palette],['type','Letras',Type],['layout','Encabezado',LayoutTemplate],['products','Productos',Grid2X2],['background','Fondo',ImageIcon],['advanced','Avanzado',Code2]]
 const publicUrl=form?.public_url||`https://${form?.slug||'negocio'}.${process.env.NEXT_PUBLIC_TENANT_ROOT_DOMAIN||'ltd.do'}`
 return <StoreShell title="Configuración" subtitle="Configuración de los negocios del propietario" context={<StoreSelector value={store} onChange={setStore}/> }>
  {!store?<div className="card p-10 text-center text-sm text-[#8d92aa]">Selecciona un negocio para configurarlo.</div>:loading||!form?<Loading/>:<div className="grid gap-5 xl:grid-cols-[190px_minmax(0,1fr)_310px]">
   <SettingsNav active={tab} onSelect={setTab}/>
   <section className="card p-5 sm:p-7">{err&&<Alert text={err}/>} {ok&&<Alert text={ok} type="success"/>}
    {tab==='general'&&<div><p className="section-kicker">Datos del negocio</p><h2 className="section-title">Información que verá tu cliente</h2><p className="section-copy">Aquí van los datos básicos de tu comercio. El diseño se maneja aparte para que puedas cambiar la apariencia sin tocar tus productos.</p>
      <div className="mt-6 grid gap-6 lg:grid-cols-[220px_1fr]"><div className="space-y-4"><div><label className="label">Logo del negocio</label><ImagePicker value={form.logo_url} onPick={f=>pick('logo_url',f)} onClear={()=>setForm({...form,logo_url:''})} label="Subir logo" busy={up==='logo_url'}/></div><div className="rounded-2xl border border-[#edf0f4] bg-[#fbfcfd] p-4"><p className="text-sm font-semibold text-ink-900">Para que se vea bien</p><p className="mt-2 text-xs leading-5 text-[#9197ad]">Usa un logo cuadrado y sencillo. Si no tienes logo todavía, WAMERCIO mostrará un ícono limpio del negocio.</p></div></div><div className="space-y-4"><div><label className="label">Nombre del negocio *</label><input className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="label">WhatsApp del negocio</label><PhoneInput value={form.whatsapp||''} onChange={value=>setForm({...form,whatsapp:value})}/></div><div><label className="label">Dirección o referencia</label><input className="field" value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Ej.: Av. Duarte #10, Bonao"/></div><div><label className="label">Descripción corta</label><textarea className="field min-h-24 resize-none" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Ej.: Pizzas artesanales, delivery y pickup en Bonao."/></div><div><label className="label">Enlace de tu catálogo</label><div className="flex gap-2"><div className="field flex min-w-0 flex-1 items-center overflow-hidden text-sm text-[#737990]"><span className="truncate">{publicUrl}</span></div><a href={publicUrl} target="_blank" className="btn-secondary px-3" title="Abrir catálogo"><ExternalLink className="h-4 w-4"/></a></div><p className="mt-1.5 text-xs text-[#9aa0b4]">Tus clientes entran directamente por el dominio de este negocio.</p></div></div></div>
      <div className="mt-7 border-t border-slate-100 pt-6"><div className="mb-3 flex items-center gap-2"><ImageIcon className="h-4 w-4 text-brand-600"/><h3 className="font-semibold text-ink-900">Foto de portada</h3></div><ImagePicker value={form.banner_url} onPick={f=>pick('banner_url',f)} onClear={()=>setForm({...form,banner_url:''})} label="Subir portada" busy={up==='banner_url'} ratio="banner"/><p className="mt-2 text-xs text-[#9aa0b4]">Úsala para mostrar el ambiente, productos o una promoción. El diseño elegido la acomodará automáticamente.</p></div>
    </div>}

    {tab==='design'&&<div><p className="section-kicker">Apariencia del catálogo</p><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="section-title">Diseño y marca</h2><p className="section-copy">Primero elige un diseño. Después ajusta colores, letras y presentación con palabras fáciles, sin tocar código.</p></div><button type="button" onClick={()=>applyTheme(form.visual_theme||'minimal-shop')} className="btn-secondary px-3 text-xs"><RotateCcw className="h-3.5 w-3.5"/>Restablecer diseño</button></div>
      <div className="modal-scroll mt-5 flex gap-2 overflow-x-auto pb-1">{designTabs.map(([id,label,I])=><button key={id} type="button" onClick={()=>setDesignTab(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-full px-3.5 py-2 text-xs font-semibold transition ${designTab===id?'bg-brand-500 text-white':'border border-[#e7eaf0] bg-white text-[#747a92] hover:border-brand-200 hover:text-brand-700'}`}><I className="h-3.5 w-3.5"/>{label}</button>)}</div>

      {designTab==='theme'&&<div className="mt-6"><div className="rounded-2xl border border-brand-100 bg-brand-50/60 p-4"><p className="text-sm font-semibold text-brand-800">Elige la personalidad de tu negocio</p><p className="mt-1 text-xs leading-5 text-brand-700/80">Cambiar de diseño no borra productos, pedidos ni configuraciones. Solo cambia cómo se ve tu catálogo.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{STORE_THEMES.map(t=>{const active=form.visual_theme===t.id;return <button type="button" key={t.id} onClick={()=>applyTheme(t.id)} className={`overflow-hidden rounded-[22px] border text-left transition ${active?'border-brand-400 shadow-[0_10px_30px_rgba(54,179,133,.14)]':'border-[#e8ebf1] hover:-translate-y-0.5 hover:border-brand-200 hover:shadow-md'}`}><div className="h-28 p-3" style={{background:`linear-gradient(135deg,${t.config.colors.background},${t.config.colors.secondary})`}}><div className="flex h-full gap-2"><div className="relative w-[38%] overflow-hidden rounded-xl" style={{background:t.config.colors.primary}}><div className="absolute inset-x-3 bottom-3 h-3 rounded-full bg-white/80"/><div className="absolute left-3 top-3 h-8 w-8 rounded-lg bg-white/25"/></div><div className="flex flex-1 flex-col gap-2"><div className="h-9 rounded-lg" style={{background:t.config.colors.surface}}/><div className="grid flex-1 grid-cols-2 gap-2"><div className="rounded-lg" style={{background:t.config.colors.surface}}/><div className="rounded-lg" style={{background:t.config.colors.surface}}/></div></div></div></div><div className="p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-ink-900">{t.name}</h3>{active&&<span className="rounded-full bg-brand-50 px-2 py-0.5 text-[9px] font-bold uppercase tracking-wide text-brand-700">En uso</span>}</div><p className="mt-1 text-xs leading-5 text-[#8d92aa]">{t.description}</p><p className="mt-2 text-[10px] font-semibold uppercase tracking-wide text-brand-700">Ideal para: {t.bestFor}</p></div>{active&&<CheckCircle2 className="h-5 w-5 shrink-0 text-brand-500"/>}</div></div></button>})}</div></div>}

      {designTab==='colors'&&<div className="mt-6"><h3 className="font-semibold text-ink-900">Colores de tu negocio</h3><p className="mt-1 text-sm text-[#8d92aa]">Puedes empezar con una combinación lista y luego cambiar cualquier color a tu gusto.</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{PALETTES.map(p=><button key={p.id} type="button" onClick={()=>applyPalette(p.colors)} className="rounded-2xl border border-[#e8ebf1] bg-white p-3 text-left transition hover:border-brand-200 hover:shadow-sm"><div className="mb-2 flex gap-1.5">{[p.colors.primary,p.colors.secondary,p.colors.accent,p.colors.background].map((c,i)=><span key={i} className="h-6 flex-1 rounded-md border border-black/5" style={{background:c}}/>)}</div><p className="text-xs font-semibold text-ink-900">{p.name}</p><p className="mt-0.5 text-[10px] text-[#969bad]">{p.detail}</p></button>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2">{([['primary','Color principal','Botones, precios y elementos importantes'],['secondary','Color de apoyo','Degradados y áreas secundarias'],['accent','Color de detalle','Contraste y pequeños acentos'],['background','Fondo del catálogo','Color detrás de tus productos'],['surface','Fondo de tarjetas','Tarjetas, encabezados y paneles'],['text','Texto principal','Nombres y títulos'],['muted','Texto suave','Descripciones y datos secundarios'],['border','Líneas y bordes','Separadores y contornos'],['buttonText','Texto de botones','Color de las letras dentro del botón']] as const).map(([key,label,detail])=><label key={key} className="flex items-center gap-3 rounded-2xl border border-[#e9ebf2] bg-white p-3"><input type="color" className="h-11 w-11 cursor-pointer rounded-xl border-0 bg-transparent p-0" value={cfg.colors[key]} onChange={e=>setThemeConfig(`colors.${key}`,e.target.value)}/><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-ink-900">{label}</span><span className="block text-[11px] text-[#9aa0b4]">{detail}</span></span><span className="hidden text-[10px] uppercase text-[#a3a8b9] sm:block">{cfg.colors[key]}</span></label>)}</div></div>}

      {designTab==='type'&&<div className="mt-6"><h3 className="font-semibold text-ink-900">Letras del catálogo</h3><p className="mt-1 text-sm text-[#8d92aa]">Combina una letra con personalidad para los títulos y otra fácil de leer para productos y precios.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="label">Letra de títulos</label><select className="field" value={cfg.typography.heading} onChange={e=>setThemeConfig('typography.heading',e.target.value)}>{FONT_OPTIONS.map(x=><option key={x}>{x}</option>)}</select><div className="mt-3 rounded-2xl border border-[#e9ebf2] p-4 text-2xl font-semibold" style={{fontFamily:cfg.typography.heading}}>{form.name||'Nombre de tu negocio'}</div></div><div><label className="label">Letra para productos y textos</label><select className="field" value={cfg.typography.body} onChange={e=>setThemeConfig('typography.body',e.target.value)}>{FONT_OPTIONS.map(x=><option key={x}>{x}</option>)}</select><div className="mt-3 rounded-2xl border border-[#e9ebf2] p-4 text-sm" style={{fontFamily:cfg.typography.body}}>Producto destacado · RD$1,250.00<br/><span className="text-[#8d92aa]">Descripción clara y fácil de leer.</span></div></div><div className="sm:col-span-2"><label className="label">Tamaño general</label><div className="grid grid-cols-3 gap-2">{([['compact','Compacto'],['normal','Normal'],['large','Grande']] as const).map(([value,label])=><button type="button" key={value} onClick={()=>setThemeConfig('typography.scale',value)} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${cfg.typography.scale===value?'border-brand-400 bg-brand-50 text-brand-700':'border-[#e7eaf0] text-[#747a92]'}`}>{label}</button>)}</div></div></div></div>}

      {designTab==='layout'&&<div className="mt-6"><h3 className="font-semibold text-ink-900">Presentación de la parte superior</h3><p className="mt-1 text-sm text-[#8d92aa]">Controla cómo aparecen tu logo, portada y categorías cuando el cliente abre el catálogo.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="label">Encabezado</label><select className="field" value={cfg.header.variant} onChange={e=>setThemeConfig('header.variant',e.target.value)}><option value="classic">Clásico: logo a la izquierda</option><option value="centered">Centrado: marca protagonista</option><option value="minimal">Limpio: menos elementos</option><option value="glass">Transparente: efecto moderno</option></select></div><div><label className="label">Portada</label><select className="field" value={cfg.hero.variant} onChange={e=>setThemeConfig('hero.variant',e.target.value)}><option value="gradient">Degradado de colores</option><option value="overlay">Foto con texto encima</option><option value="editorial">Editorial y elegante</option><option value="split">Mitad información / mitad foto</option><option value="compact">Compacta</option></select></div><div><label className="label">Altura de portada</label><select className="field" value={cfg.hero.height} onChange={e=>setThemeConfig('hero.height',e.target.value)}><option value="compact">Baja</option><option value="normal">Normal</option><option value="large">Alta y llamativa</option></select></div><div><label className="label">Cómo mostrar categorías</label><select className="field" value={cfg.categories.variant} onChange={e=>setThemeConfig('categories.variant',e.target.value)}><option value="pills">Botones redondos</option><option value="circles">Círculos visuales</option><option value="cards">Tarjetas</option><option value="underline">Línea simple / editorial</option></select></div><Switch checked={cfg.header.sticky} onChange={v=>setThemeConfig('header.sticky',v)} label="Dejar el encabezado visible" detail="El nombre del negocio y el botón del pedido quedan arriba mientras el cliente baja."/></div></div>}

      {designTab==='products'&&<div className="mt-6"><h3 className="font-semibold text-ink-900">Cómo se ven tus productos</h3><p className="mt-1 text-sm text-[#8d92aa]">Ajusta la tarjeta, el tamaño de las fotos y cuántos productos se ven por fila en celular.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="label">Tipo de tarjeta</label><select className="field" value={cfg.products.card} onChange={e=>setThemeConfig('products.card',e.target.value)}><option value="clean">Clásica y limpia</option><option value="editorial">Fotográfica / boutique</option><option value="dense">Compacta y comercial</option><option value="industrial">Lista técnica</option><option value="luxury">Premium</option></select></div><div><label className="label">Forma de la foto</label><select className="field" value={cfg.products.imageRatio} onChange={e=>setThemeConfig('products.imageRatio',e.target.value)}><option value="1:1">Cuadrada</option><option value="4:3">Horizontal</option><option value="3:4">Vertical</option><option value="16:9">Panorámica</option></select></div><div><label className="label">Productos por fila en celular</label><select className="field" value={cfg.products.columnsMobile} onChange={e=>setThemeConfig('products.columnsMobile',Number(e.target.value))}><option value={1}>1 producto: más grande</option><option value={2}>2 productos: más catálogo</option></select></div><div><label className="label">Esquinas de tarjetas: {cfg.shape.radius}px</label><input type="range" min="0" max="32" value={Math.min(32,cfg.shape.radius)} onChange={e=>setThemeConfig('shape.radius',Number(e.target.value))} className="w-full accent-brand-500"/><div className="mt-1 flex justify-between text-[10px] text-[#a0a5b6]"><span>Rectas</span><span>Redondeadas</span></div></div><div><label className="label">Sombra</label><select className="field" value={cfg.shape.shadow} onChange={e=>setThemeConfig('shape.shadow',e.target.value)}><option value="none">Sin sombra</option><option value="soft">Suave</option><option value="medium">Media</option><option value="strong">Marcada</option></select></div><div><label className="label">Estilo de botones</label><select className="field" value={cfg.buttons.variant} onChange={e=>setThemeConfig('buttons.variant',e.target.value)}><option value="solid">Rellenos</option><option value="soft">Suaves</option><option value="outline">Solo borde</option></select></div><div><label className="label">Esquinas de botones: {cfg.shape.buttonRadius>=100?'Completamente redondos':`${cfg.shape.buttonRadius}px`}</label><input type="range" min="0" max="40" value={Math.min(40,cfg.shape.buttonRadius)} onChange={e=>setThemeConfig('shape.buttonRadius',Number(e.target.value))} className="w-full accent-brand-500"/></div></div></div>}

      {designTab==='background'&&<div className="mt-6"><h3 className="font-semibold text-ink-900">Fondo general</h3><p className="mt-1 text-sm text-[#8d92aa]">Para la mayoría de negocios recomendamos un color sólido claro. El degradado sirve para estilos más llamativos.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="label">Tipo de fondo</label><select className="field" value={cfg.background.type} onChange={e=>setThemeConfig('background.type',e.target.value)}><option value="solid">Color sólido</option><option value="gradient">Degradado</option></select></div>{cfg.background.type==='solid'?<div><label className="label">Color del fondo</label><div className="flex gap-2"><input type="color" className="h-11 w-14 rounded-xl border border-[#e7eaf0] bg-white p-1" value={cfg.background.value?.startsWith('#')?cfg.background.value:cfg.colors.background} onChange={e=>{setThemeConfig('background.value',e.target.value);setThemeConfig('colors.background',e.target.value)}}/><input className="field" value={cfg.background.value} onChange={e=>setThemeConfig('background.value',e.target.value)} placeholder="#f7f9fc"/></div></div>:<div><label className="label">Degradado</label><input className="field" value={cfg.background.value} onChange={e=>setThemeConfig('background.value',e.target.value)} placeholder="linear-gradient(135deg, #fff, #f3f4f6)"/><p className="mt-1 text-[10px] text-[#9aa0b4]">Opción avanzada: usa un valor CSS de degradado.</p></div>}</div><div className="mt-5 h-36 rounded-[24px] border border-[#e7eaf0]" style={{background:cfg.background.value||cfg.colors.background}}/></div>}

      {designTab==='advanced'&&<div className="mt-6"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Solo para personalización avanzada</strong><p className="mt-1 text-xs leading-5 text-amber-800">Si trabajas con un diseñador o desarrollador, puedes agregar CSS propio. Por seguridad no se permite JavaScript personalizado.</p></div><div className="mt-4"><label className="label">CSS adicional</label><textarea className="field min-h-56 font-mono text-xs" value={cfg.custom_css||''} onChange={e=>setThemeConfig('custom_css',e.target.value)} placeholder={'.storefront-product-card {\n  /* ajustes opcionales */\n}'}/></div></div>}
    </div>}

    {tab==='sales'&&<div><p className="section-kicker">Cómo vendes</p><h2 className="section-title">{capabilities.isService?'Reservas y atención':'Ventas y entrega'}</h2><p className="section-copy">WAMERCIO muestra únicamente las modalidades compatibles con {form.template_name||'este tipo de negocio'}. Los métodos de pago se administran desde su sección dedicada.</p><div className="mt-6 rounded-2xl border border-[#d9eee7] bg-brand-50/50 p-4"><Switch checked={form.accepting_orders!==false} onChange={v=>setForm({...form,accepting_orders:v})} label={capabilities.appointments?'Aceptar reservas':capabilities.quotation?'Aceptar solicitudes':'Aceptar pedidos'} detail={`Pausa temporalmente las ${capabilities.orderNounPlural} sin cerrar ni ocultar tu catálogo.`}/></div><div className="mt-4 grid gap-4 md:grid-cols-3">{capabilities.supportsDelivery&&<Switch checked={!!form.delivery_enabled} onChange={v=>setForm({...form,delivery_enabled:v})} label="Delivery" detail="Lleva el pedido donde está el cliente."/>}{capabilities.supportsPickup&&<Switch checked={!!form.pickup_enabled} onChange={v=>setForm({...form,pickup_enabled:v})} label={capabilities.isService?'Atención en el negocio':'Recoger en el negocio'} detail={capabilities.pickupDetail}/>} {capabilities.supportsDineIn&&<Switch checked={!!form.dine_in_enabled} onChange={v=>setForm({...form,dine_in_enabled:v})} label="Mesas y reservas" detail="El cliente reserva una mesa y su pedido para comer en el negocio."/>}</div>{capabilities.appointments&&<div className="mt-4 rounded-2xl border border-brand-100 bg-brand-50/40 p-4 text-sm text-[#637080]"><strong className="text-ink-900">Reservas adaptadas a servicios</strong><p className="mt-1 text-xs leading-5">La tienda solicitará los datos de cita definidos por la plantilla, como fecha, hora y profesional, sin mostrar opciones de restaurante.</p></div>}
      {capabilities.supportsDineIn&&form.dine_in_enabled&&<div className="mt-6 rounded-2xl border border-[#e7ebe9] bg-[#fbfcfc] p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-brand-600"><UtensilsCrossed className="h-5 w-5"/></span><div><h3 className="font-semibold text-ink-900">Administrar mesas</h3><p className="text-xs text-[#8d92aa]">Define las mesas disponibles y su capacidad para reservar.</p></div></div><div className="flex items-center gap-2"><label className="text-xs font-medium text-[#737990]">Duración</label><select className="field h-10 w-32 py-1.5" value={form.reservation_duration_minutes||90} onChange={e=>setForm({...form,reservation_duration_minutes:Number(e.target.value)})}><option value={60}>60 min</option><option value={90}>90 min</option><option value={120}>120 min</option><option value={180}>180 min</option></select></div></div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_140px_auto]"><input className="field" placeholder="Ej.: Mesa 1, Terraza A" value={newTable.name} onChange={e=>setNewTable({...newTable,name:e.target.value})}/><input className="field" type="number" min="1" max="50" value={newTable.capacity} onChange={e=>setNewTable({...newTable,capacity:Number(e.target.value)})}/><button type="button" disabled={tableBusy||!newTable.name.trim()} onClick={addTable} className="btn-primary justify-center"><Plus className="h-4 w-4"/>Agregar mesa</button></div><div className="mt-4 space-y-2">{tables.filter(t=>t.is_active!==false).length?tables.filter(t=>t.is_active!==false).map((t,i)=><div key={t.id} className="grid items-center gap-2 rounded-xl border border-[#e9ecec] bg-white p-3 sm:grid-cols-[1fr_120px_auto]"><input className="field h-10 py-1.5" value={t.name} onChange={e=>setTables(v=>v.map(x=>x.id===t.id?{...x,name:e.target.value}:x))}/><div className="flex items-center gap-2"><input className="field h-10 py-1.5" type="number" min="1" max="50" value={t.capacity} onChange={e=>setTables(v=>v.map(x=>x.id===t.id?{...x,capacity:Number(e.target.value)}:x))}/><span className="text-xs text-[#8d92aa]">pers.</span></div><div className="flex justify-end gap-1"><button type="button" className="icon-action text-brand-700" disabled={tableBusy} onClick={()=>saveTable(t)} title="Guardar mesa"><Save className="h-4 w-4"/></button><button type="button" className="icon-action text-rose-600" disabled={tableBusy} onClick={()=>removeTable(t)} title="Archivar mesa"><Trash2 className="h-4 w-4"/></button></div></div>):<div className="rounded-xl border border-dashed border-[#dfe4e6] p-5 text-center text-sm text-[#8d92aa]">Agrega tu primera mesa para aceptar reservas.</div>}</div></div>}
      <div className="mt-6 max-w-sm"><label className="label">Pedido mínimo</label><div className="relative"><span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-sm font-semibold text-[#9197aa]">RD$</span><input type="number" min="0" step="0.01" className="field pl-12" value={form.minimum_order||0} onChange={e=>setForm({...form,minimum_order:Number(e.target.value)})}/></div></div><div className="mt-7 border-t border-slate-100 pt-6"><div className="flex items-center gap-2"><Truck className="h-5 w-5 text-brand-600"/><h3 className="font-semibold text-ink-900">Aviso para tus clientes</h3></div><div className="mt-4"><label className="label">Mensaje en el catálogo</label><textarea className="field min-h-20 resize-none" value={form.order_notice||''} onChange={e=>setForm({...form,order_notice:e.target.value})} placeholder="Ej.: Delivery disponible hasta las 9:00 p. m."/></div></div></div>}

    {tab==='hours'&&<div><p className="section-kicker">Disponibilidad</p><h2 className="section-title">Horario del negocio</h2><p className="section-copy">Marca los días que abres. Fuera de horario el cliente podrá mirar el catálogo, pero verá que no estás recibiendo pedidos.</p><div className="mt-6 space-y-2">{days.map(([key,label])=>{const d=form.business_hours?.[key]||defaultHours[key];return <div key={key} className={`grid items-center gap-3 rounded-2xl border p-3.5 sm:grid-cols-[130px_110px_1fr_1fr] ${d.enabled?'border-[#e7ebe9] bg-white':'border-slate-100 bg-[#fafbfc]'}`}><div className="font-semibold text-ink-900">{label}</div><button type="button" onClick={()=>setForm({...form,business_hours:{...form.business_hours,[key]:{...d,enabled:!d.enabled}}})} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${d.enabled?'bg-brand-50 text-brand-700':'bg-slate-100 text-slate-500'}`}>{d.enabled?'Abierto':'Cerrado'}</button><input type="time" disabled={!d.enabled} className="field disabled:bg-slate-50 disabled:text-slate-400" value={d.open||'08:00'} onChange={e=>setForm({...form,business_hours:{...form.business_hours,[key]:{...d,open:e.target.value}}})}/><input type="time" disabled={!d.enabled} className="field disabled:bg-slate-50 disabled:text-slate-400" value={d.close||'18:00'} onChange={e=>setForm({...form,business_hours:{...form.business_hours,[key]:{...d,close:e.target.value}}})}/></div>})}</div></div>}
    {tab==='domains'&&<StoreDomainsSettings storeId={store} slug={form.slug}/>}
    {tab!=='domains'&&<div className="mt-8 flex justify-end border-t border-slate-100 pt-5"><button onClick={save} disabled={saving} className="btn-primary min-w-44"><CheckCircle2 className="h-4 w-4"/>{saving?'Guardando...':'Guardar cambios'}</button></div>}
   </section>
   <aside className="hidden space-y-4 xl:sticky xl:top-[82px] xl:block xl:max-h-[calc(100dvh-98px)] xl:self-start xl:overflow-hidden"><div className="card p-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Smartphone className="h-5 w-5"/></span><div><p className="section-kicker">Así lo verá tu cliente</p><h3 className="text-lg font-semibold text-ink-900">{resolvedTheme(form.visual_theme,form.theme_config).preset.name}</h3></div></div><p className="mt-2 text-sm leading-6 text-[#8d92aa]">{previewTip}</p><div className="mt-5"><StoreThemePreview form={form}/></div></div></aside>
  </div>}
 </StoreShell>
}
