'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import StoreShell from '@/components/store-shell'
import {api,dateTime,money} from '@/lib/api'
import {Loading,Status} from '@/components/ui'
import {Store,Boxes,ShoppingBag,CircleDollarSign,ArrowUpRight,UsersRound,MessageCircleMore,ChevronRight,Plus,Truck,Settings2} from 'lucide-react'

export default function Dashboard(){
 const[d,setD]=useState<any>(null),[me,setMe]=useState<any>(null)
 useEffect(()=>{api('/dashboard').then(setD).catch(()=>{});api('/me').then(setMe).catch(()=>{})},[])
 if(!d)return <StoreShell title="Inicio" subtitle="Tu negocio, de un vistazo"><Loading/></StoreShell>
 const metrics=[
  ['Pedidos',d.metrics.orders,ShoppingBag,'bg-brand-50 text-brand-600'],
  ['Ventas',money(d.metrics.revenue),CircleDollarSign,'bg-emerald-50 text-emerald-600'],
  ['Productos',d.metrics.products,Boxes,'bg-sky-50 text-sky-600'],
  ['Clientes',d.metrics.customers||0,UsersRound,'bg-violet-50 text-violet-600']
 ]
 const first=String(me?.name||'').split(' ')[0]||'Hola'
 return <StoreShell title="Inicio" subtitle="Todo lo importante, sin complicaciones">
  <section className="relative overflow-hidden rounded-[24px] bg-gradient-to-br from-[#2da87d] to-[#42bd91] p-5 text-white shadow-soft sm:p-7"><div className="absolute -right-12 -top-16 h-48 w-48 rounded-full bg-white/10"/><div className="absolute -bottom-20 right-24 h-40 w-40 rounded-full bg-white/10"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-medium text-white/75">Buen día, {first}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">¿Qué quieres hacer hoy?</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/75">Administra pedidos, productos y WhatsApp desde un panel pensado para trabajar rápido.</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><Link href="/catalog/products" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-[#247e61] shadow-sm"><Plus className="h-4 w-4"/>Producto</Link><Link href="/orders" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white/15 px-4 py-3 text-sm font-semibold text-white ring-1 ring-white/25"><ShoppingBag className="h-4 w-4"/>Pedidos</Link><Link href="/conversations" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white/15 px-4 py-3 text-sm font-semibold text-white ring-1 ring-white/25"><MessageCircleMore className="h-4 w-4"/>WhatsApp</Link></div></div></section>

  <section className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map(([label,value,Icon,color]:any)=><div key={label} className="card p-4 sm:p-5"><div className="flex items-center gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${color}`}><Icon className="h-5 w-5"/></div><div className="min-w-0"><p className="text-xs font-medium text-[#9298ad]">{label}</p><p className="mt-0.5 truncate text-xl font-semibold text-ink-900 sm:text-2xl">{value}</p></div></div></div>)}</section>

  <section className="mt-4 grid gap-4 xl:grid-cols-[1fr_330px]">
   <div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#f0f1f5] px-4 py-4 sm:px-5"><div><h2 className="font-semibold text-ink-900">Pedidos recientes</h2><p className="mt-0.5 text-xs text-[#8d92aa]">Lo último que está pasando en tus tiendas</p></div><Link href="/orders" className="inline-flex items-center gap-1 text-xs font-semibold text-brand-600 sm:text-sm">Ver todos<ChevronRight className="h-4 w-4"/></Link></div>
    {d.recent_orders.length?<><div className="divide-y divide-slate-100 sm:hidden">{d.recent_orders.map((o:any)=><Link key={o.id} href="/orders" className="flex items-center gap-3 p-4 active:bg-[#fafbfe]"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-brand-50 text-brand-600"><ShoppingBag className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><strong className="truncate text-sm">#{o.number} · {o.customer}</strong><span className="shrink-0 text-sm font-semibold">{money(o.total)}</span></div><div className="mt-1 flex items-center justify-between gap-2"><span className="truncate text-xs text-[#8d92aa]">{o.store} · {dateTime(o.created_at)}</span><Status value={o.status}/></div></div></Link>)}</div><div className="hidden overflow-x-auto sm:block"><table className="table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Tienda</th><th>Total</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{d.recent_orders.map((o:any)=><tr key={o.id}><td className="font-semibold">#{o.number}</td><td>{o.customer}</td><td>{o.store}</td><td className="font-semibold">{money(o.total)}</td><td><Status value={o.status}/></td><td className="text-[#8d92aa]">{dateTime(o.created_at)}</td></tr>)}</tbody></table></div></>:<div className="flex min-h-72 flex-col items-center justify-center p-8 text-center"><div className="grid h-14 w-14 place-items-center rounded-full bg-brand-50 text-brand-600"><ShoppingBag className="h-6 w-6"/></div><h3 className="mt-4 font-semibold text-ink-900">Aún no hay pedidos</h3><p className="mt-1 max-w-sm text-sm leading-6 text-[#8d92aa]">Cuando tus clientes compren desde el catálogo, los pedidos aparecerán aquí.</p><Link href="/stores" className="btn-secondary mt-4">Ver mi tienda</Link></div>}
   </div>
   <div className="space-y-4"><div className="card p-5"><div className="flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-brand-600"><MessageCircleMore className="h-5 w-5"/></span><div><h3 className="font-semibold text-ink-900">WhatsApp conectado</h3><p className="text-xs text-[#9298ad]">Atiende desde WAMERCIO</p></div></div><p className="mt-4 text-sm leading-6 text-[#7e849b]">Recibe conversaciones y responde a tus clientes sin salir del panel.</p><Link href="/settings/whatsapp" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-brand-600">Revisar conexión <ArrowUpRight className="h-4 w-4"/></Link></div><div className="card p-5"><h3 className="font-semibold text-ink-900">Accesos rápidos</h3><div className="mt-3 grid grid-cols-2 gap-2"><Link href="/delivery" className="rounded-2xl bg-[#f8fafb] p-3 text-xs font-semibold text-[#6f758d]"><Truck className="mb-2 h-5 w-5 text-brand-600"/>Delivery</Link><Link href="/settings/store" className="rounded-2xl bg-[#f8fafb] p-3 text-xs font-semibold text-[#6f758d]"><Settings2 className="mb-2 h-5 w-5 text-brand-600"/>Ajustes</Link><Link href="/stores" className="rounded-2xl bg-[#f8fafb] p-3 text-xs font-semibold text-[#6f758d]"><Store className="mb-2 h-5 w-5 text-brand-600"/>Mi tienda</Link><Link href="/customers" className="rounded-2xl bg-[#f8fafb] p-3 text-xs font-semibold text-[#6f758d]"><UsersRound className="mb-2 h-5 w-5 text-brand-600"/>Clientes</Link></div></div></div>
  </section>
 </StoreShell>
}
