'use client'
import { useEffect, useState } from 'react'
import AdminShell from '@/components/admin-shell'
import { api, dateTime, money } from '@/lib/api'
import { Loading, Status } from '@/components/ui'
import { Store, Boxes, ShoppingBag, CircleDollarSign, ArrowUpRight, UsersRound } from 'lucide-react'
export default function Dashboard(){const [d,setD]=useState<any>(null);useEffect(()=>{api('/dashboard').then(setD).catch(()=>{})},[]);return <AdminShell title="Dashboard" subtitle="Resumen general de tu operación comercial">{!d?<Loading/>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[
 ['Tiendas',d.metrics.stores,Store,'bg-indigo-50 text-indigo-600'],['Productos',d.metrics.products,Boxes,'bg-sky-50 text-sky-600'],['Pedidos',d.metrics.orders,ShoppingBag,'bg-amber-50 text-amber-600'],['Clientes',d.metrics.customers||0,UsersRound,'bg-fuchsia-50 text-fuchsia-600'],['Ventas',money(d.metrics.revenue),CircleDollarSign,'bg-emerald-50 text-emerald-600']
].map(([l,v,I,c]:any)=><div key={l} className="card p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-500">{l}</p><p className="mt-2 text-3xl font-black text-slate-900">{v}</p></div><div className={`grid h-11 w-11 place-items-center rounded-2xl ${c}`}><I className="h-5 w-5"/></div></div></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]"><div className="card overflow-hidden"><div className="flex items-center justify-between px-5 py-4"><div><h2 className="font-bold text-slate-900">Pedidos recientes</h2><p className="text-sm text-slate-500">Últimos movimientos de tus tiendas</p></div><a href="/orders" className="text-sm font-semibold text-brand-600">Ver todos</a></div><div className="overflow-x-auto"><table className="table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Tienda</th><th>Total</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{d.recent_orders.length?d.recent_orders.map((o:any)=><tr key={o.id}><td className="font-semibold">#{o.number}</td><td>{o.customer}</td><td>{o.store}</td><td className="font-semibold">{money(o.total)}</td><td><Status value={o.status}/></td><td className="text-slate-500">{dateTime(o.created_at)}</td></tr>):<tr><td colSpan={6} className="py-12 text-center text-slate-400">Aún no hay pedidos</td></tr>}</tbody></table></div></div><div className="card p-5"><div className="rounded-2xl bg-slate-950 p-5 text-white"><div className="text-sm font-semibold text-brand-300">WAMERCIO</div><h3 className="mt-2 text-xl font-bold">Tu tienda vive donde están tus clientes.</h3><p className="mt-2 text-sm leading-6 text-slate-300">Conecta WhatsApp, publica tu catálogo y recibe pedidos sin depender de Twilio.</p><a href="/settings/whatsapp" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-brand-300">Conectar WhatsApp <ArrowUpRight className="h-4 w-4"/></a></div><div className="mt-4 rounded-2xl border border-slate-200 p-4"><p className="text-sm font-semibold">Flujo principal</p><div className="mt-3 space-y-3 text-sm text-slate-500">{['Crea una tienda','Organiza categorías y productos','Configura delivery','Conecta WhatsApp','Recibe y gestiona pedidos'].map((x,i)=><div key={x} className="flex items-center gap-3"><span className="grid h-6 w-6 place-items-center rounded-full bg-brand-50 text-xs font-bold text-brand-700">{i+1}</span>{x}</div>)}</div></div></div></div></>}</AdminShell>}
