'use client'
import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {Alert,Loading,Modal,PageEmpty,Status} from '@/components/ui'
import {api,dateTime} from '@/lib/api'
import {CheckCircle2,Clock3,ListTodo,Plus,Trash2} from 'lucide-react'
const blank={title:'',description:'',priority:'normal',status:'pending',assigned_staff_id:'',due_at:''}
export default function Tasks(){
 const[store,setStore]=useState(''),[rows,setRows]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState('')
 const load=()=>{if(!store)return;setLoading(true);Promise.all([api<any[]>(`/tasks?store_id=${store}`),api<any[]>(`/staff?store_id=${store}`)]).then(([t,s])=>{setRows(t);setStaff(s.filter(x=>x.status==='active'))}).finally(()=>setLoading(false))};useEffect(load,[store])
 const groups=useMemo(()=>({overdue:rows.filter(x=>x.status!=='completed'&&x.due_at&&new Date(x.due_at)<new Date()),pending:rows.filter(x=>!['completed','cancelled'].includes(x.status)),completed:rows.filter(x=>x.status==='completed')}),[rows])
 const start=(x?:any)=>{setEdit(x||null);setForm(x?{...x,due_at:x.due_at?String(x.due_at).slice(0,16):''}:blank);setErr('');setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');try{const body={...form,store_id:store,due_at:form.due_at?new Date(form.due_at).toISOString():null};if(edit)await api(`/tasks/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/tasks',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e:any){setErr(e.message)}}
 const complete=async(x:any)=>{await api(`/tasks/${x.id}`,{method:'PUT',body:JSON.stringify({...x,store_id:store,status:'completed'})});load()};const del=async(x:any)=>{if(!confirm('¿Eliminar esta tarea?'))return;await api(`/tasks/${x.id}?store_id=${store}`,{method:'DELETE'});load()}
 return <StoreShell title="Tareas" subtitle="Seguimientos y compromisos operativos vinculados a ventas, clientes y conversaciones" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store} className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Nueva tarea</button>}>
 {!store?<PageEmpty title="Selecciona un negocio" detail="Elige una tienda para administrar las tareas del equipo."/>:loading?<Loading/>:<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[['Pendientes',groups.pending.length],['Vencidas',groups.overdue.length],['Completadas',groups.completed.length]].map(([l,v])=><div className="card p-5" key={l}><div className="text-2xl font-semibold">{v}</div><div className="mt-1 text-xs text-[#8d92aa]">{l}</div></div>)}</div><section className="card overflow-hidden">{rows.length?<div className="divide-y divide-[#edf0f5]">{rows.map(x=><article key={x.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${x.status==='completed'?'bg-emerald-50 text-emerald-600':'bg-brand-50 text-brand-600'}`}>{x.status==='completed'?<CheckCircle2 className="h-5 w-5"/>:<ListTodo className="h-5 w-5"/>}</span><button className="min-w-0 flex-1 text-left" onClick={()=>start(x)}><div className="flex flex-wrap items-center gap-2"><strong>{x.title}</strong><Status value={x.status}/>{x.priority==='urgent'&&<Status value="urgent"/>}</div><p className="mt-1 line-clamp-1 text-xs text-[#8d92aa]">{x.description||x.customer_name||'Sin descripción'}</p><div className="mt-1 flex flex-wrap gap-3 text-[11px] text-[#9aa0b4]">{x.due_at&&<span className="inline-flex items-center gap-1"><Clock3 className="h-3 w-3"/>{dateTime(x.due_at)}</span>}{x.assigned_staff_name&&<span>{x.assigned_staff_name}</span>}</div></button><div className="flex gap-2">{x.status!=='completed'&&<button className="btn-secondary" onClick={()=>complete(x)}>Completar</button>}<button className="icon-action text-rose-600" onClick={()=>del(x)}><Trash2 className="h-4 w-4"/></button></div></article>)}</div>:<PageEmpty title="No hay tareas" detail="Crea tareas desde aquí o deja que Flow Builder las genere automáticamente."/>}</section></div>}
 <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar tarea':'Nueva tarea'} subtitle="Define responsable, prioridad y fecha límite."><form onSubmit={save} className="space-y-4">{err&&<Alert text={err}/>}<div><label className="label">Título *</label><input required className="field" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div><label className="label">Descripción</label><textarea className="field min-h-24" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="grid gap-3 sm:grid-cols-2"><div><label className="label">Prioridad</label><select className="field" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div><div><label className="label">Responsable</label><select className="field" value={form.assigned_staff_id||''} onChange={e=>setForm({...form,assigned_staff_id:e.target.value})}><option value="">Sin asignar</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div></div><div><label className="label">Fecha límite</label><input className="field" type="datetime-local" value={form.due_at||''} onChange={e=>setForm({...form,due_at:e.target.value})}/></div>{edit&&<div><label className="label">Estado</label><select className="field" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="pending">Pendiente</option><option value="in_progress">En curso</option><option value="completed">Completada</option><option value="cancelled">Cancelada</option></select></div>}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary">Guardar</button></div></form></Modal>
 </StoreShell>
}
