DROP TABLE IF EXISTS store_attributes;
DROP TABLE IF EXISTS store_attribute_groups;
ALTER TABLE orders DROP COLUMN IF EXISTS custom_fields;
ALTER TABLE orders DROP COLUMN IF EXISTS flow_type;
ALTER TABLE products DROP COLUMN IF EXISTS attributes;
ALTER TABLE stores DROP COLUMN IF EXISTS template_config;
ALTER TABLE stores DROP COLUMN IF EXISTS business_engine;
ALTER TABLE stores DROP COLUMN IF EXISTS template_id;
DROP TABLE IF EXISTS template_quick_replies;
DROP TABLE IF EXISTS template_attributes;
DROP TABLE IF EXISTS template_attribute_groups;
DROP TABLE IF EXISTS template_products;
DROP TABLE IF EXISTS template_categories;
DROP TABLE IF EXISTS business_templates;
