"use client";
import {useEffect,useMemo,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {api,money} from "@/lib/api";
import {MediaUpload} from "@/components/media-upload";
import {GeoAddressPicker,GeoAddressValue} from "@/components/geo-address-picker";
import {MapPinned} from "lucide-react";

export default function Settings(){
 const q=useQuery({queryKey:['settings'],queryFn:()=>api<any>('/api/v1/dashboard/settings')});const[form,setForm]=useState<any>(null);const[msg,setMsg]=useState('');const[err,setErr]=useState('');useEffect(()=>{if(q.data?.settings)setForm(q.data.settings)},[q.data]);
 const location:GeoAddressValue=useMemo(()=>({geo_province_code:form?.GeoProvinceCode||'',geo_city_id:form?.GeoCityID||'',geo_neighborhood_id:form?.GeoNeighborhoodID||'',geo_id:form?.GeoID||'',geo_address_label:form?.GeoAddressLabel||'',geo_address_source:form?.GeoAddressSource||'',latitude:Number(form?.Latitude||0),longitude:Number(form?.Longitude||0),province:'',municipality:'',sector:form?.Sector||'',address:form?.Address||'',reference:form?.Reference||''}),[form]);
 if(!form)return <div>Cargando...</div>;
 function f(k:string,v:any){setForm({...form,[k]:v})}
 function setLocation(v:GeoAddressValue){setForm((x:any)=>({...x,GeoProvinceCode:v.geo_province_code,GeoCityID:v.geo_city_id,GeoNeighborhoodID:v.geo_neighborhood_id,GeoID:v.geo_id,GeoAddressLabel:v.geo_address_label,GeoAddressSource:v.geo_address_source,Latitude:v.latitude,Longitude:v.longitude,Sector:v.sector,Address:v.address,Reference:v.reference||''}))}
 async function save(){setErr('');try{const d=await api<any>('/api/v1/dashboard/settings',{method:'PUT',body:JSON.stringify(form)});setForm(d.settings);setMsg('Configuración guardada');setTimeout(()=>setMsg(''),2500)}catch(e:any){setErr(e.message)}}
 const checks=[['DeliveryEnabled','Delivery'],['PickupEnabled','Recogida'],['TableEnabled','Mesa'],['OtherEnabled','Otros pedidos'],['MarketplaceEnabled','Marketplace'],['CashEnabled','Efectivo'],['CardOnDeliveryEnabled','Tarjeta al recibir'],['BankTransferEnabled','Transferencia bancaria'],['PaymentLinkEnabled','Enlace de pago']];
 return <div><h1 className="text-3xl font-black">Configuración</h1><p className="mt-2 text-gray-500">Identidad, ubicación, operación, entrega y pagos del negocio.</p><div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-soft"><h2 className="text-xl font-black">Identidad</h2><div className="mt-4 grid gap-3"><input className="field" value={form.Name} onChange={e=>f('Name',e.target.value)} placeholder="Nombre"/><textarea className="field min-h-24" value={form.Description} onChange={e=>f('Description',e.target.value)} placeholder="Descripción"/><div className="grid gap-3 md:grid-cols-2"><MediaUpload label="Logo" value={form.LogoURL||''} onChange={v=>f('LogoURL',v)}/><MediaUpload label="Portada" value={form.CoverURL||''} onChange={v=>f('CoverURL',v)}/></div><label className="text-sm font-bold">Color principal<input className="field mt-2 h-12" type="color" value={form.Accent||'#ff5400'} onChange={e=>f('Accent',e.target.value)}/></label></div></section>
 <section className="rounded-2xl bg-white p-6 shadow-soft"><h2 className="text-xl font-black">Contacto</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="field" value={form.WhatsApp} onChange={e=>f('WhatsApp',e.target.value)} placeholder="WhatsApp"/><input className="field" value={form.Email} onChange={e=>f('Email',e.target.value)} placeholder="Correo"/><input className="field" value={form.Instagram} onChange={e=>f('Instagram',e.target.value)} placeholder="Instagram"/><input className="field" value={form.Facebook} onChange={e=>f('Facebook',e.target.value)} placeholder="Facebook"/></div></section>
 <section className="rounded-2xl bg-white p-6 shadow-soft xl:col-span-2"><div className="flex items-start gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-orange-50 text-[#ff5400]"><MapPinned/></div><div><h2 className="text-xl font-black">Ubicación GEO RD MAP</h2><p className="text-sm text-gray-500">Esta coordenada es el origen de las rutas de delivery y la ubicación oficial del negocio.</p></div></div><div className="mt-5"><GeoAddressPicker value={location} onChange={setLocation} requiredCoordinates/></div></section>
 <section className="rounded-2xl bg-white p-6 shadow-soft"><h2 className="text-xl font-black">Operación</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm font-bold">Pedido mínimo<input className="field mt-2" type="number" value={form.MinimumOrder} onChange={e=>f('MinimumOrder',Number(e.target.value))}/><span className="mt-1 block text-xs font-normal text-gray-400">Actual: {money(form.MinimumOrder)}</span></label><label className="text-sm font-bold">Tarifa delivery predeterminada<input className="field mt-2" type="number" value={form.DefaultDeliveryFee} onChange={e=>f('DefaultDeliveryFee',Number(e.target.value))}/></label></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="field" value={form.DeliveryLabel||'Delivery'} onChange={e=>f('DeliveryLabel',e.target.value)} placeholder="Nombre de Delivery"/><input className="field" value={form.PickupLabel||'Recogida'} onChange={e=>f('PickupLabel',e.target.value)} placeholder="Nombre de Recogida"/><input className="field" value={form.TableLabel||'Mesa'} onChange={e=>f('TableLabel',e.target.value)} placeholder="Nombre de Mesa"/><input className="field" value={form.OtherLabel||'Otro'} onChange={e=>f('OtherLabel',e.target.value)} placeholder="Nombre de Otro"/></div><div className="mt-5 grid gap-3 md:grid-cols-2">{checks.map(([k,l])=><label key={k} className="flex items-center gap-3 rounded-xl bg-gray-50 p-3 text-sm font-bold"><input type="checkbox" checked={!!form[k]} onChange={e=>f(k,e.target.checked)}/>{l}</label>)}</div></section>
 <section className="rounded-2xl bg-white p-6 shadow-soft"><h2 className="text-xl font-black">Pagos</h2><textarea className="field mt-4 min-h-28" value={form.BankTransferInfo||''} onChange={e=>f('BankTransferInfo',e.target.value)} placeholder="Datos para transferencia: banco, cuenta, beneficiario..."/><input className="field mt-3" value={form.PaymentLinkURL||''} onChange={e=>f('PaymentLinkURL',e.target.value)} placeholder="URL de pago opcional"/></section></div>{err&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-600">{err}</p>}<button onClick={save} className="btn btn-brand mt-6">Guardar configuración</button>{msg&&<span className="ml-3 text-sm font-bold text-green-600">{msg}</span>}</div>
}
