'use client'

import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime} from '@/lib/api'
import {Alert,Loading,Modal,PageEmpty,Status} from '@/components/ui'
import type {Reservation} from '@/lib/types'
import {CalendarClock,Plus,UsersRound,UtensilsCrossed,Phone,Clock3} from 'lucide-react'

type TableRow={id:string;name:string;area_id:string;area_name:string;capacity:number;is_active:boolean}
type Settings={dine_in_enabled?:boolean;reservation_duration_minutes?:number}
const blank={table_id:'',reserved_at:'',duration_minutes:90,party_size:2,guest_name:'',guest_phone:'',notes:''}
const statuses=['reserved','confirmed','seated','completed','canceled','no_show'] as const
function localInput(hours=1){const d=new Date(Date.now()+hours*3600000);d.setMinutes(Math.ceil(d.getMinutes()/15)*15,0,0);const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function localDay(value:string){const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const todayKey=()=>localDay(new Date().toISOString())

export default function Reservations(){
 const[store,setStore]=useState(''),[rows,setRows]=useState<Reservation[]>([]),[tables,setTables]=useState<TableRow[]>([]),[settings,setSettings]=useState<Settings|null>(null),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[form,setForm]=useState<any>({...blank,reserved_at:localInput()}),[view,setView]=useState<'today'|'upcoming'|'all'>('today'),[err,setErr]=useState(''),[ok,setOk]=useState(''),[busy,setBusy]=useState(false)
 const load=()=>{if(!store){setRows([]);setTables([]);setSettings(null);return};setLoading(true);setErr('');Promise.all([api<Reservation[]>(`/reservations?store_id=${store}`),api<TableRow[]>(`/tables?store_id=${store}`),api<Settings>(`/stores/${store}/settings`)]).then(([r,t,s])=>{setRows(r);setTables(t.filter(x=>x.is_active!==false));setSettings(s)}).catch((e:any)=>setErr(e.message)).finally(()=>setLoading(false))}
 useEffect(load,[store])
 const filtered=useMemo(()=>{const now=Date.now(),today=todayKey();return rows.filter(row=>view==='all'?true:view==='today'?localDay(row.reserved_at)===today:new Date(row.reserved_at).getTime()>=now&&row.status!=='canceled'&&row.status!=='completed'&&row.status!=='no_show')},[rows,view])
 const create=async(e:React.FormEvent)=>{e.preventDefault();setErr('');setOk('');setBusy(true);try{if(!form.table_id)throw new Error('Selecciona una mesa.');await api('/reservations',{method:'POST',body:JSON.stringify({...form,store_id:store,reserved_at:new Date(form.reserved_at).toISOString(),duration_minutes:Number(form.duration_minutes),party_size:Number(form.party_size)})});setOpen(false);setForm({...blank,reserved_at:localInput(),duration_minutes:settings?.reservation_duration_minutes||90});setOk('Reservación creada correctamente.');load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const updateStatus=async(row:Reservation,status:string)=>{if(status===row.status)return;setBusy(true);setErr('');setOk('');try{await api(`/reservations/${row.id}/status`,{method:'PATCH',body:JSON.stringify({status})});setRows(current=>current.map(x=>x.id===row.id?{...x,status:status as Reservation['status']}:x));setOk('Estado de la reservación actualizado.')}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const start=()=>{setForm({...blank,reserved_at:localInput(),duration_minutes:settings?.reservation_duration_minutes||90,party_size:2});setErr('');setOpen(true)}
 return <StoreShell title="Reservaciones" subtitle="Agenda, confirma y organiza las mesas del negocio" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store||!settings?.dine_in_enabled} onClick={start} className="btn-primary"><Plus className="h-4 w-4"/>Nueva reservación</button>}>
  {!store?<PageEmpty title="Selecciona un negocio" detail="Elige el negocio donde administrarás las reservaciones."/>:loading?<Loading/>:<div className="space-y-5">{err&&<Alert text={err}/>} {ok&&<Alert text={ok} type="success"/>}
   {!settings?.dine_in_enabled?<section className="card p-6"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-amber-50 text-amber-600"><UtensilsCrossed className="h-5 w-5"/></span><div><h2 className="text-lg font-semibold">Mesas y reservas está desactivado</h2><p className="mt-1 text-sm leading-6 text-[#8d92aa]">Activa esta modalidad en Configuración → Ventas y entrega para gestionar reservaciones.</p><a className="btn-secondary mt-4 inline-flex" href="/settings/store?tab=sales">Ir a Ventas y entrega</a></div></div></section>:<>
    <section className="grid gap-4 md:grid-cols-3">{[
     {label:'Hoy',value:rows.filter(x=>localDay(x.reserved_at)===todayKey()&&!['canceled','no_show'].includes(x.status)).length,detail:'Reservaciones del día',icon:CalendarClock},
     {label:'Próximas',value:rows.filter(x=>new Date(x.reserved_at).getTime()>=Date.now()&&!['canceled','completed','no_show'].includes(x.status)).length,detail:'Pendientes por atender',icon:Clock3},
     {label:'Personas hoy',value:rows.filter(x=>localDay(x.reserved_at)===todayKey()&&!['canceled','no_show'].includes(x.status)).reduce((sum,x)=>sum+Number(x.party_size||0),0),detail:'Comensales previstos',icon:UsersRound},
    ].map(card=>{const I=card.icon;return <article key={card.label} className="card p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.1em] text-[#9aa0b4]">{card.label}</p><p className="mt-2 text-2xl font-semibold">{card.value}</p><p className="mt-1 text-xs text-[#8f95a9]">{card.detail}</p></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-600"><I className="h-5 w-5"/></span></div></article>})}</section>

    <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#edf0f5] p-5"><div><p className="section-kicker">Agenda</p><h2 className="mt-1 text-lg font-semibold">Reservaciones</h2></div><div className="inline-flex rounded-2xl border border-[#e8ebf1] bg-white p-1">{([['today','Hoy'],['upcoming','Próximas'],['all','Todas']] as const).map(([value,label])=><button key={value} onClick={()=>setView(value)} className={`rounded-xl px-3 py-2 text-xs font-semibold ${view===value?'bg-brand-50 text-brand-700':'text-[#7f859b]'}`}>{label}</button>)}</div></div>
     {filtered.length?<div className="overflow-x-auto"><table className="table"><thead><tr><th>Fecha y hora</th><th>Cliente</th><th>Mesa</th><th>Personas</th><th>Estado</th><th>Notas</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><div className="min-w-[165px] font-medium">{dateTime(row.reserved_at)}</div><div className="mt-1 text-xs text-[#9399ad]">{row.duration_minutes} min</div></td><td><div className="min-w-[150px]"><div className="font-semibold">{row.customer_name||'Cliente'}</div>{row.customer_phone&&<div className="mt-1 flex items-center gap-1 text-xs text-[#8d92aa]"><Phone className="h-3 w-3"/>{row.customer_phone}</div>}</div></td><td><div className="font-medium">{row.table_name}</div><div className="mt-1 text-xs text-[#9399ad]">{row.area_name}</div></td><td>{row.party_size}</td><td><div className="space-y-2"><Status value={row.status}/><select disabled={busy} className="field min-w-[145px] py-2 text-xs" value={row.status} onChange={e=>void updateStatus(row,e.target.value)}>{statuses.map(status=><option key={status} value={status}>{status==='reserved'?'Reservada':status==='confirmed'?'Confirmada':status==='seated'?'En mesa':status==='completed'?'Completada':status==='canceled'?'Cancelada':'No asistió'}</option>)}</select></div></td><td><div className="max-w-[260px] whitespace-normal text-xs leading-5 text-[#7f8599]">{row.notes||'—'}</div></td></tr>)}</tbody></table></div>:<div className="p-10 text-center text-sm text-[#8d92aa]">No hay reservaciones para esta vista.</div>}
    </section>
   </>}
  </div>}
  <Modal open={open} onClose={()=>setOpen(false)} title="Nueva reservación" subtitle="Registra manualmente una mesa y WAMERCIO validará la disponibilidad.">
   <form onSubmit={create}>{err&&<Alert text={err}/>}<div className="space-y-4"><div><label className="label">Mesa *</label><select className="field" required value={form.table_id} onChange={e=>setForm({...form,table_id:e.target.value})}><option value="">Selecciona una mesa</option>{tables.map(row=><option key={row.id} value={row.id}>{row.area_name} · {row.name} · {row.capacity} personas</option>)}</select></div><div className="grid gap-3 sm:grid-cols-2"><div><label className="label">Fecha y hora *</label><input className="field" type="datetime-local" required value={form.reserved_at} onChange={e=>setForm({...form,reserved_at:e.target.value})}/></div><div><label className="label">Duración</label><select className="field" value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:Number(e.target.value)})}><option value={60}>60 minutos</option><option value={90}>90 minutos</option><option value={120}>120 minutos</option><option value={180}>180 minutos</option></select></div></div><div className="grid gap-3 sm:grid-cols-2"><div><label className="label">Nombre del cliente</label><input className="field" value={form.guest_name} onChange={e=>setForm({...form,guest_name:e.target.value})} placeholder="Ej.: María Pérez"/></div><div><label className="label">WhatsApp</label><input className="field" inputMode="tel" value={form.guest_phone} onChange={e=>setForm({...form,guest_phone:e.target.value})} placeholder="8095550000"/></div></div><div><label className="label">Cantidad de personas</label><input className="field" type="number" min="1" max="50" value={form.party_size} onChange={e=>setForm({...form,party_size:Number(e.target.value)})}/></div><div><label className="label">Notas</label><textarea className="field min-h-24 resize-none" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Cumpleaños, silla para bebé, ubicación preferida..."/></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button disabled={busy} className="btn-primary">{busy?'Guardando...':'Crear reservación'}</button></div></form>
  </Modal>
 </StoreShell>
}
