'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import SuperAdminShell from '@/components/superadmin-shell'
import {api,money} from '@/lib/api'
import {Alert,Loading,Modal,SearchBox,Status} from '@/components/ui'
import {BadgeDollarSign,Boxes,Layers3,Pencil,Plus,RefreshCw,Star} from 'lucide-react'

const blank={name:'',slug:'',description:'',price:0,billing_period:'monthly',max_stores:1,max_products:100,max_orders:999999,whatsapp_enabled:true,is_active:true,is_featured:false}
const payload=(p:any)=>({name:p.name,slug:p.slug,description:p.description||'',price:Number(p.price||0),billing_period:p.billing_period||'monthly',max_stores:Number(p.max_stores||1),max_products:Number(p.max_products||1),max_orders:Number(p.max_orders||999999),whatsapp_enabled:p.whatsapp_enabled!==false,is_active:!!p.is_active,is_featured:!!p.is_featured})

export default function AdminPlans(){
 const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState<'all'|'active'|'inactive'>('all'),[busy,setBusy]=useState('')
 const load=async()=>{setLoading(true);setErr('');try{setRows(await api<any[]>('/admin/plans'))}catch(e:any){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const start=(x?:any)=>{setEdit(x||null);setForm(x?{...x}:blank);setErr('');setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');setBusy('save');try{if(edit)await api(`/admin/plans/${edit.id}`,{method:'PUT',body:JSON.stringify(payload(form))});else await api('/admin/plans',{method:'POST',body:JSON.stringify(payload(form))});setOpen(false);await load()}catch(e:any){setErr(e.message)}finally{setBusy('')}}
 const toggle=async(p:any)=>{setBusy(p.id);setErr('');try{const next={...p,is_active:!p.is_active};await api(`/admin/plans/${p.id}`,{method:'PUT',body:JSON.stringify(payload(next))});setRows(v=>v.map(x=>x.id===p.id?next:x))}catch(e:any){setErr(e.message)}finally{setBusy('')}}
 const filtered=useMemo(()=>rows.filter(p=>{const q=`${p.name} ${p.slug} ${p.description||''}`.toLowerCase();return q.includes(search.toLowerCase())&&(filter==='all'||(filter==='active'&&p.is_active)||(filter==='inactive'&&!p.is_active))}),[rows,search,filter])
 const featured=rows.filter(x=>x.is_featured).length,active=rows.filter(x=>x.is_active).length
 const actions=<><Link href="/admin/subscriptions" className="btn-secondary"><Layers3 className="h-4 w-4"/>Suscripciones</Link><button className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Nuevo plan</button></>
 return <SuperAdminShell title="Planes" subtitle="Oferta comercial, límites y disponibilidad de los planes de WAMERCIO." actions={actions}>
  {err&&<Alert text={err}/>}<section className="grid gap-3 sm:grid-cols-3"><div className="admin-kpi"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e3f6ea] text-[#0b5d3b]"><BadgeDollarSign className="h-4 w-4"/></span><div className="mt-3 text-[10px] font-bold uppercase tracking-wide text-[#718078]">Planes</div><div className="text-2xl font-extrabold text-[#0a3f2a]">{rows.length}</div></div><div className="admin-kpi"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e3f6ea] text-[#0b5d3b]"><Boxes className="h-4 w-4"/></span><div className="mt-3 text-[10px] font-bold uppercase tracking-wide text-[#718078]">Activos</div><div className="text-2xl font-extrabold text-[#0a3f2a]">{active}</div></div><div className="admin-kpi"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#fff3dd] text-[#bd431e]"><Star className="h-4 w-4"/></span><div className="mt-3 text-[10px] font-bold uppercase tracking-wide text-[#718078]">Destacados</div><div className="text-2xl font-extrabold text-[#0a3f2a]">{featured}</div></div></section>
  <div className="admin-form-card mt-4"><div className="flex flex-col gap-3 md:flex-row"><div className="flex-1"><SearchBox value={search} onChange={setSearch} placeholder="Buscar plan..."/></div><select className="field md:w-48" value={filter} onChange={e=>setFilter(e.target.value as any)}><option value="all">Todos los estados</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select><button className="btn-secondary px-3" onClick={()=>void load()} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div>
  <div className="mt-4">{loading?<Loading/>:<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Plan</th><th>Precio</th><th>Negocios</th><th>Productos</th><th>Estado</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><div className="font-semibold text-[#0a3f2a]">{p.name}{p.is_featured&&<span className="ml-2 rounded-full bg-[#fff3dd] px-2 py-0.5 text-[10px] font-bold text-[#a65f08]">DESTACADO</span>}</div><div className="text-xs text-[#7f8a84]">{p.slug}</div></td><td>{p.price?money(p.price):'Gratis'}<div className="text-[10px] text-[#7f8a84]">/{p.billing_period==='yearly'?'año':'mes'}</div></td><td>{p.max_stores}</td><td>{p.max_products}</td><td><button type="button" className="inline-flex items-center gap-2" disabled={busy===p.id} onClick={()=>void toggle(p)} title={p.is_active?'Desactivar plan':'Activar plan'}><span className="admin-switch" data-on={!!p.is_active}/><Status value={p.is_active?'active':'inactive'}/></button></td><td className="text-right"><button className="btn-secondary px-3" onClick={()=>start(p)}><Pencil className="h-4 w-4"/></button></td></tr>)}{filtered.length===0&&<tr><td colSpan={6} className="py-10 text-center text-[#718078]">No hay planes para este filtro.</td></tr>}</tbody></table></div>}</div>
  <Modal open={open} onClose={()=>!busy&&setOpen(false)} title={edit?'Editar plan':'Nuevo plan'} wide><form onSubmit={save}>{err&&<Alert text={err}/>}<div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Nombre *</label><input required className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="label">Slug</label><input className="field" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></div><div className="sm:col-span-2"><label className="label">Descripción</label><textarea className="field min-h-20" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></div><div><label className="label">Precio</label><input type="number" min="0" step="0.01" className="field" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></div><div><label className="label">Periodo</label><select className="field" value={form.billing_period} onChange={e=>setForm({...form,billing_period:e.target.value})}><option value="monthly">Mensual</option><option value="yearly">Anual</option></select></div><div><label className="label">Máx. negocios</label><input type="number" min="1" className="field" value={form.max_stores} onChange={e=>setForm({...form,max_stores:Number(e.target.value)})}/></div><div><label className="label">Máx. productos</label><input type="number" min="1" className="field" value={form.max_products} onChange={e=>setForm({...form,max_products:Number(e.target.value)})}/></div><div className="sm:col-span-2 grid gap-3 sm:grid-cols-2"><button type="button" className="admin-setting-row rounded-xl border border-[#eee8df] px-4 text-left" onClick={()=>setForm({...form,is_featured:!form.is_featured})}><span><span className="block text-sm font-semibold text-[#0a3f2a]">Plan destacado</span><span className="mt-1 block text-xs text-[#718078]">Resáltalo en la página comercial.</span></span><span className="admin-switch" data-on={!!form.is_featured}/></button><button type="button" className="admin-setting-row rounded-xl border border-[#eee8df] px-4 text-left" onClick={()=>setForm({...form,is_active:!form.is_active})}><span><span className="block text-sm font-semibold text-[#0a3f2a]">Plan activo</span><span className="mt-1 block text-xs text-[#718078]">Permite nuevas suscripciones.</span></span><span className="admin-switch" data-on={!!form.is_active}/></button></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary" disabled={busy==='save'}>{busy==='save'?'Guardando...':'Guardar plan'}</button></div></form></Modal>
 </SuperAdminShell>
}
