'use client'
import {useEffect,useState} from 'react'
import SuperAdminShell from '@/components/superadmin-shell'
import {api,dateTime,money} from '@/lib/api'
import {Loading,Status} from '@/components/ui'
import {phoneDisplay} from '@/components/phone-input'
import {Check,X,Layers3,Clock3} from 'lucide-react'
export default function Subscriptions(){
 const[tab,setTab]=useState<'subscriptions'|'requests'>('subscriptions'),[subs,setSubs]=useState<any[]>([]),[reqs,setReqs]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('')
 const load=()=>{setLoading(true);Promise.all([api<any[]>('/admin/subscriptions'),api<any[]>('/admin/subscription-requests')]).then(([s,r])=>{setSubs(s);setReqs(r)}).finally(()=>setLoading(false))};useEffect(load,[])
 const review=async(id:string,decision:'approved'|'rejected')=>{setBusy(id+decision);try{await api(`/admin/subscription-requests/${id}`,{method:'PATCH',body:JSON.stringify({decision})});load()}finally{setBusy('')}}
 return <SuperAdminShell title="Gestión de planes y suscripciones" subtitle="Administra los planes comerciales y las suscripciones de los negocios desde una sola sección">
  <div className="card p-3"><div className="grid gap-2 sm:grid-cols-2"><button onClick={()=>setTab('subscriptions')} className={`flex items-center gap-3 rounded-2xl px-4 py-3 text-left ${tab==='subscriptions'?'bg-brand-50 text-brand-700':'bg-[#fafbfe] text-[#737991]'}`}><span className="grid h-9 w-9 place-items-center rounded-xl bg-white"><Layers3 className="h-4 w-4"/></span><span><strong className="block text-sm">Suscripciones</strong><span className="text-xs opacity-70">{subs.length} activa(s) o registradas</span></span></button><button onClick={()=>setTab('requests')} className={`flex items-center gap-3 rounded-2xl px-4 py-3 text-left ${tab==='requests'?'bg-brand-50 text-brand-700':'bg-[#fafbfe] text-[#737991]'}`}><span className="grid h-9 w-9 place-items-center rounded-xl bg-white"><Clock3 className="h-4 w-4"/></span><span><strong className="block text-sm">Solicitudes</strong><span className="text-xs opacity-70">{reqs.filter(r=>r.status==='pending').length} pendiente(s)</span></span></button></div></div>
  <div className="mt-5">{loading?<Loading/>:tab==='subscriptions'?<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Propietario</th><th>Plan</th><th>Negocios</th><th>Precio</th><th>Estado</th><th>Inicio</th><th>Fin</th></tr></thead><tbody>{subs.length?subs.map(s=><tr key={s.id}><td><div className="font-semibold">{s.user_name}</div><div className="text-xs text-[#a2a6b8]">{phoneDisplay(s.user_phone)||'Sin WhatsApp'}</div></td><td className="font-semibold">{s.plan_name}</td><td>{s.stores}</td><td>{s.price?money(s.price):'Gratis'}</td><td><Status value={s.status}/></td><td>{dateTime(s.starts_at)}</td><td>{s.ends_at?dateTime(s.ends_at):'Sin vencimiento'}</td></tr>):<tr><td colSpan={7} className="py-10 text-center text-[#a2a6b8]">No hay suscripciones registradas.</td></tr>}</tbody></table></div>:<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Usuario</th><th>Plan actual</th><th>Solicita</th><th>Nota</th><th>Estado</th><th>Fecha</th><th></th></tr></thead><tbody>{reqs.length?reqs.map(r=><tr key={r.id}><td><div className="font-semibold">{r.user_name}</div><div className="text-xs text-[#a2a6b8]">{phoneDisplay(r.user_phone)||'Sin WhatsApp'}</div></td><td>{r.current_plan}</td><td><div className="font-semibold">{r.requested_plan}</div><div className="text-xs text-[#a2a6b8]">{r.price?money(r.price):'Gratis'}</div></td><td className="max-w-[240px] text-[#8d92aa]">{r.note||'—'}</td><td><Status value={r.status}/></td><td>{dateTime(r.created_at)}</td><td>{r.status==='pending'&&<div className="flex justify-end gap-2"><button disabled={!!busy} className="btn-secondary px-3 text-emerald-700" onClick={()=>review(r.id,'approved')}><Check className="h-4 w-4"/></button><button disabled={!!busy} className="btn-danger px-3" onClick={()=>review(r.id,'rejected')}><X className="h-4 w-4"/></button></div>}</td></tr>):<tr><td colSpan={7} className="py-10 text-center text-[#a2a6b8]">No hay solicitudes.</td></tr>}</tbody></table></div>}</div>
 </SuperAdminShell>
}
