'use client'
import {useEffect,useMemo,useState} from 'react'
import SuperAdminShell from '@/components/superadmin-shell'
import {api,dateTime} from '@/lib/api'
import {phoneDisplay} from '@/components/phone-input'
import {Alert,Loading,Modal,SearchBox,Status} from '@/components/ui'
import {ExternalLink,RefreshCw,Store,Trash2} from 'lucide-react'

export default function AdminStores(){
 const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[filter,setFilter]=useState<'all'|'active'|'inactive'>('all')
 const[deleteTarget,setDeleteTarget]=useState<any>(null),[deleting,setDeleting]=useState(false),[statusBusy,setStatusBusy]=useState(''),[err,setErr]=useState('')
 const load=async()=>{setLoading(true);setErr('');try{setRows(await api<any[]>('/admin/stores'))}catch(e:any){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>rows.filter(x=>{const q=(x.name+' '+x.slug+' '+x.owner+' '+x.owner_phone).toLowerCase();const match=q.includes(search.toLowerCase());const state=filter==='all'||(filter==='active'&&x.is_active)||(filter==='inactive'&&!x.is_active);return match&&state}),[rows,search,filter])
 const remove=async()=>{if(!deleteTarget)return;setDeleting(true);setErr('');try{await api(`/admin/stores/${deleteTarget.id}`,{method:'DELETE'});setRows(v=>v.filter(x=>x.id!==deleteTarget.id));setDeleteTarget(null)}catch(e:any){setErr(e.message)}finally{setDeleting(false)}}
 const toggleStatus=async(s:any)=>{setStatusBusy(s.id);setErr('');try{const next=!s.is_active;await api(`/admin/stores/${s.id}/status`,{method:'PATCH',body:JSON.stringify({is_active:next})});setRows(v=>v.map(x=>x.id===s.id?{...x,is_active:next}:x))}catch(e:any){setErr(e.message)}finally{setStatusBusy('')}}
 const actions=<button className="btn-secondary" onClick={()=>void load()} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Actualizar</button>
 return <SuperAdminShell title="Negocios" subtitle="Todos los comercios creados dentro de WAMERCIO." actions={actions}>
  {err&&<Alert text={err}/>}<div className="admin-form-card"><div className="flex flex-col gap-3 md:flex-row md:items-center"><div className="min-w-0 flex-1"><SearchBox value={search} onChange={setSearch} placeholder="Buscar negocio o propietario..."/></div><select className="field md:w-48" value={filter} onChange={e=>setFilter(e.target.value as any)}><option value="all">Todos los estados</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></div><div className="mt-3 flex flex-wrap gap-2 text-xs text-[#718078]"><span className="admin-chip"><Store className="h-3.5 w-3.5"/>{filtered.length} resultado(s)</span><span className="admin-chip">{rows.filter(x=>x.is_active).length} activos</span><span className="admin-chip">{rows.filter(x=>!x.is_active).length} inactivos</span></div></div>
  <div className="mt-4">{loading?<Loading/>:<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Tienda</th><th>Propietario</th><th>Productos</th><th>Pedidos</th><th>Estado</th><th>Creada</th><th></th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><div className="font-semibold text-[#0a3f2a]">{s.name}</div><div className="text-xs text-[#7f8a84]">/{s.slug}</div></td><td><div>{s.owner}</div><div className="text-xs text-[#7f8a84]">{phoneDisplay(s.owner_phone)||'Sin WhatsApp'}</div></td><td>{s.products}</td><td>{s.orders}</td><td><button type="button" disabled={statusBusy===s.id} onClick={()=>void toggleStatus(s)} title={s.is_active?'Desactivar negocio':'Activar negocio'} className="inline-flex items-center gap-2"><span className="admin-switch" data-on={!!s.is_active}/><Status value={s.is_active?'active':'inactive'}/></button></td><td className="text-[#718078]">{dateTime(s.created_at)}</td><td><div className="flex justify-end gap-2"><a title="Abrir tienda" target="_blank" rel="noreferrer" href={s.public_url||`https://${s.slug}.${process.env.NEXT_PUBLIC_TENANT_ROOT_DOMAIN||'ltd.do'}`} className="btn-secondary px-3"><ExternalLink className="h-4 w-4"/></a><button type="button" title="Eliminar tienda" className="btn-danger px-3" onClick={()=>{setErr('');setDeleteTarget(s)}}><Trash2 className="h-4 w-4"/></button></div></td></tr>)}{filtered.length===0&&<tr><td colSpan={7} className="py-12 text-center text-sm text-[#7f8a84]">No hay negocios para este filtro.</td></tr>}</tbody></table></div>}</div>
  <Modal open={!!deleteTarget} onClose={()=>!deleting&&setDeleteTarget(null)} title="Eliminar tienda" subtitle="Esta acción es permanente y no se puede deshacer.">
   {deleteTarget&&<div>{err&&<Alert text={err}/>}<div className="rounded-xl border border-rose-100 bg-rose-50 p-4 text-sm leading-6 text-rose-800">Vas a eliminar <strong>{deleteTarget.name}</strong>. También se eliminarán definitivamente sus productos, categorías, pedidos, clientes, conversaciones y demás datos asociados.</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-[#eee8df] bg-[#fcfaf6] p-4"><div className="text-xs text-[#718078]">Productos</div><div className="mt-1 text-xl font-semibold text-[#0a3f2a]">{deleteTarget.products}</div></div><div className="rounded-xl border border-[#eee8df] bg-[#fcfaf6] p-4"><div className="text-xs text-[#718078]">Pedidos</div><div className="mt-1 text-xl font-semibold text-[#0a3f2a]">{deleteTarget.orders}</div></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" disabled={deleting} onClick={()=>setDeleteTarget(null)}>Cancelar</button><button type="button" className="btn-danger" disabled={deleting} onClick={()=>void remove()}><Trash2 className="h-4 w-4"/>{deleting?'Eliminando...':'Eliminar definitivamente'}</button></div></div>}
  </Modal>
 </SuperAdminShell>
}
