'use client'
import {useEffect,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {Loading,PageEmpty,Status,Switch} from '@/components/ui'
import {api,dateTime} from '@/lib/api'
import {AudioLines,Search,Save,TriangleAlert} from 'lucide-react'
export default function Voice(){
 const[store,setStore]=useState(''),[settings,setSettings]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false)
 const load=()=>{if(!store)return;setLoading(true);Promise.all([api(`/voice/settings?store_id=${store}`),api<any[]>(`/voice/transcripts?store_id=${store}${q?`&q=${encodeURIComponent(q)}`:''}`)]).then(([s,t])=>{setSettings(s);setRows(t)}).finally(()=>setLoading(false))};useEffect(load,[store]);useEffect(()=>{const t=setTimeout(()=>{if(store)load()},350);return()=>clearTimeout(t)},[q])
 const save=async()=>{setBusy(true);try{await api('/voice/settings',{method:'PUT',body:JSON.stringify({...settings,store_id:store})});load()}finally{setBusy(false)}}
 return <StoreShell title="Voz y transcripciones" subtitle="Convierte notas de voz de WhatsApp en texto buscable sin cambiar el flujo de atención" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store||!settings} className="btn-primary" onClick={save}><Save className="h-4 w-4"/>{busy?'Guardando...':'Guardar'}</button>}>
 {!store?<PageEmpty title="Selecciona un negocio" detail="Elige una tienda para configurar la transcripción de voz."/>:loading&&!settings?<Loading/>:<div className="grid gap-5 xl:grid-cols-[360px_1fr]"><section className="card p-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-600"><AudioLines className="h-5 w-5"/></span><div><h2 className="font-semibold">Transcripción automática</h2><p className="text-xs text-[#8d92aa]">Notas de voz entrantes</p></div></div>{settings&&<div className="mt-5 space-y-3"><Switch checked={!!settings.is_active} onChange={v=>setSettings({...settings,is_active:v})} label="Activar transcripciones"/><Switch checked={!!settings.auto_transcribe_voice_notes} onChange={v=>setSettings({...settings,auto_transcribe_voice_notes:v})} label="Transcribir automáticamente"/><div><label className="label">Idioma</label><select className="field" value={settings.language||'es'} onChange={e=>setSettings({...settings,language:e.target.value})}><option value="es">Español</option><option value="en">Inglés</option><option value="auto">Detección automática</option></select></div>{!settings.provider_configured&&<div className="rounded-2xl bg-amber-50 p-4 text-xs leading-5 text-amber-800"><div className="flex items-center gap-2 font-semibold"><TriangleAlert className="h-4 w-4"/>Proveedor pendiente</div><p className="mt-1">Configura <code>STT_API_URL</code> y, si aplica, <code>STT_API_KEY</code> en el servicio API.</p></div>}</div>}</section><section className="card overflow-hidden"><div className="border-b border-[#edf0f5] p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#a2a6b8]"/><input className="field pl-10" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar dentro de transcripciones..."/></div></div>{rows.length?<div className="divide-y divide-[#edf0f5]">{rows.map(x=><article key={x.id} className="p-4"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">{x.contact_name||x.phone||'Contacto'}</strong><Status value={x.status}/><span className="text-[11px] text-[#9aa0b4]">{dateTime(x.created_at)}</span></div>{x.text?<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#596178]">{x.text}</p>:<p className="mt-2 text-xs text-[#9aa0b4]">{x.error||'Esperando procesamiento...'}</p>}</article>)}</div>:<PageEmpty title="Sin transcripciones" detail="Las notas de voz aparecerán aquí cuando el módulo esté activo."/>}</section></div>}
 </StoreShell>
}
