'use client'
import {useEffect,useState} from 'react'
import AdminShell from '@/components/store-shell'
import {api,money,dateTime} from '@/lib/api'
import {Alert,Loading,Modal,Status} from '@/components/ui'
import type {Plan} from '@/lib/types'
import {Check,MessageCircleMore,Store,Boxes,ShoppingBag,ArrowRight,BarChart3} from 'lucide-react'

export default function Plans(){
 const[p,setP]=useState<Plan[]>([]),[sub,setSub]=useState<any>(null),[reqs,setReqs]=useState<any[]>([]),[selected,setSelected]=useState<Plan|null>(null),[note,setNote]=useState(''),[err,setErr]=useState(''),[ok,setOk]=useState(''),[busy,setBusy]=useState(false)
 const load=()=>Promise.all([api<Plan[]>('/plans'),api('/subscription').catch(()=>null),api<any[]>('/subscription/requests').catch(()=>[])]).then(([plans,current,requests])=>{setP(plans);setSub(current);setReqs(requests)})
 useEffect(()=>{load()},[])
 const request=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);setErr('');setOk('');try{await api('/subscription/requests',{method:'POST',body:JSON.stringify({plan_id:selected.id,note})});setSelected(null);setNote('');setOk('Solicitud enviada al administrador.');await load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 if(!p.length)return <AdminShell title="Plan y suscripción"><Loading/></AdminShell>
 return <AdminShell title="Plan y suscripción" subtitle="Límites SaaS y cambios de plan sin pasarelas externas">
  {err&&<Alert text={err}/>} {ok&&<Alert text={ok} type="success"/>}
  {sub&&<div className="card mb-6 p-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="text-xs font-bold uppercase tracking-widest text-brand-600">Plan actual</div><div className="mt-1 flex items-center gap-3"><h2 className="text-2xl font-black">{sub.plan.name}</h2><Status value={sub.status}/></div><p className="mt-1 text-sm text-slate-500">{sub.plan.price?`${money(sub.plan.price)} / ${sub.plan.billing_period==='monthly'?'mes':sub.plan.billing_period}`:'Plan gratuito'}</p></div><div className="grid flex-[1.4] gap-3 sm:grid-cols-3">{[['Tiendas',sub.usage.stores,sub.plan.max_stores],['Productos',sub.usage.products,sub.plan.max_products],['Pedidos del mes',sub.usage.orders,sub.plan.max_orders]].map(([l,v,max]:any)=><div key={l} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between text-xs font-semibold text-slate-500"><span>{l}</span><span>{v}/{max}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-brand-500" style={{width:`${Math.min(100,(Number(v)/Math.max(1,Number(max)))*100)}%`}}/></div></div>)}</div></div></div>}
  <div className="grid gap-5 lg:grid-cols-3">{p.map(x=><div key={x.id} className={`card relative p-6 ${x.is_featured?'ring-2 ring-brand-500':''}`}>{x.is_featured&&<span className="absolute -top-3 left-6 rounded-full bg-brand-600 px-3 py-1 text-xs font-bold text-white">Recomendado</span>}<h3 className="text-xl font-black text-slate-900">{x.name}</h3><p className="mt-2 min-h-10 text-sm text-slate-500">{x.description||'Plan WAMERCIO'}</p><div className="mt-3 flex items-end gap-1"><span className="text-4xl font-black">{x.price?money(x.price):'Gratis'}</span>{x.price>0&&<span className="pb-1 text-sm text-slate-400">/mes</span>}</div><div className="my-6 border-t border-slate-100"/><div className="space-y-3 text-sm">{[[Store,`${x.max_stores} tienda${x.max_stores>1?'s':''}`],[Boxes,`${x.max_products.toLocaleString()} productos`],[ShoppingBag,`${x.max_orders.toLocaleString()} pedidos/mes`],[MessageCircleMore,x.whatsapp_enabled?'WhatsApp con QR':'Sin WhatsApp']].map(([I,t]:any)=><div key={t} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-50 text-brand-600"><I className="h-4 w-4"/></span><span>{t}</span><Check className="ml-auto h-4 w-4 text-brand-600"/></div>)}</div><button disabled={sub?.plan?.id===x.id||reqs.some(r=>r.status==='pending')} onClick={()=>setSelected(x)} className={`${sub?.plan?.id===x.id?'btn-secondary':'btn-primary'} mt-7 w-full`}>{sub?.plan?.id===x.id?'Plan actual':reqs.some(r=>r.status==='pending')?'Solicitud pendiente':<>Solicitar plan <ArrowRight className="h-4 w-4"/></>}</button></div>)}</div>
  {reqs.length>0&&<div className="card mt-6 overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-100 px-5 py-4"><BarChart3 className="h-5 w-5 text-brand-600"/><div><h3 className="font-bold">Historial de solicitudes</h3><p className="text-xs text-slate-500">Cambios de plan revisados por el SuperAdmin</p></div></div><div className="overflow-x-auto"><table className="table"><thead><tr><th>Plan</th><th>Estado</th><th>Fecha</th><th>Revisión</th></tr></thead><tbody>{reqs.map(r=><tr key={r.id}><td className="font-semibold">{r.plan_name}</td><td><Status value={r.status}/></td><td>{dateTime(r.created_at)}</td><td>{r.reviewed_at?dateTime(r.reviewed_at):'Pendiente'}</td></tr>)}</tbody></table></div></div>}
  <Modal open={!!selected} onClose={()=>setSelected(null)} title={selected?`Solicitar ${selected.name}`:'Solicitar plan'}>{selected&&<form onSubmit={request}><p className="text-sm leading-6 text-slate-600">La solicitud será revisada por el administrador de WAMERCIO. No se procesará ningún pago automáticamente.</p><div className="mt-4 rounded-2xl bg-brand-50 p-4"><div className="font-bold text-brand-800">{selected.name}</div><div className="mt-1 text-2xl font-black text-brand-900">{selected.price?money(selected.price):'Gratis'}</div></div><div className="mt-4"><label className="label">Nota para el administrador (opcional)</label><textarea className="field min-h-24" value={note} onChange={e=>setNote(e.target.value)} placeholder="Ej.: necesito ampliar a dos sucursales..."/></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setSelected(null)}>Cancelar</button><button disabled={busy} className="btn-primary">{busy?'Enviando...':'Enviar solicitud'}</button></div></form>}</Modal>
 </AdminShell>
}
