'use client'
import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime} from '@/lib/api'
import {Alert,Loading,PageEmpty} from '@/components/ui'
import {Settings2,Star,Smile,Meh,Frown,Search,X,Save,MessageCircleMore,MapPin,Printer,FileSpreadsheet} from 'lucide-react'

const faces:any={1:Frown,2:Frown,3:Meh,4:Smile,5:Star}
const defaultSettings={enabled:false,question:'¿Cómo valoras la atención recibida?',options:[{score:1,label:'Mala'},{score:2,label:'Regular'},{score:3,label:'Buena'},{score:4,label:'Muy Buena'},{score:5,label:'Excelente'}],feedback_enabled:true,feedback_max_score:2,feedback_message:'Gracias por tu respuesta. ¿En qué podemos mejorar nuestro servicio?',google_review_enabled:false,google_review_min_score:1,google_review_message:'Gracias por compartir tu valoración. Si deseas, también puedes compartir tu experiencia en Google:',thank_you_message:'Gracias por evaluar nuestra atención. Tu opinión es muy importante para nosotros.'}
function Toggle({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void}){return <button type="button" aria-pressed={checked} onClick={()=>onChange(!checked)} className={`relative h-6 w-11 shrink-0 rounded-full transition ${checked?'bg-brand-500':'bg-slate-200'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition ${checked?'left-6':'left-1'}`}/></button>}

export default function Evaluations(){
 const[store,setStore]=useState(''),[data,setData]=useState<any>(null),[settings,setSettings]=useState<any>(defaultSettings),[modal,setModal]=useState(false),[loading,setLoading]=useState(false),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[score,setScore]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[agent,setAgent]=useState(''),[channel,setChannel]=useState(''),[staff,setStaff]=useState<any[]>([])
 const load=async()=>{if(!store)return;setLoading(true);setErr('');try{const q=new URLSearchParams({store_id:store});if(score!=='all')q.set('score',score);if(from)q.set('from',from);if(to)q.set('to',to);if(agent)q.set('agent_id',agent);if(channel)q.set('source',channel);const[d,s]=await Promise.all([api<any>(`/evaluations?${q}`),api<any>(`/evaluations/settings?store_id=${store}`)]);setData(d);setSettings({...defaultSettings,...s})}catch(e:any){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(store)void load()},[store,score,from,to,agent,channel])
 useEffect(()=>{if(!store){setStaff([]);return}api<any[]>(`/staff?store_id=${store}`).then(setStaff).catch(()=>setStaff([]))},[store])
 const save=async()=>{setBusy(true);setErr('');try{const out=await api(`/evaluations/settings?store_id=${store}`,{method:'PUT',body:JSON.stringify(settings)});setSettings(out);setModal(false)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const summary=data?.summary||{average:0,count:0,counts:{}}
 const printReport=()=>{const items=data?.items||[];const win=window.open('','_blank','width=1100,height=760');if(!win)return;const rows=items.map((x:any)=>`<tr><td>${x.label} · ${x.score}/5</td><td>${x.agent_name||'Atención automática'}</td><td>${x.contact_name}<br><small>${x.contact_phone||''}</small></td><td>${dateTime(x.created_at)}</td><td>${x.feedback||'Sin comentario adicional'}</td></tr>`).join('');win.document.write(`<html><head><title>Evaluaciones</title><style>body{font-family:Arial,sans-serif;padding:28px;color:#20233a}h1{font-size:22px}p{color:#687086}table{width:100%;border-collapse:collapse;margin-top:20px;font-size:12px}th,td{border-bottom:1px solid #e8ebf0;padding:10px;text-align:left}th{background:#f7f8fa}</style></head><body><h1>Evaluaciones de atención</h1><p>Promedio: ${Number(summary.average||0).toFixed(1)} · Total: ${summary.count||0}</p><table><thead><tr><th>Evaluación</th><th>Agente</th><th>Contacto</th><th>Fecha</th><th>Feedback</th></tr></thead><tbody>${rows}</tbody></table></body></html>`);win.document.close();win.focus();win.print()}
 const exportExcel=()=>{const clean=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const lines=[['Evaluación','Puntuación','Agente','Canal','Contacto','WhatsApp','Fecha','Feedback'].map(clean).join(';'),...(data?.items||[]).map((x:any)=>[x.label,x.score,x.agent_name||'Atención automática',x.source||'whatsapp',x.contact_name,x.contact_phone,dateTime(x.created_at),x.feedback||''].map(clean).join(';'))];const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`evaluaciones-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 return <StoreShell title="Evaluaciones" subtitle="Satisfacción real de los clientes después de cada conversación finalizada" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store} className="btn-secondary" onClick={()=>setModal(true)}><Settings2 className="h-4 w-4"/> Configurar evaluaciones</button>}>
  {!store?<PageEmpty title="Selecciona una tienda" detail="Las evaluaciones se registran por negocio y por atención."/>:<div className="space-y-5">{err&&<Alert text={err}/>}<section className="card p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><select className="field" value={agent} onChange={e=>setAgent(e.target.value)}><option value="">Todos los agentes</option>{staff.filter((x:any)=>x.status==='active').map((x:any)=><option key={x.id} value={x.id}>{[x.name,x.last_name].filter(Boolean).join(' ')}</option>)}</select><select className="field" value={channel} onChange={e=>setChannel(e.target.value)}><option value="">Todos los canales</option><option value="whatsapp">WhatsApp</option></select><input type="date" className="field" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" className="field" value={to} onChange={e=>setTo(e.target.value)}/><button className="btn-secondary justify-center" onClick={printReport}><Printer className="h-4 w-4"/> Imprimir</button><button className="btn-secondary justify-center border-emerald-200 text-emerald-700" onClick={exportExcel}><FileSpreadsheet className="h-4 w-4"/> Excel</button></div><div className="mt-3 flex flex-wrap items-center gap-2"><select className="field max-w-xs" value={score} onChange={e=>setScore(e.target.value)}><option value="all">Todas las evaluaciones</option>{settings.options.map((o:any)=><option key={o.score} value={o.score}>{o.score} · {o.label}</option>)}</select><button className="btn-secondary" onClick={load}><Search className="h-4 w-4"/> Actualizar</button></div></section>
   {loading?<Loading/>:<><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7"><article className="card border-brand-200 p-4"><Star className="h-5 w-5 text-amber-500"/><div className="mt-2 text-2xl font-semibold">{Number(summary.average||0).toFixed(1)}</div><div className="text-[10px] font-semibold uppercase tracking-wide text-[#9298ad]">Promedio</div></article>{settings.options.slice().reverse().map((o:any)=>{const I=faces[o.score]||Smile;return <button key={o.score} onClick={()=>setScore(String(o.score))} className="card p-4 text-left"><I className="h-5 w-5 text-brand-600"/><div className="mt-2 text-xl font-semibold">{summary.counts?.[o.score]||0}</div><div className="text-[10px] font-semibold uppercase tracking-wide text-[#9298ad]">{o.label}</div></button>})}<article className="card p-4"><Search className="h-5 w-5 text-brand-600"/><div className="mt-2 text-xl font-semibold">{summary.count||0}</div><div className="text-[10px] font-semibold uppercase tracking-wide text-[#9298ad]">Mostrar todo</div></article></section>
    {data?.items?.length?<section className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#fbfbfc] text-[10px] font-semibold uppercase tracking-wide text-[#8f95aa]"><tr><th className="px-5 py-3">Evaluación</th><th className="px-5 py-3">Usuario evaluado</th><th className="px-5 py-3">Contacto</th><th className="px-5 py-3">Fecha</th><th className="px-5 py-3">Feedback del cliente</th></tr></thead><tbody>{data.items.map((x:any)=><tr key={x.id} className="border-t border-[#edf0f4]"><td className="px-5 py-4"><span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">{x.label} · {x.score}/5</span></td><td className="px-5 py-4"><div className="font-medium">{x.agent_name||'Atención automática'}</div><div className="text-xs text-[#9aa0b4]">WhatsApp</div></td><td className="px-5 py-4"><div className="font-medium">{x.contact_name}</div><div className="text-xs text-[#9aa0b4]">+{x.contact_phone}</div></td><td className="whitespace-nowrap px-5 py-4 text-[#6f758b]">{dateTime(x.created_at)}</td><td className="max-w-sm px-5 py-4 text-[#7f8498]">{x.feedback||'Sin comentario adicional'}</td></tr>)}</tbody></table></div></section>:<PageEmpty title="Sin evaluaciones" detail={settings.enabled?'Las respuestas aparecerán cuando cierres conversaciones y los clientes evalúen la atención.':'Activa la encuesta nativa de WhatsApp desde Configurar evaluaciones.'}/>}</>}
  </div>}
  {modal&&<div className="fixed inset-0 z-[80] grid place-items-center bg-[#20233a]/40 p-3"><section className="flex max-h-[94dvh] w-full max-w-5xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-[#edf0f4] px-5 py-4"><div><div className="flex items-center gap-2"><h2 className="text-xl font-semibold">Configurar evaluaciones</h2><span className="rounded-full bg-brand-50 px-2.5 py-1 text-[10px] font-semibold text-brand-700">WhatsApp</span></div><p className="mt-1 text-xs text-[#8d92aa]">Define la encuesta, feedback y acciones posteriores a cada atención.</p></div><button className="rounded-xl bg-[#f6f7f9] p-2" onClick={()=>setModal(false)}><X className="h-5 w-5"/></button></header><div className="min-h-0 flex-1 space-y-5 overflow-y-auto p-5"><div className="flex items-center gap-4 rounded-2xl border border-[#edf0f4] p-4"><MessageCircleMore className="h-5 w-5 text-brand-600"/><div className="min-w-0 flex-1"><div className="text-sm font-semibold">Enviar evaluación al finalizar la conversación</div><p className="text-xs text-[#8d92aa]">Se envía una encuesta nativa de WhatsApp. La primera respuesta válida queda registrada como evaluación definitiva.</p></div><Toggle checked={!!settings.enabled} onChange={v=>setSettings({...settings,enabled:v})}/></div>
   <section className="rounded-3xl border border-[#edf0f4] p-5"><h3 className="font-semibold">Encuesta de satisfacción</h3><div className="mt-4"><label className="label">Pregunta</label><input className="field" value={settings.question} onChange={e=>setSettings({...settings,question:e.target.value})}/></div><div className="mt-4 grid gap-3 sm:grid-cols-5">{settings.options.map((o:any,i:number)=><div key={o.score} className="rounded-2xl bg-[#fafbfc] p-3"><div className="text-[10px] font-semibold uppercase text-[#9ba0b4]">Respuesta {o.score}</div><input className="field mt-2" value={o.label} onChange={e=>{const options=settings.options.slice();options[i]={...o,label:e.target.value};setSettings({...settings,options})}}/><div className="mt-2 text-center text-[10px] text-[#9ba0b4]">{o.score} punto{o.score!==1?'s':''} fijo{o.score!==1?'s':''}</div></div>)}</div></section>
   <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-3xl border border-[#edf0f4] p-5"><div className="flex items-center gap-3"><MessageCircleMore className="h-5 w-5 text-rose-500"/><div className="flex-1"><h3 className="font-semibold">Recuperar feedback</h3><p className="text-xs text-[#8d92aa]">Pregunta qué se puede mejorar cuando la valoración cumple la condición.</p></div><Toggle checked={!!settings.feedback_enabled} onChange={v=>setSettings({...settings,feedback_enabled:v})}/></div><div className="mt-4 grid gap-3 sm:grid-cols-[150px_1fr]"><div><label className="label">Si la puntuación es hasta</label><select className="field" value={settings.feedback_max_score} onChange={e=>setSettings({...settings,feedback_max_score:Number(e.target.value)})}>{settings.options.map((o:any)=><option key={o.score} value={o.score}>{o.score} · {o.label}</option>)}</select></div><div><label className="label">Mensaje de seguimiento</label><textarea className="field min-h-24" value={settings.feedback_message} onChange={e=>setSettings({...settings,feedback_message:e.target.value})}/></div></div></section>
    <section className="rounded-3xl border border-[#edf0f4] p-5"><div className="flex items-center gap-3"><MapPin className="h-5 w-5 text-brand-600"/><div className="flex-1"><h3 className="font-semibold">Invitación neutral a reseña</h3><p className="text-xs text-[#8d92aa]">Ofrece el enlace del Perfil de Empresa en Google sin pedir una calificación concreta.</p></div><Toggle checked={!!settings.google_review_enabled} onChange={v=>setSettings({...settings,google_review_enabled:v})}/></div><div className="mt-4"><label className="label">Enviar invitación si la puntuación es desde</label><select className="field" value={settings.google_review_min_score} onChange={e=>setSettings({...settings,google_review_min_score:Number(e.target.value)})}>{settings.options.map((o:any)=><option key={o.score} value={o.score}>{o.score} · {o.label}</option>)}</select></div><div className="mt-3"><label className="label">Mensaje de invitación</label><textarea className="field min-h-24" value={settings.google_review_message} onChange={e=>setSettings({...settings,google_review_message:e.target.value})}/></div></section></div>
   <section className="rounded-3xl border border-[#edf0f4] p-5"><label className="label">Mensaje de agradecimiento al completar la evaluación</label><textarea className="field min-h-20" value={settings.thank_you_message} onChange={e=>setSettings({...settings,thank_you_message:e.target.value})}/></section></div><footer className="flex justify-end gap-2 border-t border-[#edf0f4] p-4"><button className="btn-secondary" onClick={()=>setModal(false)}>Cancelar</button><button disabled={busy} className="btn-primary" onClick={save}><Save className="h-4 w-4"/> Guardar evaluaciones</button></footer></section></div>}
 </StoreShell>
}
