'use client'
import {useEffect,useMemo,useState} from 'react'
import SuperAdminShell from '@/components/superadmin-shell'
import {api} from '@/lib/api'
import {Alert,Loading} from '@/components/ui'
import {Eye,RotateCcw,Save,ShieldCheck} from 'lucide-react'
const defaults={brand_name:'WAMERCIO',brand_subtitle:'Comercio conversacional',hero_badge:'Comercio conversacional hecho en República Dominicana 🇩🇴',hero_title:'Tu comercio y tus pedidos más fáciles con WhatsApp.',hero_subtitle:'Crea tu tienda digital, comparte tu catálogo, recibe pedidos y administra clientes desde WAMERCIO. Sin complicaciones y pensado para vender desde el celular.',access_label:'Acceder',demo_label:'Ver demo',maintenance_mode:false,maintenance_title:'Estamos realizando mejoras en la página principal',maintenance_text:'La página principal estará temporalmente en mantenimiento. Los negocios activos continúan operando desde sus subdominios.'}
export default function LandingSettings(){
 const[data,setData]=useState<any>(null),[err,setErr]=useState(''),[saved,setSaved]=useState(false)
 useEffect(()=>{api('/admin/platform/landing').then(x=>setData({...defaults,...x})).catch(e=>setErr(e.message))},[])
 const domain=typeof window!=='undefined'?window.location.hostname:'wamercio.com';const replace=(v:string)=>String(v||'').replaceAll('{domain}',domain)
 const save=async()=>{setErr('');setSaved(false);try{await api('/admin/platform/landing',{method:'PUT',body:JSON.stringify(data)});setSaved(true)}catch(e:any){setErr(e.message)}}
 const preview=useMemo(()=>data?{title:replace(data.hero_title),subtitle:replace(data.hero_subtitle),badge:replace(data.hero_badge)}:null,[data,domain])
 if(!data)return <SuperAdminShell title="Página comercial" subtitle="Personalización de la página comercial"><Loading/></SuperAdminShell>
 return <SuperAdminShell title="Página comercial" subtitle="Personalización de la página comercial" actions={<><a href="/" target="_blank" className="btn-secondary"><Eye className="h-4 w-4"/>Vista pública</a><button className="btn-primary" onClick={save}><Save className="h-4 w-4"/>Guardar</button></>}>
  <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
   <section className="card overflow-hidden"><div className="border-b border-[#edf0f5] p-5 sm:p-6"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-brand-600">Página comercial</div><h2 className="mt-1 text-xl font-semibold">Personalización de la página comercial</h2><p className="mt-1 text-sm text-[#8d92aa]">Personaliza la página principal con el diseño comercial de WAMERCIO. Puedes usar <strong>{'{domain}'}</strong> en cualquier texto.</p></div><div className="space-y-5 p-5 sm:p-6">{err&&<Alert text={err}/>} {saved&&<div className="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">Cambios guardados correctamente.</div>}
    <div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Nombre visible</label><input className="field" value={data.brand_name} onChange={e=>setData({...data,brand_name:e.target.value})}/></div><div><label className="label">Subtítulo</label><input className="field" value={data.brand_subtitle} onChange={e=>setData({...data,brand_subtitle:e.target.value})}/></div></div>
    <div><label className="label">Insignia principal</label><input className="field" value={data.hero_badge} onChange={e=>setData({...data,hero_badge:e.target.value})}/></div>
    <div><label className="label">Título principal</label><textarea className="field min-h-24" value={data.hero_title} onChange={e=>setData({...data,hero_title:e.target.value})}/></div>
    <div><label className="label">Texto principal</label><textarea className="field min-h-28" value={data.hero_subtitle} onChange={e=>setData({...data,hero_subtitle:e.target.value})}/></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Botón acceso</label><input className="field" value={data.access_label} onChange={e=>setData({...data,access_label:e.target.value})}/></div><div><label className="label">Botón demo</label><input className="field" value={data.demo_label} onChange={e=>setData({...data,demo_label:e.target.value})}/></div></div>
    <label className="flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><input type="checkbox" checked={!!data.maintenance_mode} onChange={e=>setData({...data,maintenance_mode:e.target.checked})}/><div><div className="font-semibold text-amber-900">Modo mantenimiento</div><div className="text-xs text-amber-700">Pausa únicamente la página principal; las tiendas y paneles siguen operando.</div></div></label>
    {data.maintenance_mode&&<><div><label className="label">Título de mantenimiento</label><input className="field" value={data.maintenance_title} onChange={e=>setData({...data,maintenance_title:e.target.value})}/></div><div><label className="label">Mensaje de mantenimiento</label><textarea className="field min-h-24" value={data.maintenance_text} onChange={e=>setData({...data,maintenance_text:e.target.value})}/></div></>}
    <button className="btn-secondary" onClick={()=>setData({...defaults})}><RotateCcw className="h-4 w-4"/>Restaurar valores base</button>
   </div></section>
   <aside className="card h-fit p-5 sm:p-6"><div className="mb-4 flex items-center gap-2 text-sm font-semibold"><ShieldCheck className="h-4 w-4 text-brand-600"/>Vista previa</div><div className="rounded-[28px] bg-brand-500 p-6 text-white shadow-lg"><div className="text-[10px] font-bold uppercase tracking-[.15em] text-white/70">{preview?.badge}</div><h3 className="mt-5 text-3xl font-semibold leading-tight">{preview?.title}</h3><p className="mt-4 text-sm leading-6 text-white/80">{preview?.subtitle}</p><div className="mt-6 flex gap-2"><span className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-brand-700">{data.access_label}</span><span className="rounded-full border border-white/50 px-4 py-2 text-xs font-semibold">{data.demo_label}</span></div></div><div className="mt-4 rounded-2xl bg-[#fafbfe] p-4 text-xs leading-5 text-[#8d92aa]">Dominio detectado: <strong className="text-ink-900">{domain}</strong>. El marcador <strong>{'{domain}'}</strong> se reemplaza automáticamente.</div></aside>
  </div>
 </SuperAdminShell>
}
