'use client'
import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,money} from '@/lib/api'
import {Alert,PageEmpty,SearchBox} from '@/components/ui'
import type {Product,Order} from '@/lib/types'
import {Minus,Plus,ShoppingCart,Trash2} from 'lucide-react'
export default function POSPage(){
 const[store,setStore]=useState(''),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[search,setSearch]=useState(''),[cart,setCart]=useState<Record<string,number>>({}),[customer,setCustomer]=useState(''),[phone,setPhone]=useState(''),[payment,setPayment]=useState('cash'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('')
 useEffect(()=>{if(store)Promise.all([api<Product[]>(`/products?store_id=${store}`),api<Order[]>(`/orders?store_id=${store}`)]).then(([p,o])=>{setProducts(p.filter(x=>x.is_active));setOrders(o.slice(0,8))});else{setProducts([]);setOrders([])}},[store])
 const filtered=useMemo(()=>products.filter(p=>(p.name+' '+(p.sku||'')).toLowerCase().includes(search.toLowerCase())),[products,search])
 const items=useMemo(()=>products.filter(p=>cart[p.id]).map(p=>({...p,quantity:cart[p.id]})),[products,cart]);const total=items.reduce((n,p)=>n+Number(p.price)*p.quantity,0)
 const qty=(id:string,d:number)=>setCart(v=>{const n=Math.max(0,(v[id]||0)+d);const next={...v};if(n)next[id]=n;else delete next[id];return next})
 const checkout=async()=>{if(!store||!items.length)return;setBusy(true);setErr('');setMsg('');try{const r:any=await api('/pos/sales',{method:'POST',body:JSON.stringify({store_id:store,customer_name:customer,customer_phone:phone,payment_method:payment,items:items.map(x=>({product_id:x.id,quantity:x.quantity}))})});setCart({});setCustomer('');setPhone('');setMsg(`Venta #${r.number} registrada por ${money(r.total)}.`)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 return <StoreShell title="Punto de Venta" subtitle="Gestiona ventas locales, pedidos asistidos y pedidos en línea desde una misma sección" context={<StoreSelector value={store} onChange={setStore}/> }>
  {!store?<PageEmpty title="Selecciona un negocio" detail="Elige el negocio donde registrarás la venta."/>:<div className="grid gap-5 xl:grid-cols-[1fr_390px]">
   <section><div className="mb-4"><SearchBox value={search} onChange={setSearch} placeholder="Buscar producto por nombre o código..."/></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(p=><button key={p.id} onClick={()=>qty(p.id,1)} className="card p-4 text-left transition hover:-translate-y-0.5 hover:border-brand-200 hover:shadow-md"><div className="flex items-start gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-600"><ShoppingCart className="h-5 w-5"/></div><div className="min-w-0"><div className="truncate font-semibold">{p.name}</div><div className="mt-1 text-sm font-semibold text-brand-700">{money(p.price)}</div><div className="mt-1 text-xs text-[#9ba0b4]">{p.track_stock?`Stock: ${p.stock??0}`:'Disponible'}</div></div></div></button>)}</div><div className="mt-6 card overflow-hidden"><div className="border-b border-[#edf0f5] p-4"><div className="text-[10px] font-bold uppercase tracking-[.14em] text-brand-600">Actividad</div><h2 className="mt-1 font-semibold">Pedidos recientes</h2></div><div className="divide-y divide-[#edf0f5]">{orders.length?orders.map(o=><div key={o.id} className="flex items-center gap-3 p-4 text-sm"><div className="min-w-0 flex-1"><div className="font-semibold">#{o.number} · {o.customer_name}</div><div className="mt-1 text-xs text-[#9ba0b4]">{o.source==='pos'?'Punto de Venta':o.source==='whatsapp'?'WhatsApp':'Tienda en línea'} · {o.status}</div></div><strong>{money(o.total)}</strong></div>):<div className="p-8 text-center text-sm text-[#9ba0b4]">Aún no hay pedidos.</div>}</div></div></section>
   <aside className="card h-fit p-5 xl:sticky xl:top-24"><h2 className="text-lg font-semibold">Venta actual</h2>{err&&<Alert text={err}/>} {msg&&<div className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm font-medium text-emerald-700">{msg}</div>}<div className="mt-4 space-y-2">{items.length?items.map(p=><div key={p.id} className="flex items-center gap-2 rounded-xl bg-[#fafbfe] p-3"><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{p.name}</div><div className="text-xs text-[#8d92aa]">{money(p.price)} c/u</div></div><button className="icon-action" onClick={()=>qty(p.id,-1)}><Minus className="h-3.5 w-3.5"/></button><span className="w-6 text-center text-sm font-semibold">{p.quantity}</span><button className="icon-action" onClick={()=>qty(p.id,1)}><Plus className="h-3.5 w-3.5"/></button><button className="icon-action text-rose-600" onClick={()=>setCart(v=>{const n={...v};delete n[p.id];return n})}><Trash2 className="h-3.5 w-3.5"/></button></div>):<div className="rounded-2xl border border-dashed border-[#dfe4ee] p-8 text-center text-sm text-[#9ba0b4]">Agrega productos para iniciar la venta.</div>}</div>
    <div className="mt-5 grid gap-3"><input className="field" placeholder="Cliente (opcional)" value={customer} onChange={e=>setCustomer(e.target.value)}/><input className="field" placeholder="WhatsApp (opcional)" value={phone} onChange={e=>setPhone(e.target.value)}/><select className="field" value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">Efectivo</option><option value="cash_on_delivery">Tarjeta en terminal</option><option value="bank_transfer">Transferencia electrónica</option></select></div><div className="mt-5 flex items-center justify-between border-t border-[#edf0f5] pt-5"><span className="text-sm text-[#8d92aa]">Total</span><strong className="text-2xl">{money(total)}</strong></div><button disabled={!items.length||busy} onClick={checkout} className="btn-primary mt-4 w-full justify-center">{busy?'Registrando...':'Completar venta'}</button>
   </aside>
  </div>}
 </StoreShell>
}
