'use client'
import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {Alert,Loading,Modal,PageEmpty,Status} from '@/components/ui'
import {api,money} from '@/lib/api'
import {BriefcaseBusiness,Plus,UserRound,CalendarClock} from 'lucide-react'

const blank={stage_id:'',customer_id:'',conversation_id:'',quote_id:'',assigned_staff_id:'',title:'',value:0,probability:50,notes:'',next_action_at:'',status:'open'}
export default function CRM(){
 const[store,setStore]=useState(''),[stages,setStages]=useState<any[]>([]),[ops,setOps]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState('')
 const load=()=>{if(!store)return;setLoading(true);Promise.all([api<any[]>(`/crm/stages?store_id=${store}`),api<any[]>(`/crm/opportunities?store_id=${store}`),api<any[]>(`/customers?store_id=${store}`),api<any[]>(`/staff?store_id=${store}`)]).then(([s,o,c,u])=>{setStages(s.filter(x=>x.is_active));setOps(o.filter(x=>x.status!=='archived'));setCustomers(c);setStaff(u.filter(x=>x.status==='active'))}).finally(()=>setLoading(false))}
 useEffect(load,[store])
 const grouped=useMemo(()=>Object.fromEntries(stages.map(s=>[s.id,ops.filter(o=>o.stage_id===s.id)])),[stages,ops])
 const start=(x?:any,stageID?:string)=>{setEdit(x||null);setErr('');setForm(x?{...x,next_action_at:x.next_action_at?String(x.next_action_at).slice(0,16):''}:{...blank,stage_id:stageID||stages[0]?.id||''});setOpen(true)}
 const payload=(v:any)=>({...v,store_id:store,next_action_at:v.next_action_at?new Date(v.next_action_at).toISOString():null})
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');try{if(edit)await api(`/crm/opportunities/${edit.id}`,{method:'PUT',body:JSON.stringify(payload(form))});else await api('/crm/opportunities',{method:'POST',body:JSON.stringify(payload(form))});setOpen(false);load()}catch(e:any){setErr(e.message)}}
 const move=async(x:any,stageID:string)=>{if(stageID===x.stage_id)return;await api(`/crm/opportunities/${x.id}`,{method:'PUT',body:JSON.stringify(payload({...x,stage_id:stageID}))});load()}
 return <StoreShell title="CRM Comercial" subtitle="Convierte conversaciones, cotizaciones y clientes en oportunidades visibles para todo el equipo" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store||!stages.length} onClick={()=>start()} className="btn-primary"><Plus className="h-4 w-4"/>Nueva oportunidad</button>}>
 {!store?<PageEmpty title="Selecciona un negocio" detail="Elige una tienda para abrir su embudo comercial."/>:loading?<Loading/>:<div className="overflow-x-auto pb-3"><div className="flex min-w-max gap-4">{stages.map(stage=><section key={stage.id} className="w-[310px] shrink-0"><div className="mb-3 flex items-center justify-between rounded-2xl border border-[#edf0f5] bg-white px-4 py-3"><div className="flex items-center gap-2"><span className="h-3 w-3 rounded-full" style={{background:stage.color}}/><strong className="text-sm">{stage.name}</strong><span className="rounded-full bg-[#f2f4f7] px-2 py-0.5 text-[10px] text-[#8d92aa]">{grouped[stage.id]?.length||0}</span></div><button className="text-brand-600" onClick={()=>start(undefined,stage.id)}>+</button></div><div className="space-y-3 rounded-[24px] bg-[#f1f4f8] p-3 min-h-[520px]" onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData('text/opportunity');const x=ops.find(o=>o.id===id);if(x)void move(x,stage.id)}}>{(grouped[stage.id]||[]).map((x:any)=><article draggable onDragStart={e=>e.dataTransfer.setData('text/opportunity',x.id)} key={x.id} onClick={()=>start(x)} className="card cursor-pointer p-4 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-600"><BriefcaseBusiness className="h-4 w-4"/></span><div className="min-w-0 flex-1"><h3 className="line-clamp-2 text-sm font-semibold">{x.title}</h3><div className="mt-1 text-xs text-[#8d92aa]">{x.customer_name||'Sin cliente asignado'}</div></div></div><div className="mt-4 flex items-center justify-between"><strong className="text-sm text-brand-700">{money(x.value)}</strong><span className="text-[10px] font-semibold text-[#8d92aa]">{x.probability}%</span></div>{x.assigned_staff_name&&<div className="mt-3 flex items-center gap-1.5 text-[11px] text-[#8d92aa]"><UserRound className="h-3 w-3"/>{x.assigned_staff_name}</div>}{x.next_action_at&&<div className="mt-1 flex items-center gap-1.5 text-[11px] text-[#8d92aa]"><CalendarClock className="h-3 w-3"/>{new Date(x.next_action_at).toLocaleString('es-DO')}</div>}<div className="mt-3"><Status value={x.status}/></div></article>)}</div></section>)}</div></div>}
 <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar oportunidad':'Nueva oportunidad'} subtitle="Relaciona la oportunidad con un cliente, responsable y próxima acción."><form onSubmit={save} className="space-y-4">{err&&<Alert text={err}/>}<div><label className="label">Título *</label><input required className="field" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="grid gap-3 sm:grid-cols-2"><div><label className="label">Etapa *</label><select required className="field" value={form.stage_id} onChange={e=>setForm({...form,stage_id:e.target.value})}>{stages.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><label className="label">Cliente</label><select className="field" value={form.customer_id||''} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Sin cliente</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name} · {x.phone}</option>)}</select></div></div><div className="grid gap-3 sm:grid-cols-3"><div><label className="label">Valor</label><input className="field" type="number" min="0" step="0.01" value={form.value} onChange={e=>setForm({...form,value:Number(e.target.value)})}/></div><div><label className="label">Probabilidad %</label><input className="field" type="number" min="0" max="100" value={form.probability} onChange={e=>setForm({...form,probability:Number(e.target.value)})}/></div><div><label className="label">Responsable</label><select className="field" value={form.assigned_staff_id||''} onChange={e=>setForm({...form,assigned_staff_id:e.target.value})}><option value="">Sin asignar</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div></div><div><label className="label">Próxima acción</label><input type="datetime-local" className="field" value={form.next_action_at||''} onChange={e=>setForm({...form,next_action_at:e.target.value})}/></div><div><label className="label">Notas</label><textarea className="field min-h-24" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary">Guardar</button></div></form></Modal>
 </StoreShell>
}
