'use client'
import {useEffect,useState} from 'react'
import SuperAdminShell from '@/components/superadmin-shell'
import {api} from '@/lib/api'
import {Alert,Loading,Modal} from '@/components/ui'
import {Settings,MapPin,Store,Globe2,Database,Landmark,MessageCircleMore,Bell,KeyRound,ScanFace,Scale,Cloud,History,Save,Plus,Pencil,Trash2} from 'lucide-react'
const sections=[
 ['Plataforma',[['general','General','Ajustes globales',Settings]]],
 ['Estructura SaaS',[['territory','Territorio','División territorial',MapPin],['business-types','Tipos de negocio','Clasificación y dominios',Store],['domains','Dominios','Subdominios y dominios propios',Globe2],['databases','Bases de datos','Persistencia por negocio',Database],['banks','Bancos','Catálogo bancario',Landmark]]],
 ['Comunicaciones',[['whatsapp','WhatsApp','Proveedor y sesión global',MessageCircleMore],['notifications','Notificaciones','Plantillas de mensajes',Bell]]],
 ['Seguridad y cumplimiento',[['access','Acceso','PIN y recuperación',KeyRound],['identity','Identidad','Cédulas, RNC y límites',ScanFace],['legal','Legal','Términos y privacidad',Scale],['backups','Backups','Cloudflare R2 y copias',Cloud],['audit','Auditoría','Historial de acciones',History]]]
] as const
export default function SaaSSettings(){
 const[active,setActive]=useState('general'),[data,setData]=useState<any>(null),[banks,setBanks]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[err,setErr]=useState(''),[saved,setSaved]=useState(false),[bankOpen,setBankOpen]=useState(false),[bank,setBank]=useState<any>({name:'',short_name:'',is_active:true,sort_order:0})
 const load=()=>{api('/admin/platform/settings').then(setData);api<any[]>('/admin/platform/banks').then(setBanks);api<any[]>('/admin/platform/audit').then(setAudit).catch(()=>{})};useEffect(load,[])
 const save=async()=>{setErr('');setSaved(false);try{await api('/admin/platform/settings',{method:'PUT',body:JSON.stringify(data)});setSaved(true)}catch(e:any){setErr(e.message)}}
 const saveBank=async(e:React.FormEvent)=>{e.preventDefault();try{if(bank.id)await api(`/admin/platform/banks/${bank.id}`,{method:'PUT',body:JSON.stringify(bank)});else await api('/admin/platform/banks',{method:'POST',body:JSON.stringify(bank)});setBankOpen(false);setBank({name:'',short_name:'',is_active:true,sort_order:0});load()}catch(e:any){setErr(e.message)}}
 const delBank=async(x:any)=>{if(confirm(`¿Eliminar ${x.name}?`)){await api(`/admin/platform/banks/${x.id}`,{method:'DELETE'});load()}}
 if(!data)return <SuperAdminShell title="Configuración" subtitle="Centro SaaS"><Loading/></SuperAdminShell>
 const current=sections.flatMap(x=>x[1]).find(x=>x[0]===active)
 return <SuperAdminShell title="Configuración" subtitle="Centro SaaS" actions={<button className="btn-primary" onClick={save}><Save className="h-4 w-4"/>Guardar configuración</button>}>
  <div className="grid gap-5 lg:grid-cols-[250px_1fr]">
   <aside className="card h-fit p-3"><div className="p-3"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-brand-600">Configuración</div><div className="mt-1 text-lg font-semibold">Centro SaaS</div><p className="mt-1 text-xs leading-5 text-[#8d92aa]">Administra la estructura, las integraciones y las políticas de la plataforma.</p></div>{sections.map(([group,items])=><div key={group} className="mt-2"><div className="px-3 py-2 text-[9px] font-bold uppercase tracking-[.14em] text-[#b0b4c4]">{group}</div>{items.map(([id,label,desc,I])=><button key={id} onClick={()=>setActive(id)} className={`mb-1 flex w-full items-center gap-3 rounded-2xl px-3 py-2.5 text-left ${active===id?'bg-brand-50 text-brand-700':'hover:bg-[#fafbfe]'}`}><span className={`grid h-9 w-9 place-items-center rounded-xl ${active===id?'bg-brand-500 text-white':'bg-[#f5f6f9] text-[#8d92aa]'}`}><I className="h-4 w-4"/></span><span><span className="block text-sm font-semibold">{label}</span><span className="block text-[10px] text-[#9ba0b4]">{desc}</span></span></button>)}</div>)}</aside>
   <section className="card min-h-[620px] p-5 sm:p-6">{err&&<Alert text={err}/>} {saved&&<div className="mb-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">Configuración guardada.</div>}<div className="mb-6"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-brand-600">{current?.[1]}</div><h2 className="mt-1 text-xl font-semibold">{current?.[2]}</h2></div>
    {active==='general'&&<div className="grid gap-4 sm:grid-cols-2"><div><label className="label">WhatsApp soporte</label><input className="field" value={data.general?.support_whatsapp||''} onChange={e=>setData({...data,general:{...data.general,support_whatsapp:e.target.value}})}/></div><div><label className="label">Correo soporte</label><input className="field" value={data.general?.support_email||''} onChange={e=>setData({...data,general:{...data.general,support_email:e.target.value}})}/></div><div><label className="label">Plan por defecto</label><input className="field" value={data.general?.default_plan||''} onChange={e=>setData({...data,general:{...data.general,default_plan:e.target.value}})}/></div><div><label className="label">Días de gracia</label><input type="number" className="field" value={data.general?.grace_days||0} onChange={e=>setData({...data,general:{...data.general,grace_days:Number(e.target.value)}})}/></div><div className="sm:col-span-2"><label className="label">Dominio de negocios</label><input className="field" value={data.general?.tenant_domain||'ltd.do'} onChange={e=>setData({...data,general:{...data.general,tenant_domain:e.target.value}})}/></div><label className="sm:col-span-2 flex items-center gap-3 rounded-2xl bg-[#fafbfe] p-4"><input type="checkbox" checked={!!data.general?.public_registration} onChange={e=>setData({...data,general:{...data.general,public_registration:e.target.checked}})}/><span><strong className="block text-sm">Permitir registro público de negocios</strong><span className="text-xs text-[#8d92aa]">Permite el alta automática desde la página principal.</span></span></label></div>}
    {active==='banks'&&<div><div className="mb-4 flex items-center justify-between"><p className="text-sm text-[#8d92aa]">Catálogo central para cuentas y transferencias de los negocios.</p><button className="btn-primary" onClick={()=>{setBank({name:'',short_name:'',is_active:true,sort_order:0});setBankOpen(true)}}><Plus className="h-4 w-4"/>Nuevo banco</button></div><div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Banco</th><th>Nombre corto</th><th>Estado</th><th></th></tr></thead><tbody>{banks.map(x=><tr key={x.id}><td className="font-semibold">{x.name}</td><td>{x.short_name}</td><td>{x.is_active?'Activo':'Inactivo'}</td><td className="text-right"><button className="btn-secondary px-3" onClick={()=>{setBank({...x});setBankOpen(true)}}><Pencil className="h-4 w-4"/></button><button className="btn-danger ml-2 px-3" onClick={()=>delBank(x)}><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div></div>}
    {active==='identity'&&<div className="max-w-2xl space-y-4"><label className="flex items-center gap-3 rounded-2xl bg-[#fafbfe] p-4"><input type="checkbox" checked={!!data.identity?.enabled} onChange={e=>setData({...data,identity:{...data.identity,enabled:e.target.checked}})}/><span><strong className="block text-sm">Habilitar Identidad Dominicana</strong><span className="text-xs text-[#8d92aa]">Preparado para verificar cédulas/RNC y propietarios.</span></span></label><label className="flex items-center gap-3 rounded-2xl bg-[#fafbfe] p-4"><input type="checkbox" checked={!!data.identity?.require_owner_verification} onChange={e=>setData({...data,identity:{...data.identity,require_owner_verification:e.target.checked}})}/><span className="text-sm font-semibold">Exigir verificación al propietario</span></label></div>}
    {active==='backups'&&<div className="max-w-2xl space-y-4"><div><label className="label">Proveedor</label><input className="field" value={data.backups?.provider||'Cloudflare R2'} onChange={e=>setData({...data,backups:{...data.backups,provider:e.target.value}})}/></div><label className="flex items-center gap-3 rounded-2xl bg-[#fafbfe] p-4"><input type="checkbox" checked={!!data.backups?.enabled} onChange={e=>setData({...data,backups:{...data.backups,enabled:e.target.checked}})}/><span className="text-sm font-semibold">Backups automáticos habilitados</span></label></div>}
    {active==='territory'&&<div className="max-w-2xl space-y-4"><div><label className="label">Proveedor territorial</label><input className="field" value={data.territory?.provider||'GEO RD MAP'} onChange={e=>setData({...data,territory:{...data.territory,provider:e.target.value}})}/></div><label className="flex items-center gap-3 rounded-2xl bg-[#fafbfe] p-4"><input type="checkbox" checked={!!data.territory?.enabled} onChange={e=>setData({...data,territory:{...data.territory,enabled:e.target.checked}})}/><span><strong className="block text-sm">Integración territorial activa</strong><span className="text-xs text-[#8d92aa]">Centraliza provincias, municipios, sectores y zonas de entrega.</span></span></label></div>}
    {active==='business-types'&&<div className="max-w-2xl rounded-2xl bg-[#fafbfe] p-6"><h3 className="font-semibold">Tipos de negocio basados en plantillas</h3><p className="mt-2 text-sm leading-6 text-[#8d92aa]">WAMERCIO utiliza plantillas comerciales por tipo de negocio. Se conserva esa arquitectura y el catálogo se administra desde la sección existente.</p><a href="/admin/templates" className="btn-primary mt-4 inline-flex">Administrar tipos y plantillas</a></div>}
    {active==='domains'&&<div className="max-w-2xl space-y-4"><div><label className="label">Dominio comodín de negocios</label><input className="field" value={data.domains?.tenant_domain||'ltd.do'} onChange={e=>setData({...data,domains:{...data.domains,tenant_domain:e.target.value}})}/></div><label className="flex items-center gap-3 rounded-2xl bg-[#fafbfe] p-4"><input type="checkbox" checked={!!data.domains?.custom_domains_enabled} onChange={e=>setData({...data,domains:{...data.domains,custom_domains_enabled:e.target.checked}})}/><span className="text-sm font-semibold">Permitir dominios propios</span></label></div>}
    {active==='databases'&&<div className="max-w-2xl rounded-2xl border border-[#edf0f5] bg-[#fafbfe] p-6"><h3 className="font-semibold">Arquitectura de datos actual</h3><p className="mt-2 text-sm leading-6 text-[#8d92aa]">WAMERCIO conserva su arquitectura PostgreSQL central con aislamiento lógico por negocio. No se copia el patrón de una base física por tenant porque esta versión fue concebida con un modelo conversacional compartido.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white p-4"><div className="text-xs text-[#9ba0b4]">Motor</div><div className="mt-1 font-semibold">{data.database?.engine||'PostgreSQL'}</div></div><div className="rounded-xl bg-white p-4"><div className="text-xs text-[#9ba0b4]">Aislamiento</div><div className="mt-1 font-semibold">Por negocio</div></div></div></div>}
    {active==='whatsapp'&&<div className="max-w-2xl space-y-4"><div><label className="label">Proveedor</label><input className="field" value={data.whatsapp?.provider||'WhatsApp Bridge'} onChange={e=>setData({...data,whatsapp:{...data.whatsapp,provider:e.target.value}})}/></div><div className="rounded-2xl bg-[#fafbfe] p-4 text-sm text-[#8d92aa]">La sesión global de soporte se administra desde el módulo existente de soporte WhatsApp.</div><a href="/admin/whatsapp" className="btn-primary inline-flex">Abrir soporte WhatsApp</a></div>}
    {active==='notifications'&&<div className="max-w-2xl space-y-4"><div><label className="label">Plantilla · Nuevo pedido</label><input className="field" value={data.notifications?.order_new||''} onChange={e=>setData({...data,notifications:{...data.notifications,order_new:e.target.value}})}/></div><div><label className="label">Plantilla · Pedido listo</label><input className="field" value={data.notifications?.order_ready||''} onChange={e=>setData({...data,notifications:{...data.notifications,order_ready:e.target.value}})}/></div></div>}
    {active==='access'&&<div className="max-w-2xl grid gap-4 sm:grid-cols-2"><div><label className="label">PIN propietarios</label><input type="number" min="4" max="8" className="field" value={data.access?.owner_pin_length||4} onChange={e=>setData({...data,access:{...data.access,owner_pin_length:Number(e.target.value)}})}/></div><div><label className="label">PIN usuarios internos</label><input type="number" min="4" max="8" className="field" value={data.access?.staff_pin_length||4} onChange={e=>setData({...data,access:{...data.access,staff_pin_length:Number(e.target.value)}})}/></div></div>}
    {active==='legal'&&<div className="max-w-2xl space-y-4"><div><label className="label">URL términos</label><input className="field" value={data.legal?.terms_url||''} onChange={e=>setData({...data,legal:{...data.legal,terms_url:e.target.value}})}/></div><div><label className="label">URL privacidad</label><input className="field" value={data.legal?.privacy_url||''} onChange={e=>setData({...data,legal:{...data.legal,privacy_url:e.target.value}})}/></div></div>}
    {active==='audit'&&<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Acción</th><th>Actor</th><th>Entidad</th><th>Fecha</th></tr></thead><tbody>{audit.length?audit.map(x=><tr key={x.id}><td className="font-semibold">{x.action}</td><td>{x.actor}</td><td>{x.entity_type} {x.entity_id}</td><td>{new Date(x.created_at).toLocaleString('es-DO')}</td></tr>):<tr><td colSpan={4} className="py-10 text-center text-[#9ba0b4]">La auditoría aparecerá cuando se registren cambios centralizados.</td></tr>}</tbody></table></div>}
    {!['general','banks','identity','backups','territory','business-types','domains','databases','whatsapp','notifications','access','legal','audit'].includes(active)&&<div className="rounded-2xl border border-dashed border-[#dfe4ee] bg-[#fafbfe] p-8 text-center"><div className="text-sm font-semibold text-ink-900">Configuración centralizada</div><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-[#8d92aa]">Esta sección conserva el patrón de WAMERCIO y queda preparada para concentrar la configuración de {current?.[1]?.toLowerCase()} sin mezclarla con la operación diaria de cada negocio.</p></div>}
   </section>
  </div>
  <Modal open={bankOpen} onClose={()=>setBankOpen(false)} title={bank.id?'Editar banco':'Nuevo banco'}><form onSubmit={saveBank}><div className="space-y-4"><div><label className="label">Nombre *</label><input required className="field" value={bank.name} onChange={e=>setBank({...bank,name:e.target.value})}/></div><div><label className="label">Nombre corto</label><input className="field" value={bank.short_name||''} onChange={e=>setBank({...bank,short_name:e.target.value})}/></div>{bank.id&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!bank.is_active} onChange={e=>setBank({...bank,is_active:e.target.checked})}/>Activo</label>}</div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setBankOpen(false)}>Cancelar</button><button className="btn-primary">Guardar</button></div></form></Modal>
 </SuperAdminShell>
}
