'use client'
import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import CatalogNav from '@/components/catalog-nav'
import {api,money,upload} from '@/lib/api'
import {Alert,ImagePicker,Loading,Modal,OptionEditor,PageEmpty,SearchBox,Status,Switch} from '@/components/ui'
import type {Allergen,Category,ModifierGroup,PriceOption,Product,Store} from '@/lib/types'
import {resolveBusinessCapabilities} from '@/lib/business-capabilities'
import {Plus,Boxes,Pencil,Trash2,ChevronDown,Sparkles,Package2,Image as ImageIcon,ListFilter,Layers3,ShieldAlert,PackagePlus,Images,Languages,ArrowUp,ArrowDown,UploadCloud} from 'lucide-react'

type AttributeDef={id:string;key:string;label:string;input_type:string;options:any[];is_required:boolean;sort_order:number;group_name:string}

const blank={name:'',slug:'',sku:'',tag:'',description:'',image_url:'',category_id:'',price:0,compare_price:null as number|null,stock:null as number|null,track_stock:false,variants:[] as PriceOption[],extras:[] as PriceOption[],attributes:{} as Record<string,any>,is_featured:false,sort_order:0,is_active:true,modifier_group_ids:[] as string[],bundle_components:[] as {product_id:string;quantity:number;sort_order?:number}[],allergen_ids:[] as string[],dietary_tags:[] as string[],product_media:[] as {id?:string;url:string;alt_text:string;sort_order:number}[],product_translations:[] as {locale:string;name:string;description:string}[]}

export default function Products(){
 const[store,setStore]=useState(''),[currentStore,setCurrentStore]=useState<Store|null>(null),[rows,setRows]=useState<Product[]>([]),[cats,setCats]=useState<Category[]>([]),[attrs,setAttrs]=useState<AttributeDef[]>([]),[modifierGroups,setModifierGroups]=useState<ModifierGroup[]>([]),[allergens,setAllergens]=useState<Allergen[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[edit,setEdit]=useState<Product|null>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState(''),[search,setSearch]=useState(''),[up,setUp]=useState(false),[advanced,setAdvanced]=useState(false)
 const capabilities=useMemo(()=>resolveBusinessCapabilities(currentStore),[currentStore])
 const load=()=>{if(!store){setRows([]);setCats([]);setAttrs([]);setModifierGroups([]);setAllergens([]);return};setLoading(true);Promise.all([api<Product[]>(`/products?store_id=${store}`),api<Category[]>(`/categories?store_id=${store}`),api<AttributeDef[]>(`/product-attributes?store_id=${store}`),api<ModifierGroup[]>(`/modifier-groups?store_id=${store}`),api<Allergen[]>(`/allergens?store_id=${store}`)]).then(([p,c,a,m,al])=>{setRows(p);setCats(c);setAttrs(a);setModifierGroups(m);setAllergens(al)}).finally(()=>setLoading(false))}
 useEffect(load,[store])
 const filtered=useMemo(()=>rows.filter(x=>(x.name+' '+(x.description||'')).toLowerCase().includes(search.toLowerCase())),[rows,search])
 const start=(x?:Product)=>{setEdit(x||null);setForm(x?{...x,variants:x.variants||[],extras:x.extras||[],attributes:x.attributes||{},modifier_group_ids:x.modifier_group_ids||[],bundle_components:x.bundle_components||[],allergen_ids:x.allergen_ids||[],dietary_tags:x.dietary_tags||[],product_media:x.product_media||[],product_translations:x.product_translations||[]}:{...blank,track_stock:capabilities.trackStockDefault,stock:capabilities.trackStockDefault?0:null,attributes:{},modifier_group_ids:[],bundle_components:[],allergen_ids:[],dietary_tags:[],product_media:[],product_translations:[],sort_order:(rows.length+1)*10});setAdvanced(!!(x&&(x.track_stock||x.variants?.length||x.extras?.length||x.modifier_group_ids?.length||x.bundle_components?.length||x.allergen_ids?.length||x.dietary_tags?.length||x.product_media?.length||x.product_translations?.length||!x.is_active||x.attributes?.wamercio_weighted_sale)));setErr('');setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');try{const body={...form,store_id:store,slug:form.slug||'',sku:form.sku||'',tag:form.tag||'',compare_price:form.compare_price||null,is_featured:!!form.is_featured,sort_order:Number(form.sort_order||0)};let productID=edit?.id||'';if(edit)await api(`/products/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else{const created=await api<{id:string}>('/products',{method:'POST',body:JSON.stringify(body)});productID=created.id}await api(`/products/${productID}/composition`,{method:'PUT',body:JSON.stringify({store_id:store,modifier_group_ids:form.modifier_group_ids||[],bundle_components:(form.bundle_components||[]).map((x:any,i:number)=>({...x,quantity:Number(x.quantity||1),sort_order:(i+1)*10})),allergen_ids:form.allergen_ids||[],dietary_tags:form.dietary_tags||[]})});await api(`/products/${productID}/experience`,{method:'PUT',body:JSON.stringify({store_id:store,product_media:(form.product_media||[]).filter((x:any)=>String(x.url||'').trim()).map((x:any,i:number)=>({...x,url:String(x.url).trim(),alt_text:String(x.alt_text||'').trim(),sort_order:(i+1)*10})),product_translations:(form.product_translations||[]).filter((x:any)=>String(x.locale||'').trim()&&String(x.locale||'').trim()!=='es').map((x:any)=>({locale:String(x.locale).trim().toLowerCase(),name:String(x.name||'').trim(),description:String(x.description||'').trim()}))})});setOpen(false);load()}catch(e:any){setErr(e.message)}}
 const del=async(x:Product)=>{if(!confirm(`¿Eliminar ${x.name}?`))return;await api(`/products/${x.id}`,{method:'DELETE'}).catch(e=>alert(e.message));load()}
 const pick=async(f:File)=>{setUp(true);try{const url=await upload(f);setForm((v:any)=>({...v,image_url:url}))}catch(e:any){setErr(e.message)}finally{setUp(false)}}
 const toggleList=(key:'modifier_group_ids'|'allergen_ids'|'dietary_tags',id:string)=>setForm((v:any)=>({...v,[key]:(v[key]||[]).includes(id)?(v[key]||[]).filter((x:string)=>x!==id):[...(v[key]||[]),id]}))
 const addBundleComponent=()=>{const candidate=rows.find(x=>x.id!==edit?.id&&!(form.bundle_components||[]).some((c:any)=>c.product_id===x.id));if(candidate)setForm((v:any)=>({...v,bundle_components:[...(v.bundle_components||[]),{product_id:candidate.id,quantity:1}]}))}
 const updateBundleComponent=(i:number,patch:any)=>setForm((v:any)=>({...v,bundle_components:(v.bundle_components||[]).map((x:any,j:number)=>j===i?{...x,...patch}:x)}))
 const removeBundleComponent=(i:number)=>setForm((v:any)=>({...v,bundle_components:(v.bundle_components||[]).filter((_:any,j:number)=>j!==i)}))
 const addMedia=()=>setForm((v:any)=>({...v,product_media:[...(v.product_media||[]),{url:'',alt_text:'',sort_order:((v.product_media||[]).length+1)*10}]}))
 const updateMedia=(i:number,patch:any)=>setForm((v:any)=>({...v,product_media:(v.product_media||[]).map((x:any,j:number)=>j===i?{...x,...patch}:x)}))
 const removeMedia=(i:number)=>setForm((v:any)=>({...v,product_media:(v.product_media||[]).filter((_:any,j:number)=>j!==i)}))
 const moveMedia=(i:number,dir:number)=>setForm((v:any)=>{const a=[...(v.product_media||[])];const j=i+dir;if(j<0||j>=a.length)return v;[a[i],a[j]]=[a[j],a[i]];return {...v,product_media:a}})
 const uploadMedia=async(i:number,f:File)=>{setUp(true);setErr('');try{const url=await upload(f);updateMedia(i,{url})}catch(e:any){setErr(e.message)}finally{setUp(false)}}
 const addTranslation=()=>setForm((v:any)=>{const used=new Set((v.product_translations||[]).map((x:any)=>x.locale));const locale=['en','fr','de','pt','it'].find(x=>!used.has(x))||'en';return {...v,product_translations:[...(v.product_translations||[]),{locale,name:'',description:''}]}})
 const updateTranslation=(i:number,patch:any)=>setForm((v:any)=>({...v,product_translations:(v.product_translations||[]).map((x:any,j:number)=>j===i?{...x,...patch}:x)}))
 const removeTranslation=(i:number)=>setForm((v:any)=>({...v,product_translations:(v.product_translations||[]).filter((_:any,j:number)=>j!==i)}))
 const categoryName=cats.find(c=>c.id===form.category_id)?.name||'Sin categoría'
 const itemLabel=capabilities.itemLabel
 const itemLabelPlural=capabilities.itemPlural
 const cap=(v:string)=>v.charAt(0).toUpperCase()+v.slice(1)
 const newLabel='Nuevo producto'
 const nameLabel=`Nombre del ${itemLabel}`
 const variantHint=capabilities.variantHint
 const engine=capabilities.engine
 const weightedProduct=!!form.attributes?.wamercio_weighted_sale
 const attributeGroups=useMemo(()=>{const map=new Map<string,AttributeDef[]>();for(const a of attrs){const key=a.group_name||'Detalles';const list=map.get(key)||[];list.push(a);map.set(key,list)}return Array.from(map.entries())},[attrs])

 return <StoreShell title={cap(itemLabelPlural)} subtitle="Tu catálogo, sin configuraciones técnicas" context={<StoreSelector value={store} onChange={setStore} onStoreChange={setCurrentStore}/>} actions={<button disabled={!store} onClick={()=>start()} className="btn-primary"><Plus className="h-4 w-4"/> {newLabel}</button>}>
  <CatalogNav/>
  <div className="mb-5"><SearchBox value={search} onChange={setSearch} placeholder="Buscar productos..."/></div>
  {!store?<PageEmpty title="Selecciona una tienda" detail="Elige la tienda cuyo catálogo quieres administrar."/>:loading?<Loading/>:filtered.length===0?<PageEmpty title="Tu catálogo está listo para crecer" detail={`Agrega tu primer ${itemLabel}. WAMERCIO se ocupa del identificador, orden y demás datos técnicos.`} action={<button className="btn-primary" onClick={()=>start()}>Agregar {itemLabel}</button>}/>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map(x=>{
   const cat=cats.find(c=>c.id===x.category_id)?.name||'Sin categoría'
   return <article key={x.id} className="merchant-grid-card group"><button onClick={()=>start(x)} className="block w-full text-left"><div className="relative aspect-[4/3] overflow-hidden bg-[#f4f6f8]">{x.image_url?<img src={x.image_url} className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.02]"/>:<div className="grid h-full place-items-center text-slate-300"><Boxes className="h-10 w-10"/></div>}{x.track_stock&&Number(x.stock||0)<=0&&<span className="absolute left-3 top-3 rounded-full bg-rose-600 px-2.5 py-1 text-[10px] font-bold uppercase text-white">Agotado</span>}</div><div className="p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><h3 className="truncate font-semibold text-ink-900">{x.name}</h3><p className="mt-1 truncate text-xs text-[#989db0]">{cat}</p></div><strong className="shrink-0 text-brand-700">{money(x.price)}</strong></div><p className="mt-3 line-clamp-2 min-h-10 text-sm leading-5 text-[#858ba3]">{x.description||'Listo para vender.'}</p><div className="mt-4 flex items-center justify-between"><Status value={x.is_active?'active':'inactive'}/><span className="text-xs text-[#9ca1b3]">{x.variants?.length||0} variantes · {x.extras?.length||0} extras</span></div></div></button><div className="flex border-t border-slate-100"><button onClick={()=>start(x)} className="flex flex-1 items-center justify-center gap-2 py-3 text-xs font-semibold text-[#71778e] hover:bg-[#fafbfc] hover:text-brand-700"><Pencil className="h-3.5 w-3.5"/>Editar</button><button onClick={()=>del(x)} className="grid w-12 place-items-center border-l border-slate-100 text-[#a3a8b8] hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></div></article>
  })}</div>}

  <Modal open={open} onClose={()=>setOpen(false)} title={edit?`Editar ${itemLabel}`:newLabel} subtitle={`WAMERCIO adapta este formulario al tipo de negocio: ${currentStore?.template_name||'venta estándar'}.`} wide>
   <form onSubmit={save}>
    {err&&<Alert text={err}/>}<div className="grid gap-6 xl:grid-cols-[280px_minmax(0,1fr)]">
      <aside className="space-y-4 xl:sticky xl:top-0 xl:self-start">
        <div className="rounded-[28px] border border-[#edf0f4] bg-[#fbfcfd] p-4"><ImagePicker value={form.image_url} onPick={pick} onClear={()=>setForm({...form,image_url:''})} label={`Foto del ${itemLabel}`} busy={up}/><div className="mt-4 rounded-2xl bg-white p-4"><p className="text-sm font-semibold text-ink-900">Vista rápida</p><div className="mt-3 flex items-center gap-3 rounded-2xl border border-[#edf0f4] p-3"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-2xl bg-[#f3f5f7]">{form.image_url?<img src={form.image_url} className="h-full w-full object-cover"/>:<ImageIcon className="h-5 w-5 text-[#b1b6c5]"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-ink-900">{form.name||nameLabel}</p><p className="mt-1 truncate text-xs text-[#9aa0b4]">{categoryName}</p><p className="mt-2 text-sm font-semibold text-brand-700">{money(Number(form.price||0))}{weightedProduct&&<span className="ml-1 text-[10px] text-[#9aa0b4]">/ lb</span>}</p></div></div><p className="mt-3 text-xs leading-5 text-[#9ca1b3]">Usa una imagen clara. El cliente verá primero la foto, el nombre y el precio.</p></div></div>
      </aside>

      <div className="space-y-5">
        <section className="rounded-[28px] border border-[#edf0f4] bg-white p-5">
          <div className="mb-4 flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Package2 className="h-5 w-5"/></span><div><h3 className="text-base font-semibold text-ink-900">Información principal</h3><p className="text-sm text-[#8d92aa]">Solo completa lo que el cliente necesita ver en el catálogo.</p></div></div>
          <div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label">{nameLabel} *</label><input autoFocus className="field" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder={engine==='food'?'Ej.: Pizza familiar':engine==='fashion'?'Ej.: Vestido midi':engine==='services'?'Ej.: Corte + barba':'Ej.: Producto destacado'}/></div><div><label className="label">Categoría</label><select className="field" value={form.category_id||''} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Sin categoría</option>{cats.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div><label className="label">{weightedProduct?'Precio por libra *':'Precio *'}</label><div className="relative"><span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-sm font-semibold text-[#8f95aa]">RD$</span><input className="field pl-12" type="number" min="0" step="0.01" required value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></div></div><div className="sm:col-span-2"><label className="label">Descripción</label><textarea className="field min-h-28 resize-none" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe brevemente lo que hace especial este producto."/></div></div>
        </section>

        {attrs.length>0&&<section className="rounded-[28px] border border-[#edf0f4] bg-white p-5">
          <div className="mb-4 flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-brand-600"><ListFilter className="h-5 w-5"/></span><div><h3 className="text-base font-semibold text-ink-900">Detalles del {itemLabel}</h3><p className="text-sm text-[#8d92aa]">Estos campos ya vienen preparados para {currentStore?.template_name||'tu tipo de negocio'}.</p></div></div>
          <div className="space-y-5">{attributeGroups.map(([group,fields])=><div key={group}><p className="mb-3 text-xs font-bold uppercase tracking-[.12em] text-[#969cb0]">{group}</p><div className="grid gap-4 sm:grid-cols-2">{fields.map(a=><div key={a.id}><label className="label">{a.label}{a.is_required?' *':''}</label>{a.input_type==='select'?<select className="field" required={a.is_required} value={String(form.attributes?.[a.key]??'')} onChange={e=>setForm({...form,attributes:{...(form.attributes||{}),[a.key]:e.target.value}})}><option value="">Seleccionar</option>{(a.options||[]).map((o:any)=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select>:<input className="field" required={a.is_required} type={a.input_type==='number'?'number':'text'} value={String(form.attributes?.[a.key]??'')} onChange={e=>setForm({...form,attributes:{...(form.attributes||{}),[a.key]:a.input_type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value}})} placeholder={a.label}/>}</div>)}</div></div>)}</div>
        </section>}

        <section className="rounded-[28px] border border-[#edf0f4] bg-white p-5">
          <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Images className="h-5 w-5"/></span><div><h3 className="text-base font-semibold">Galería</h3><p className="mt-1 text-sm text-[#8d92aa]">Agrega imágenes adicionales sin reemplazar la foto principal.</p></div></div><button type="button" className="btn-secondary" onClick={addMedia}><Plus className="h-4 w-4"/>Agregar imagen</button></div>
          {(form.product_media||[]).length?<div className="mt-4 space-y-3">{(form.product_media||[]).map((m:any,i:number)=><div key={`${m.url}-${i}`} className="grid gap-3 rounded-2xl border border-[#edf0f4] bg-[#fbfcfd] p-3 sm:grid-cols-[84px_minmax(0,1fr)_auto]"><div className="grid h-20 w-20 place-items-center overflow-hidden rounded-xl bg-white">{m.url?<img src={m.url} alt="" className="h-full w-full object-cover"/>:<ImageIcon className="h-6 w-6 text-slate-300"/>}</div><div className="space-y-2"><input className="field" placeholder="URL de la imagen" value={m.url||''} onChange={e=>updateMedia(i,{url:e.target.value})}/><input className="field" placeholder="Texto alternativo (opcional)" value={m.alt_text||''} onChange={e=>updateMedia(i,{alt_text:e.target.value})}/><label className="btn-secondary inline-flex cursor-pointer"><UploadCloud className="h-4 w-4"/>{up?'Subiendo...':'Subir archivo'}<input hidden type="file" accept="image/*" disabled={up} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadMedia(i,f);e.currentTarget.value='' }}/></label></div><div className="flex gap-1 sm:flex-col"><button type="button" className="btn-secondary px-2.5" onClick={()=>moveMedia(i,-1)} disabled={i===0}><ArrowUp className="h-4 w-4"/></button><button type="button" className="btn-secondary px-2.5" onClick={()=>moveMedia(i,1)} disabled={i===(form.product_media||[]).length-1}><ArrowDown className="h-4 w-4"/></button><button type="button" className="btn-danger px-2.5" onClick={()=>removeMedia(i)}><Trash2 className="h-4 w-4"/></button></div></div>)}</div>:<p className="mt-4 rounded-2xl border border-dashed border-[#e1e5ec] bg-[#fafbfc] p-4 text-center text-xs text-[#969caf]">La foto principal seguirá funcionando como hasta ahora. La galería es opcional.</p>}
        </section>

        <section className="rounded-[28px] border border-[#edf0f4] bg-white p-5">
          <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Languages className="h-5 w-5"/></span><div><h3 className="text-base font-semibold">Traducciones</h3><p className="mt-1 text-sm text-[#8d92aa]">Español continúa siendo el contenido principal y siempre funciona como respaldo.</p></div></div><button type="button" className="btn-secondary" onClick={addTranslation}><Plus className="h-4 w-4"/>Agregar idioma</button></div>
          {(form.product_translations||[]).length?<div className="mt-4 space-y-3">{(form.product_translations||[]).map((tr:any,i:number)=><div key={`${tr.locale}-${i}`} className="rounded-2xl border border-[#edf0f4] bg-[#fbfcfd] p-4"><div className="grid gap-3 sm:grid-cols-[150px_minmax(0,1fr)_42px]"><select className="field" value={tr.locale||'en'} onChange={e=>updateTranslation(i,{locale:e.target.value})}><option value="en">Inglés</option><option value="fr">Francés</option><option value="de">Alemán</option><option value="pt">Portugués</option><option value="it">Italiano</option></select><input className="field" placeholder="Nombre traducido" value={tr.name||''} onChange={e=>updateTranslation(i,{name:e.target.value})}/><button type="button" className="btn-danger px-2.5" onClick={()=>removeTranslation(i)}><Trash2 className="h-4 w-4"/></button></div><textarea className="field mt-3 min-h-20" placeholder="Descripción traducida" value={tr.description||''} onChange={e=>updateTranslation(i,{description:e.target.value})}/></div>)}</div>:<p className="mt-4 rounded-2xl border border-dashed border-[#e1e5ec] bg-[#fafbfc] p-4 text-center text-xs text-[#969caf]">Ideal para negocios turísticos. Si no agregas traducciones, la tienda seguirá completamente en español.</p>}
        </section>

        <section className="rounded-[28px] border border-[#edf0f4] bg-white p-5">
          <button type="button" onClick={()=>setAdvanced(!advanced)} className="flex w-full items-center gap-3 text-left"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Sparkles className="h-5 w-5"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-ink-900">Opciones del {itemLabel}</span><span className="mt-0.5 block text-xs text-[#9298ad]">{variantHint}, inventario o adicionales.</span></span><ChevronDown className={`h-4 w-4 text-[#9298ad] transition ${advanced?'rotate-180':''}`}/></button>
          {advanced&&<div className="mt-5 space-y-5 border-t border-slate-100 pt-5">
            {edit&&<Switch checked={!!form.is_active} onChange={v=>setForm({...form,is_active:v})} label="Disponible para vender" detail="Desactívalo temporalmente si no quieres mostrarlo en el catálogo."/>}
            <Switch checked={weightedProduct} onChange={v=>setForm({...form,attributes:{...(form.attributes||{}),wamercio_weighted_sale:v,wamercio_weight_unit:'lb',wamercio_weight_increment:Number(form.attributes?.wamercio_weight_increment||0.25),wamercio_min_weight:Number(form.attributes?.wamercio_min_weight||0.25),wamercio_allow_amount_sale:form.attributes?.wamercio_allow_amount_sale??true}})} label="Vender por libra" detail="Permite que el cliente compre por peso y, opcionalmente, indicando el monto que desea gastar."/>
            {weightedProduct&&<div className="grid gap-4 rounded-2xl border border-brand-100 bg-brand-50/50 p-4 sm:grid-cols-3"><div><label className="label">Incremento</label><select className="field" value={String(form.attributes?.wamercio_weight_increment||0.25)} onChange={e=>setForm({...form,attributes:{...(form.attributes||{}),wamercio_weight_increment:Number(e.target.value)}})}><option value="0.25">0.25 lb</option><option value="0.5">0.50 lb</option><option value="1">1 lb</option></select></div><div><label className="label">Compra mínima</label><input className="field" type="number" min="0.01" step="0.01" value={Number(form.attributes?.wamercio_min_weight||0.25)} onChange={e=>setForm({...form,attributes:{...(form.attributes||{}),wamercio_min_weight:Number(e.target.value)||0.25}})}/></div><div className="flex items-end"><Switch checked={form.attributes?.wamercio_allow_amount_sale!==false} onChange={v=>setForm({...form,attributes:{...(form.attributes||{}),wamercio_allow_amount_sale:v}})} label="Permitir compra por monto" detail="El cliente puede indicar RD$ y WAMERCIO calcula el peso."/></div></div>}
            <Switch checked={!!form.track_stock} onChange={v=>setForm({...form,track_stock:v,stock:v?(form.stock??0):null})} label="Controlar inventario" detail="Actívalo solo si quieres limitar la cantidad disponible."/>
            {form.track_stock&&<div className="max-w-xs"><label className="label">{weightedProduct?'Existencia disponible (lb)':'Cantidad disponible'}</label><input className="field" type="number" min="0" step={weightedProduct?'0.01':'1'} value={form.stock??0} onChange={e=>setForm({...form,stock:Number(e.target.value)})}/></div>}
            <div className="grid gap-4 md:grid-cols-2">{capabilities.supportsVariants&&<OptionEditor label={`Variantes · ${variantHint}`} value={form.variants||[]} onChange={v=>setForm({...form,variants:v})}/>} {capabilities.supportsExtras&&<OptionEditor label="Adicionales / extras" value={form.extras||[]} onChange={v=>setForm({...form,extras:v})}/>} {!capabilities.supportsVariants&&!capabilities.supportsExtras&&<div className="md:col-span-2 rounded-2xl border border-dashed border-[#e1e5ec] bg-[#fafbfc] px-4 py-5 text-center text-xs text-[#8d92aa]">Este tipo de negocio no necesita variantes ni adicionales por defecto.</div>}</div>

            {modifierGroups.length>0&&<section className="rounded-3xl border border-[#edf0f4] bg-[#fbfcfd] p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-50 text-brand-600"><Layers3 className="h-4 w-4"/></span><div><h4 className="font-semibold">Modificadores reutilizables</h4><p className="mt-1 text-xs text-[#9298ad]">Asigna grupos como salsas, toppings, tamaños o acompañamientos.</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{modifierGroups.filter(g=>g.is_active).map(g=><label key={g.id} className="flex cursor-pointer items-start gap-3 rounded-2xl border border-[#e8ebf0] bg-white p-3"><input className="mt-1" type="checkbox" checked={(form.modifier_group_ids||[]).includes(g.id)} onChange={()=>toggleList('modifier_group_ids',g.id)}/><span><span className="block text-sm font-semibold">{g.name}</span><span className="mt-0.5 block text-[11px] text-[#969caf]">{g.is_required?'Obligatorio':'Opcional'} · {g.min_select}–{g.max_select}</span></span></label>)}</div></section>}

            <section className="rounded-3xl border border-[#edf0f4] bg-[#fbfcfd] p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-50 text-brand-600"><PackagePlus className="h-4 w-4"/></span><div><h4 className="font-semibold">Combo / paquete</h4><p className="mt-1 text-xs text-[#9298ad]">Compón este producto usando otros productos del catálogo.</p></div></div><button type="button" className="btn-secondary" onClick={addBundleComponent} disabled={rows.filter(x=>x.id!==edit?.id).length===0}><Plus className="h-4 w-4"/>Agregar</button></div>{(form.bundle_components||[]).length>0?<div className="mt-4 space-y-2">{(form.bundle_components||[]).map((c:any,i:number)=><div key={`${c.product_id}-${i}`} className="grid grid-cols-[1fr_100px_42px] gap-2"><select className="field" value={c.product_id} onChange={e=>updateBundleComponent(i,{product_id:e.target.value})}>{rows.filter(x=>x.id!==edit?.id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="field" type="number" min="0.01" step="0.01" value={c.quantity||1} onChange={e=>updateBundleComponent(i,{quantity:Number(e.target.value)})}/><button type="button" className="grid place-items-center rounded-xl border border-[#e9ebf2] bg-white text-[#a2a6b8] hover:text-rose-600" onClick={()=>removeBundleComponent(i)}><Trash2 className="h-4 w-4"/></button></div>)}</div>:<p className="mt-4 rounded-2xl border border-dashed border-[#e1e5ec] bg-white p-4 text-center text-xs text-[#9ca1b3]">Déjalo vacío para un producto normal.</p>}</section>

            {engine==='food'&&<section className="rounded-3xl border border-[#edf0f4] bg-[#fbfcfd] p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-50 text-amber-700"><ShieldAlert className="h-4 w-4"/></span><div><h4 className="font-semibold">Alérgenos y dieta</h4><p className="mt-1 text-xs text-[#9298ad]">Información visible para el cliente; no sustituye las políticas del negocio.</p></div></div>{allergens.length>0&&<div className="mt-4 flex flex-wrap gap-2">{allergens.filter(a=>a.is_active).map(a=><button type="button" key={a.id} onClick={()=>toggleList('allergen_ids',a.id)} className={`rounded-full border px-3 py-2 text-xs font-semibold ${(form.allergen_ids||[]).includes(a.id)?'border-amber-300 bg-amber-50 text-amber-800':'border-[#e3e6ec] bg-white text-[#777e94]'}`}>{a.icon&&<span className="mr-1">{a.icon}</span>}{a.name}</button>)}</div>}<div className="mt-4 flex flex-wrap gap-2">{[['vegetarian','Vegetariano'],['vegan','Vegano'],['spicy','Picante'],['gluten_free','Sin gluten']].map(([key,label])=><button type="button" key={key} onClick={()=>toggleList('dietary_tags',key)} className={`rounded-full border px-3 py-2 text-xs font-semibold ${(form.dietary_tags||[]).includes(key)?'border-brand-300 bg-brand-50 text-brand-700':'border-[#e3e6ec] bg-white text-[#777e94]'}`}>{label}</button>)}</div></section>}
          </div>}
        </section>
      </div>
    </div>

    <div className="mt-7 flex flex-col-reverse gap-2 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary">{edit?'Guardar cambios':`Crear ${itemLabel}`}</button></div>
   </form>
  </Modal>
 </StoreShell>
}
