'use client'

import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,money} from '@/lib/api'
import {Alert,Loading,Modal,PageEmpty,Switch} from '@/components/ui'
import {Boxes,Building2,Clock,MapPin,Pencil,Phone,Plus,Search,Star,Trash2} from 'lucide-react'

type Branch={
 id:string;store_id:string;name:string;code:string;address:string;street:string;street_number:string;province_code:string;province:string;municipality_id:string;municipality:string;neighborhood_id:string;neighborhood:string;phone:string;whatsapp:string;latitude?:number|null;longitude?:number|null;delivery_radius_km:number;opens_at:string;closes_at:string;is_primary:boolean;is_active:boolean;orders_count:number;cash_open:boolean
}
type BranchCatalogItem={product_id:string;name:string;sku:string;image_url:string;base_price:number;price:number;has_override:boolean;is_available:boolean;product_active:boolean}
const blank={name:'',code:'',address:'',street:'',street_number:'',province_code:'',province:'',municipality_id:'',municipality:'',neighborhood_id:'',neighborhood:'',phone:'',whatsapp:'',latitude:null as number|null,longitude:null as number|null,delivery_radius_km:5,opens_at:'08:00',closes_at:'22:00',is_primary:false,is_active:true}

export default function BranchesPage(){
 const[store,setStore]=useState(''),[rows,setRows]=useState<Branch[]>([]),[loading,setLoading]=useState(false),[err,setErr]=useState('')
 const[open,setOpen]=useState(false),[edit,setEdit]=useState<Branch|null>(null),[form,setForm]=useState<any>(blank),[busy,setBusy]=useState(false)
 const[catalogBranch,setCatalogBranch]=useState<Branch|null>(null),[catalog,setCatalog]=useState<BranchCatalogItem[]>([]),[catalogLoading,setCatalogLoading]=useState(false),[catalogSearch,setCatalogSearch]=useState(''),[catalogDraft,setCatalogDraft]=useState<Record<string,{price_override:string;is_available:boolean}>>({})
 const load=()=>{if(!store){setRows([]);return};setLoading(true);setErr('');api<Branch[]>(`/branches?store_id=${store}`).then(setRows).catch((e:any)=>setErr(e.message)).finally(()=>setLoading(false))}
 useEffect(load,[store])
 const start=(row?:Branch)=>{setEdit(row||null);setForm(row?{...row}:{...blank,is_primary:rows.length===0});setErr('');setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setErr('');try{const body={...form,store_id:store,name:String(form.name||'').trim(),delivery_radius_km:Number(form.delivery_radius_km||0),latitude:form.latitude===''?null:form.latitude,longitude:form.longitude===''?null:form.longitude};if(!body.name)throw new Error('Escribe el nombre de la sucursal.');if(edit)await api(`/branches/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/branches',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const remove=async(row:Branch)=>{if(!confirm(`¿Eliminar ${row.name}?`))return;setErr('');try{await api(`/branches/${row.id}`,{method:'DELETE'});load()}catch(e:any){setErr(e.message)}}
 const openCatalog=async(row:Branch)=>{setCatalogBranch(row);setCatalog([]);setCatalogDraft({});setCatalogSearch('');setCatalogLoading(true);try{const items=await api<BranchCatalogItem[]>(`/branches/${row.id}/catalog`);setCatalog(items);const draft:Record<string,{price_override:string;is_available:boolean}>={};for(const item of items)draft[item.product_id]={price_override:item.has_override?String(item.price):'',is_available:item.is_available};setCatalogDraft(draft)}catch(e:any){setErr(e.message)}finally{setCatalogLoading(false)}}
 const saveCatalogItem=async(item:BranchCatalogItem)=>{if(!catalogBranch)return;const draft=catalogDraft[item.product_id]||{price_override:'',is_available:true};setBusy(true);try{await api(`/branches/${catalogBranch.id}/catalog/${item.product_id}`,{method:'PUT',body:JSON.stringify({store_id:store,price_override:draft.price_override===''?null:Number(draft.price_override),is_available:draft.is_available})});const items=await api<BranchCatalogItem[]>(`/branches/${catalogBranch.id}/catalog`);setCatalog(items)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const filteredCatalog=useMemo(()=>{const q=catalogSearch.trim().toLowerCase();return catalog.filter(x=>!q||`${x.name} ${x.sku}`.toLowerCase().includes(q))},[catalog,catalogSearch])
 return <StoreShell title="Sucursales" subtitle="Ubicaciones, horarios, catálogo y precios por local" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store} className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Nueva sucursal</button>}>
  {!store?<PageEmpty title="Selecciona un negocio" detail="Elige el negocio donde administrarás sus sucursales."/>:loading?<Loading/>:<div className="space-y-5">{err&&<Alert text={err}/>}<section className="rounded-[26px] border border-brand-100 bg-brand-50/45 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white text-brand-700 shadow-sm"><Building2 className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="section-kicker">OPERACIÓN MULTISUCURSAL</p><h2 className="mt-1 text-lg font-semibold">Un negocio, varias ubicaciones</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-[#7d8499]">Cada sucursal puede tener horario, WhatsApp, cobertura, disponibilidad y precio propio sin convertirse en otro tenant.</p></div><div className="grid grid-cols-2 gap-2"><div className="rounded-2xl bg-white px-4 py-3 text-center"><strong className="block text-xl">{rows.length}</strong><span className="text-[10px] text-[#8d92aa]">sucursales</span></div><div className="rounded-2xl bg-white px-4 py-3 text-center"><strong className="block text-xl">{rows.filter(x=>x.cash_open).length}</strong><span className="text-[10px] text-[#8d92aa]">cajas abiertas</span></div></div></div></section>
   {rows.length?<div className="grid gap-4 xl:grid-cols-2">{rows.map(row=><article key={row.id} className="card p-5"><div className="flex items-start gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${row.is_primary?'bg-amber-50 text-amber-700':'bg-brand-50 text-brand-700'}`}>{row.is_primary?<Star className="h-5 w-5"/>:<Building2 className="h-5 w-5"/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-base font-semibold">{row.name}</h3>{row.is_primary&&<span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-semibold text-amber-700">Principal</span>}<span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${row.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{row.is_active?'Activa':'Inactiva'}</span>{row.cash_open&&<span className="rounded-full bg-cyan-50 px-2.5 py-1 text-[10px] font-semibold text-cyan-700">Caja abierta</span>}</div><p className="mt-1 text-xs text-[#9298ad]">{row.code||'Sin código'} · {row.orders_count||0} pedidos</p></div></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div className="flex items-start gap-2 rounded-2xl bg-[#f8fafb] p-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-brand-600"/><span>{row.address||[row.neighborhood,row.municipality,row.province].filter(Boolean).join(', ')||'Dirección pendiente'}</span></div><div className="flex items-start gap-2 rounded-2xl bg-[#f8fafb] p-3"><Clock className="mt-0.5 h-4 w-4 shrink-0 text-brand-600"/><span>{row.opens_at} – {row.closes_at}</span></div><div className="flex items-start gap-2 rounded-2xl bg-[#f8fafb] p-3"><Phone className="mt-0.5 h-4 w-4 shrink-0 text-brand-600"/><span>{row.whatsapp||row.phone||'Sin teléfono'}</span></div><div className="flex items-start gap-2 rounded-2xl bg-[#f8fafb] p-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-brand-600"/><span>Radio sugerido: {Number(row.delivery_radius_km||0).toFixed(1)} km</span></div></div><div className="mt-4 flex flex-wrap gap-2 border-t border-[#edf0f5] pt-4"><button className="btn-secondary" onClick={()=>openCatalog(row)}><Boxes className="h-4 w-4"/>Catálogo y precios</button><button className="btn-secondary" onClick={()=>start(row)}><Pencil className="h-4 w-4"/>Editar</button>{!row.is_primary&&<button className="btn-danger" onClick={()=>remove(row)}><Trash2 className="h-4 w-4"/>Eliminar</button>}</div></article>)}</div>:<PageEmpty title="Sin sucursales" detail="Crea la primera ubicación operativa del negocio." action={<button className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Crear sucursal</button>}/>}</div>}
  <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar sucursal':'Nueva sucursal'} subtitle="Configura una ubicación operativa sin crear otro negocio." wide><form onSubmit={save} className="space-y-5">{err&&<Alert text={err}/>}<div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Nombre *</label><input autoFocus className="field" required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ej.: Bonao Centro"/></div><div><label className="label">Código</label><input className="field" value={form.code||''} onChange={e=>setForm({...form,code:e.target.value})} placeholder="BNA01"/></div><div className="sm:col-span-2"><label className="label">Dirección</label><input className="field" value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Calle, número y referencia"/></div><div><label className="label">Provincia</label><input className="field" value={form.province||''} onChange={e=>setForm({...form,province:e.target.value})}/></div><div><label className="label">Municipio</label><input className="field" value={form.municipality||''} onChange={e=>setForm({...form,municipality:e.target.value})}/></div><div><label className="label">Barrio / sector</label><input className="field" value={form.neighborhood||''} onChange={e=>setForm({...form,neighborhood:e.target.value})}/></div><div><label className="label">Radio de delivery (km)</label><input className="field" type="number" min="0.1" step="0.1" value={form.delivery_radius_km||5} onChange={e=>setForm({...form,delivery_radius_km:Number(e.target.value)})}/></div><div><label className="label">WhatsApp</label><input className="field" value={form.whatsapp||''} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></div><div><label className="label">Teléfono</label><input className="field" value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="label">Abre</label><input className="field" type="time" value={form.opens_at||'08:00'} onChange={e=>setForm({...form,opens_at:e.target.value})}/></div><div><label className="label">Cierra</label><input className="field" type="time" value={form.closes_at||'22:00'} onChange={e=>setForm({...form,closes_at:e.target.value})}/></div></div><div className="grid gap-3 sm:grid-cols-2"><Switch checked={!!form.is_primary} onChange={v=>setForm({...form,is_primary:v})} label="Sucursal principal" detail="Será la ubicación predeterminada para TPV y pedidos."/><Switch checked={form.is_active!==false} onChange={v=>setForm({...form,is_active:v})} label="Sucursal activa" detail="Desactívala para impedir nuevas operaciones sin perder historial."/></div><div className="flex justify-end gap-2 border-t border-slate-100 pt-5"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button disabled={busy} className="btn-primary">{busy?'Guardando...':'Guardar sucursal'}</button></div></form></Modal>
  <Modal open={!!catalogBranch} onClose={()=>setCatalogBranch(null)} title={`Catálogo · ${catalogBranch?.name||''}`} subtitle="Controla disponibilidad y precio local sin duplicar productos." wide>{catalogLoading?<Loading/>:<div className="space-y-4"><div className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#a2a6b8]"/><input className="field pl-10" value={catalogSearch} onChange={e=>setCatalogSearch(e.target.value)} placeholder="Buscar producto o SKU..."/></div><div className="max-h-[58vh] space-y-2 overflow-y-auto pr-1">{filteredCatalog.map(item=>{const draft=catalogDraft[item.product_id]||{price_override:'',is_available:item.is_available};return <div key={item.product_id} className="grid gap-3 rounded-2xl border border-[#e9edf1] bg-white p-3 sm:grid-cols-[minmax(0,1fr)_150px_135px_auto] sm:items-center"><div className="flex min-w-0 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-xl bg-brand-50">{item.image_url?<img src={item.image_url} alt="" className="h-full w-full object-cover"/>:<Boxes className="h-4 w-4 text-brand-600"/>}</span><div className="min-w-0"><div className="truncate text-sm font-semibold">{item.name}</div><div className="text-[11px] text-[#9399ab]">Base {money(item.base_price)} {item.sku?`· ${item.sku}`:''}</div></div></div><div><label className="label">Precio local</label><input className="field" type="number" min="0" step="0.01" value={draft.price_override} onChange={e=>setCatalogDraft(v=>({...v,[item.product_id]:{...draft,price_override:e.target.value}}))} placeholder={String(item.base_price)}/></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={draft.is_available} onChange={e=>setCatalogDraft(v=>({...v,[item.product_id]:{...draft,is_available:e.target.checked}}))}/> Disponible</label><button disabled={busy||!item.product_active} className="btn-secondary justify-center" onClick={()=>saveCatalogItem(item)}>Guardar</button></div>})}{!filteredCatalog.length&&<div className="rounded-2xl border border-dashed p-8 text-center text-sm text-[#9aa0b4]">No hay productos para este filtro.</div>}</div></div>}</Modal>
 </StoreShell>
}
