'use client'
import {useEffect,useMemo,useState} from 'react'
import SuperAdminShell from '@/components/superadmin-shell'
import {api} from '@/lib/api'
import {Alert,Loading,Modal,SearchBox,Status,Switch} from '@/components/ui'
import {Copy,Eye,LayoutTemplate,Plus,Pencil,Sparkles,Store,Tag,MessageCircleMore,Boxes,Settings2,Trash2,SlidersHorizontal} from 'lucide-react'

type T={id:string;slug:string;name:string;family:string;description:string;icon:string;engine:string;recommended_style:string;settings:Record<string,any>;is_featured:boolean;is_active:boolean;sort_order:number;category_count:number;product_count:number;reply_count:number}
type TemplateCategory={name:string;slug:string;description:string;sort_order:number}
type TemplateProduct={category_slug:string;name:string;slug:string;description:string;price:number;track_stock:boolean;variants:any[];extras:any[];attributes:Record<string,any>;is_featured:boolean;sort_order:number}
type TemplateAttribute={group_name:string;key:string;label:string;input_type:string;options:string[];is_required:boolean;sort_order:number}
type TemplateReply={shortcut:string;title:string;message:string;sort_order:number}
type TemplateContent={categories:TemplateCategory[];products:TemplateProduct[];attributes:TemplateAttribute[];quick_replies:TemplateReply[]}
type ContentTab='categories'|'products'|'attributes'|'replies'

const blank={name:'',slug:'',family:'Otros',description:'',icon:'✨',engine:'retail',recommended_style:'Minimal',settings:{item_label:'producto',item_label_plural:'productos',primary_action:'Comprar',delivery_enabled:true,pickup_enabled:true,supports_variants:true,supports_extras:false,track_stock_default:true,supports_dine_in:false,checkout_fields:[]},is_featured:false,is_active:false,sort_order:999}
const emptyContent:TemplateContent={categories:[],products:[],attributes:[],quick_replies:[]}
const slugifyLocal=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')

export default function AdminTemplates(){
 const[rows,setRows]=useState<T[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[family,setFamily]=useState('Todos'),[open,setOpen]=useState(false),[preview,setPreview]=useState<T|null>(null),[edit,setEdit]=useState<T|null>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState('')
 const[contentFor,setContentFor]=useState<T|null>(null),[content,setContent]=useState<TemplateContent>(emptyContent),[contentTab,setContentTab]=useState<ContentTab>('categories'),[contentLoading,setContentLoading]=useState(false),[contentSaving,setContentSaving]=useState(false),[contentErr,setContentErr]=useState('')
 const load=()=>{setLoading(true);api<T[]>('/admin/templates').then(setRows).finally(()=>setLoading(false))}
 useEffect(load,[])
 const families=useMemo(()=>['Todos',...Array.from(new Set(rows.map(x=>x.family)))],[rows])
 const filtered=useMemo(()=>rows.filter(x=>(family==='Todos'||x.family===family)&&(x.name+' '+x.family+' '+x.description).toLowerCase().includes(search.toLowerCase())),[rows,family,search])
 const start=(x?:T)=>{setEdit(x||null);setForm(x?{...x,settings:{...(x.settings||{})}}:{...blank,settings:{...blank.settings}});setErr('');setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');try{const body={...form,sort_order:Number(form.sort_order||0)};if(edit)await api(`/admin/templates/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/admin/templates',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e:any){setErr(e.message)}}
 const duplicate=async(x:T)=>{try{await api(`/admin/templates/${x.id}/duplicate`,{method:'POST'});load()}catch(e:any){alert(e.message)}}
 const toggle=async(x:T)=>{try{await api(`/admin/templates/${x.id}`,{method:'PUT',body:JSON.stringify({...x,is_active:!x.is_active})});load()}catch(e:any){alert(e.message)}}
 const openContent=async(x:T)=>{setContentFor(x);setContentTab('categories');setContentErr('');setContentLoading(true);try{setContent(await api<TemplateContent>(`/admin/templates/${x.id}/content`))}catch(e:any){setContentErr(e.message);setContent(emptyContent)}finally{setContentLoading(false)}}
 const saveContent=async()=>{if(!contentFor)return;setContentSaving(true);setContentErr('');try{await api(`/admin/templates/${contentFor.id}/content`,{method:'PUT',body:JSON.stringify(content)});setContentFor(null);load()}catch(e:any){setContentErr(e.message)}finally{setContentSaving(false)}}
 const setCategories=(categories:TemplateCategory[])=>setContent(v=>({...v,categories}))
 const setProducts=(products:TemplateProduct[])=>setContent(v=>({...v,products}))
 const setAttributes=(attributes:TemplateAttribute[])=>setContent(v=>({...v,attributes}))
 const setReplies=(quick_replies:TemplateReply[])=>setContent(v=>({...v,quick_replies}))
 const contentTabs:[ContentTab,string,React.ElementType][]=[['categories','Categorías',Tag],['products','Ejemplos',Boxes],['attributes','Campos',SlidersHorizontal],['replies','WhatsApp',MessageCircleMore]]
 const setTemplateSetting=(key:string,value:any)=>setForm((v:any)=>({...v,settings:{...(v.settings||{}),[key]:value}}))
 const checkoutFields=Array.isArray(form.settings?.checkout_fields)?form.settings.checkout_fields:[]
 const setCheckoutFields=(fields:any[])=>setTemplateSetting('checkout_fields',fields)
 const capabilitySwitches:[string,string,string][]=[
  ['supports_variants','Variantes','Tamaños, colores, presentaciones u otras opciones de precio.'],
  ['supports_extras','Adicionales','Complementos, ingredientes, mejoras o servicios extra.'],
  ['track_stock_default','Inventario por defecto','Los nuevos artículos controlan existencia automáticamente.'],
  ['delivery_enabled','Delivery','El negocio puede entregar a domicilio.'],
  ['pickup_enabled','Atención / recogida','Permite recoger productos o recibir el servicio en el negocio.'],
  ['supports_dine_in','Mesas y reservas','Habilita consumo en el negocio con mesa y horario.'],
  ['appointments','Citas','El flujo requiere fecha/hora y se trata como reserva.'],
  ['quotation','Cotización','El flujo se trata como solicitud/cotización antes de cerrar venta.'],
  ['personalization','Personalización','El cliente puede enviar datos especiales del pedido.'],
  ['wholesale','Mayorista','El negocio trabaja con compras por volumen o empresas.'],
  ['requires_lead_time','Preparación anticipada','El pedido normalmente requiere fecha futura o tiempo de preparación.'],
 ]

 return <SuperAdminShell title="Plantillas" subtitle="Bases preconstruidas para que cada comercio empiece listo" actions={<button onClick={()=>start()} className="btn-primary"><Plus className="h-4 w-4"/> Nueva plantilla</button>}>
  <div className="mb-5 grid gap-3 md:grid-cols-[1fr_auto]"><SearchBox value={search} onChange={setSearch} placeholder="Buscar plantilla..."/><div className="modal-scroll flex gap-2 overflow-x-auto">{families.map(f=><button key={f} onClick={()=>setFamily(f)} className={`shrink-0 rounded-full px-3.5 py-2 text-xs font-semibold ${family===f?'bg-brand-500 text-white':'border border-[#e8ebf1] bg-white text-[#777e94]'}`}>{f}</button>)}</div></div>
  {loading?<Loading/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(x=><article key={x.id} className="card overflow-hidden"><div className="p-5"><div className="flex items-start gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-brand-50 text-2xl">{x.icon||'✨'}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-ink-900">{x.name}</h3><Status value={x.is_active?'active':'inactive'}/>{x.is_featured&&<span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">Destacada</span>}</div><p className="mt-1 text-xs font-medium text-brand-700">{x.family} · {x.engine}</p><p className="mt-2 line-clamp-2 text-sm leading-5 text-[#8d92aa]">{x.description}</p></div></div><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-[#fafbfc] p-3 text-center"><Tag className="mx-auto h-4 w-4 text-brand-600"/><div className="mt-1 text-lg font-semibold">{x.category_count}</div><div className="text-[10px] text-[#949aaf]">Categorías</div></div><div className="rounded-2xl bg-[#fafbfc] p-3 text-center"><Boxes className="mx-auto h-4 w-4 text-brand-600"/><div className="mt-1 text-lg font-semibold">{x.product_count}</div><div className="text-[10px] text-[#949aaf]">Ejemplos</div></div><div className="rounded-2xl bg-[#fafbfc] p-3 text-center"><MessageCircleMore className="mx-auto h-4 w-4 text-brand-600"/><div className="mt-1 text-lg font-semibold">{x.reply_count}</div><div className="text-[10px] text-[#949aaf]">Respuestas</div></div></div></div><div className="grid grid-cols-5 border-t border-slate-100"><button onClick={()=>setPreview(x)} className="grid place-items-center py-3 text-[#7d8398] hover:bg-brand-50 hover:text-brand-700" title="Vista previa"><Eye className="h-4 w-4"/></button><button onClick={()=>start(x)} className="grid place-items-center border-l border-slate-100 py-3 text-[#7d8398] hover:bg-brand-50 hover:text-brand-700" title="Editar configuración"><Pencil className="h-4 w-4"/></button><button onClick={()=>openContent(x)} className="grid place-items-center border-l border-slate-100 py-3 text-[#7d8398] hover:bg-brand-50 hover:text-brand-700" title="Editar contenido"><Settings2 className="h-4 w-4"/></button><button onClick={()=>duplicate(x)} className="grid place-items-center border-l border-slate-100 py-3 text-[#7d8398] hover:bg-brand-50 hover:text-brand-700" title="Duplicar"><Copy className="h-4 w-4"/></button><button onClick={()=>toggle(x)} className="border-l border-slate-100 py-3 text-xs font-semibold text-brand-700 hover:bg-brand-50">{x.is_active?'Ocultar':'Publicar'}</button></div></article>)}</div>}

  <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar plantilla':'Nueva plantilla'} subtitle="La plantilla define qué funciones verá cada tipo de negocio y qué datos pedirá al cliente." wide>
   <form onSubmit={save}>
    {err&&<Alert text={err}/>} 
    <div className="grid gap-4 sm:grid-cols-2">
     <div><label className="label">Nombre *</label><input className="field" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div>
     <div><label className="label">Familia</label><input className="field" value={form.family} onChange={e=>setForm({...form,family:e.target.value})}/></div>
     <div><label className="label">Icono</label><input className="field" value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})} placeholder="✨"/></div>
     <div><label className="label">Motor</label><select className="field" value={form.engine} onChange={e=>setForm({...form,engine:e.target.value})}><option value="retail">Venta de productos</option><option value="fashion">Moda</option><option value="food">Gastronomía</option><option value="catalog">Catálogo especializado</option><option value="quotation">Venta + cotización</option><option value="services">Servicios / citas</option><option value="wholesale">Mayorista</option></select></div>
     <div><label className="label">Estilo recomendado</label><select className="field" value={form.recommended_style} onChange={e=>setForm({...form,recommended_style:e.target.value})}>{['Fresh','Minimal','Bold','Elegant','Urban','Warm'].map(x=><option key={x}>{x}</option>)}</select></div>
     <div><label className="label">Orden</label><input type="number" className="field" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></div>
     <div className="sm:col-span-2"><label className="label">Descripción</label><textarea className="field min-h-24 resize-none" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>
     <div><label className="label">Nombre del artículo</label><input className="field" value={form.settings?.item_label||''} onChange={e=>setTemplateSetting('item_label',e.target.value)} placeholder="producto / prenda / servicio"/></div>
     <div><label className="label">Nombre plural</label><input className="field" value={form.settings?.item_label_plural||''} onChange={e=>setTemplateSetting('item_label_plural',e.target.value)} placeholder="productos / prendas / servicios"/></div>
     <div className="sm:col-span-2"><label className="label">Acción principal</label><input className="field" value={form.settings?.primary_action||''} onChange={e=>setTemplateSetting('primary_action',e.target.value)} placeholder="Comprar / Reservar / Cotizar"/></div>
    </div>

    <div className="mt-6 border-t border-slate-100 pt-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-brand-700"><SlidersHorizontal className="h-5 w-5"/></span><div><h3 className="font-semibold text-ink-900">Funciones de esta plantilla</h3><p className="mt-1 text-xs leading-5 text-[#8d92aa]">Estas capacidades controlan catálogo, configuración y checkout. Así WAMERCIO no muestra funciones que no aplican al negocio.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2">{capabilitySwitches.map(([key,label,detail])=><Switch key={key} checked={!!form.settings?.[key]} onChange={v=>setTemplateSetting(key,v)} label={label} detail={detail}/>)}</div></div>

    <div className="mt-6 border-t border-slate-100 pt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-ink-900">Datos adicionales del checkout</h3><p className="mt-1 text-xs leading-5 text-[#8d92aa]">Solicita únicamente información propia del tipo de negocio: fecha de cita, destinatario, RNC, personalización, etc.</p></div><button type="button" className="btn-secondary px-3" onClick={()=>setCheckoutFields([...checkoutFields,{key:'',label:'',type:'text',required:false,options:[]}])}><Plus className="h-4 w-4"/>Agregar campo</button></div><div className="mt-4 space-y-3">{checkoutFields.length===0?<div className="rounded-2xl border border-dashed border-slate-200 p-5 text-center text-sm text-[#8d92aa]">Esta plantilla no necesita datos adicionales.</div>:checkoutFields.map((field:any,i:number)=><div key={i} className="rounded-2xl border border-[#edf0f4] bg-[#fbfcfd] p-3"><div className="grid gap-2 sm:grid-cols-[1fr_150px_42px]"><input className="field" placeholder="Etiqueta: Fecha requerida" value={field.label||''} onChange={e=>{const label=e.target.value;setCheckoutFields(checkoutFields.map((x:any,j:number)=>j===i?{...x,label,key:x.key||slugifyLocal(label).replace(/-/g,'_')}:x))}}/><select className="field" value={field.type||'text'} onChange={e=>setCheckoutFields(checkoutFields.map((x:any,j:number)=>j===i?{...x,type:e.target.value,options:e.target.value==='select'?(x.options||[]):[]}:x))}><option value="text">Texto</option><option value="textarea">Texto largo</option><option value="number">Número</option><option value="date">Fecha</option><option value="time">Hora</option><option value="select">Selector</option></select><button type="button" className="icon-action text-rose-600" onClick={()=>setCheckoutFields(checkoutFields.filter((_:any,j:number)=>j!==i))}><Trash2 className="h-4 w-4"/></button></div><div className="mt-2 grid gap-2 sm:grid-cols-[1fr_auto]"><input className="field" placeholder="Identificador" value={field.key||''} onChange={e=>setCheckoutFields(checkoutFields.map((x:any,j:number)=>j===i?{...x,key:slugifyLocal(e.target.value).replace(/-/g,'_')}:x))}/><label className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-medium text-[#6f758d]"><input type="checkbox" checked={!!field.required} onChange={e=>setCheckoutFields(checkoutFields.map((x:any,j:number)=>j===i?{...x,required:e.target.checked}:x))}/>Obligatorio</label></div>{field.type==='select'&&<input className="field mt-2" placeholder="Opciones separadas por comas" value={(field.options||[]).join(', ')} onChange={e=>setCheckoutFields(checkoutFields.map((x:any,j:number)=>j===i?{...x,options:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)}:x))}/>}</div>)}</div></div>

    <div className="mt-5 grid gap-3 md:grid-cols-2"><Switch checked={!!form.is_featured} onChange={v=>setForm({...form,is_featured:v})} label="Plantilla destacada"/><Switch checked={!!form.is_active} onChange={v=>setForm({...form,is_active:v})} label="Disponible para nuevos comercios"/></div>
    <div className="mt-6 flex justify-end gap-2 border-t border-slate-100 pt-5"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary">Guardar plantilla</button></div>
   </form>
  </Modal>

  <Modal open={!!contentFor} onClose={()=>setContentFor(null)} title={`Contenido · ${contentFor?.name||''}`} subtitle="Categorías, ejemplos, campos y respuestas que se clonarán al crear una tienda." wide>
    {contentLoading?<Loading/>:<div>{contentErr&&<Alert text={contentErr}/>}<div className="modal-scroll mb-5 flex gap-2 overflow-x-auto rounded-2xl bg-[#f7f9fb] p-1.5">{contentTabs.map(([id,label,I])=><button key={id} onClick={()=>setContentTab(id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition ${contentTab===id?'bg-white text-brand-700 shadow-sm':'text-[#7e849b] hover:text-ink-900'}`}><I className="h-4 w-4"/>{label}</button>)}</div>
      {contentTab==='categories'&&<div className="space-y-3"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-ink-900">Categorías iniciales</h3><p className="text-xs text-[#8d92aa]">El identificador se genera automáticamente si lo dejas vacío.</p></div><button className="btn-secondary px-3" onClick={()=>setCategories([...content.categories,{name:'',slug:'',description:'',sort_order:(content.categories.length+1)*10}])}><Plus className="h-4 w-4"/>Agregar</button></div>{content.categories.map((c,i)=><div key={i} className="grid gap-2 rounded-2xl border border-[#edf0f4] bg-[#fbfcfd] p-3 sm:grid-cols-[1fr_1.5fr_42px]"><input className="field" placeholder="Nombre" value={c.name} onChange={e=>setCategories(content.categories.map((x,j)=>j===i?{...x,name:e.target.value,slug:x.slug||slugifyLocal(e.target.value)}:x))}/><input className="field" placeholder="Descripción opcional" value={c.description||''} onChange={e=>setCategories(content.categories.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><button className="icon-action text-rose-600" onClick={()=>setCategories(content.categories.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4"/></button></div>)}</div>}
      {contentTab==='products'&&<div className="space-y-3"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-ink-900">Ejemplos listos para personalizar</h3><p className="text-xs text-[#8d92aa]">Son productos/servicios de demostración; el comerciante podrá cambiarlos o eliminarlos.</p></div><button className="btn-secondary px-3" onClick={()=>setProducts([...content.products,{category_slug:content.categories[0]?.slug||'',name:'',slug:'',description:'',price:0,track_stock:false,variants:[],extras:[],attributes:{},is_featured:false,sort_order:(content.products.length+1)*10}])}><Plus className="h-4 w-4"/>Agregar</button></div>{content.products.map((prod,i)=><div key={i} className="rounded-2xl border border-[#edf0f4] bg-[#fbfcfd] p-4"><div className="grid gap-3 sm:grid-cols-[1.2fr_1fr_140px_42px]"><input className="field" placeholder="Nombre" value={prod.name} onChange={e=>setProducts(content.products.map((x,j)=>j===i?{...x,name:e.target.value,slug:x.slug||slugifyLocal(e.target.value)}:x))}/><select className="field" value={prod.category_slug||''} onChange={e=>setProducts(content.products.map((x,j)=>j===i?{...x,category_slug:e.target.value}:x))}><option value="">Sin categoría</option>{content.categories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs font-semibold text-[#959aae]">RD$</span><input className="field pl-11" type="number" min="0" step="0.01" value={prod.price} onChange={e=>setProducts(content.products.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/></div><button className="icon-action text-rose-600" onClick={()=>setProducts(content.products.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4"/></button></div><textarea className="field mt-3 min-h-16 resize-none" placeholder="Descripción" value={prod.description||''} onChange={e=>setProducts(content.products.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><div className="mt-3 flex flex-wrap gap-3 text-xs"><label className="inline-flex items-center gap-2"><input type="checkbox" checked={!!prod.is_featured} onChange={e=>setProducts(content.products.map((x,j)=>j===i?{...x,is_featured:e.target.checked}:x))}/>Destacado</label><label className="inline-flex items-center gap-2"><input type="checkbox" checked={!!prod.track_stock} onChange={e=>setProducts(content.products.map((x,j)=>j===i?{...x,track_stock:e.target.checked}:x))}/>Control de inventario</label>{prod.variants?.length>0&&<span className="rounded-full bg-brand-50 px-2.5 py-1 text-brand-700">{prod.variants.length} variantes preconfiguradas</span>}{prod.extras?.length>0&&<span className="rounded-full bg-brand-50 px-2.5 py-1 text-brand-700">{prod.extras.length} extras preconfigurados</span>}</div></div>)}</div>}
      {contentTab==='attributes'&&<div className="space-y-3"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-ink-900">Campos especializados</h3><p className="text-xs text-[#8d92aa]">Ej.: Marca, modelo, año, medida, presentación. Solo aparecen en negocios que los necesitan.</p></div><button className="btn-secondary px-3" onClick={()=>setAttributes([...content.attributes,{group_name:'Detalles',key:'',label:'',input_type:'text',options:[],is_required:false,sort_order:(content.attributes.length+1)*10}])}><Plus className="h-4 w-4"/>Agregar</button></div>{content.attributes.map((a,i)=><div key={i} className="rounded-2xl border border-[#edf0f4] bg-[#fbfcfd] p-3"><div className="grid gap-2 sm:grid-cols-[1fr_1fr_140px_42px]"><input className="field" placeholder="Grupo (ej. Especificaciones)" value={a.group_name} onChange={e=>setAttributes(content.attributes.map((x,j)=>j===i?{...x,group_name:e.target.value}:x))}/><input className="field" placeholder="Etiqueta (ej. Marca)" value={a.label} onChange={e=>setAttributes(content.attributes.map((x,j)=>j===i?{...x,label:e.target.value,key:x.key||slugifyLocal(e.target.value).replace(/-/g,'_')}:x))}/><select className="field" value={a.input_type} onChange={e=>setAttributes(content.attributes.map((x,j)=>j===i?{...x,input_type:e.target.value}:x))}><option value="text">Texto</option><option value="number">Número</option><option value="select">Lista</option></select><button className="icon-action text-rose-600" onClick={()=>setAttributes(content.attributes.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4"/></button></div>{a.input_type==='select'&&<input className="field mt-2" placeholder="Opciones separadas por comas" value={(a.options||[]).join(', ')} onChange={e=>setAttributes(content.attributes.map((x,j)=>j===i?{...x,options:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)}:x))}/>}<label className="mt-2 inline-flex items-center gap-2 text-xs text-[#6f758d]"><input type="checkbox" checked={!!a.is_required} onChange={e=>setAttributes(content.attributes.map((x,j)=>j===i?{...x,is_required:e.target.checked}:x))}/>Obligatorio al crear el artículo</label></div>)}</div>}
      {contentTab==='replies'&&<div className="space-y-3"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-ink-900">Respuestas rápidas de WhatsApp</h3><p className="text-xs text-[#8d92aa]">Se clonan al comercio y aparecen directamente sobre el compositor del chat.</p></div><button className="btn-secondary px-3" onClick={()=>setReplies([...content.quick_replies,{shortcut:'',title:'',message:'',sort_order:(content.quick_replies.length+1)*10}])}><Plus className="h-4 w-4"/>Agregar</button></div>{content.quick_replies.map((r,i)=><div key={i} className="rounded-2xl border border-[#edf0f4] bg-[#fbfcfd] p-3"><div className="grid gap-2 sm:grid-cols-[160px_1fr_42px]"><input className="field" placeholder="Atajo: hola" value={r.shortcut} onChange={e=>setReplies(content.quick_replies.map((x,j)=>j===i?{...x,shortcut:e.target.value}:x))}/><input className="field" placeholder="Título" value={r.title} onChange={e=>setReplies(content.quick_replies.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/><button className="icon-action text-rose-600" onClick={()=>setReplies(content.quick_replies.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4"/></button></div><textarea className="field mt-2 min-h-20 resize-none" placeholder="Mensaje" value={r.message} onChange={e=>setReplies(content.quick_replies.map((x,j)=>j===i?{...x,message:e.target.value}:x))}/></div>)}</div>}
      <div className="mt-6 flex justify-end gap-2 border-t border-slate-100 pt-5"><button className="btn-secondary" onClick={()=>setContentFor(null)}>Cancelar</button><button disabled={contentSaving} className="btn-primary" onClick={saveContent}>{contentSaving?'Guardando...':'Guardar contenido'}</button></div>
    </div>}
  </Modal>

  <Modal open={!!preview} onClose={()=>setPreview(null)} title={preview?.name||'Vista previa'} subtitle="Referencia de cómo WAMERCIO interpreta esta plantilla.">{preview&&<div><div className="mx-auto w-[300px] rounded-[36px] bg-[#101827] p-3 shadow-xl"><div className="overflow-hidden rounded-[26px] bg-[#f7f9fa]"><div className="bg-white p-4 pt-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-xl">{preview.icon}</span><div><p className="text-sm font-semibold">Mi {preview.name}</p><p className="text-[10px] text-[#9aa0b2]">Comercio listo en WAMERCIO</p></div></div></div><div className="m-3 rounded-3xl bg-brand-500 p-4 text-white"><span className="text-[9px] font-bold uppercase tracking-[.15em]">{preview.family}</span><h3 className="mt-2 text-xl font-semibold">{preview.name}</h3><p className="mt-2 text-xs leading-5 text-white/85">{preview.description}</p></div><div className="grid grid-cols-2 gap-2 p-3 pt-0"><div className="rounded-2xl bg-white p-3"><div className="h-16 rounded-xl bg-brand-50"/><p className="mt-2 text-xs font-semibold">Ejemplo 1</p></div><div className="rounded-2xl bg-white p-3"><div className="h-16 rounded-xl bg-[#eef1f4]"/><p className="mt-2 text-xs font-semibold">Ejemplo 2</p></div></div></div></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-[#fafbfc] p-3"><Store className="mx-auto h-4 w-4 text-brand-600"/><p className="mt-1 text-xs font-semibold">{preview.recommended_style}</p></div><div className="rounded-2xl bg-[#fafbfc] p-3"><Sparkles className="mx-auto h-4 w-4 text-brand-600"/><p className="mt-1 text-xs font-semibold">{preview.engine}</p></div><div className="rounded-2xl bg-[#fafbfc] p-3"><LayoutTemplate className="mx-auto h-4 w-4 text-brand-600"/><p className="mt-1 text-xs font-semibold">{preview.product_count} ejemplos</p></div></div></div>}</Modal>
 </SuperAdminShell>
}
