'use client'
import {useEffect,useMemo,useState} from 'react'
import CustomerShell from '@/components/customer-shell'
import {api,money,dateTime} from '@/lib/api'
import {Package} from 'lucide-react'

const labels:any={pending:'Pendiente',confirmed:'Confirmado',processing:'Preparando',preparing:'Preparando',ready:'Listo',out_for_delivery:'En camino',delivered:'Entregado',completed:'Completado',canceled:'Cancelado',cancelled:'Cancelado'}
export default function CustomerOrdersPage(){
 const[orders,setOrders]=useState<any[]>([]),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true)
 useEffect(()=>{api<any[]>('/customer/orders').then(setOrders).finally(()=>setLoading(false))},[])
 const rows=useMemo(()=>filter==='all'?orders:orders.filter(o=>o.status===filter),[orders,filter])
 const completed=orders.filter(o=>['delivered','completed'].includes(o.status)).length,active=orders.filter(o=>!['delivered','completed','canceled','cancelled'].includes(o.status)).length,canceled=orders.filter(o=>['canceled','cancelled'].includes(o.status)).length
 return <CustomerShell active="orders"><section className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-emerald-600">Compras</p><h1 className="mt-1 text-2xl font-semibold">Mis pedidos</h1><p className="mt-1 text-sm text-slate-400">Todos tus pedidos de WAMERCIO en un solo lugar.</p></div><div className="flex flex-wrap gap-2">{[['all','Todos'],['pending','Pendiente'],['preparing','Preparando'],['ready','Listo'],['out_for_delivery','En camino'],['delivered','Entregado'],['canceled','Cancelado']].map(([k,l])=><button key={k} onClick={()=>setFilter(k)} className={`rounded-full px-3 py-2 text-xs font-semibold ${filter===k?'bg-emerald-500 text-white':'border border-slate-200 bg-white text-slate-500'}`}>{l}</button>)}</div></div></section><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="card p-4 text-center"><strong className="text-xl">{orders.length}</strong><div className="text-xs text-slate-400">Total pedidos</div></div><div className="card p-4 text-center"><strong className="text-xl text-emerald-600">{completed}</strong><div className="text-xs text-slate-400">Completados</div></div><div className="card p-4 text-center"><strong className="text-xl text-violet-600">{active}</strong><div className="text-xs text-slate-400">En proceso · {canceled} cancelados</div></div></div><div className="mt-4 space-y-3">{loading?<div className="card p-10 text-center text-slate-400">Cargando pedidos...</div>:rows.length===0?<div className="card grid min-h-52 place-items-center p-8 text-center"><div><Package className="mx-auto h-10 w-10 text-slate-200"/><h3 className="mt-3 font-semibold">No hay pedidos en esta vista</h3></div></div>:rows.map(o=><article key={o.id} className="card flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-600"><Package className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong>#{o.number}</strong><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase text-emerald-700">{labels[o.status]||o.status}</span></div><div className="mt-1 text-sm text-slate-500">{o.store_name} · {o.item_count} producto(s)</div><div className="mt-1 text-xs text-slate-400">{dateTime(o.created_at)}</div></div><div className="flex items-center gap-3"><strong className="text-emerald-600">{money(o.total)}</strong><a href={`/${o.store_slug}`} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">Ver negocio</a></div></article>)}</div></CustomerShell>
}
