'use client'

import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime} from '@/lib/api'
import {Alert,Loading,Modal,PageEmpty,Status,Switch} from '@/components/ui'
import type {AutomationRule,AutomationRun} from '@/lib/types'
import {Clock3,MessageCircleMore,Pencil,Plus,Send,Trash2,Zap} from 'lucide-react'

const events=[
 ['promotion_started','Promoción iniciada','{promocion}, {negocio}'],['reservation_created','Reservación creada','{cliente}, {fecha}, {mesa}, {negocio}'],['reservation_reminder','Recordatorio de reservación','{cliente}, {fecha}, {mesa}, {negocio}'],['order_confirmed','Pedido confirmado','{cliente}, {pedido}, {total}, {negocio}'],['order_ready','Pedido listo','{cliente}, {pedido}, {total}, {negocio}'],['order_completed','Pedido completado','{cliente}, {pedido}, {total}, {negocio}'],['review_request','Solicitud de reseña','{cliente}, {pedido}, {negocio}'],
] as const
const defaults:Record<string,string>={promotion_started:'🔥 {promocion} ya está disponible en {negocio}. Escríbenos para aprovecharla.',reservation_created:'Hola {cliente} 👋 Tu reservación en {negocio} quedó registrada para {fecha}, {mesa}.',reservation_reminder:'Hola {cliente} 👋 Te recordamos tu reservación en {negocio} para {fecha}, {mesa}.',order_confirmed:'Hola {cliente} 👋 Confirmamos tu pedido #{pedido} en {negocio}. Total: {total}.',order_ready:'✅ {cliente}, tu pedido #{pedido} en {negocio} está listo.',order_completed:'Gracias por comprar en {negocio}, {cliente}. Tu pedido #{pedido} fue completado.',review_request:'Hola {cliente} 👋 ¿Cómo fue tu experiencia con el pedido #{pedido} en {negocio}? Tu opinión nos ayuda a mejorar.'}
const blank={name:'',event:'order_ready',audience:'event_customer',template_text:defaults.order_ready,delay_minutes:0,is_active:true}
const eventLabel=(v:string)=>events.find(x=>x[0]===v)?.[1]||v

export default function Automations(){
 const[store,setStore]=useState(''),[rules,setRules]=useState<AutomationRule[]>([]),[runs,setRuns]=useState<AutomationRun[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[edit,setEdit]=useState<AutomationRule|null>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState<'rules'|'history'>('rules')
 const load=()=>{if(!store){setRules([]);setRuns([]);return};setLoading(true);setErr('');Promise.all([api<AutomationRule[]>(`/automations?store_id=${store}`),api<AutomationRun[]>(`/automations/runs?store_id=${store}`)]).then(([a,b])=>{setRules(a);setRuns(b)}).catch((e:any)=>setErr(e.message)).finally(()=>setLoading(false))}
 useEffect(load,[store])
 const start=(row?:AutomationRule)=>{setEdit(row||null);setForm(row?{...row}:{...blank});setErr('');setOpen(true)}
 const setEvent=(event:string)=>setForm((v:any)=>({...v,event,template_text:edit?v.template_text:(defaults[event]||v.template_text)}))
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setErr('');try{const body={...form,store_id:store,name:String(form.name||'').trim(),template_text:String(form.template_text||'').trim(),delay_minutes:Number(form.delay_minutes||0)};if(!body.name||!body.template_text)throw new Error('Completa nombre y mensaje.');if(edit)await api(`/automations/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/automations',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const remove=async(row:AutomationRule)=>{if(!confirm(`¿Eliminar ${row.name}?`))return;try{await api(`/automations/${row.id}`,{method:'DELETE'});load()}catch(e:any){setErr(e.message)}}
 const activeCount=useMemo(()=>rules.filter(x=>x.is_active).length,[rules])
 return <StoreShell title="Automatizaciones" subtitle="Mensajes comerciales disparados por eventos reales de WAMERCIO" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store} className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Nueva regla</button>}>
  <div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="card p-4"><p className="section-kicker">Reglas activas</p><p className="mt-1 text-2xl font-semibold">{activeCount}</p></div><div className="card p-4"><p className="section-kicker">Mensajes registrados</p><p className="mt-1 text-2xl font-semibold">{runs.length}</p></div><div className="card p-4"><p className="section-kicker">Motor</p><p className="mt-1 flex items-center gap-2 text-sm font-semibold text-emerald-700"><Zap className="h-4 w-4"/>WhatsApp Outbox</p></div></div>
  <div className="mb-5 flex gap-2 rounded-2xl border border-[#edf0f4] bg-white p-1.5"><button onClick={()=>setTab('rules')} className={`flex-1 rounded-xl px-4 py-2.5 text-sm font-semibold ${tab==='rules'?'bg-brand-50 text-brand-700':'text-[#83899f]'}`}>Reglas</button><button onClick={()=>setTab('history')} className={`flex-1 rounded-xl px-4 py-2.5 text-sm font-semibold ${tab==='history'?'bg-brand-50 text-brand-700':'text-[#83899f]'}`}>Historial</button></div>
  {!store?<PageEmpty title="Selecciona una tienda" detail="Elige una tienda para gestionar sus automatizaciones."/>:loading?<Loading/>:<div className="space-y-4">{err&&<Alert text={err}/>} {tab==='rules'?(rules.length===0?<PageEmpty title="No hay automatizaciones" detail="Crea reglas para promociones, reservaciones y estados de pedidos sin duplicar el sistema de WhatsApp." action={<button className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Crear regla</button>}/>:<div className="grid gap-4 lg:grid-cols-2">{rules.map(row=><article key={row.id} className="card p-5"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-600"><MessageCircleMore className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate font-semibold">{row.name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${row.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{row.is_active?'Activa':'Pausada'}</span></div><p className="mt-1 text-xs font-medium text-brand-700">{eventLabel(row.event)}</p></div></div><p className="mt-4 rounded-2xl bg-[#f8fafb] p-3 text-sm leading-6 text-[#6f768d]">{row.template_text}</p><div className="mt-3 flex flex-wrap gap-2 text-[11px] text-[#8f95aa]"><span className="rounded-full bg-[#f3f5f7] px-2.5 py-1">{row.audience==='all_customers'?'Todos los clientes':'Cliente del evento'}</span><span className="rounded-full bg-[#f3f5f7] px-2.5 py-1"><Clock3 className="mr-1 inline h-3 w-3"/>{row.delay_minutes?`${row.delay_minutes} min`:'Inmediato'}</span></div><div className="mt-4 flex gap-2 border-t border-slate-100 pt-4"><button className="btn-secondary flex-1" onClick={()=>start(row)}><Pencil className="h-4 w-4"/>Editar</button><button className="btn-danger px-3" onClick={()=>void remove(row)}><Trash2 className="h-4 w-4"/></button></div></article>)}</div>):(runs.length===0?<PageEmpty title="Sin ejecuciones todavía" detail="Aquí aparecerán los mensajes generados por las reglas cuando ocurran eventos."/>:<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Regla</th><th>Evento</th><th>Destino</th><th>Programado</th><th>Estado</th></tr></thead><tbody>{runs.map(run=><tr key={run.id}><td><div className="font-semibold">{run.rule_name}</div><div className="mt-1 max-w-[320px] truncate text-xs text-[#969caf]" title={run.rendered_text}>{run.rendered_text}</div>{run.error&&<div className="mt-1 text-[11px] text-rose-600">{run.error}</div>}</td><td>{eventLabel(run.event)}</td><td>{run.destination?`+${run.destination}`:'—'}</td><td className="text-xs">{dateTime(run.scheduled_for)}</td><td><Status value={run.status}/></td></tr>)}</tbody></table></div>)}</div>}
  <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar automatización':'Nueva automatización'} subtitle="La regla se procesa en segundo plano y envía el mensaje usando el mismo motor WhatsApp de WAMERCIO." wide>
   <form onSubmit={save}>{err&&<Alert text={err}/>}<div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-4"><div><label className="label">Nombre *</label><input autoFocus className="field" required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ej.: Avisar cuando el pedido esté listo"/></div><div><label className="label">Evento</label><select className="field" value={form.event} onChange={e=>setEvent(e.target.value)}>{events.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div><div><label className="label">Mensaje *</label><textarea className="field min-h-40 resize-none" required value={form.template_text||''} onChange={e=>setForm({...form,template_text:e.target.value})}/><p className="mt-2 text-xs text-[#969caf]">Variables disponibles: {events.find(x=>x[0]===form.event)?.[2]||'{cliente}, {negocio}'}</p></div></div><aside className="space-y-4"><div><label className="label">Audiencia</label><select className="field" value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="event_customer">Cliente relacionado</option><option value="all_customers">Todos los clientes</option></select></div><div><label className="label">Retraso (minutos)</label><input className="field" type="number" min="0" max="43200" value={form.delay_minutes||0} onChange={e=>setForm({...form,delay_minutes:Number(e.target.value)})}/></div><Switch checked={form.is_active!==false} onChange={v=>setForm({...form,is_active:v})} label="Regla activa" detail="Páusala sin perder su configuración ni historial."/><div className="rounded-2xl border border-brand-100 bg-brand-50/50 p-4"><Send className="h-5 w-5 text-brand-600"/><p className="mt-2 text-sm font-semibold text-brand-800">No bloquea la operación</p><p className="mt-1 text-xs leading-5 text-brand-800/75">Si WhatsApp no está disponible, el pedido o reservación continúa y el error queda registrado.</p></div></aside></div><div className="mt-6 flex justify-end gap-2 border-t border-slate-100 pt-5"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button disabled={busy} className="btn-primary">{busy?'Guardando...':'Guardar regla'}</button></div></form>
  </Modal>
 </StoreShell>
}
