'use client'
import {useEffect,useMemo,useState} from 'react'
import AdminShell from '@/components/store-shell'
import {Alert,Loading,Modal,PageEmpty,SearchBox,Status} from '@/components/ui'
import {api,dateTime} from '@/lib/api'
import type {SupportTicket,TicketMessage} from '@/lib/types'
import {LifeBuoy,MessageSquarePlus,Send,LockKeyhole} from 'lucide-react'

export default function SupportPage(){
 const [rows,setRows]=useState<SupportTicket[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[open,setOpen]=useState(false),[selected,setSelected]=useState<SupportTicket|null>(null),[detail,setDetail]=useState<SupportTicket|null>(null),[reply,setReply]=useState(''),[error,setError]=useState('')
 const [form,setForm]=useState({subject:'',priority:'normal',message:''})
 const load=()=>{setLoading(true);api<SupportTicket[]>('/tickets').then(setRows).finally(()=>setLoading(false))}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(x=>`${x.number} ${x.subject} ${x.status}`.toLowerCase().includes(q.toLowerCase())),[rows,q])
 const view=async(t:SupportTicket)=>{setSelected(t);setError('');setDetail(await api<SupportTicket>(`/tickets/${t.id}`))}
 const create=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await api('/tickets',{method:'POST',body:JSON.stringify(form)});setOpen(false);setForm({subject:'',priority:'normal',message:''});load()}catch(e:any){setError(e.message)}}
 const send=async()=>{if(!selected||!reply.trim())return;setError('');try{await api(`/tickets/${selected.id}/reply`,{method:'POST',body:JSON.stringify({message:reply})});setReply('');setDetail(await api(`/tickets/${selected.id}`));load()}catch(e:any){setError(e.message)}}
 const close=async()=>{if(!selected)return;await api(`/tickets/${selected.id}/close`,{method:'PATCH'});setDetail(await api(`/tickets/${selected.id}`));load()}
 return <AdminShell title="Centro de soporte" subtitle="Tickets de ayuda para tu cuenta WAMERCIO" actions={<button className="btn-primary" onClick={()=>setOpen(true)}><MessageSquarePlus className="h-4 w-4"/> Nuevo ticket</button>}>
  <div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#f0f1f5] p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Mis tickets</h2><p className="text-sm text-[#8d92aa]">Conserva el historial de cada solicitud de soporte.</p></div><SearchBox value={q} onChange={setQ}/></div>{loading?<Loading/>:filtered.length===0?<PageEmpty title="No tienes tickets" detail="Si necesitas ayuda, abre un ticket y el equipo de WAMERCIO podrá responderte." action={<button className="btn-primary" onClick={()=>setOpen(true)}>Crear ticket</button>}/>:<div className="divide-y divide-slate-100">{filtered.map(t=><button key={t.id} onClick={()=>view(t)} className="flex w-full items-center gap-4 p-4 text-left hover:bg-[#fafbfe]"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-600"><LifeBuoy className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="truncate text-ink-900">#{t.number} · {t.subject}</strong><Status value={t.status}/></div><p className="mt-1 text-xs text-[#8d92aa]">Prioridad: {priorityLabel(t.priority)} · Última actividad {dateTime(t.last_reply_at)}</p></div></button>)}</div>}</div>
  <Modal open={open} onClose={()=>setOpen(false)} title="Nuevo ticket"><form onSubmit={create} className="space-y-4">{error&&<Alert text={error}/>}<div><label className="label">Asunto</label><input className="field" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} required/></div><div><label className="label">Prioridad</label><select className="field" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div><div><label className="label">Mensaje</label><textarea className="field min-h-36" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} required/></div><button className="btn-primary w-full">Enviar ticket</button></form></Modal>
  <Modal open={!!selected} onClose={()=>{setSelected(null);setDetail(null)}} title={detail?`Ticket #${detail.number} · ${detail.subject}`:'Ticket'} wide>{error&&<Alert text={error}/>} {!detail?<Loading/>:<div><div className="mb-4 flex flex-wrap items-center gap-2 rounded-xl bg-[#fafbfe] p-3"><Status value={detail.status}/><span className="text-sm text-[#8d92aa]">Prioridad {priorityLabel(detail.priority)}</span><span className="ml-auto text-xs text-[#a2a6b8]">{dateTime(detail.created_at)}</span></div><div className="space-y-3">{(detail.messages||[]).map((m:TicketMessage)=><div key={m.id} className={`flex ${m.sender_role==='superadmin'?'justify-start':'justify-end'}`}><div className={`max-w-[85%] rounded-lg px-4 py-3 ${m.sender_role==='superadmin'?'bg-[#f1f2f6] text-slate-800':'bg-brand-600 text-white'}`}><div className="mb-1 text-xs font-semibold opacity-70">{m.sender_role==='superadmin'?'Soporte WAMERCIO':'Tú'}</div><div className="whitespace-pre-wrap text-sm">{m.message}</div><div className="mt-1 text-[10px] opacity-60">{dateTime(m.created_at)}</div></div></div>)}</div>{detail.status==='closed'?<div className="mt-5 flex items-center justify-center gap-2 rounded-xl bg-[#f1f2f6] p-4 text-sm font-medium text-slate-600"><LockKeyhole className="h-4 w-4"/> Este ticket está cerrado.</div>:<div className="mt-5 border-t border-[#f0f1f5] pt-4"><textarea className="field min-h-24" placeholder="Escribe una respuesta..." value={reply} onChange={e=>setReply(e.target.value)}/><div className="mt-3 flex justify-between"><button className="btn-secondary" onClick={close}>Cerrar ticket</button><button className="btn-primary" onClick={send}><Send className="h-4 w-4"/> Responder</button></div></div>}</div>}</Modal>
 </AdminShell>
}
function priorityLabel(v:string){return ({low:'Baja',normal:'Normal',high:'Alta',urgent:'Urgente'} as any)[v]||v}
