'use client'
import {useEffect,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime} from '@/lib/api'
import {Alert,Loading,Modal,PageEmpty,Status} from '@/components/ui'
import {Plus,Pencil,Trash2,UserCog} from 'lucide-react'
const blank={name:'',phone:'',role:'operator',panel:'operations',pin:'',status:'active'}
export default function StaffPage(){
 const[store,setStore]=useState(''),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState('')
 const load=()=>{if(!store){setRows([]);return};setLoading(true);api<any[]>(`/staff?store_id=${store}`).then(setRows).finally(()=>setLoading(false))};useEffect(load,[store])
 const start=(x?:any)=>{setEdit(x||null);setForm(x?{...x,pin:''}:{...blank});setErr('');setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');try{const body={...form,store_id:store};if(edit)await api(`/staff/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/staff',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e:any){setErr(e.message)}}
 const del=async(x:any)=>{if(confirm(`¿Eliminar a ${x.name}?`)){await api(`/staff/${x.id}`,{method:'DELETE'});load()}}
 return <StoreShell title="Usuarios" subtitle="Crea usuarios internos y asigna el panel que podrán usar" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store} className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Agregar usuario</button>}>
  {!store?<PageEmpty title="Selecciona un negocio" detail="Los usuarios internos pertenecen a cada negocio."/>:loading?<Loading/>:<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Usuario</th><th>WhatsApp</th><th>Rol</th><th>Panel</th><th>Estado</th><th>Creado</th><th></th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-brand-50 text-brand-700"><UserCog className="h-4 w-4"/></span><span className="font-semibold">{x.name}</span></div></td><td>{x.phone||'—'}</td><td>{x.role==='cashier'?'Cajero':x.role==='delivery'?'Repartidor':x.role==='admin'?'Administrador':'Operaciones'}</td><td>{x.panel}</td><td><Status value={x.status}/></td><td>{dateTime(x.created_at)}</td><td className="text-right"><button className="btn-secondary px-3" onClick={()=>start(x)}><Pencil className="h-4 w-4"/></button><button className="btn-danger ml-2 px-3" onClick={()=>del(x)}><Trash2 className="h-4 w-4"/></button></td></tr>):<tr><td colSpan={7} className="py-10 text-center text-[#9ba0b4]">No hay usuarios internos todavía.</td></tr>}</tbody></table></div>}
  <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar usuario':'Agregar usuario'} subtitle="Asigna una función clara para mantener la operación simple."><form onSubmit={save}>{err&&<Alert text={err}/>}<div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Nombre *</label><input required className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="label">WhatsApp</label><input className="field" value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="label">Rol</label><select className="field" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="admin">Administrador</option><option value="cashier">Cajero</option><option value="operator">Operaciones</option><option value="delivery">Repartidor</option></select></div><div><label className="label">Panel</label><select className="field" value={form.panel} onChange={e=>setForm({...form,panel:e.target.value})}><option value="operations">Operaciones</option><option value="pos">Punto de Venta</option><option value="delivery">Entregas</option><option value="catalog">Catálogo</option></select></div>{!edit&&<div><label className="label">PIN de 4 dígitos</label><input inputMode="numeric" maxLength={4} className="field" value={form.pin} onChange={e=>setForm({...form,pin:e.target.value.replace(/\D/g,'').slice(0,4)})}/></div>}{edit&&<div><label className="label">Estado</label><select className="field" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Activo</option><option value="inactive">Inactivo</option></select></div>}</div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary">Guardar</button></div></form></Modal>
 </StoreShell>
}
