'use client'
import {useEffect,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime} from '@/lib/api'
import {Alert,Loading,Modal,PageEmpty,Status} from '@/components/ui'
import PhoneInput,{phoneDisplay} from '@/components/phone-input'
import {CheckCircle2,IdCard,Plus,Pencil,RefreshCw,Trash2,UserCog} from 'lucide-react'

const blank={name:'',last_name:'',phone:'',document_number:'',birth_date:'',gender:'',role:'operator',panel:'operations',pin:'',status:'active',identity_verified:false,whatsapp_verified:false,whatsapp_name:'',profile_picture_url:''}
const digits=(v:string)=>String(v||'').replace(/\D/g,'')
const formatCedula=(v:string)=>{const d=digits(v).slice(0,11);return [d.slice(0,3),d.slice(3,10),d.slice(10,11)].filter(Boolean).join('-')}
const normalizeGender=(v:any)=>{const x=String(v||'').toLowerCase();if(x.startsWith('m'))return'masculino';if(x.startsWith('f'))return'femenino';return String(v||'')}

export default function StaffPage(){
 const[store,setStore]=useState(''),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState(''),[staffPinLength,setStaffPinLength]=useState(4)
 const[phoneValid,setPhoneValid]=useState(false),[waState,setWaState]=useState<'idle'|'checking'|'valid'|'invalid'>('idle'),[lastWa,setLastWa]=useState(''),[identityVerified,setIdentityVerified]=useState(false),[verifying,setVerifying]=useState(false)
 const load=()=>{if(!store){setRows([]);return};setLoading(true);api<any[]>(`/staff?store_id=${store}`).then(setRows).finally(()=>setLoading(false))};useEffect(load,[store]);useEffect(()=>{api<any>('/public/platform').then(x=>setStaffPinLength(Math.max(4,Math.min(8,Number(x?.access?.staff_pin_length)||4)))).catch(()=>{})},[])
 const start=(x?:any)=>{setEdit(x||null);setForm(x?{...blank,...x,pin:''}:{...blank});setErr('');setPhoneValid(Boolean(x?.phone));setWaState(x?.whatsapp_verified?'valid':'idle');setLastWa(x?.whatsapp_verified?digits(x.phone):'');setIdentityVerified(!!x?.identity_verified);setOpen(true)}
 const validateWhatsApp=async(silent=true)=>{const phone=digits(form.phone);if(phone.length<10||!phoneValid){setWaState('idle');return false}if(lastWa===phone&&waState==='valid')return true;setWaState('checking');try{await api('/auth/store/validate-whatsapp',{method:'POST',body:JSON.stringify({phone:form.phone})});setWaState('valid');setLastWa(phone);return true}catch(e:any){setWaState('invalid');if(!silent)setErr(e.message);return false}}
 useEffect(()=>{if(!open||!phoneValid||digits(form.phone).length<10||digits(form.phone)===lastWa)return;const t=window.setTimeout(()=>void validateWhatsApp(true),650);return()=>window.clearTimeout(t)},[open,form.phone,phoneValid,lastWa])
 const verifyCedula=async()=>{const cedula=digits(form.document_number);if(cedula.length!==11){setErr('La Cédula debe tener exactamente 11 dígitos.');return}setVerifying(true);setErr('');try{const out=await api<any>('/auth/store/verify-identity',{method:'POST',body:JSON.stringify({cedula})});const p=out?.profile||{};setForm((v:any)=>({...v,document_number:cedula,name:String(p.name||v.name||''),last_name:String(p.last_name||v.last_name||''),birth_date:String(p.birth_date||v.birth_date||''),gender:normalizeGender(p.gender||v.gender)}));setIdentityVerified(true)}catch(e:any){setIdentityVerified(false);setErr(e.message)}finally{setVerifying(false)}}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');if(!await validateWhatsApp(false))return;if(digits(form.document_number).length!==11){setErr('La Cédula es obligatoria y debe tener exactamente 11 dígitos.');return}if(!identityVerified){setErr('Verifica la Cédula antes de guardar el usuario.');return}if(!form.name.trim()){setErr('El nombre es obligatorio.');return}try{const body={...form,store_id:store,identity_verified:identityVerified};if(edit)await api(`/staff/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/staff',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e:any){setErr(e.message)}}
 const del=async(x:any)=>{if(confirm(`¿Eliminar a ${x.name}?`)){await api(`/staff/${x.id}`,{method:'DELETE'});load()}}
 const locked=identityVerified
 return <StoreShell title="Usuarios" subtitle="Crea usuarios internos y asigna el panel que podrán usar" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store} className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Agregar usuario</button>}>
  {!store?<PageEmpty title="Selecciona un negocio" detail="Los usuarios internos pertenecen a cada negocio."/>:loading?<Loading/>:<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Usuario</th><th>WhatsApp</th><th>Rol</th><th>Panel</th><th>Estado</th><th>Creado</th><th></th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><div className="flex min-w-[210px] items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-full bg-brand-50 text-brand-700">{x.profile_picture_url?<img src={x.profile_picture_url} alt={x.whatsapp_name||x.name} className="h-full w-full object-cover"/>:<UserCog className="h-4 w-4"/>}</span><span className="min-w-0"><span className="block truncate font-semibold">{[x.name,x.last_name].filter(Boolean).join(' ')}</span>{x.whatsapp_name&&x.whatsapp_name!==[x.name,x.last_name].filter(Boolean).join(' ')&&<span className="block truncate text-[11px] text-brand-600">WhatsApp: {x.whatsapp_name}</span>}</span></div></td><td>{x.phone?phoneDisplay(x.phone):'—'}</td><td>{x.role==='cashier'?'Cajero':x.role==='delivery'?'Repartidor':x.role==='admin'?'Administrador':'Operaciones'}</td><td>{x.panel}</td><td><Status value={x.status}/></td><td>{dateTime(x.created_at)}</td><td className="text-right"><button className="btn-secondary px-3" onClick={()=>start(x)}><Pencil className="h-4 w-4"/></button><button className="btn-danger ml-2 px-3" onClick={()=>del(x)}><Trash2 className="h-4 w-4"/></button></td></tr>):<tr><td colSpan={7} className="py-10 text-center text-[#9ba0b4]">No hay usuarios internos todavía.</td></tr>}</tbody></table></div>}
  <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar usuario':'Agregar usuario'} subtitle="Verifica su identidad y asigna una función clara para mantener la operación simple."><form onSubmit={save}>{err&&<Alert text={err}/>}<div className="grid gap-4 sm:grid-cols-2">
   <div><label className="label">WhatsApp *</label><PhoneInput value={form.phone||''} onChange={phone=>{setForm({...form,phone});setWaState('idle');setLastWa('')}} onValidityChange={setPhoneValid} required/><p className={`mt-1.5 text-xs font-semibold ${waState==='valid'?'text-emerald-600':waState==='invalid'?'text-rose-600':'text-[#9298ad]'}`}>{waState==='checking'?'Verificando WhatsApp...':waState==='valid'?'WhatsApp activo y validado.':waState==='invalid'?'No se pudo validar este WhatsApp.':'Introduce el WhatsApp del usuario.'}</p></div>
   <div><label className="label">Cédula *</label><div className="flex gap-2"><div className="relative flex-1"><IdCard className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#a2a6b8]"/><input inputMode="numeric" readOnly={locked} className={`field pl-10 ${locked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={formatCedula(form.document_number||'')} onChange={e=>{setIdentityVerified(false);setForm({...form,document_number:digits(e.target.value).slice(0,11)})}} placeholder="000-0000000-0"/></div><button type="button" className="btn-secondary px-3" disabled={locked||verifying||digits(form.document_number).length!==11} onClick={verifyCedula}>{locked?<CheckCircle2 className="h-4 w-4"/>:verifying?<RefreshCw className="h-4 w-4 animate-spin"/>:'Verificar'}</button></div>{locked&&<p className="mt-1.5 text-xs font-semibold text-emerald-600">Identidad verificada y datos protegidos.</p>}</div>
   <div><label className="label">Nombre *</label><input required readOnly={locked} className={`field ${locked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div>
   <div><label className="label">Apellido</label><input readOnly={locked} className={`field ${locked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={form.last_name||''} onChange={e=>setForm({...form,last_name:e.target.value})}/></div>
   <div><label className="label">Fecha de nacimiento</label><input type="date" readOnly={locked} className={`field ${locked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={form.birth_date||''} onChange={e=>setForm({...form,birth_date:e.target.value})}/></div>
   <div><label className="label">Género</label><select disabled={locked} className={`field ${locked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={form.gender||''} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Seleccionar género</option><option value="masculino">Masculino</option><option value="femenino">Femenino</option></select></div>
   <div><label className="label">Rol</label><select className="field" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="admin">Administrador</option><option value="cashier">Cajero</option><option value="operator">Operaciones</option><option value="delivery">Repartidor</option></select></div>
   <div><label className="label">Panel</label><select className="field" value={form.panel} onChange={e=>setForm({...form,panel:e.target.value})}><option value="operations">Operaciones</option><option value="pos">Punto de Venta</option><option value="delivery">Entregas</option><option value="catalog">Catálogo</option></select></div>
   {!edit&&<div><label className="label">PIN de {staffPinLength} dígitos</label><input inputMode="numeric" maxLength={staffPinLength} className="field" value={form.pin} onChange={e=>setForm({...form,pin:e.target.value.replace(/\D/g,'').slice(0,staffPinLength)})}/></div>}{edit&&<div><label className="label">Estado</label><select className="field" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Activo</option><option value="inactive">Inactivo</option></select></div>}
  </div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary">Guardar</button></div></form></Modal>
 </StoreShell>
}
