'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import AdminShell from '@/components/store-shell'
import {api,dateTime,money} from '@/lib/api'
import {Alert,Loading,Status} from '@/components/ui'
import PhoneInput,{phoneDisplay} from '@/components/phone-input'
import PinInput from '@/components/pin-input'
import {ArrowRight,Headphones,IdCard,KeyRound,Layers3,Save,ShieldCheck,UserRound} from 'lucide-react'

const digits=(v:string)=>String(v||'').replace(/\D/g,'')
const formatCedula=(v:string)=>{const d=digits(v).slice(0,11);return [d.slice(0,3),d.slice(3,10),d.slice(10,11)].filter(Boolean).join('-')}

export default function Profile(){
 const[me,setMe]=useState<any>(null),[form,setForm]=useState<any>(null),[pin,setPin]=useState({current_pin:'',new_pin:''}),[err,setErr]=useState(''),[ok,setOk]=useState(''),[busy,setBusy]=useState(false),[sub,setSub]=useState<any>(null),[support,setSupport]=useState<any>(null),[pinLength,setPinLength]=useState(4)
 const load=()=>api('/me').then((x:any)=>{setMe(x);setForm({name:x.name||'',last_name:x.last_name||'',phone:x.phone||'',document_number:x.document_number||'',birth_date:x.birth_date||'',gender:x.gender||''})})
 useEffect(()=>{load();api('/subscription').then(setSub).catch(()=>{});api('/support/whatsapp').then(setSupport).catch(()=>{});api<any>('/public/platform').then(x=>setPinLength(Math.max(4,Math.min(8,Number(x?.access?.owner_pin_length)||4)))).catch(()=>{})},[])
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');setOk('');setBusy(true);try{await api('/me',{method:'PATCH',body:JSON.stringify(form)});await load();setOk('Perfil actualizado correctamente.')}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const change=async(e:React.FormEvent)=>{e.preventDefault();setErr('');setOk('');if(!new RegExp(`^\\d{${pinLength}}$`).test(pin.current_pin)||!new RegExp(`^\\d{${pinLength}}$`).test(pin.new_pin)){setErr(`Completa los ${pinLength} dígitos del PIN actual y del nuevo PIN.`);return}setBusy(true);try{await api('/me/pin',{method:'POST',body:JSON.stringify({current_pin:pin.current_pin,new_pin:pin.new_pin})});setPin({current_pin:'',new_pin:''});setOk('PIN actualizado correctamente.')}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const identityLocked=!!me?.identity_verified
 return <AdminShell title="Mi cuenta" subtitle="Tu acceso, identidad, plan y ayuda en un solo lugar">{!me||!form?<Loading/>:<div>{err&&<Alert text={err}/>} {ok&&<Alert text={ok} type="success"/>}<div className="grid gap-5 xl:grid-cols-[1fr_420px]">
  <form onSubmit={save} className="card p-5 sm:p-6"><div className="flex items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-full bg-brand-50 text-brand-600">{me.profile_picture_url?<img src={me.profile_picture_url} alt={me.whatsapp_name||`${me.name} ${me.last_name||''}`} className="h-full w-full object-cover"/>:<UserRound className="h-7 w-7"/>}</div><div className="min-w-0"><h2 className="truncate text-xl font-bold">{[me.name,me.last_name].filter(Boolean).join(' ')}</h2><p className="text-sm text-[#8d92aa]">{me.whatsapp_name&&me.whatsapp_name!==[me.name,me.last_name].filter(Boolean).join(' ')?`WhatsApp: ${me.whatsapp_name}`:'Cuenta comercial WAMERCIO'}</p><p className="mt-0.5 text-xs font-medium text-brand-600">{phoneDisplay(me.phone)}</p></div></div>
   <div className="mt-6 grid gap-4 sm:grid-cols-2"><div><label className="label">WhatsApp de acceso *</label><PhoneInput value={form.phone} onChange={value=>setForm({...form,phone:value})} required/><p className="mt-1 text-xs text-[#a2a6b8]">Este número funciona como tu usuario.</p></div><div><label className="label">Cédula</label><div className="relative"><IdCard className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#a2a6b8]"/><input inputMode="numeric" readOnly={identityLocked} className={`field pl-10 ${identityLocked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={formatCedula(form.document_number)} onChange={e=>setForm({...form,document_number:digits(e.target.value).slice(0,11)})} placeholder="000-0000000-0"/></div>{identityLocked&&<p className="mt-1 text-xs font-semibold text-emerald-600">Identidad verificada · datos protegidos</p>}</div><div><label className="label">Nombre *</label><input required readOnly={identityLocked} className={`field ${identityLocked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="label">Apellido</label><input readOnly={identityLocked} className={`field ${identityLocked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></div><div><label className="label">Fecha de nacimiento</label><input type="date" readOnly={identityLocked} className={`field ${identityLocked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={form.birth_date} onChange={e=>setForm({...form,birth_date:e.target.value})}/></div><div><label className="label">Género</label><select disabled={identityLocked} className={`field ${identityLocked?'bg-[#f7f8fb] text-[#6f758c]':''}`} value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Seleccionar género</option><option value="masculino">Masculino</option><option value="femenino">Femenino</option></select></div></div>
   <div className="mt-6 flex flex-col gap-3 border-t border-[#f0f1f5] pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-[#a2a6b8]">Cuenta creada: {dateTime(me.created_at)}</p><button disabled={busy} className="btn-primary"><Save className="h-4 w-4"/>Guardar cambios</button></div></form>
  <form onSubmit={change} className="card p-5 sm:p-6"><div className="grid h-12 w-12 place-items-center rounded-full bg-brand-50 text-brand-600"><ShieldCheck/></div><h3 className="mt-4 text-lg font-bold">PIN de acceso</h3><p className="mt-1 text-sm leading-6 text-[#8d92aa]">Usa el número de dígitos definido por la plataforma y evita combinaciones predecibles.</p><div className="mt-5 space-y-5"><div><label className="label">PIN actual</label><PinInput value={pin.current_pin} onChange={value=>setPin({...pin,current_pin:value})} required label="PIN actual" length={pinLength}/></div><div><label className="label">Nuevo PIN</label><PinInput value={pin.new_pin} onChange={value=>setPin({...pin,new_pin:value})} required label="Nuevo PIN" length={pinLength}/></div></div><button disabled={busy} className="btn-secondary mt-5 w-full"><KeyRound className="h-4 w-4"/>Cambiar PIN</button></form>
 </div>
 <div className="mt-5 grid gap-5 lg:grid-cols-2">
  <section className="card p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Layers3 className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="text-xs font-semibold uppercase tracking-[.12em] text-brand-600">Plan actual</p><div className="mt-1 flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold text-ink-900">{sub?.plan?.name||'WAMERCIO'}</h3>{sub?.status&&<Status value={sub.status}/>}</div><p className="mt-1 text-sm text-[#8d92aa]">{sub?.plan?.price?`${money(sub.plan.price)} / ${sub.plan.billing_period==='monthly'?'mes':'periodo'}`:'Plan gratuito o pendiente de asignación'}</p></div></div>{sub&&<div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#fafbfe] p-4"><p className="text-xs text-[#8d92aa]">Tiendas</p><p className="mt-1 text-lg font-semibold">{sub.usage?.stores||0} / {sub.plan?.max_stores||0}</p></div><div className="rounded-2xl bg-[#fafbfe] p-4"><p className="text-xs text-[#8d92aa]">Productos</p><p className="mt-1 text-lg font-semibold">{sub.usage?.products||0} / {sub.plan?.max_products||0}</p></div></div>}<Link href="/plans" className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-brand-600">Ver o cambiar plan <ArrowRight className="h-4 w-4"/></Link></section>
  <section className="card p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Headphones className="h-5 w-5"/></span><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-brand-600">Ayuda</p><h3 className="mt-1 text-lg font-semibold text-ink-900">Soporte directo por WhatsApp</h3><p className="mt-2 text-sm leading-6 text-[#8d92aa]">Si necesitas ayuda con tu cuenta o tu tienda, conversa directamente con el equipo de WAMERCIO.</p></div></div>{support?.phone?<a target="_blank" rel="noreferrer" href={`https://wa.me/${String(support.phone).replace(/\D/g,'')}`} className="btn-primary mt-5 w-full">Abrir soporte por WhatsApp</a>:<p className="mt-5 rounded-2xl bg-[#fafbfe] p-4 text-sm text-[#8d92aa]">El canal de soporte todavía no está conectado.</p>}</section>
 </div>
 </div>}</AdminShell>
}
