'use client'

import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime} from '@/lib/api'
import {Alert,Loading,PageEmpty} from '@/components/ui'
import {BellRing,ChefHat,Clock3,RefreshCw,CheckCircle2,Truck,Store as StoreIcon,UtensilsCrossed} from 'lucide-react'

type KDSItem={product_name:string;variant_name:string;extras:any;quantity:number}
type KDSOrder={id:string;number:number;customer_name:string;customer_phone:string;status:string;delivery_type:string;notes:string;created_at:string;total:number;table_name:string;area_name:string;items:KDSItem[]}
type Settings={dine_in_enabled?:boolean}
const columns=[
 {key:'new',title:'Nuevos',detail:'Por comenzar',statuses:['pending','confirmed'],icon:BellRing},
 {key:'preparing',title:'Preparando',detail:'En cocina',statuses:['processing','preparing'],icon:ChefHat},
 {key:'ready',title:'Listos',detail:'Para entregar',statuses:['ready'],icon:CheckCircle2},
]
function elapsed(value:string){const min=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(min<60)return `${min} min`;return `${Math.floor(min/60)} h ${min%60} min`}
function extrasText(value:any){if(!value)return '';const rows=Array.isArray(value)?value:[];return rows.map((x:any)=>typeof x==='string'?x:x?.name||'').filter(Boolean).join(', ')}
function fulfillment(order:KDSOrder){if(order.delivery_type==='dine_in')return order.table_name?`${order.area_name?`${order.area_name} · `:''}${order.table_name}`:'Mesa';if(order.delivery_type==='pickup')return 'Recoger';return 'Delivery'}

export default function KDS(){
 const[store,setStore]=useState(''),[rows,setRows]=useState<KDSOrder[]>([]),[settings,setSettings]=useState<Settings|null>(null),[loading,setLoading]=useState(false),[refreshing,setRefreshing]=useState(false),[err,setErr]=useState('')
 const load=async(silent=false)=>{if(!store){setRows([]);setSettings(null);return};silent?setRefreshing(true):setLoading(true);try{const [orders,config]=await Promise.all([api<KDSOrder[]>(`/kds?store_id=${store}`),api<Settings>(`/stores/${store}/settings`)]);setRows(orders);setSettings(config);setErr('')}catch(e:any){setErr(e.message)}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load();if(!store)return;const timer=setInterval(()=>void load(true),15000);return()=>clearInterval(timer)},[store])
 const grouped=useMemo(()=>columns.map(column=>({...column,rows:rows.filter(row=>column.statuses.includes(row.status))})),[rows])
 const move=async(order:KDSOrder)=>{let status='preparing';if(order.status==='processing'||order.status==='preparing')status='ready';else if(order.status==='ready')status=order.delivery_type==='delivery'?'out_for_delivery':order.delivery_type==='pickup'?'picked_up':'delivered';try{await api(`/orders/${order.id}/status`,{method:'PATCH',body:JSON.stringify({status})});setRows(current=>status==='out_for_delivery'||status==='picked_up'||status==='delivered'?current.filter(x=>x.id!==order.id):current.map(x=>x.id===order.id?{...x,status}:x));setErr('')}catch(e:any){setErr(e.message)}}
 return <StoreShell title="KDS · Cocina" subtitle="Pedidos en vivo para preparación y entrega" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store||refreshing} className="btn-secondary" onClick={()=>void load(true)}><RefreshCw className={`h-4 w-4 ${refreshing?'animate-spin':''}`}/>Actualizar</button>}>
  {!store?<PageEmpty title="Selecciona un negocio" detail="Elige el negocio que mostrará la pantalla de cocina."/>:loading?<Loading/>:<div className="space-y-4">{err&&<Alert text={err}/>} {!settings?.dine_in_enabled&&<div className="rounded-2xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-800">El KDS está disponible como capacidad gastronómica. Activa Mesas y reservas en Configuración si este negocio trabajará con consumo en mesa.</div>}<div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#edf0f5] bg-white px-4 py-3 text-xs text-[#858ba0]"><span>Actualización automática cada 15 segundos</span><span>{rows.length} pedidos activos</span></div>
   <div className="grid gap-4 xl:grid-cols-3">{grouped.map(column=>{const I=column.icon;return <section key={column.key} className="min-w-0 rounded-[26px] border border-[#e8ebf0] bg-[#f4f6f9] p-3"><div className="flex items-center gap-3 px-2 py-2"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white text-brand-600 shadow-sm"><I className="h-5 w-5"/></span><div className="min-w-0 flex-1"><h2 className="font-semibold text-ink-900">{column.title}</h2><p className="text-xs text-[#9298ab]">{column.detail}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-xs font-bold text-brand-700">{column.rows.length}</span></div><div className="mt-2 space-y-3">{column.rows.length?column.rows.map(order=><article key={order.id} className="rounded-[22px] border border-white bg-white p-4 shadow-[0_5px_20px_rgba(35,42,60,.05)]"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-bold text-ink-900">#{order.number}</p><p className="mt-0.5 text-xs text-[#8f95a9]">{dateTime(order.created_at)}</p></div><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ${Date.now()-new Date(order.created_at).getTime()>20*60000?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'}`}><Clock3 className="h-3.5 w-3.5"/>{elapsed(order.created_at)}</span></div><div className="mt-3 flex items-center gap-2 rounded-xl bg-[#f8f9fb] px-3 py-2 text-xs font-semibold text-[#687087]">{order.delivery_type==='dine_in'?<UtensilsCrossed className="h-3.5 w-3.5"/>:order.delivery_type==='pickup'?<StoreIcon className="h-3.5 w-3.5"/>:<Truck className="h-3.5 w-3.5"/>}{fulfillment(order)}</div><div className="mt-4 space-y-3">{order.items.map((item,index)=>{const extras=extrasText(item.extras);return <div key={`${item.product_name}-${index}`} className="flex items-start gap-3"><span className="grid h-7 min-w-7 place-items-center rounded-lg bg-brand-50 px-1.5 text-xs font-bold text-brand-700">{Number(item.quantity)}×</span><div className="min-w-0"><p className="text-sm font-semibold leading-5">{item.product_name}</p>{item.variant_name&&<p className="text-xs text-[#858ba0]">{item.variant_name}</p>}{extras&&<p className="mt-0.5 text-xs leading-4 text-[#9aa0b3]">+ {extras}</p>}</div></div>})}</div>{order.notes&&<div className="mt-4 rounded-xl border border-amber-100 bg-amber-50 p-3 text-xs leading-5 text-amber-900"><strong>Nota:</strong> {order.notes}</div>}<button onClick={()=>void move(order)} className="btn-primary mt-4 w-full justify-center">{column.key==='new'?'Comenzar preparación':column.key==='preparing'?'Marcar listo':order.delivery_type==='delivery'?'Enviar a delivery':order.delivery_type==='pickup'?'Entregar al cliente':'Completar mesa'}</button></article>):<div className="rounded-[22px] border border-dashed border-[#dfe4e8] bg-white/60 p-8 text-center text-sm text-[#9aa0b3]">Sin pedidos</div>}</div></section>})}</div>
  </div>}
 </StoreShell>
}
