'use client'

import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime} from '@/lib/api'
import {Alert,Loading,Modal,PageEmpty,Switch} from '@/components/ui'
import type {Category,Product} from '@/lib/types'
import {BellRing,ChefHat,Clock3,RefreshCw,CheckCircle2,Truck,Store as StoreIcon,UtensilsCrossed,Settings2,Plus,Pencil,Trash2} from 'lucide-react'

type KDSItem={product_id?:string;product_name:string;variant_name:string;extras:any;quantity:number}
type KDSOrder={id:string;number:number;customer_name:string;customer_phone:string;status:string;delivery_type:string;notes:string;created_at:string;total:number;table_name:string;area_name:string;station_id?:string;items:KDSItem[]}
type Settings={dine_in_enabled?:boolean}
type Station={id:string;name:string;sort_order:number;is_active:boolean;category_ids:string[];product_ids:string[]}
const columns=[
 {key:'new',title:'Nuevos',detail:'Por comenzar',statuses:['pending','confirmed'],icon:BellRing},
 {key:'preparing',title:'Preparando',detail:'En cocina',statuses:['processing','preparing'],icon:ChefHat},
 {key:'ready',title:'Listos',detail:'Para entregar',statuses:['ready'],icon:CheckCircle2},
]
function elapsed(value:string){const min=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(min<60)return `${min} min`;return `${Math.floor(min/60)} h ${min%60} min`}
function extrasText(value:any){if(!value)return '';const rows=Array.isArray(value)?value:[];return rows.map((x:any)=>typeof x==='string'?x:x?.name||'').filter(Boolean).join(', ')}
function fulfillment(order:KDSOrder){if(order.delivery_type==='dine_in')return order.table_name?`${order.area_name?`${order.area_name} · `:''}${order.table_name}`:'Mesa';if(order.delivery_type==='pickup')return 'Recoger';return 'Delivery'}
const blankStation={name:'',sort_order:0,is_active:true,category_ids:[] as string[],product_ids:[] as string[]}

export default function KDS(){
 const[store,setStore]=useState(''),[rows,setRows]=useState<KDSOrder[]>([]),[settings,setSettings]=useState<Settings|null>(null),[stations,setStations]=useState<Station[]>([]),[categories,setCategories]=useState<Category[]>([]),[products,setProducts]=useState<Product[]>([]),[station,setStation]=useState(''),[loading,setLoading]=useState(false),[refreshing,setRefreshing]=useState(false),[err,setErr]=useState(''),[stationOpen,setStationOpen]=useState(false),[editStation,setEditStation]=useState<Station|null>(null),[stationForm,setStationForm]=useState<any>(blankStation),[busy,setBusy]=useState(false)
 const load=async(silent=false)=>{if(!store){setRows([]);setSettings(null);setStations([]);setProducts([]);return};silent?setRefreshing(true):setLoading(true);try{const qs=station?`&station_id=${station}`:'';const [orders,config,stationRows,cats,productRows]=await Promise.all([api<KDSOrder[]>(`/kds?store_id=${store}${qs}`),api<Settings>(`/stores/${store}/settings`),api<Station[]>(`/kds/stations?store_id=${store}`),api<Category[]>(`/categories?store_id=${store}`),api<Product[]>(`/products?store_id=${store}`)]);setRows(orders);setSettings(config);setStations(stationRows);setCategories(cats);setProducts(productRows);setErr('')}catch(e:any){setErr(e.message)}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load();if(!store)return;const timer=setInterval(()=>void load(true),15000);return()=>clearInterval(timer)},[store,station])
 const grouped=useMemo(()=>columns.map(column=>({...column,rows:rows.filter(row=>column.statuses.includes(row.status))})),[rows])
 const move=async(order:KDSOrder)=>{let status='preparing';if(order.status==='processing'||order.status==='preparing')status='ready';else if(order.status==='ready')status=order.delivery_type==='delivery'?'out_for_delivery':order.delivery_type==='pickup'?'picked_up':'delivered';try{await api(`/orders/${order.id}/status`,{method:'PATCH',body:JSON.stringify({status})});setRows(current=>status==='out_for_delivery'||status==='picked_up'||status==='delivered'?current.filter(x=>x.id!==order.id):current.map(x=>x.id===order.id?{...x,status}:x));setErr('')}catch(e:any){setErr(e.message)}}
 const startStation=(row?:Station)=>{setEditStation(row||null);setStationForm(row?{...row,category_ids:[...(row.category_ids||[])],product_ids:[...(row.product_ids||[])]}:{...blankStation,sort_order:(stations.length+1)*10,category_ids:[],product_ids:[]});setStationOpen(true)}
 const toggleCategory=(id:string)=>setStationForm((v:any)=>({...v,category_ids:(v.category_ids||[]).includes(id)?v.category_ids.filter((x:string)=>x!==id):[...(v.category_ids||[]),id]}))
 const toggleProduct=(id:string)=>setStationForm((v:any)=>({...v,product_ids:(v.product_ids||[]).includes(id)?v.product_ids.filter((x:string)=>x!==id):[...(v.product_ids||[]),id]}))
 const saveStation=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setErr('');try{const body={...stationForm,store_id:store,name:String(stationForm.name||'').trim(),sort_order:Number(stationForm.sort_order||0)};if(!body.name)throw new Error('Escribe el nombre de la estación.');if(editStation)await api(`/kds/stations/${editStation.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/kds/stations',{method:'POST',body:JSON.stringify(body)});setStationOpen(false);await load(true)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const removeStation=async(row:Station)=>{if(!confirm(`¿Eliminar la estación ${row.name}?`))return;setBusy(true);try{await api(`/kds/stations/${row.id}`,{method:'DELETE'});if(station===row.id)setStation('');await load(true)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 return <StoreShell title="KDS · Cocina" subtitle="Pedidos en vivo para preparación y entrega" context={<StoreSelector value={store} onChange={setStore}/>} actions={<><button disabled={!store} className="btn-secondary" onClick={()=>startStation()}><Settings2 className="h-4 w-4"/>Estaciones</button><button disabled={!store||refreshing} className="btn-secondary" onClick={()=>void load(true)}><RefreshCw className={`h-4 w-4 ${refreshing?'animate-spin':''}`}/>Actualizar</button></>}>
  {!store?<PageEmpty title="Selecciona un negocio" detail="Elige el negocio que mostrará la pantalla de cocina."/>:loading?<Loading/>:<div className="space-y-4">{err&&<Alert text={err}/>} {!settings?.dine_in_enabled&&<div className="rounded-2xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-800">El KDS está disponible como capacidad gastronómica. Activa Mesas y reservas en Configuración si este negocio trabajará con consumo en mesa.</div>}
   <div className="flex flex-col gap-3 rounded-2xl border border-[#edf0f5] bg-white px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="text-xs text-[#858ba0]">Actualización automática cada 15 segundos · {rows.length} pedidos activos</div><div className="flex items-center gap-2"><label className="text-xs font-semibold text-[#777e94]">Estación</label><select className="field min-w-[190px] py-2" value={station} onChange={e=>setStation(e.target.value)}><option value="">Todas las estaciones</option>{stations.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div></div>
   <div className="grid gap-4 xl:grid-cols-3">{grouped.map(column=>{const I=column.icon;return <section key={column.key} className="min-w-0 rounded-[26px] border border-[#e8ebf0] bg-[#f4f6f9] p-3"><div className="flex items-center gap-3 px-2 py-2"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white text-brand-600 shadow-sm"><I className="h-5 w-5"/></span><div className="min-w-0 flex-1"><h2 className="font-semibold text-ink-900">{column.title}</h2><p className="text-xs text-[#9298ab]">{column.detail}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-xs font-bold text-brand-700">{column.rows.length}</span></div><div className="mt-2 space-y-3">{column.rows.length?column.rows.map(order=><article key={order.id} className="rounded-[22px] border border-white bg-white p-4 shadow-[0_5px_20px_rgba(35,42,60,.05)]"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-bold text-ink-900">#{order.number}</p><p className="mt-0.5 text-xs text-[#8f95a9]">{dateTime(order.created_at)}</p></div><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ${Date.now()-new Date(order.created_at).getTime()>20*60000?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'}`}><Clock3 className="h-3.5 w-3.5"/>{elapsed(order.created_at)}</span></div><div className="mt-3 flex items-center gap-2 rounded-xl bg-[#f8f9fb] px-3 py-2 text-xs font-semibold text-[#687087]">{order.delivery_type==='dine_in'?<UtensilsCrossed className="h-3.5 w-3.5"/>:order.delivery_type==='pickup'?<StoreIcon className="h-3.5 w-3.5"/>:<Truck className="h-3.5 w-3.5"/>}{fulfillment(order)}</div><div className="mt-4 space-y-3">{order.items.map((item,index)=>{const extras=extrasText(item.extras);return <div key={`${item.product_name}-${index}`} className="flex items-start gap-3"><span className="grid h-7 min-w-7 place-items-center rounded-lg bg-brand-50 px-1.5 text-xs font-bold text-brand-700">{Number(item.quantity)}×</span><div className="min-w-0"><p className="text-sm font-semibold leading-5">{item.product_name}</p>{item.variant_name&&<p className="text-xs text-[#858ba0]">{item.variant_name}</p>}{extras&&<p className="mt-0.5 text-xs leading-4 text-[#9aa0b3]">+ {extras}</p>}</div></div>})}</div>{order.notes&&<div className="mt-4 rounded-xl border border-amber-100 bg-amber-50 p-3 text-xs leading-5 text-amber-900"><strong>Nota:</strong> {order.notes}</div>}<button onClick={()=>void move(order)} className="btn-primary mt-4 w-full justify-center">{column.key==='new'?'Comenzar preparación':column.key==='preparing'?'Marcar listo':order.delivery_type==='delivery'?'Enviar a delivery':order.delivery_type==='pickup'?'Entregar al cliente':'Completar mesa'}</button></article>):<div className="rounded-[22px] border border-dashed border-[#dfe4e8] bg-white/60 p-8 text-center text-sm text-[#9aa0b3]">Sin pedidos</div>}</div></section>})}</div>
  </div>}
  <Modal open={stationOpen} onClose={()=>setStationOpen(false)} title="Estaciones KDS" subtitle="Divide cocina, bar o preparación por categorías sin duplicar pedidos." wide>
   <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-3">{stations.length?stations.map(row=><article key={row.id} className="rounded-2xl border border-[#edf0f4] p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="font-semibold">{row.name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${row.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{row.is_active?'Activa':'Pausada'}</span></div><p className="mt-1 text-xs text-[#969caf]">{row.category_ids.length?row.category_ids.map(id=>categories.find(c=>c.id===id)?.name).filter(Boolean).join(' · '):'Sin categorías'}{row.product_ids?.length?` · ${row.product_ids.length} producto(s) específico(s)`:''}</p></div><button className="btn-secondary px-2.5" onClick={()=>startStation(row)}><Pencil className="h-4 w-4"/></button><button disabled={busy} className="btn-danger px-2.5" onClick={()=>void removeStation(row)}><Trash2 className="h-4 w-4"/></button></div></article>):<PageEmpty title="Sin estaciones" detail="Crea Cocina, Bar, Postres u otra estación y asígnale categorías."/>}</div>
    <form onSubmit={saveStation} className="rounded-2xl border border-[#edf0f4] bg-[#fbfcfd] p-4"><p className="section-kicker">{editStation?'Editar estación':'Nueva estación'}</p><div className="mt-3"><label className="label">Nombre *</label><input className="field" value={stationForm.name||''} onChange={e=>setStationForm({...stationForm,name:e.target.value})} placeholder="Ej.: Cocina caliente"/></div><div className="mt-4"><label className="label">Categorías que prepara</label><div className="mt-2 max-h-60 space-y-2 overflow-y-auto">{categories.map(cat=><label key={cat.id} className="flex items-center gap-3 rounded-xl border border-[#e8ebf0] bg-white p-3 text-sm"><input type="checkbox" checked={(stationForm.category_ids||[]).includes(cat.id)} onChange={()=>toggleCategory(cat.id)}/><span>{cat.name}</span></label>)}</div></div><div className="mt-4"><label className="label">Productos específicos</label><p className="mt-1 text-xs text-[#969caf]">Úsalo para excepciones que deban ir a esta estación aunque su categoría se prepare en otra.</p><div className="mt-2 max-h-52 space-y-2 overflow-y-auto">{products.map(product=><label key={product.id} className="flex items-center gap-3 rounded-xl border border-[#e8ebf0] bg-white p-3 text-sm"><input type="checkbox" checked={(stationForm.product_ids||[]).includes(product.id)} onChange={()=>toggleProduct(product.id)}/><span className="min-w-0 flex-1 truncate">{product.name}</span></label>)}</div></div><div className="mt-4"><Switch checked={stationForm.is_active!==false} onChange={v=>setStationForm({...stationForm,is_active:v})} label="Estación activa" detail="Las estaciones pausadas no aparecen como filtro operativo."/></div><button disabled={busy} className="btn-primary mt-5 w-full justify-center"><Plus className="h-4 w-4"/>{editStation?'Guardar estación':'Crear estación'}</button>{editStation&&<button type="button" className="btn-secondary mt-2 w-full justify-center" onClick={()=>startStation()}>Crear otra</button>}</form></div>
  </Modal>
 </StoreShell>
}
