'use client'
import {useEffect,useMemo,useState} from 'react'
import SuperAdminShell from '@/components/superadmin-shell'
import {api,dateTime} from '@/lib/api'
import {Loading,Modal,SearchBox,Status,Alert} from '@/components/ui'
import type {Plan} from '@/lib/types'
import {ShieldBan,ShieldCheck,Layers3,KeyRound,MessageCircleMore} from 'lucide-react'

export default function AdminUsers(){
 const[rows,setRows]=useState<any[]>([]),[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[planUser,setPlanUser]=useState<any>(null),[plan,setPlan]=useState(''),[pinUser,setPinUser]=useState<any>(null),[access,setAccess]=useState({phone:'',pin:''}),[err,setErr]=useState('')
 const load=()=>{setLoading(true);Promise.all([api<any[]>('/admin/users'),api<Plan[]>('/plans')]).then(([u,p])=>{setRows(u);setPlans(p)}).finally(()=>setLoading(false))}
 useEffect(load,[])
 const filtered=useMemo(()=>rows.filter(x=>(`${x.name} ${x.email||''} ${x.phone||''}`).toLowerCase().includes(search.toLowerCase())),[rows,search])
 const status=async(u:any)=>{const next=u.status==='active'?'blocked':'active';if(!confirm(`${next==='blocked'?'Bloquear':'Activar'} a ${u.name}?`))return;await api(`/admin/users/${u.id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});load()}
 const assign=async(e:React.FormEvent)=>{e.preventDefault();await api(`/admin/users/${planUser.id}/plan`,{method:'PUT',body:JSON.stringify({plan_id:plan})});setPlanUser(null);load()}
 const savePin=async(e:React.FormEvent)=>{e.preventDefault();setErr('');if(!access.phone.trim()){setErr('El WhatsApp es obligatorio.');return}if(access.pin&&!/^\d{4}$/.test(access.pin)){setErr('El PIN debe tener exactamente 4 dígitos.');return}try{await api(`/admin/users/${pinUser.id}/access`,{method:'PUT',body:JSON.stringify(access)});setPinUser(null);setAccess({phone:'',pin:''});load()}catch(e:any){setErr(e.message)}}
 return <SuperAdminShell title="Comerciantes" subtitle="Acceso WhatsApp + PIN, estado y plan asignado"><div className="mb-5"><SearchBox value={search} onChange={setSearch} placeholder="Buscar comerciante o WhatsApp..."/></div>{loading?<Loading/>:<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Comerciante</th><th>Acceso</th><th>Plan</th><th>Tiendas</th><th>Estado</th><th>Registro</th><th></th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><div className="font-semibold">{u.name}</div><div className="text-xs text-[#a2a6b8]">{u.email||'Sin correo'}</div></td><td><div className="flex items-center gap-2 font-medium text-slate-700"><MessageCircleMore className="h-4 w-4 text-brand-500"/>{u.phone?`+${u.phone}`:'Sin WhatsApp'}</div><div className={`mt-1 text-xs ${u.pin_configured?'text-brand-600':'font-semibold text-brand-600'}`}>{u.pin_configured?'PIN configurado':'PIN pendiente'}</div></td><td>{u.plan_name}</td><td>{u.stores}</td><td><Status value={u.status}/></td><td className="text-[#8d92aa]">{dateTime(u.created_at)}</td><td><div className="flex justify-end gap-2"><button title="Asignar / cambiar PIN" className="btn-secondary px-3" onClick={()=>{setErr('');setAccess({phone:u.phone||'',pin:''});setPinUser(u)}}><KeyRound className="h-4 w-4"/></button><button title="Cambiar plan" className="btn-secondary px-3" onClick={()=>{setPlanUser(u);setPlan(u.plan_id||plans[0]?.id||'')}}><Layers3 className="h-4 w-4"/></button><button title={u.status==='active'?'Bloquear':'Activar'} className={u.status==='active'?'btn-danger px-3':'btn-secondary px-3'} onClick={()=>status(u)}>{u.status==='active'?<ShieldBan className="h-4 w-4"/>:<ShieldCheck className="h-4 w-4"/>}</button></div></td></tr>)}</tbody></table></div>}
 <Modal open={!!planUser} onClose={()=>setPlanUser(null)} title={planUser?`Plan de ${planUser.name}`:'Asignar plan'}>{planUser&&<form onSubmit={assign}><label className="label">Plan</label><select required className="field" value={plan} onChange={e=>setPlan(e.target.value)}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setPlanUser(null)}>Cancelar</button><button className="btn-primary">Asignar plan</button></div></form>}</Modal>
 <Modal open={!!pinUser} onClose={()=>setPinUser(null)} title={pinUser?`PIN de ${pinUser.name}`:'Configurar PIN'}>{pinUser&&<form onSubmit={savePin}>{err&&<Alert text={err}/>}<div className="rounded-lg bg-brand-50 p-4 text-sm text-brand-800"><strong>Acceso de tienda:</strong> el comerciante entrará con su WhatsApp <strong>{pinUser.phone?`+${pinUser.phone}`:'sin configurar'}</strong> y este PIN.</div><div className="mt-4"><label className="label">WhatsApp de acceso</label><input autoFocus className="field" inputMode="tel" value={access.phone} onChange={e=>setAccess({...access,phone:e.target.value})} required/></div><div className="mt-4"><label className="label">Nuevo PIN de 4 dígitos <span className="font-normal text-[#a2a6b8]">(déjalo vacío para conservarlo)</span></label><input className="field h-14 text-center text-2xl font-semibold tracking-[.45em]" inputMode="numeric" type="password" maxLength={4} value={access.pin} onChange={e=>setAccess({...access,pin:e.target.value.replace(/\D/g,'').slice(0,4)})}/></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setPinUser(null)}>Cancelar</button><button className="btn-primary"><KeyRound className="h-4 w-4"/>Guardar PIN</button></div></form>}</Modal>
 </SuperAdminShell>
}
