'use client'
import {useEffect,useState} from 'react'
import SuperAdminShell from '@/components/superadmin-shell'
import {api,dateTime} from '@/lib/api'
import {Alert,Loading,Modal,Status} from '@/components/ui'
import {Plus,ShieldCheck,Trash2} from 'lucide-react'
const blank={name:'',email:'',password:'',role:'platform_admin',access:['dashboard','owners','plans','settings']}

const accessOptions=[['dashboard','Resumen'],['landing','Página comercial'],['owners','Propietarios'],['plans','Planes'],['customers','Clientes globales'],['users','Usuarios SaaS'],['settings','Configuración']]
export default function PlatformUsers(){
 const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[form,setForm]=useState<any>(blank),[err,setErr]=useState('')
 const load=()=>{setLoading(true);api<any[]>('/admin/platform-users').then(setRows).finally(()=>setLoading(false))};useEffect(load,[])
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');try{await api('/admin/platform-users',{method:'POST',body:JSON.stringify(form)});setOpen(false);setForm(blank);load()}catch(e:any){setErr(e.message)}}
 const toggle=async(x:any)=>{await api(`/admin/platform-users/${x.id}/status`,{method:'PATCH',body:JSON.stringify({status:x.status==='active'?'inactive':'active'})});load()}
 const remove=async(x:any)=>{if(!confirm(`¿Eliminar a ${x.name}?`))return;await api(`/admin/platform-users/${x.id}`,{method:'DELETE'});load()}
 const counts=(role:string)=>rows.filter(x=>x.role===role&&x.status==='active').length
 return <SuperAdminShell title="Usuarios SaaS" subtitle="Crea usuarios internos y controla las áreas centrales que pueden administrar" actions={<button className="btn-primary" onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Agregar usuario</button>}>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['Usuarios activos',rows.filter(x=>x.status==='active').length],['Superadmins',counts('superadmin')],['Administradores',counts('platform_admin')],['Operaciones',counts('operations')],['Soporte / Auditoría',counts('support')+counts('auditor')]].map(([l,v])=><div key={String(l)} className="card p-5"><div className="text-[10px] font-bold uppercase tracking-wide text-brand-600">{l}</div><div className="mt-2 text-2xl font-semibold">{v}</div></div>)}</div>
  <div className="mt-5">{loading?<Loading/>:<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Usuario</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Creado</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-brand-50 text-brand-700"><ShieldCheck className="h-4 w-4"/></span><span className="font-semibold">{x.name}</span></div></td><td>{x.email}</td><td>{x.role==='superadmin'?'Superadministrador':x.role==='platform_admin'?'Administrador':x.role==='operations'?'Operaciones':x.role==='support'?'Soporte':'Auditoría'}</td><td><button onClick={()=>x.role!=='superadmin'&&toggle(x)}><Status value={x.status}/></button></td><td className="text-[#8d92aa]">{dateTime(x.created_at)}</td><td className="text-right">{x.role!=='superadmin'&&<button className="btn-danger px-3" onClick={()=>remove(x)}><Trash2 className="h-4 w-4"/></button>}</td></tr>)}</tbody></table></div>}</div>
  <Modal open={open} onClose={()=>setOpen(false)} title="Nuevo usuario SaaS" subtitle="Este usuario accede únicamente a la administración central."><form onSubmit={save}>{err&&<Alert text={err}/>}<div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Nombre *</label><input className="field" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="label">Correo *</label><input type="email" className="field" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="label">Contraseña *</label><input type="password" minLength={8} className="field" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><div><label className="label">Rol</label><select className="field" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="platform_admin">Administrador</option><option value="operations">Operaciones</option><option value="support">Soporte</option><option value="auditor">Auditoría</option></select></div><div className="sm:col-span-2"><label className="label">Áreas permitidas</label><div className="grid gap-2 sm:grid-cols-2">{accessOptions.map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-xl bg-[#fafbfe] px-3 py-2 text-sm"><input type="checkbox" checked={form.access.includes(key)} onChange={e=>setForm({...form,access:e.target.checked?[...form.access,key]:form.access.filter((x:string)=>x!==key)})}/>{label}</label>)}</div></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary">Crear usuario</button></div></form></Modal>
 </SuperAdminShell>
}
