'use client'

import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime,money} from '@/lib/api'
import {Alert,Loading,Modal,PageEmpty} from '@/components/ui'
import type {Category,Product,Promotion} from '@/lib/types'
import {CalendarClock,FolderTree,Pencil,Plus,Tag,Trash2,Boxes} from 'lucide-react'

const blank={name:'',discount_type:'percentage',discount_value:10,scope:'all',min_order:0,usage_limit:null as number|null,starts_at:'',ends_at:'',is_active:true,product_ids:[] as string[],category_ids:[] as string[]}

function toLocalInput(value?:string|null){
 if(!value)return ''
 const d=new Date(value);if(Number.isNaN(d.getTime()))return ''
 const pad=(n:number)=>String(n).padStart(2,'0')
 return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`
}
function toISO(value?:string|null){return value?new Date(value).toISOString():null}
function temporalState(row:Promotion){
 if(!row.is_active)return {label:'Inactiva',className:'bg-slate-100 text-slate-600'}
 const now=Date.now(),start=row.starts_at?new Date(row.starts_at).getTime():0,end=row.ends_at?new Date(row.ends_at).getTime():0
 if(start&&start>now)return {label:'Programada',className:'bg-cyan-50 text-cyan-700'}
 if(end&&end<now)return {label:'Finalizada',className:'bg-slate-100 text-slate-600'}
 if(row.usage_limit&&row.used_count>=row.usage_limit)return {label:'Agotada',className:'bg-amber-50 text-amber-700'}
 return {label:'Activa',className:'bg-emerald-50 text-emerald-700'}
}
function scopeLabel(row:Promotion){
 if(row.scope==='products')return `${row.product_ids?.length||0} productos`
 if(row.scope==='categories')return `${row.category_ids?.length||0} categorías`
 return 'Todo el catálogo'
}

export default function Promotions(){
 const[store,setStore]=useState(''),[rows,setRows]=useState<Promotion[]>([]),[products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[edit,setEdit]=useState<Promotion|null>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 const load=()=>{if(!store){setRows([]);setProducts([]);setCategories([]);return};setLoading(true);setErr('');Promise.all([api<Promotion[]>(`/promotions?store_id=${store}`),api<Product[]>(`/products?store_id=${store}`),api<Category[]>(`/categories?store_id=${store}`)]).then(([a,b,c])=>{setRows(a);setProducts(b.filter(x=>x.is_active!==false));setCategories(c.filter(x=>x.is_active!==false))}).catch((e:any)=>setErr(e.message)).finally(()=>setLoading(false))}
 useEffect(load,[store])
 const start=(row?:Promotion)=>{setEdit(row||null);setForm(row?{...row,starts_at:toLocalInput(row.starts_at),ends_at:toLocalInput(row.ends_at),product_ids:[...(row.product_ids||[])],category_ids:[...(row.category_ids||[])]}:{...blank,product_ids:[],category_ids:[]});setErr('');setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');setBusy(true);try{const body={...form,store_id:store,name:String(form.name||'').trim(),starts_at:toISO(form.starts_at),ends_at:toISO(form.ends_at),product_ids:form.scope==='products'?form.product_ids:[],category_ids:form.scope==='categories'?form.category_ids:[]};if(!body.name)throw new Error('Escribe un nombre para la promoción.');if(body.starts_at&&body.ends_at&&new Date(body.ends_at)<=new Date(body.starts_at))throw new Error('La fecha de fin debe ser posterior al inicio.');if(body.scope==='products'&&!body.product_ids.length)throw new Error('Selecciona al menos un producto.');if(body.scope==='categories'&&!body.category_ids.length)throw new Error('Selecciona al menos una categoría.');if(edit)await api(`/promotions/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/promotions',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const del=async(row:Promotion)=>{if(!confirm(`¿Eliminar la promoción ${row.name}?`))return;setBusy(true);try{await api(`/promotions/${row.id}`,{method:'DELETE'});load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const toggleTarget=(key:'product_ids'|'category_ids',id:string)=>setForm((current:any)=>({...current,[key]:(current[key]||[]).includes(id)?current[key].filter((x:string)=>x!==id):[...(current[key]||[]),id]}))
 const selectedProducts=useMemo(()=>new Set<string>(form.product_ids||[]),[form.product_ids])
 const selectedCategories=useMemo(()=>new Set<string>(form.category_ids||[]),[form.category_ids])
 return <StoreShell title="Promociones" subtitle="Descuentos automáticos por fecha, producto o categoría" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store} className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Nueva promoción</button>}>
  {!store?<PageEmpty title="Selecciona una tienda" detail="Elige una tienda para administrar sus promociones automáticas."/>:loading?<Loading/>:<div className="space-y-4">{err&&<Alert text={err}/>} {rows.length===0?<PageEmpty title="No hay promociones" detail="Crea una promoción para aplicar descuentos automáticamente sin pedirle un código al cliente." action={<button className="btn-primary" onClick={()=>start()}><Plus className="h-4 w-4"/>Crear promoción</button>}/>:<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr><th>Promoción</th><th>Alcance</th><th>Descuento</th><th>Vigencia</th><th>Usos</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map(row=>{const state=temporalState(row);return <tr key={row.id}><td><div className="flex min-w-[180px] items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-600"><Tag className="h-4 w-4"/></span><div><div className="font-semibold text-ink-900">{row.name}</div>{row.min_order>0&&<div className="mt-0.5 text-[11px] text-[#969caf]">Mínimo {money(row.min_order)}</div>}</div></div></td><td>{scopeLabel(row)}</td><td className="font-semibold">{row.discount_type==='percentage'?`${row.discount_value}%`:money(row.discount_value)}</td><td><div className="min-w-[180px] text-xs text-[#737a91]"><div className="flex items-center gap-1.5"><CalendarClock className="h-3.5 w-3.5 text-brand-600"/>{row.starts_at?dateTime(row.starts_at):'Inicio inmediato'}</div><div className="mt-1 pl-5">{row.ends_at?`Hasta ${dateTime(row.ends_at)}`:'Sin vencimiento'}</div></div></td><td>{row.used_count}{row.usage_limit?` / ${row.usage_limit}`:''}</td><td><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${state.className}`}>{state.label}</span></td><td><div className="flex justify-end gap-2"><button className="btn-secondary px-3" onClick={()=>start(row)}><Pencil className="h-4 w-4"/></button><button className="btn-danger px-3" disabled={busy} onClick={()=>void del(row)}><Trash2 className="h-4 w-4"/></button></div></td></tr>})}</tbody></table></div>}</div>}

  <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar promoción':'Nueva promoción'} subtitle="El descuento se aplicará automáticamente cuando sea la mejor promoción disponible." wide>
   <form onSubmit={save}>{err&&<Alert text={err}/>}<div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]">
    <div className="space-y-5">
     <section className="rounded-[26px] border border-[#edf0f4] bg-white p-5"><div className="mb-4"><p className="section-kicker">Información</p><h3 className="mt-1 font-semibold">Regla de descuento</h3></div><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label">Nombre *</label><input className="field" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ej.: Especial de fin de semana"/></div><div><label className="label">Tipo</label><select className="field" value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})}><option value="percentage">Porcentaje</option><option value="flat">Monto fijo</option></select></div><div><label className="label">Valor</label><input className="field" type="number" min="0.01" max={form.discount_type==='percentage'?100:undefined} step="0.01" value={form.discount_value} onChange={e=>setForm({...form,discount_value:Number(e.target.value)})}/></div><div><label className="label">Compra mínima</label><input className="field" type="number" min="0" step="0.01" value={form.min_order} onChange={e=>setForm({...form,min_order:Number(e.target.value)})}/></div><div><label className="label">Límite de usos</label><input className="field" type="number" min="1" value={form.usage_limit??''} onChange={e=>setForm({...form,usage_limit:e.target.value===''?null:Number(e.target.value)})} placeholder="Sin límite"/></div></div></section>
     <section className="rounded-[26px] border border-[#edf0f4] bg-white p-5"><div className="mb-4"><p className="section-kicker">Alcance</p><h3 className="mt-1 font-semibold">¿Qué debe recibir el descuento?</h3></div><div className="grid gap-2 sm:grid-cols-3">{([{value:'all',label:'Todo el catálogo',icon:Tag},{value:'products',label:'Productos',icon:Boxes},{value:'categories',label:'Categorías',icon:FolderTree}] as any[]).map(option=>{const I=option.icon,active=form.scope===option.value;return <button type="button" key={option.value} onClick={()=>setForm({...form,scope:option.value})} className={`rounded-2xl border p-4 text-left transition ${active?'border-brand-300 bg-brand-50':'border-[#e7ebe9] bg-[#fbfcfc] hover:border-brand-200'}`}><I className={`h-5 w-5 ${active?'text-brand-600':'text-[#9aa0b4]'}`}/><div className="mt-3 text-sm font-semibold">{option.label}</div></button>})}</div>
      {form.scope==='products'&&<div className="mt-4 max-h-72 space-y-2 overflow-y-auto rounded-2xl border border-[#edf0f5] bg-[#fbfcfc] p-3">{products.length?products.map(p=><label key={p.id} className="flex cursor-pointer items-center gap-3 rounded-xl bg-white px-3 py-2.5 text-sm"><input type="checkbox" checked={selectedProducts.has(p.id)} onChange={()=>toggleTarget('product_ids',p.id)}/><span className="min-w-0 flex-1 truncate font-medium">{p.name}</span><span className="text-xs text-[#949aad]">{money(p.price)}</span></label>):<p className="p-3 text-sm text-[#8d92aa]">No hay productos activos.</p>}</div>}
      {form.scope==='categories'&&<div className="mt-4 max-h-72 space-y-2 overflow-y-auto rounded-2xl border border-[#edf0f5] bg-[#fbfcfc] p-3">{categories.length?categories.map(c=><label key={c.id} className="flex cursor-pointer items-center gap-3 rounded-xl bg-white px-3 py-2.5 text-sm"><input type="checkbox" checked={selectedCategories.has(c.id)} onChange={()=>toggleTarget('category_ids',c.id)}/><span className="font-medium">{c.name}</span></label>):<p className="p-3 text-sm text-[#8d92aa]">No hay categorías activas.</p>}</div>}
     </section>
    </div>
    <aside className="space-y-5"><section className="rounded-[26px] border border-[#edf0f4] bg-[#fbfcfd] p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-brand-600"><CalendarClock className="h-5 w-5"/></span><div><p className="section-kicker">Programación</p><h3 className="font-semibold">Vigencia</h3></div></div><div className="mt-5 space-y-4"><div><label className="label">Inicio</label><input className="field" type="datetime-local" value={form.starts_at||''} onChange={e=>setForm({...form,starts_at:e.target.value})}/><p className="mt-1 text-[11px] text-[#9aa0b2]">Vacío = comienza inmediatamente.</p></div><div><label className="label">Fin</label><input className="field" type="datetime-local" value={form.ends_at||''} onChange={e=>setForm({...form,ends_at:e.target.value})}/><p className="mt-1 text-[11px] text-[#9aa0b2]">Vacío = no vence.</p></div>{edit&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Promoción activa</label>}</div></section><section className="rounded-[26px] border border-brand-100 bg-brand-50/50 p-5"><p className="text-sm font-semibold text-brand-800">Regla de compatibilidad</p><p className="mt-2 text-xs leading-5 text-brand-800/80">Si el cliente también usa un cupón, WAMERCIO compara ambos descuentos y aplica solo el que más le conviene. No se acumulan.</p></section></aside>
   </div><div className="mt-6 flex justify-end gap-2 border-t border-slate-100 pt-5"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button disabled={busy} className="btn-primary">{busy?'Guardando...':'Guardar promoción'}</button></div></form>
  </Modal>
 </StoreShell>
}
