'use client'
import {useEffect,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,money} from '@/lib/api'
import {Alert,Loading,Modal,PageEmpty,Status,Switch} from '@/components/ui'
import type {Shipping} from '@/lib/types'
import {Plus,Pencil,Trash2,Truck,MapPin} from 'lucide-react'

const blank={name:'',charge:0,estimated_minutes:30,is_active:true}
export default function Delivery(){
 const[store,setStore]=useState(''),[rows,setRows]=useState<Shipping[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[edit,setEdit]=useState<Shipping|null>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState('')
 const load=()=>{if(!store){setRows([]);return};setLoading(true);api<Shipping[]>(`/shipping?store_id=${store}`).then(setRows).finally(()=>setLoading(false))}
 useEffect(load,[store])
 const start=(x?:Shipping)=>{setEdit(x||null);setForm(x?{...x}:blank);setErr('');setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');try{const body={...form,store_id:store,estimated_minutes:Number(form.estimated_minutes||30)};if(edit)await api(`/shipping/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/shipping',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e:any){setErr(e.message)}}
 const del=async(x:Shipping)=>{if(!confirm(`¿Eliminar zona ${x.name}?`))return;await api(`/shipping/${x.id}`,{method:'DELETE'});load()}
 return <StoreShell title="Delivery" subtitle="Define dónde entregas y cuánto cuesta" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store} onClick={()=>start()} className="btn-primary"><Plus className="h-4 w-4"/> Nueva zona</button>}>
  
  {!store?<PageEmpty title="Selecciona una tienda" detail="Elige la tienda para configurar sus zonas de entrega."/>:loading?<Loading/>:rows.length===0?<PageEmpty title="Aún no tienes zonas de delivery" detail="Crea una zona con su nombre y cargo. WAMERCIO se ocupa del resto." action={<button className="btn-primary" onClick={()=>start()}>Crear zona</button>}/>:<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rows.map(x=><article className="card p-5" key={x.id}><div className="flex items-start gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Truck className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate font-semibold text-ink-900">{x.name}</h3><Status value={x.is_active?'active':'inactive'}/></div><p className="mt-1 text-sm text-[#8d92aa]">Cargo de entrega <strong className="text-ink-900">{money(x.charge)}</strong></p></div></div><div className="mt-5 flex gap-2"><button className="btn-secondary flex-1" onClick={()=>start(x)}><Pencil className="h-4 w-4"/> Editar</button><button className="icon-action hover:border-rose-200 hover:bg-rose-50 hover:text-rose-600" onClick={()=>del(x)}><Trash2 className="h-4 w-4"/></button></div></article>)}</div>}

  <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar zona':'Nueva zona de delivery'} subtitle="Solo necesitas indicar el área y el costo."><form onSubmit={save}>{err&&<Alert text={err}/>}<div className="mb-5 flex items-center gap-3 rounded-2xl bg-brand-50 p-4 text-brand-700"><span className="grid h-10 w-10 place-items-center rounded-full bg-white"><MapPin className="h-5 w-5"/></span><div><div className="text-sm font-semibold">Zona de entrega</div><div className="text-xs text-brand-700/70">Ej.: Centro de Bonao, Los Quemados, Maimón</div></div></div><div className="space-y-4"><div><label className="label">Nombre de la zona *</label><input autoFocus className="field" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ej.: Centro de Bonao"/></div><div><label className="label">Cargo de entrega</label><div className="relative"><span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-sm font-semibold text-[#9298ad]">RD$</span><input className="field pl-12" type="number" min="0" step="0.01" value={form.charge} onChange={e=>setForm({...form,charge:Number(e.target.value)})}/></div></div>{edit&&<Switch checked={!!form.is_active} onChange={v=>setForm({...form,is_active:v})} label="Zona disponible" detail="Desactívala temporalmente sin eliminarla."/>}</div><div className="mt-7 flex flex-col-reverse gap-2 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary">{edit?'Guardar cambios':'Crear zona'}</button></div></form></Modal>
 </StoreShell>
}
