package main

import (
	"context"
	"crypto/sha256"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

const outputName = "wamercio-custom-domains.yml"

func normalizeHost(value string) string {
	return strings.ToLower(strings.TrimSuffix(strings.TrimSpace(value), "."))
}

func routerID(host string) string {
	sum := sha256.Sum256([]byte(host))
	return fmt.Sprintf("custom-%x", sum[:6])
}

func render(hosts []string) string {
	sort.Strings(hosts)
	var b strings.Builder
	b.WriteString("# Generated by WAMERCIO domain-router. Do not edit.\nhttp:\n  routers:\n")
	if len(hosts) == 0 {
		b.WriteString("    {}\n")
	}
	for _, host := range hosts {
		id := routerID(host)
		fmt.Fprintf(&b, "    wamercio-%s-http:\n      rule: \"Host(`%s`)\"\n      entryPoints: [web]\n      service: wamercio-custom-domain-service\n      priority: 900\n", id, host)
		fmt.Fprintf(&b, "    wamercio-%s-https:\n      rule: \"Host(`%s`)\"\n      entryPoints: [websecure]\n      service: wamercio-custom-domain-service\n      priority: 900\n      tls:\n        certResolver: letsencrypt\n", id, host)
	}
	b.WriteString("  services:\n    wamercio-custom-domain-service:\n      loadBalancer:\n        passHostHeader: true\n        servers:\n          - url: \"http://wamercio-gateway:8080\"\n")
	return b.String()
}

func loadHosts(ctx context.Context, db *pgxpool.Pool) ([]string, error) {
	rows, err := db.Query(ctx, `SELECT hostname FROM store_domains WHERE status='active' ORDER BY hostname`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	hosts := []string{}
	for rows.Next() {
		var raw string
		if rows.Scan(&raw) == nil {
			host := normalizeHost(raw)
			if host != "" {
				hosts = append(hosts, host)
			}
		}
	}
	return hosts, rows.Err()
}

func sync(ctx context.Context, db *pgxpool.Pool, target string) error {
	hosts, err := loadHosts(ctx, db)
	if err != nil {
		return err
	}
	data := render(hosts)
	path := filepath.Join(target, outputName)
	tmp := path + ".tmp"
	current, _ := os.ReadFile(path)
	if string(current) == data {
		return nil
	}
	if err = os.WriteFile(tmp, []byte(data), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func main() {
	dsn := strings.TrimSpace(os.Getenv("DATABASE_URL"))
	target := strings.TrimSpace(os.Getenv("TRAEFIK_DYNAMIC_DIR"))
	if target == "" {
		target = "/target"
	}
	if dsn == "" {
		log.Fatal("DATABASE_URL is required")
	}
	db, err := pgxpool.New(context.Background(), dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	run := func() {
		if err := sync(context.Background(), db, target); err != nil {
			log.Printf("domain sync: %v", err)
		}
	}
	run()
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()
	for range ticker.C {
		run()
	}
}
