package main

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"
)

func normalizeHost(value string) string {
	return strings.ToLower(strings.TrimSuffix(strings.TrimSpace(value), "."))
}

func routerID(host string) string {
	sum := sha256.Sum256([]byte(host))
	return fmt.Sprintf("store-%x", sum[:6])
}

func render(hosts []string) string {
	sort.Strings(hosts)
	var b strings.Builder
	b.WriteString("# Generated by WAMERCIO domain-router. Do not edit.\nhttp:\n  routers:\n")
	if len(hosts) == 0 {
		b.WriteString("    {}\n")
	}
	for _, host := range hosts {
		id := routerID(host)
		fmt.Fprintf(&b, "    wamercio-%s-http:\n      rule: \"Host(`%s`)\"\n      entryPoints: [web]\n      service: wamercio-store-host-service\n      priority: 900\n", id, host)
		fmt.Fprintf(&b, "    wamercio-%s-https:\n      rule: \"Host(`%s`)\"\n      entryPoints: [websecure]\n      service: wamercio-store-host-service\n      priority: 900\n      tls:\n        certResolver: letsencrypt\n", id, host)
	}
	b.WriteString("  services:\n    wamercio-store-host-service:\n      loadBalancer:\n        passHostHeader: true\n        healthCheck:\n          path: /gateway-health\n          interval: 10s\n          timeout: 3s\n        servers:\n          - url: \"http://wamercio-gateway:8080\"\n")
	return b.String()
}
