'use client'

import {useEffect,useState} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {api} from '@/lib/api'
import {Home,LogOut,Package,UserRound} from 'lucide-react'

export default function CustomerShell({active,children}:{active:'orders'|'profile';children:React.ReactNode}){
  const router=useRouter(),[customer,setCustomer]=useState<any>(null),[store,setStore]=useState<any>(null),[loading,setLoading]=useState(true)
  useEffect(()=>{Promise.all([api('/customer/me'),api('/public/store').catch(()=>null)]).then(([c,s]:any[])=>{setCustomer(c);setStore(s?.store||null)}).catch(()=>router.replace('/')).finally(()=>setLoading(false))},[router])
  const logout=async()=>{try{await api('/auth/customer/logout',{method:'POST'})}catch{}router.push('/');router.refresh()}
  if(loading)return <div className="grid min-h-screen place-items-center bg-[#f7f9fc] text-sm text-slate-400">Cargando tu cuenta...</div>
  if(!customer)return null
  const brand=store?.name||'WAMERCIO'
  return <div className="min-h-screen bg-[#f7f9fc] pb-[calc(74px+env(safe-area-inset-bottom))] text-[#222b45] md:pb-0">
    <header className="border-b border-slate-100 bg-white"><div className="mx-auto flex max-w-6xl items-center gap-3 px-4 py-4 sm:px-6"><Link href="/" className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-2xl bg-emerald-500 font-bold text-white">{store?.logo_url?<img src={store.logo_url} className="h-full w-full object-cover"/>:'W'}</span><span className="min-w-0"><strong className="block truncate leading-none">{brand}</strong><small className="mt-1 block text-[10px] font-semibold uppercase tracking-[.16em] text-emerald-600">Mi cuenta</small></span></Link><nav className="ml-auto hidden items-center gap-2 md:flex"><Link href="/cliente/pedidos" className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold ${active==='orders'?'bg-emerald-50 text-emerald-700':'text-slate-500 hover:bg-slate-50'}`}><Package className="h-4 w-4"/>Mis pedidos</Link><Link href="/cliente/perfil" className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold ${active==='profile'?'bg-emerald-50 text-emerald-700':'text-slate-500 hover:bg-slate-50'}`}><UserRound className="h-4 w-4"/>Mi perfil</Link><button onClick={logout} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-500"><LogOut className="h-4 w-4"/>Cerrar sesión</button></nav></div></header>
    <main className="mx-auto max-w-6xl px-3 py-4 sm:px-6 sm:py-8"><div className="mb-4 flex items-center gap-3 rounded-2xl border border-slate-100 bg-white p-4 shadow-sm sm:mb-6"><div className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-full bg-emerald-50 font-bold text-emerald-700">{customer.profile_picture_url?<img src={customer.profile_picture_url} alt={customer.whatsapp_name||customer.name||'Perfil de WhatsApp'} className="h-full w-full object-cover"/>:String(customer.name||'C').slice(0,1).toUpperCase()}</div><div className="min-w-0"><div className="truncate font-semibold">{customer.name} {customer.last_name}</div><div className="text-xs text-slate-400">WhatsApp +{customer.phone}</div></div></div>{children}</main>
    <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-slate-100 bg-white/95 pb-[env(safe-area-inset-bottom)] shadow-[0_-8px_30px_rgba(15,23,42,.06)] backdrop-blur md:hidden"><div className="mx-auto grid h-[62px] max-w-lg grid-cols-4"><Link href="/" className="flex flex-col items-center justify-center gap-1 text-[10px] font-semibold text-slate-500"><Home className="h-5 w-5"/><span>Inicio</span></Link><Link href="/cliente/pedidos" className={`flex flex-col items-center justify-center gap-1 text-[10px] font-semibold ${active==='orders'?'text-emerald-600':'text-slate-500'}`}><Package className="h-5 w-5"/><span>Pedidos</span></Link><Link href="/cliente/perfil" className={`flex flex-col items-center justify-center gap-1 text-[10px] font-semibold ${active==='profile'?'text-emerald-600':'text-slate-500'}`}><UserRound className="h-5 w-5"/><span>Perfil</span></Link><button onClick={logout} className="flex flex-col items-center justify-center gap-1 text-[10px] font-semibold text-slate-500"><LogOut className="h-5 w-5"/><span>Salir</span></button></div></nav>
  </div>
}
