"use client";

import {useState} from "react";
import {BadgeCheck,Loader2,ShieldCheck} from "lucide-react";
import {GeoAddressPicker,blankGeoAddress,GeoAddressValue} from "@/components/geo-address-picker";

const digits=(v:string)=>(v||"").replace(/\D/g,"");
const cedulaFormat=(v:string)=>{const d=digits(v).slice(0,11);return d.length<=3?d:d.length<=10?`${d.slice(0,3)}-${d.slice(3)}`:`${d.slice(0,3)}-${d.slice(3,10)}-${d.slice(10)}`};
const displayDate=(v:string)=>{if(!v)return "";const[y,m,d]=v.split("-");return y&&m&&d?`${d}/${m}/${y}`:v};
const displaySex=(v:string)=>v==="M"?"Masculino":v==="F"?"Femenino":v||"";

export function CustomerRegistration({tenant}:{tenant:any}){
 const[form,setForm]=useState<any>({cedula:"",name:"",birth_date:"",sex:"",whatsapp:"",email:""});
 const[location,setLocation]=useState<GeoAddressValue>({...blankGeoAddress});
 const[identity,setIdentity]=useState<any>(null);const[verifying,setVerifying]=useState(false);const[saving,setSaving]=useState(false);const[err,setErr]=useState("");const[done,setDone]=useState<any>(null);
 async function verify(){setVerifying(true);setErr("");try{const r=await fetch("/api/backend/api/v1/public/identity/customer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cedula:form.cedula})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible verificar la cédula");setIdentity(d.identity);setForm((f:any)=>({...f,name:d.identity.nombre_completo,birth_date:d.identity.fecha_nacimiento,sex:d.identity.sexo}))}catch(e:any){setIdentity(null);setErr(e.message)}finally{setVerifying(false)}}
 async function save(e:React.FormEvent){e.preventDefault();if(!identity){setErr("Verifica primero tu cédula.");return}if(!location.geo_province_code||!location.geo_city_id){setErr("Selecciona provincia y ciudad.");return}setSaving(true);setErr("");try{const payload={cedula:digits(form.cedula),whatsapp:form.whatsapp,email:form.email,province:location.province,municipality:location.municipality,sector:location.sector,address:location.address,reference:location.reference||"",geo_province_code:location.geo_province_code,geo_city_id:location.geo_city_id,geo_neighborhood_id:location.geo_neighborhood_id,geo_id:location.geo_id,geo_address_label:location.geo_address_label,geo_address_source:location.geo_address_source,latitude:location.latitude,longitude:location.longitude};const r=await fetch(`/api/backend/api/v1/public/tenants/${tenant.Slug}/customers`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible completar el registro");setDone(d.customer)}catch(e:any){setErr(e.message)}finally{setSaving(false)}}
 if(done)return <div className="rounded-3xl bg-white p-8 text-center shadow-soft"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-green-50 text-green-600"><BadgeCheck size={34}/></div><h2 className="mt-4 text-2xl font-black">Registro completado</h2><p className="mt-2 text-gray-500">{done.Name}, ya estás registrado como cliente de <b>{tenant.Name}</b>.</p><a href="/" className="btn btn-brand mt-6">Volver al catálogo</a></div>;
 return <form onSubmit={save} className="rounded-3xl bg-white p-6 shadow-soft"><div className="flex items-start gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-orange-50 text-[#ff5400]"><ShieldCheck/></div><div><h2 className="text-xl font-black">Registro de cliente</h2><p className="text-sm text-gray-500">Identidad verificada y dirección validada con GEO RD MAP.</p></div></div><div className="mt-6 flex gap-2"><input className="field" placeholder="Cédula 001-0000000-0" value={form.cedula} onChange={e=>{setIdentity(null);setForm({...form,cedula:cedulaFormat(e.target.value),name:"",birth_date:"",sex:""})}}/><button type="button" disabled={verifying||digits(form.cedula).length!==11} onClick={verify} className="btn btn-dark min-w-28">{verifying?<Loader2 className="animate-spin" size={18}/>:"Verificar"}</button></div>{identity&&<div className="mt-3 flex items-center gap-2 rounded-xl bg-green-50 p-3 text-sm font-bold text-green-700"><BadgeCheck size={18}/> Identidad verificada</div>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><input className="field bg-gray-50 sm:col-span-2" readOnly value={form.name} placeholder="Nombre completo"/><input className="field bg-gray-50" readOnly value={displayDate(form.birth_date)} placeholder="Fecha de nacimiento"/><input className="field bg-gray-50" readOnly value={displaySex(form.sex)} placeholder="Sexo"/><input className="field" required placeholder="WhatsApp 809, 829 o 849" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/><input className="field" type="email" placeholder="Correo (opcional)" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="mt-5"><GeoAddressPicker value={location} onChange={setLocation}/></div>{err&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{err}</p>}<button disabled={saving||!identity} className="btn btn-brand mt-5 w-full">{saving?"Registrando...":"Registrarme como cliente"}</button></form>
}
