"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {LocateFixed,MapPin,Search,Loader2,CheckCircle2,Navigation,PlusCircle} from "lucide-react";

export type GeoAddressValue={
 geo_province_code:string;geo_city_id:string;geo_neighborhood_id:string;geo_id:string;geo_address_label:string;geo_address_source:string;
 latitude:number;longitude:number;province:string;municipality:string;sector:string;address:string;reference?:string;
};

type Props={value:GeoAddressValue;onChange:(v:GeoAddressValue)=>void;tenantSlug?:string;showQuote?:boolean;compact?:boolean;requiredCoordinates?:boolean};
const emptyData={provinces:[],cities:[],neighborhoods:[]};
async function getJSON(url:string,init?:RequestInit){const r=await fetch(url,init);const d=await r.json();if(!r.ok)throw new Error(d.error||d.message||"No fue posible consultar GEO RD MAP");return d}

export function GeoAddressPicker({value,onChange,tenantSlug,showQuote=false,compact=false,requiredCoordinates=false}:Props){
 const[selectors,setSelectors]=useState<any>(emptyData);const[loading,setLoading]=useState(false);const[locating,setLocating]=useState(false);const[query,setQuery]=useState(value.geo_address_label||"");const[results,setResults]=useState<any[]>([]);const[searching,setSearching]=useState(false);const[error,setError]=useState("");const[quote,setQuote]=useState<any>(null);const[suggesting,setSuggesting]=useState(false);const[suggestionName,setSuggestionName]=useState("");const[suggestionMessage,setSuggestionMessage]=useState("");const timer=useRef<any>(null);
 const province=useMemo(()=>selectors.provinces?.find((x:any)=>x.code===value.geo_province_code),[selectors.provinces,value.geo_province_code]);
 const city=useMemo(()=>selectors.cities?.find((x:any)=>x.cityId===value.geo_city_id),[selectors.cities,value.geo_city_id]);
 const neighborhood=useMemo(()=>selectors.neighborhoods?.find((x:any)=>x.id===value.geo_neighborhood_id),[selectors.neighborhoods,value.geo_neighborhood_id]);

 async function loadSelectors(provinceCode=value.geo_province_code,cityId=value.geo_city_id){setLoading(true);setError("");try{const p=new URLSearchParams();if(provinceCode)p.set("provinceCode",provinceCode);if(cityId)p.set("cityId",cityId);p.set("includeCustom","true");const d=await getJSON(`/api/backend/api/v1/public/geo/selectors?${p}`);setSelectors(d.data||emptyData)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{loadSelectors(value.geo_province_code,value.geo_city_id)},[]);// eslint-disable-line react-hooks/exhaustive-deps

 useEffect(()=>{if(timer.current)clearTimeout(timer.current);const q=query.trim();if(q.length<3||q===value.geo_address_label){setResults([]);return}timer.current=setTimeout(async()=>{setSearching(true);try{const p=new URLSearchParams({q});if(value.latitude)p.set("lat",String(value.latitude));if(value.longitude)p.set("lng",String(value.longitude));const d=await getJSON(`/api/backend/api/v1/public/geo/autocomplete?${p}`);setResults(d.data?.results||[])}catch{setResults([])}finally{setSearching(false)}},350);return()=>{if(timer.current)clearTimeout(timer.current)}},[query,value.latitude,value.longitude,value.geo_address_label]);

 async function chooseResult(x:any){setResults([]);setQuery(x.label||x.name||"");try{if(x.selectionToken)await getJSON("/api/backend/api/v1/public/geo/selections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query,result:x})});const next={...value,geo_province_code:x.provinceCode||value.geo_province_code,geo_city_id:x.cityId||value.geo_city_id,geo_id:x.geoId||x.id||"",geo_address_label:x.label||x.name||"",geo_address_source:x.source||"",latitude:Number(x.lat)||0,longitude:Number(x.lng)||0,province:x.province||value.province,municipality:x.cityName||x.municipality||value.municipality,sector:x.neighborhood||value.sector,address:x.street||x.label||value.address};onChange(next);await loadSelectors(next.geo_province_code,next.geo_city_id);if(showQuote&&tenantSlug&&next.latitude&&next.longitude)await loadQuote(next.latitude,next.longitude)}catch(e:any){setError(e.message)}}

 function locate(){if(!navigator.geolocation){setError("Tu navegador no permite obtener la ubicación.");return}setLocating(true);setError("");navigator.geolocation.getCurrentPosition(async pos=>{try{const lat=pos.coords.latitude,lng=pos.coords.longitude;const d=await getJSON(`/api/backend/api/v1/public/geo/reverse?lat=${lat}&lng=${lng}`);const x=d.data?.result;if(!x)throw new Error("No fue posible identificar la dirección.");const next={...value,geo_province_code:x.provinceCode||"",geo_city_id:x.cityId||"",geo_id:x.geoId||x.id||"",geo_address_label:x.label||x.name||"Ubicación actual",geo_address_source:x.source||"",latitude:lat,longitude:lng,province:x.province||"",municipality:x.cityName||x.municipality||"",sector:x.neighborhood||"",address:x.street||x.label||""};setQuery(next.geo_address_label);onChange(next);await loadSelectors(next.geo_province_code,next.geo_city_id);if(showQuote&&tenantSlug)await loadQuote(lat,lng)}catch(e:any){setError(e.message)}finally{setLocating(false)}},()=>{setLocating(false);setError("No pudimos acceder a tu ubicación. Revisa el permiso del navegador.")},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}

 async function loadQuote(lat=value.latitude,lng=value.longitude){if(!tenantSlug||!lat||!lng)return;try{const d=await getJSON(`/api/backend/api/v1/public/tenants/${tenantSlug}/delivery/quote?lat=${lat}&lng=${lng}`);setQuote(d.quote)}catch(e:any){setQuote({serviceable:false,reason:e.message})}}

 async function setProvince(code:string){const p=(selectors.provinces||[]).find((x:any)=>x.code===code);const next={...value,geo_province_code:code,geo_city_id:"",geo_neighborhood_id:"",geo_id:"",geo_address_label:"",geo_address_source:"",latitude:0,longitude:0,province:p?.name||"",municipality:"",sector:""};setQuery("");setQuote(null);onChange(next);await loadSelectors(code,"")}
 async function setCity(id:string){const c=(selectors.cities||[]).find((x:any)=>x.cityId===id);const next={...value,geo_city_id:id,geo_neighborhood_id:"",geo_id:"",geo_address_label:"",geo_address_source:"",latitude:0,longitude:0,municipality:c?.name||"",sector:""};setQuery("");setQuote(null);onChange(next);await loadSelectors(value.geo_province_code,id)}
 function setNeighborhood(id:string){const n=(selectors.neighborhoods||[]).find((x:any)=>x.id===id);onChange({...value,geo_neighborhood_id:id,sector:n?.name||""})}
 async function suggestNeighborhood(){const name=suggestionName.trim();if(!name||!value.geo_city_id)return;setSuggesting(true);setSuggestionMessage("");setError("");try{const d=await getJSON("/api/backend/api/v1/public/geo/neighborhood-suggestions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenant_slug:tenantSlug||"",name,cityId:value.geo_city_id,provinceCode:value.geo_province_code,provinceName:province?.name||value.province,municipalityName:city?.name||value.municipality})});setSuggestionName("");setSuggestionMessage(d.data?.status==="pending"?"Sugerencia enviada. Quedará disponible cuando GEO RD MAP la apruebe.":"Sugerencia enviada a GEO RD MAP.")}catch(e:any){setError(e.message)}finally{setSuggesting(false)}}

 return <div className={compact?"space-y-3":"space-y-4"}>
  <div className="relative"><div className="flex gap-2"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input className="field pl-10" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busca calle, sector, residencial o lugar"/>{searching&&<Loader2 size={17} className="absolute right-3 top-1/2 -translate-y-1/2 animate-spin text-gray-400"/>}</div><button type="button" onClick={locate} disabled={locating} className="btn btn-dark whitespace-nowrap">{locating?<Loader2 size={17} className="animate-spin"/>:<LocateFixed size={17}/>}<span className="hidden sm:inline">Mi ubicación</span></button></div>
  {results.length>0&&<div className="absolute z-30 mt-2 max-h-72 w-full overflow-auto rounded-2xl border border-gray-100 bg-white p-2 shadow-xl">{results.map((x:any,i:number)=><button type="button" key={`${x.id}-${i}`} onClick={()=>chooseResult(x)} className="flex w-full items-start gap-3 rounded-xl p-3 text-left hover:bg-orange-50"><MapPin size={18} className="mt-0.5 shrink-0 text-[#ff5400]"/><span><b className="block text-sm">{x.name}</b><span className="text-xs text-gray-500">{x.label}</span></span></button>)}</div>}</div>
  <div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-bold text-gray-600">Provincia<select className="field mt-1" value={value.geo_province_code} onChange={e=>setProvince(e.target.value)} disabled={loading}><option value="">Seleccionar</option>{(selectors.provinces||[]).map((x:any)=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label><label className="text-xs font-bold text-gray-600">Ciudad<select className="field mt-1" value={value.geo_city_id} onChange={e=>setCity(e.target.value)} disabled={!value.geo_province_code||loading}><option value="">Seleccionar</option>{(selectors.cities||[]).map((x:any)=><option key={x.cityId} value={x.cityId}>{x.name} · {x.kindLabel}</option>)}</select></label><label className="text-xs font-bold text-gray-600">Barrio / sector<select className="field mt-1" value={value.geo_neighborhood_id} onChange={e=>setNeighborhood(e.target.value)} disabled={!value.geo_city_id||loading}><option value="">Seleccionar</option>{(selectors.neighborhoods||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}{x.custom?" · personalizado":""}</option>)}</select></label></div>
  {value.geo_city_id&&<details className="rounded-xl border border-dashed border-gray-200 bg-gray-50/60 p-3"><summary className="cursor-pointer list-none text-xs font-bold text-gray-600"><span className="inline-flex items-center gap-2"><PlusCircle size={15} className="text-[#ff5400]"/>¿No encuentras tu barrio o sector?</span></summary><div className="mt-3 flex gap-2"><input className="field" placeholder="Nombre del barrio o sector faltante" value={suggestionName} onChange={e=>setSuggestionName(e.target.value)}/><button type="button" disabled={suggesting||!suggestionName.trim()} onClick={suggestNeighborhood} className="btn btn-dark whitespace-nowrap">{suggesting?<Loader2 size={16} className="animate-spin"/>:"Sugerir"}</button></div>{suggestionMessage&&<p className="mt-2 text-xs font-semibold text-green-700">{suggestionMessage}</p>}</details>}
  <div className="grid gap-3 sm:grid-cols-[1fr_220px]"><input className="field" placeholder="Dirección / calle y número" value={value.address} onChange={e=>onChange({...value,address:e.target.value})}/><input className="field" placeholder="Referencia" value={value.reference||""} onChange={e=>onChange({...value,reference:e.target.value})}/></div>
  {value.latitude!==0&&value.longitude!==0&&<div className="flex flex-wrap items-center gap-3 rounded-2xl bg-slate-50 p-3 text-xs text-slate-600"><CheckCircle2 size={17} className="text-green-600"/><b>{value.geo_address_label||`${province?.name||value.province}, ${city?.name||value.municipality}`}</b><span>{value.latitude.toFixed(6)}, {value.longitude.toFixed(6)}</span>{showQuote&&tenantSlug&&<button type="button" onClick={()=>loadQuote()} className="ml-auto font-black text-[#ff5400]">Validar delivery</button>}</div>}
  {requiredCoordinates&&(!value.latitude||!value.longitude)&&<p className="text-xs font-semibold text-amber-700">Selecciona una dirección del buscador o usa “Mi ubicación” para fijar las coordenadas exactas.</p>}
  {quote&&<div className={`rounded-2xl p-4 text-sm ${quote.serviceable?"bg-green-50 text-green-800":"bg-red-50 text-red-700"}`}>{quote.serviceable?<div className="flex flex-wrap items-center gap-4"><span className="font-black">✓ Delivery disponible</span><span>Tarifa: <b>RD$ {Number(quote.fee||0).toLocaleString("es-DO",{minimumFractionDigits:2})}</b></span>{quote.distance_km>0&&<span className="flex items-center gap-1"><Navigation size={15}/>{Number(quote.distance_km).toFixed(1)} km · {Math.max(1,Math.round(Number(quote.duration_seconds||0)/60))} min</span>}{quote.zone?.Name&&<span>Zona: <b>{quote.zone.Name}</b></span>}</div>:<b>{quote.reason||"Esta ubicación no está cubierta por el delivery."}</b>}</div>}
  {error&&<p className="rounded-xl bg-red-50 p-3 text-xs text-red-600">{error}</p>}
 </div>
}

export const blankGeoAddress:GeoAddressValue={geo_province_code:"",geo_city_id:"",geo_neighborhood_id:"",geo_id:"",geo_address_label:"",geo_address_source:"",latitude:0,longitude:0,province:"",municipality:"",sector:"",address:"",reference:""};
