"use client";
import {useEffect,useMemo,useState} from "react";
import {useDispatch,useSelector} from "react-redux";
import {RootState,add,inc,dec,clear,CartOption} from "@/lib/store";
import {money} from "@/lib/api";
import {Search,ShoppingBag,Minus,Plus,X,MapPin,MessageCircle,Check,BadgeCheck,Loader2,ShieldCheck} from "lucide-react";
import {GeoAddressPicker,blankGeoAddress,GeoAddressValue} from "@/components/geo-address-picker";

const waDigits=(v:string)=>{let d=(v||'').replace(/\D/g,'');if(d.length===10)d='1'+d;return d};
const onlyDigits=(v:string)=>(v||'').replace(/\D/g,'');
const cedulaFormat=(v:string)=>{const d=onlyDigits(v).slice(0,11);return d.length<=3?d:d.length<=10?`${d.slice(0,3)}-${d.slice(3)}`:`${d.slice(0,3)}-${d.slice(3,10)}-${d.slice(10)}`};
const displayDate=(v:string)=>{if(!v)return '';const [y,m,d]=v.split('-');return y&&m&&d?`${d}/${m}/${y}`:v};
const displaySex=(v:string)=>v==='M'?'Masculino':v==='F'?'Femenino':v||'';

export function Storefront({data}:{data:any}){
 const{tenant,categories,products}=data;const[cat,setCat]=useState('');const[q,setQ]=useState('');const[checkout,setCheckout]=useState(false);const[done,setDone]=useState<any>(null);const[selected,setSelected]=useState<any>(null);const dispatch=useDispatch();const items=useSelector((s:RootState)=>s.cart.items);const filtered=useMemo(()=>products.filter((p:any)=>(!cat||p.CategoryID===cat)&&(!q||p.Name.toLowerCase().includes(q.toLowerCase()))),[products,cat,q]);const total=items.reduce((a,b)=>a+b.price*b.quantity,0);const accent=tenant.Accent||'#ff5400';
 return <div style={{'--brand':accent} as any} className="min-h-screen bg-[#f5f5f5] pb-28">
  <header className="bg-white"><div className="h-44 bg-[#212529]" style={tenant.CoverURL?{backgroundImage:`url(${tenant.CoverURL})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}/><div className="mx-auto max-w-5xl px-4"><div className="-mt-12 flex items-end gap-4"><div className="grid h-24 w-24 place-items-center overflow-hidden rounded-3xl border-4 border-white bg-white text-4xl shadow-soft">{tenant.LogoURL?<img className="h-full w-full object-cover" src={tenant.LogoURL}/>:<>🏪</>}</div><div className="pb-2"><h1 className="text-2xl font-black">{tenant.Name}</h1><div className={`mt-1 text-sm font-bold ${tenant.IsOpen?'text-green-600':'text-red-600'}`}>{tenant.IsOpen?'Abierto ahora':'Cerrado'}</div></div></div><p className="mt-4 max-w-2xl text-sm text-gray-500">{tenant.Description}</p><div className="mt-3 flex flex-wrap gap-4 pb-5 text-sm text-gray-500"><span className="flex items-center gap-1"><MapPin size={15}/>{tenant.GeoAddressLabel||tenant.Municipality||'República Dominicana'}</span>{tenant.WhatsApp&&<a target="_blank" href={`https://wa.me/${waDigits(tenant.WhatsApp)}`} className="flex items-center gap-1"><MessageCircle size={15}/>{tenant.WhatsApp}</a>}<a href="/registro" className="font-bold text-[var(--brand)]">Registrarme como cliente</a></div></div></header>
  <main className="mx-auto max-w-5xl px-4">{(data.banners||[]).filter((b:any)=>b.Active).length>0&&<div className="hide-scrollbar -mx-1 flex gap-3 overflow-x-auto py-4">{(data.banners||[]).filter((b:any)=>b.Active).map((b:any)=><a key={b.ID} href={b.LinkURL||undefined} className="min-w-[85%] overflow-hidden rounded-2xl bg-white shadow-soft sm:min-w-[55%] lg:min-w-[40%]">{b.DesktopURL?<img src={b.DesktopURL} className="aspect-[16/6] w-full object-cover"/>:<div className="grid aspect-[16/6] place-items-center bg-[#212529] p-6 text-center font-black text-white">{b.Title}</div>}</a>)}</div>}<div className="sticky top-0 z-20 -mx-4 bg-[#f5f5f5]/95 px-4 pt-4 backdrop-blur"><div className="relative"><Search className="absolute left-3 top-3 text-gray-400" size={20}/><input className="field pl-10" placeholder="Buscar en el catálogo" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="hide-scrollbar flex gap-2 overflow-x-auto py-4"><button onClick={()=>setCat('')} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${!cat?'bg-[var(--brand)] text-white':'bg-white'}`}>Todos</button>{categories.map((c:any)=><button key={c.ID} onClick={()=>setCat(c.ID)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${cat===c.ID?'bg-[var(--brand)] text-white':'bg-white'}`}>{c.Name}</button>)}</div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((p:any)=>{const price=p.OnSale&&p.PromoPrice?p.PromoPrice:p.Price;return <article key={p.ID} className="flex gap-4 rounded-2xl bg-white p-4 shadow-soft"><button onClick={()=>setSelected(p)} className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-xl bg-gray-100 text-4xl">{p.ImageURL?<img className="h-full w-full object-cover" src={p.ImageURL}/>:<>🛒</>}</button><div className="min-w-0 flex-1"><button onClick={()=>setSelected(p)} className="text-left"><h3 className="font-black">{p.Name}</h3><p className="mt-1 line-clamp-2 text-xs text-gray-500">{p.Description}</p></button><div className="mt-3 flex items-center justify-between"><div><b className="text-[var(--brand)]">{money(price)}</b>{p.OnSale&&p.PromoPrice>0&&<div className="text-xs text-gray-400 line-through">{money(p.Price)}</div>}</div><button onClick={()=>setSelected(p)} className="grid h-9 w-9 place-items-center rounded-full bg-[var(--brand)] text-white"><Plus size={18}/></button></div></div></article>})}</div></main>
  {items.length>0&&<button onClick={()=>setCheckout(true)} className="fixed bottom-4 left-1/2 z-30 flex w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 items-center justify-between rounded-2xl bg-[#212529] px-5 py-4 text-white shadow-2xl"><span className="flex items-center gap-2 font-bold"><ShoppingBag/>Ver carrito ({items.reduce((a,b)=>a+b.quantity,0)})</span><b>{money(total)}</b></button>}
  {selected&&<ProductModal tenant={tenant} product={selected} close={()=>setSelected(null)} onAdd={(line:any)=>{dispatch(add(line));setSelected(null)}}/>}
  {checkout&&<Checkout tenant={tenant} zones={data.delivery_zones||[]} items={items} total={total} close={()=>setCheckout(false)} done={(o:any)=>{setDone(o);dispatch(clear());setCheckout(false)}} dispatch={dispatch}/>} 
  {done&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-7 text-center"><div className="text-5xl">✅</div><h2 className="mt-4 text-2xl font-black">Pedido recibido</h2><p className="mt-2 text-gray-500">Tu pedido <b>#{done.PublicCode}</b> fue creado correctamente.</p><div className="mt-5 max-h-64 overflow-y-auto rounded-xl bg-gray-50 p-4 text-left text-sm whitespace-pre-wrap">{done.WhatsAppText}</div>{tenant.WhatsApp&&<a target="_blank" href={`https://wa.me/${waDigits(tenant.WhatsApp)}?text=${encodeURIComponent(done.WhatsAppText)}`} className="btn btn-brand mt-5 w-full">Continuar por WhatsApp</a>}<button onClick={()=>setDone(null)} className="mt-3 text-sm font-bold text-gray-500">Cerrar</button></div></div>}
 </div>
}

function ProductModal({tenant,product,close,onAdd}:{tenant:any,product:any,close:()=>void,onAdd:(line:any)=>void}){
 const[detail,setDetail]=useState<any>(null);const[err,setErr]=useState('');const[sel,setSel]=useState<Record<string,string[]>>({});const[note,setNote]=useState('');
 useEffect(()=>{fetch(`/api/backend/api/v1/public/tenants/${tenant.Slug}/products/${product.ID}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo abrir el producto');setDetail(d.detail)}).catch(e=>setErr(e.message))},[tenant.Slug,product.ID]);
 const base=product.OnSale&&product.PromoPrice?product.PromoPrice:product.Price;const groups=detail?.OptionGroups||[];const selectedOptions:CartOption[]=groups.flatMap((g:any)=>(g.Options||[]).filter((o:any)=>(sel[g.ID]||[]).includes(o.ID)).map((o:any)=>({id:o.ID,name:`${g.Name}: ${o.Name}`,price:o.PriceDelta})));const price=base+selectedOptions.reduce((a,o)=>a+o.price,0);
 function toggle(g:any,o:any){setSel(s=>{const cur=s[g.ID]||[];const has=cur.includes(o.ID);let next=has?cur.filter(x=>x!==o.ID):[...cur,o.ID];if(g.MaxSelect===1&&!has)next=[o.ID];else if(!has&&next.length>g.MaxSelect)next=next.slice(-g.MaxSelect);return {...s,[g.ID]:next}})}
 function submit(){for(const g of groups){const n=(sel[g.ID]||[]).length;if((g.Required||g.MinSelect>0)&&n<Math.max(1,g.MinSelect)){setErr(`Selecciona ${g.MinSelect||1} opción(es) en ${g.Name}`);return}}const ids=selectedOptions.map(o=>o.id);const key=[product.ID,...ids.sort(),note.trim()].join('|');onAdd({key,product_id:product.ID,name:product.Name,price,option_ids:ids,options:selectedOptions,note:note.trim()})}
 return <div className="fixed inset-0 z-40 grid place-items-end bg-black/50 md:place-items-center md:p-4"><div className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-t-3xl bg-white p-6 md:rounded-3xl"><div className="flex items-start justify-between"><div><h2 className="text-2xl font-black">{product.Name}</h2><p className="mt-1 text-sm text-gray-500">{product.Description}</p>{(product.Reference||product.PosCode)&&<div className="mt-2 text-xs text-gray-400">{product.Reference&&<>Ref. {product.Reference}</>}{product.Reference&&product.PosCode&&<> · </>}{product.PosCode&&<>Código {product.PosCode}</>}</div>}</div><button onClick={close}><X/></button></div>{detail?.Images?.length>0&&<div className="hide-scrollbar mt-5 flex gap-3 overflow-x-auto">{detail.Images.map((i:any)=><img key={i.ID} className="h-44 min-w-44 rounded-2xl object-cover" src={i.URL}/>)}</div>}{product.VideoURL&&<a className="mt-4 inline-block text-sm font-bold text-[var(--brand)]" href={product.VideoURL} target="_blank">Ver video del producto</a>}{(product.WeightKG||product.HeightCM||product.WidthCM||product.LengthCM)&&<div className="mt-4 rounded-xl bg-gray-50 p-3 text-xs text-gray-500">{product.WeightKG?`Peso: ${product.WeightKG} kg`:''} {product.HeightCM?` · Alto: ${product.HeightCM} cm`:''} {product.WidthCM?` · Ancho: ${product.WidthCM} cm`:''} {product.LengthCM?` · Largo: ${product.LengthCM} cm`:''}</div>}<div className="mt-5 space-y-5">{groups.map((g:any)=><div key={g.ID}><div className="flex items-center justify-between"><b>{g.Name}</b><span className="text-xs text-gray-400">{g.Required?'Requerido':'Opcional'} · máx. {g.MaxSelect}</span></div><div className="mt-2 grid gap-2">{g.Options.map((o:any)=>{const on=(sel[g.ID]||[]).includes(o.ID);return <button onClick={()=>toggle(g,o)} key={o.ID} className={`flex items-center justify-between rounded-xl border p-3 text-left ${on?'border-[var(--brand)] bg-orange-50':'border-gray-200'}`}><span className="flex items-center gap-2"><span className={`grid h-5 w-5 place-items-center rounded-full border ${on?'border-[var(--brand)] bg-[var(--brand)] text-white':'border-gray-300'}`}>{on&&<Check size={13}/>}</span>{o.Name}</span><span className="text-sm font-bold">{o.PriceDelta>0?`+ ${money(o.PriceDelta)}`:'Incluido'}</span></button>})}</div></div>)}</div><textarea className="field mt-5" placeholder="Nota para este producto (opcional)" value={note} onChange={e=>setNote(e.target.value)}/>{err&&<p className="mt-3 text-sm text-red-600">{err}</p>}<button onClick={submit} className="btn btn-brand mt-5 w-full">Agregar · {money(price)}</button></div></div>
}

function Checkout({tenant,zones,items,total,close,done,dispatch}:{tenant:any,zones:any[],items:any[],total:number,close:()=>void,done:(x:any)=>void,dispatch:any}){
 const[form,setForm]=useState<any>({cedula:'',customer_name:'',birth_date:'',sex:'',email:'',whatsapp:'',delivery_type:tenant.DeliveryEnabled?'delivery':'pickup',payment_method:'cash',payment_info:'',coupon_code:''});
 const[location,setLocation]=useState<GeoAddressValue>({...blankGeoAddress});
 const[identity,setIdentity]=useState<any>(null);const[verifying,setVerifying]=useState(false);const[err,setErr]=useState('');const[sending,setSending]=useState(false);
 async function verifyIdentity(){setVerifying(true);setErr('');try{const r=await fetch('/api/backend/api/v1/public/identity/customer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cedula:form.cedula})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No fue posible verificar la cédula');setIdentity(d.identity);setForm((f:any)=>({...f,customer_name:d.identity.nombre_completo,birth_date:d.identity.fecha_nacimiento,sex:d.identity.sexo}))}catch(e:any){setIdentity(null);setErr(e.message)}finally{setVerifying(false)}}
 async function submit(){if(!identity){setErr('Verifica tu cédula antes de confirmar el pedido.');return}if(form.delivery_type==='delivery'&&(!location.latitude||!location.longitude)){setErr('Selecciona la dirección exacta o usa “Mi ubicación” para validar el delivery.');return}setSending(true);setErr('');try{const payload:any={tenant_slug:tenant.Slug,...form,cedula:onlyDigits(form.cedula),items:items.map(x=>({product_id:x.product_id,quantity:x.quantity,note:x.note,option_ids:x.option_ids}))};if(form.delivery_type==='delivery')Object.assign(payload,{province:location.province,municipality:location.municipality,sector:location.sector,address:location.address,reference:location.reference||'',geo_province_code:location.geo_province_code,geo_city_id:location.geo_city_id,geo_neighborhood_id:location.geo_neighborhood_id,geo_id:location.geo_id,geo_address_label:location.geo_address_label,geo_address_source:location.geo_address_source,latitude:location.latitude,longitude:location.longitude});const r=await fetch('/api/backend/api/v1/public/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'No fue posible crear el pedido');done(d.order)}catch(e:any){setErr(e.message)}finally{setSending(false)}}
 return <div className="fixed inset-0 z-40 bg-black/50 p-0 md:p-6"><div className="ml-auto h-full w-full max-w-xl overflow-y-auto bg-white p-6 md:rounded-3xl"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Mi pedido</h2><button onClick={close}><X/></button></div>
 <div className="mt-5 space-y-3">{items.map(i=><div key={i.key} className="rounded-xl bg-gray-50 p-3"><div className="flex items-center justify-between"><div><b>{i.name}</b><div className="text-sm text-gray-500">{money(i.price)} c/u</div>{i.options?.map((o:any)=><div key={o.id} className="text-xs text-gray-400">• {o.name}</div>)}{i.note&&<div className="mt-1 text-xs italic text-gray-500">Nota: {i.note}</div>}</div><div className="flex items-center gap-2"><button onClick={()=>dispatch(dec(i.key))} className="rounded-lg bg-white p-2"><Minus size={15}/></button><b>{i.quantity}</b><button onClick={()=>dispatch(inc(i.key))} className="rounded-lg bg-white p-2"><Plus size={15}/></button></div></div></div>)}</div>
 <div className="mt-5 rounded-2xl border border-gray-200 p-4"><div className="flex items-center gap-2"><ShieldCheck size={19} className="text-[var(--brand)]"/><b>Identidad del cliente</b></div><p className="mt-1 text-xs text-gray-500">Tu nombre, fecha de nacimiento y sexo se completan desde Identidad y no pueden modificarse manualmente.</p><div className="mt-4 flex gap-2"><input className="field" placeholder="Cédula 001-0000000-0" value={form.cedula} onChange={e=>{setIdentity(null);setForm({...form,cedula:cedulaFormat(e.target.value),customer_name:'',birth_date:'',sex:''})}}/><button disabled={verifying||onlyDigits(form.cedula).length!==11} onClick={verifyIdentity} className="btn btn-dark min-w-28">{verifying?<Loader2 className="animate-spin" size={18}/>: 'Verificar'}</button></div>{identity&&<div className="mt-3 flex items-center gap-2 rounded-xl bg-green-50 p-3 text-sm font-bold text-green-700"><BadgeCheck size={18}/> Identidad verificada</div>}<div className="mt-3 grid gap-3 sm:grid-cols-2"><input className="field bg-gray-50 sm:col-span-2" readOnly placeholder="Nombre completo" value={form.customer_name}/><input className="field bg-gray-50" readOnly placeholder="Fecha de nacimiento" value={displayDate(form.birth_date)}/><input className="field bg-gray-50" readOnly placeholder="Sexo" value={displaySex(form.sex)}/></div></div>
 <div className="mt-5 grid gap-3"><input className="field" type="email" placeholder="Correo (opcional)" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="field" placeholder="WhatsApp (809, 829 o 849)" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/><select className="field" value={form.delivery_type} onChange={e=>setForm({...form,delivery_type:e.target.value})}>{tenant.DeliveryEnabled&&<option value="delivery">{tenant.DeliveryLabel||'Delivery'}</option>}{tenant.PickupEnabled&&<option value="pickup">{tenant.PickupLabel||'Recogida'}</option>}{tenant.TableEnabled&&<option value="table">{tenant.TableLabel||'Mesa'}</option>}{tenant.OtherEnabled&&<option value="other">{tenant.OtherLabel||'Otro'}</option>}</select>{form.delivery_type==='delivery'&&<div className="rounded-2xl border border-gray-200 p-4"><div className="mb-3"><b>Dirección de entrega</b><p className="text-xs text-gray-500">GEO RD MAP comprobará cobertura, tarifa, distancia y ETA.</p></div><GeoAddressPicker value={location} onChange={setLocation} tenantSlug={tenant.Slug} showQuote requiredCoordinates compact/></div>}<select className="field" value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}>{tenant.CashEnabled!==false&&<option value="cash">Efectivo</option>}{tenant.CardOnDeliveryEnabled!==false&&<option value="card_on_delivery">Tarjeta al recibir</option>}{tenant.BankTransferEnabled&&<option value="bank_transfer">Transferencia bancaria</option>}{tenant.PaymentLinkEnabled&&<option value="payment_link">Enlace de pago</option>}</select><input className="field" placeholder="Cupón (opcional)" value={form.coupon_code} onChange={e=>setForm({...form,coupon_code:e.target.value})}/></div>{err&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-600">{err}</p>}<div className="mt-6 flex items-center justify-between border-t pt-5"><div><div className="text-xs text-gray-500">Subtotal estimado</div><div className="text-xl font-black">{money(total)}</div><div className="text-xs text-gray-400">Delivery se valida en el servidor</div></div><button disabled={sending||!identity} onClick={submit} className="btn btn-brand">{sending?'Procesando...':'Confirmar pedido'}</button></div></div></div>
}
