'use client'
import { X, LoaderCircle, Search, Plus, Trash2, ImagePlus, UploadCloud } from 'lucide-react'

export function Modal({open,onClose,title,subtitle,children,wide=false}:{open:boolean;onClose:()=>void;title:string;subtitle?:string;children:React.ReactNode;wide?:boolean}){
 if(!open)return null
 return <div className="fixed inset-0 z-[80] flex items-end justify-center sm:items-center sm:p-5">
  <button aria-label="Cerrar" onClick={onClose} className="absolute inset-0 bg-[#17213a]/35 backdrop-blur-[4px]"/>
  <section className={`mobile-sheet relative flex max-h-[96dvh] w-full flex-col overflow-hidden rounded-t-[30px] border border-white/70 bg-white shadow-[0_30px_90px_rgba(46,49,84,.24)] sm:max-h-[92vh] sm:rounded-[30px] ${wide?'sm:max-w-5xl':'sm:max-w-xl'}`}>
   <div className="mx-auto mt-2 h-1 w-10 rounded-full bg-slate-200 sm:hidden"/>
   <header className="flex shrink-0 items-start gap-4 border-b border-slate-100 px-5 py-4 sm:px-6 sm:py-5">
    <div className="min-w-0 flex-1"><h3 className="text-lg font-semibold tracking-tight text-ink-900 sm:text-xl">{title}</h3>{subtitle&&<p className="mt-1 max-w-2xl text-sm leading-5 text-[#8d92aa]">{subtitle}</p>}</div>
    <button type="button" onClick={onClose} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#f6f7fa] text-[#9298ad] transition hover:bg-[#eef0f4] hover:text-ink-900"><X className="h-4 w-4"/></button>
   </header>
   <div className="modal-scroll min-h-0 flex-1 overflow-y-auto px-5 py-5 sm:px-6 sm:py-6">{children}</div>
  </section>
 </div>
}
export function PageEmpty({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <div className="card flex min-h-64 flex-col items-center justify-center p-8 text-center"><div className="mb-4 grid h-14 w-14 place-items-center rounded-full bg-brand-50 text-brand-600"><Plus/></div><h3 className="font-semibold text-ink-900">{title}</h3><p className="mt-1 max-w-md text-sm leading-6 text-[#8d92aa]">{detail}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function Loading(){return <div className="flex min-h-48 items-center justify-center text-[#a2a6b8]"><LoaderCircle className="mr-2 h-5 w-5 animate-spin"/> Cargando...</div>}
export function Alert({text,type='error'}:{text:string;type?:'error'|'success'}){return <div className={`mb-4 rounded-2xl border px-4 py-3 text-sm ${type==='error'?'border-rose-200 bg-rose-50 text-rose-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{text}</div>}
export function Status({value}:{value:string}){const map:any={active:'bg-emerald-50 text-emerald-700',inactive:'bg-[#f1f2f6] text-slate-600',blocked:'bg-rose-50 text-rose-700',pending:'bg-amber-50 text-amber-700',confirmed:'bg-cyan-50 text-cyan-700',reserved:'bg-amber-50 text-amber-700',seated:'bg-violet-50 text-violet-700',completed:'bg-emerald-50 text-emerald-700',no_show:'bg-rose-50 text-rose-700',processing:'bg-blue-50 text-blue-700',preparing:'bg-blue-50 text-blue-700',ready:'bg-emerald-50 text-emerald-700',out_for_delivery:'bg-violet-50 text-violet-700',delivered:'bg-emerald-50 text-emerald-700',picked_up:'bg-emerald-50 text-emerald-700',canceled:'bg-rose-50 text-rose-700',paid:'bg-emerald-50 text-emerald-700',failed:'bg-rose-50 text-rose-700',refunded:'bg-violet-50 text-violet-700',approved:'bg-emerald-50 text-emerald-700',rejected:'bg-rose-50 text-rose-700',open:'bg-blue-50 text-blue-700',answered:'bg-violet-50 text-violet-700',closed:'bg-[#f1f2f6] text-slate-600',draft:'bg-slate-100 text-slate-700',sent:'bg-blue-50 text-blue-700',viewed:'bg-violet-50 text-violet-700',converted:'bg-emerald-50 text-emerald-700',cancelled:'bg-rose-50 text-rose-700',won:'bg-emerald-50 text-emerald-700',lost:'bg-rose-50 text-rose-700',in_progress:'bg-blue-50 text-blue-700',urgent:'bg-rose-50 text-rose-700',assigned:'bg-blue-50 text-blue-700',accepted:'bg-cyan-50 text-cyan-700',on_route:'bg-violet-50 text-violet-700',arrived:'bg-amber-50 text-amber-700',ringing:'bg-amber-50 text-amber-700',connecting:'bg-blue-50 text-blue-700',held:'bg-violet-50 text-violet-700',transferred:'bg-cyan-50 text-cyan-700',missed:'bg-rose-50 text-rose-700'};const labels:any={active:'Activo',inactive:'Inactivo',blocked:'Bloqueado',pending:'Pendiente',confirmed:'Confirmado',reserved:'Reservada',seated:'En mesa',completed:'Completada',no_show:'No asistió',processing:'Preparando',preparing:'Preparando',ready:'Listo',out_for_delivery:'En camino',delivered:'Entregado',picked_up:'Recogido',canceled:'Cancelado',paid:'Pagado',failed:'Fallido',refunded:'Reembolsado',approved:'Aprobado',rejected:'Rechazado',open:'Abierto',answered:'Respondido',closed:'Cerrado',draft:'Borrador',sent:'Enviada',viewed:'Vista',converted:'Convertida',cancelled:'Cancelada',won:'Ganada',lost:'Perdida',in_progress:'En curso',urgent:'Urgente',assigned:'Asignada',accepted:'Aceptada',on_route:'En ruta',arrived:'Llegó',ringing:'Timbrando',connecting:'Conectando',held:'En espera',transferred:'Transferida',missed:'Perdida'};return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${map[value]||'bg-[#f1f2f6] text-slate-600'}`}>{labels[value]||value}</span>}
export function SearchBox({value,onChange,placeholder='Buscar...'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#a2a6b8]"/><input className="field pl-10" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}

export function ImagePicker({value,onPick,onClear,label='Subir imagen',busy=false,ratio='square',className=''}:{value?:string;onPick:(file:File)=>void;onClear?:()=>void;label?:string;busy?:boolean;ratio?:'square'|'banner';className?:string}){
 const ratioClass=ratio==='banner'?'aspect-[16/7]':'aspect-square'
 return <div className={className}>
  <label className={`group relative flex ${ratioClass} cursor-pointer items-center justify-center overflow-hidden rounded-[26px] border border-dashed border-[#dfe3eb] bg-[#f8fafb] transition hover:border-brand-300 hover:bg-brand-50/40`}>
   {value?<><img src={value} alt="" className="h-full w-full object-cover"/><div className="absolute inset-0 grid place-items-center bg-slate-950/0 opacity-0 transition group-hover:bg-slate-950/30 group-hover:opacity-100"><span className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-2 text-xs font-semibold text-ink-900 shadow-lg"><UploadCloud className="h-4 w-4"/>Cambiar</span></div></>:<div className="px-4 text-center text-[#9298ad]"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-white text-brand-600 shadow-sm"><ImagePlus className="h-5 w-5"/></span><div className="mt-3 text-sm font-semibold text-[#626983]">{busy?'Subiendo...':label}</div><div className="mt-1 text-xs text-[#a6aabd]">JPG, PNG o WEBP</div></div>}
   <input type="file" accept="image/*" className="hidden" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)onPick(f);e.currentTarget.value=''}}/>
  </label>
  {value&&onClear&&<button type="button" onClick={onClear} className="mt-2 text-xs font-medium text-[#969bb0] hover:text-rose-600">Quitar imagen</button>}
 </div>
}

export function Switch({checked,onChange,label,detail}:{checked:boolean;onChange:(v:boolean)=>void;label:string;detail?:string}){
 return <button type="button" onClick={()=>onChange(!checked)} className="flex w-full items-center gap-3 rounded-2xl border border-[#e9ebf2] bg-white p-3.5 text-left transition hover:border-brand-200">
  <span className={`relative h-6 w-11 shrink-0 rounded-full transition ${checked?'bg-brand-500':'bg-slate-200'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition ${checked?'left-6':'left-1'}`}/></span>
  <span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-ink-900">{label}</span>{detail&&<span className="mt-0.5 block text-xs leading-5 text-[#9298ad]">{detail}</span>}</span>
 </button>
}

export function OptionEditor({value,onChange,label}:{value:{name:string;price:number}[];onChange:(v:{name:string;price:number}[])=>void;label:string}){return <div className="rounded-3xl border border-[#edf0f4] bg-[#fbfcfd] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-sm font-semibold text-ink-900">{label}</span><button type="button" className="inline-flex items-center gap-1 text-sm font-semibold text-brand-600" onClick={()=>onChange([...value,{name:'',price:0}])}><Plus className="h-4 w-4"/>Agregar</button></div><div className="space-y-2">{value.map((o,i)=><div key={i} className="grid grid-cols-[1fr_110px_38px] gap-2"><input className="field" placeholder="Nombre" value={o.name} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input className="field" type="number" min="0" step="0.01" placeholder="RD$" value={o.price} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/><button type="button" onClick={()=>onChange(value.filter((_,j)=>j!==i))} className="grid place-items-center rounded-xl border border-[#e9ebf2] bg-white text-[#a2a6b8] hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></div>)}{value.length===0&&<div className="rounded-2xl border border-dashed border-[#e1e5ec] bg-white px-4 py-5 text-center text-xs text-[#9da2b5]">Sin opciones. Agrégalas solo si este producto las necesita.</div>}</div></div>}
