'use client'
import { X, LoaderCircle, Search, Plus, Trash2 } from 'lucide-react'

export function Modal({open,onClose,title,children,wide=false}:{open:boolean;onClose:()=>void;title:string;children:React.ReactNode;wide?:boolean}){
 if(!open)return null
 return <div className="fixed inset-0 z-[80] flex items-center justify-center p-4"><button aria-label="Cerrar" onClick={onClose} className="absolute inset-0 bg-[#2e3154]/35 backdrop-blur-[2px]"/><div className={`relative max-h-[90vh] w-full overflow-y-auto rounded-lg bg-white shadow-2xl ${wide?'max-w-3xl':'max-w-xl'}`}><div className="sticky top-0 z-10 flex items-center border-b border-[#f0f1f5] bg-white px-5 py-4"><h3 className="text-lg font-medium text-ink-900">{title}</h3><button onClick={onClose} className="ml-auto rounded p-2 text-[#a2a6b8] hover:bg-[#f1f2f6] hover:text-slate-700"><X className="h-5 w-5"/></button></div><div className="p-5">{children}</div></div></div>
}
export function PageEmpty({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <div className="card flex min-h-64 flex-col items-center justify-center p-8 text-center"><div className="mb-4 grid h-14 w-14 place-items-center rounded-full bg-brand-50 text-brand-600"><Plus/></div><h3 className="font-bold text-ink-900">{title}</h3><p className="mt-1 max-w-md text-sm text-[#8d92aa]">{detail}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function Loading(){return <div className="flex min-h-48 items-center justify-center text-[#a2a6b8]"><LoaderCircle className="mr-2 h-5 w-5 animate-spin"/> Cargando...</div>}
export function Alert({text,type='error'}:{text:string;type?:'error'|'success'}){return <div className={`mb-4 rounded-xl border px-4 py-3 text-sm ${type==='error'?'border-rose-200 bg-rose-50 text-rose-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{text}</div>}
export function Status({value}:{value:string}){const map:any={active:'bg-emerald-50 text-emerald-700',inactive:'bg-[#f1f2f6] text-slate-600',blocked:'bg-rose-50 text-rose-700',pending:'bg-amber-50 text-amber-700',processing:'bg-blue-50 text-blue-700',out_for_delivery:'bg-violet-50 text-violet-700',delivered:'bg-emerald-50 text-emerald-700',canceled:'bg-rose-50 text-rose-700',paid:'bg-emerald-50 text-emerald-700',failed:'bg-rose-50 text-rose-700',refunded:'bg-violet-50 text-violet-700',approved:'bg-emerald-50 text-emerald-700',rejected:'bg-rose-50 text-rose-700',open:'bg-blue-50 text-blue-700',answered:'bg-violet-50 text-violet-700',closed:'bg-[#f1f2f6] text-slate-600'};const labels:any={active:'Activo',inactive:'Inactivo',blocked:'Bloqueado',pending:'Pendiente',processing:'En proceso',out_for_delivery:'En camino',delivered:'Entregado',canceled:'Cancelado',paid:'Pagado',failed:'Fallido',refunded:'Reembolsado',approved:'Aprobado',rejected:'Rechazado',open:'Abierto',answered:'Respondido',closed:'Cerrado'};return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${map[value]||'bg-[#f1f2f6] text-slate-600'}`}>{labels[value]||value}</span>}
export function SearchBox({value,onChange,placeholder='Buscar...'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#a2a6b8]"/><input className="field pl-9" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
export function OptionEditor({value,onChange,label}:{value:{name:string;price:number}[];onChange:(v:{name:string;price:number}[])=>void;label:string}){return <div><div className="mb-2 flex items-center justify-between"><span className="label mb-0">{label}</span><button type="button" className="text-sm font-medium text-brand-600" onClick={()=>onChange([...value,{name:'',price:0}])}>+ Agregar</button></div><div className="space-y-2">{value.map((o,i)=><div key={i} className="grid grid-cols-[1fr_120px_38px] gap-2"><input className="field" placeholder="Nombre" value={o.name} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input className="field" type="number" step="0.01" placeholder="Precio" value={o.price} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/><button type="button" onClick={()=>onChange(value.filter((_,j)=>j!==i))} className="grid place-items-center rounded-xl border border-[#e9ebf2] text-[#a2a6b8] hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>}
