'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import StoreShell from '@/components/store-shell'
import { api,upload } from '@/lib/api'
import { Alert, ImagePicker, Loading, Modal, PageEmpty, Status } from '@/components/ui'
import BusinessTemplatePicker,{type BusinessTemplate} from '@/components/business-template-picker'
import { Plus, Store as StoreIcon, ExternalLink, Pencil, SlidersHorizontal, QrCode, Copy, MapPin, MessageCircleMore, ArrowLeft, Sparkles, Archive } from 'lucide-react'
import {QRCodeSVG} from 'qrcode.react'
import PhoneInput from '@/components/phone-input'
import type { Store } from '@/lib/types'

const blank={name:'',slug:'',description:'',logo_url:'',whatsapp:'',address:'',primary_color:'#36b385',is_active:true}
export default function Stores(){
 const [rows,setRows]=useState<Store[]>([]),[busy,setBusy]=useState(true),[open,setOpen]=useState(false),[qr,setQr]=useState<Store|null>(null),[edit,setEdit]=useState<Store|null>(null),[form,setForm]=useState<any>(blank),[err,setErr]=useState(''),[up,setUp]=useState(false)
 const[templateSlug,setTemplateSlug]=useState(''),[template,setTemplate]=useState<BusinessTemplate|undefined>(),[step,setStep]=useState<'template'|'details'>('template')
 const load=()=>{setBusy(true);api<Store[]>('/stores').then(setRows).finally(()=>setBusy(false))}
 useEffect(load,[])
 const start=(x?:Store)=>{setEdit(x||null);setForm(x?{...x}:blank);setTemplateSlug(x?.template_slug||'');setTemplate(undefined);setStep(x?'details':'template');setErr('');setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setErr('');try{const body={...form,slug:form.slug||'',primary_color:form.primary_color||'#36b385',is_active:form.is_active!==false,template_slug:templateSlug};if(edit)await api(`/stores/${edit.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/stores',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e:any){setErr(e.message)}}
 const del=async(x:Store)=>{if(!confirm(`¿Archivar ${x.name}? La tienda dejará de recibir pedidos, pero conservará su historial.`))return;try{await api(`/stores/${x.id}`,{method:'DELETE'});load()}catch(e:any){alert(e.message)}}
 const restore=async(x:Store)=>{try{await api(`/stores/${x.id}`,{method:'PUT',body:JSON.stringify({...x,is_active:true})});load()}catch(e:any){alert(e.message)}}
 const pick=async(f:File)=>{setUp(true);try{const url=await upload(f);setForm((v:any)=>({...v,logo_url:url}))}catch(e:any){setErr(e.message)}finally{setUp(false)}}
 return <StoreShell title="Tiendas" subtitle="Tus puntos de venta en un solo lugar" actions={<button onClick={()=>start()} className="btn-primary"><Plus className="h-4 w-4"/> Nueva tienda</button>}>
  {busy?<Loading/>:rows.length===0?<PageEmpty title="Crea tu primera tienda" detail="Elige el tipo de negocio y WAMERCIO preparará una base lista para personalizar." action={<button onClick={()=>start()} className="btn-primary">Crear tienda</button>}/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map(s=><article key={s.id} className="merchant-grid-card"><div className="p-5"><div className="flex items-start gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-2xl bg-brand-50 text-brand-600">{s.logo_url?<img src={s.logo_url} className="h-full w-full object-cover"/>:<StoreIcon className="h-6 w-6"/>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate text-lg font-semibold text-ink-900">{s.name}</h3><Status value={s.is_active?'active':'inactive'}/></div><p className="mt-1 line-clamp-2 text-sm leading-5 text-[#8d92aa]">{s.description||'Tu catálogo está listo para personalizar.'}</p>{s.template_name&&<div className="mt-2 inline-flex items-center gap-1.5 rounded-full bg-brand-50 px-2.5 py-1 text-[10px] font-semibold text-brand-700"><Sparkles className="h-3 w-3"/>{s.template_name}</div>}</div></div><div className="mt-4 space-y-2 text-xs text-[#82889f]">{s.whatsapp&&<div className="flex items-center gap-2"><MessageCircleMore className="h-4 w-4 text-brand-500"/><span>{s.whatsapp}</span></div>}{s.address&&<div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-brand-500"/><span className="truncate">{s.address}</span></div>}</div><div className="mt-5 grid grid-cols-2 gap-2"><a href={`/store/${s.slug}`} target="_blank" className="btn-primary"><ExternalLink className="h-4 w-4"/> Ver tienda</a><Link href="/settings/store" className="btn-secondary"><SlidersHorizontal className="h-4 w-4"/> Configurar</Link></div><div className="mt-3 flex justify-end gap-1"><button onClick={()=>setQr(s)} className="icon-action" title="Código QR"><QrCode className="h-4 w-4"/></button><button onClick={()=>start(s)} className="icon-action" title="Editar datos básicos"><Pencil className="h-4 w-4"/></button>{s.is_active?<button onClick={()=>del(s)} className="icon-action hover:border-rose-200 hover:bg-rose-50 hover:text-rose-600" title="Archivar"><Archive className="h-4 w-4"/></button>:<button onClick={()=>restore(s)} className="btn-secondary px-3 text-xs">Reactivar</button>}</div></div></article>)}</div>}

  <Modal open={open} onClose={()=>setOpen(false)} title={edit?'Editar tienda':step==='template'?'Elige el tipo de negocio':'Personaliza tu tienda'} subtitle={edit?'Actualiza los datos básicos de tu comercio.':step==='template'?'WAMERCIO preparará categorías, ejemplos y respuestas rápidas automáticamente.':'Solo completa lo esencial. Puedes cambiarlo después.'} wide>
   {!edit&&step==='template'?<div>{err&&<Alert text={err}/>}<BusinessTemplatePicker value={templateSlug} onChange={(slug,t)=>{setTemplateSlug(slug);setTemplate(t);setErr('')}}/><div className="mt-6 flex justify-end border-t border-slate-100 pt-5"><button disabled={!templateSlug} onClick={()=>setStep('details')} className="btn-primary">Continuar</button></div></div>:<form onSubmit={save}>{err&&<Alert text={err}/>} {!edit&&<button type="button" onClick={()=>setStep('template')} className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-[#7e849a] hover:text-brand-700"><ArrowLeft className="h-4 w-4"/>Cambiar plantilla</button>} {!edit&&template&&<div className="mb-5 flex items-center gap-3 rounded-2xl border border-brand-100 bg-brand-50 p-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white text-xl">{template.icon}</span><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-brand-700">Base seleccionada</p><p className="text-sm font-semibold text-ink-900">{template.name}</p></div></div>}<div className="grid gap-6 md:grid-cols-[190px_1fr]"><div><ImagePicker value={form.logo_url} onPick={pick} onClear={()=>setForm({...form,logo_url:''})} label="Agregar logo" busy={up}/><p className="mt-3 text-center text-xs leading-5 text-[#9ba0b3]">Puedes cambiarlo cuando quieras.</p></div><div className="space-y-4"><div><label className="label">Nombre del negocio *</label><input autoFocus className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required placeholder="Ej.: Boutique Luna"/></div><div><label className="label">WhatsApp comercial</label><PhoneInput value={form.whatsapp||''} onChange={value=>setForm({...form,whatsapp:value})}/></div><div><label className="label">Dirección</label><input className="field" value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Ej.: Av. Duarte #10, Bonao"/></div><div><label className="label">Descripción</label><textarea className="field min-h-24 resize-none" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Una frase corta sobre tu negocio."/></div></div></div><div className="mt-7 flex flex-col-reverse gap-2 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><button type="button" onClick={()=>setOpen(false)} className="btn-secondary">Cancelar</button><button className="btn-primary">{edit?'Guardar cambios':'Crear tienda'}</button></div></form>}
  </Modal>

  <Modal open={!!qr} onClose={()=>setQr(null)} title={qr?`Comparte ${qr.name}`:'Código QR'} subtitle="Tus clientes pueden escanearlo para abrir el catálogo.">{qr&&<div className="text-center"><div className="mx-auto inline-block rounded-3xl border border-[#e9ebf2] bg-white p-5 shadow-sm"><QRCodeSVG value={`${typeof window!=='undefined'?window.location.origin:''}/store/${qr.slug}`} size={220} level="M" includeMargin/></div><div className="mt-5 flex items-center gap-2 rounded-2xl bg-[#f7f8fa] p-2"><input className="min-w-0 flex-1 bg-transparent px-2 text-sm text-slate-600 outline-none" readOnly value={`${typeof window!=='undefined'?window.location.origin:''}/store/${qr.slug}`}/><button className="btn-secondary px-3" onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/store/${qr.slug}`)}><Copy className="h-4 w-4"/> Copiar</button></div></div>}</Modal>
 </StoreShell>
}
