'use client'
import {useEffect,useMemo,useRef,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,money} from '@/lib/api'
import {Loading,PageEmpty,Status} from '@/components/ui'
import {LocateFixed,MapPin,Navigation,PackageCheck,Route,Truck,UserRound} from 'lucide-react'

export default function CourierMode(){
 const[store,setStore]=useState(''),[staff,setStaff]=useState<any[]>([]),[courier,setCourier]=useState(''),[assignments,setAssignments]=useState<any[]>([]),[routes,setRoutes]=useState<any[]>([]),[loading,setLoading]=useState(false),[tracking,setTracking]=useState(false),[geoText,setGeoText]=useState(''),watch=useRef<number|null>(null)
 const load=()=>{if(!store){setStaff([]);setAssignments([]);setRoutes([]);return};setLoading(true);Promise.all([api<any[]>(`/staff?store_id=${store}`),api<any[]>(`/delivery/assignments?store_id=${store}`),api<any[]>(`/delivery/routes?store_id=${store}`)]).then(([s,a,r])=>{const couriers=s.filter(x=>x.status==='active'&&x.role==='delivery');setStaff(couriers);setAssignments(a);setRoutes(r);setCourier(v=>couriers.some(x=>x.id===v)?v:(couriers[0]?.id||''))}).finally(()=>setLoading(false))}
 useEffect(load,[store])
 useEffect(()=>()=>{if(watch.current!=null&&typeof navigator!=='undefined')navigator.geolocation.clearWatch(watch.current)},[])
 const mine=useMemo(()=>assignments.filter(x=>x.courier_staff_id===courier&&!['delivered','failed','cancelled'].includes(x.status)),[assignments,courier])
 const myRoutes=useMemo(()=>routes.filter(x=>x.courier_staff_id===courier&&!['completed','cancelled'].includes(x.status)),[routes,courier])
 const active=mine.find(x=>['picked_up','on_route','arrived'].includes(x.status))||mine[0]
 const setStatus=async(x:any,status:string)=>{await api(`/delivery/assignments/${x.id}`,{method:'PATCH',body:JSON.stringify({store_id:store,courier_staff_id:courier,status})});load()}
 const toggleTracking=()=>{
  if(tracking){if(watch.current!=null)navigator.geolocation.clearWatch(watch.current);watch.current=null;setTracking(false);setGeoText('Ubicación detenida');return}
  if(!navigator.geolocation){setGeoText('Este dispositivo no ofrece geolocalización');return}
  setGeoText('Solicitando ubicación…')
  watch.current=navigator.geolocation.watchPosition(async pos=>{setTracking(true);setGeoText(`Precisión aproximada: ${Math.round(pos.coords.accuracy)} m`);try{await api('/delivery/courier/location',{method:'POST',body:JSON.stringify({store_id:store,courier_staff_id:courier,assignment_id:active?.id||'',latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy_meters:pos.coords.accuracy})})}catch{}},err=>{setTracking(false);setGeoText(err.message||'No se pudo obtener la ubicación')},{enableHighAccuracy:true,maximumAge:10000,timeout:15000})
 }
 return <StoreShell title="Modo repartidor" subtitle="Entregas, rutas y ubicación operativa desde una interfaz móvil" context={<StoreSelector value={store} onChange={setStore}/>} actions={courier?<button className={tracking?'btn-primary':'btn-secondary'} onClick={toggleTracking}><LocateFixed className="h-4 w-4"/>{tracking?'Compartiendo ubicación':'Iniciar ubicación'}</button>:null}>
 {!store?<PageEmpty title="Selecciona un negocio" detail="Elige la tienda para abrir el modo repartidor."/>:loading?<Loading/>:<div className="space-y-5">
  <section className="card p-4 sm:p-5"><div className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><div><label className="label">Repartidor</label><div className="relative"><select className="field" value={courier} onChange={e=>setCourier(e.target.value)}><option value="">Selecciona un repartidor</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name} {x.last_name||''}</option>)}</select><UserRound className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9aa0b4]"/></div></div><div className={`rounded-2xl px-4 py-3 text-xs ${tracking?'bg-emerald-50 text-emerald-700':'bg-[#f7f9fc] text-[#8d92aa]'}`}>{geoText||'La ubicación solo se comparte cuando la activas.'}</div></div></section>
  {!courier?<PageEmpty title="No hay repartidor seleccionado" detail="Crea usuarios con rol Repartidor desde Usuarios y selecciónalo aquí."/>:<>
   {myRoutes.length>0&&<section className="card overflow-hidden"><div className="border-b border-[#edf0f5] p-4"><div className="flex items-center gap-2"><Route className="h-4 w-4 text-brand-600"/><h2 className="font-semibold">Ruta activa</h2></div></div><div className="divide-y divide-[#edf0f5]">{myRoutes.map(x=><div key={x.id} className="flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Navigation className="h-4 w-4"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong>{x.name}</strong><Status value={x.status}/></div><p className="mt-1 text-xs text-[#8d92aa]">{x.stops_count} paradas · {Number(x.total_distance_km||0).toFixed(1)} km · {x.estimated_minutes||0} min</p></div></div>)}</div></section>}
   <section className="card overflow-hidden"><div className="border-b border-[#edf0f5] p-4"><div className="flex items-center gap-2"><Truck className="h-4 w-4 text-brand-600"/><h2 className="font-semibold">Mis entregas</h2></div><p className="mt-1 text-xs text-[#8d92aa]">Actualiza el progreso sin entrar al panel administrativo completo.</p></div>{mine.length?<div className="divide-y divide-[#edf0f5]">{mine.map(x=><article key={x.id} className="p-4"><div className="flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-brand-50 text-brand-600"><PackageCheck className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong>#{x.order_number} · {x.customer_name}</strong><Status value={x.status}/></div><p className="mt-1 text-xs text-[#8d92aa]">{x.delivery_address||'Dirección pendiente'} {x.reference?`· ${x.reference}`:''}</p><div className="mt-2 flex flex-wrap items-center gap-2 text-xs"><strong className="text-brand-700">{money(x.total)}</strong><span className="text-[#9aa0b4]">{x.payment_method} · {x.payment_status}</span></div>{x.latitude!=null&&<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${x.latitude},${x.longitude}`} className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-brand-700"><MapPin className="h-3.5 w-3.5"/>Abrir destino</a>}</div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{x.status==='assigned'&&<button className="btn-secondary justify-center" onClick={()=>setStatus(x,'accepted')}>Aceptar</button>}{['assigned','accepted'].includes(x.status)&&<button className="btn-secondary justify-center" onClick={()=>setStatus(x,'picked_up')}>Recogido</button>}{['accepted','picked_up'].includes(x.status)&&<button className="btn-primary justify-center" onClick={()=>setStatus(x,'on_route')}>En camino</button>}{x.status==='on_route'&&<button className="btn-secondary justify-center" onClick={()=>setStatus(x,'arrived')}>Llegué</button>}{['on_route','arrived'].includes(x.status)&&<button className="btn-primary justify-center" onClick={()=>setStatus(x,'delivered')}>Entregado</button>}</div></article>)}</div>:<PageEmpty title="No tienes entregas pendientes" detail="Las asignaciones aparecerán aquí cuando se asigne este repartidor."/>}</section>
  </>}
 </div>}
 </StoreShell>
}
