http:
  routers:
    wamercio-http-file:
      rule: "Host(`wamercio.com`) || Host(`www.wamercio.com`)"
      entryPoints:
        - web
      service: wamercio-file-service
      priority: 1000

    wamercio-https-file:
      rule: "Host(`wamercio.com`) || Host(`www.wamercio.com`)"
      entryPoints:
        - websecure
      service: wamercio-file-service
      priority: 1000
      tls:
        certResolver: letsencrypt

  services:
    wamercio-file-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://wamercio-web:3000"
