'use client'

import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime,money} from '@/lib/api'
import {Alert,Loading,Modal,PageEmpty} from '@/components/ui'
import {ArrowDownCircle,ArrowUpCircle,Banknote,History,LockKeyhole,MinusCircle,Plus,ReceiptText,WalletCards} from 'lucide-react'

type Branch={id:string;name:string;is_active:boolean;is_primary:boolean}
type CashSummary={branch_id:string;branch_name:string;open:boolean;session_id?:string;opening_amount?:number;sales_cash?:number;cash_in?:number;cash_out?:number;expenses?:number;delivery_remittances?:number;refunds?:number;expected_amount?:number;opened_at?:string;movements?:Array<{id:string;type:string;amount:number;signed_amount:number;description:string;created_at:string;order_id:string}>}
type CashSession={id:string;branch_id:string;branch_name:string;opening_amount:number;closing_amount?:number|null;expected_amount?:number|null;difference?:number|null;status:string;notes:string;opened_at:string;closed_at?:string|null;opened_by:string;closed_by:string}

const movementLabels:Record<string,string>={sale_cash:'Venta en efectivo',cash_in:'Entrada de efectivo',cash_out:'Retiro de efectivo',expense:'Gasto',delivery_remittance:'Liquidación de delivery',refund:'Reembolso'}

export default function CashPage(){
 const[store,setStore]=useState(''),[branches,setBranches]=useState<Branch[]>([]),[branch,setBranch]=useState(''),[summary,setSummary]=useState<CashSummary|null>(null),[sessions,setSessions]=useState<CashSession[]>([]),[loading,setLoading]=useState(false),[err,setErr]=useState(''),[msg,setMsg]=useState('')
 const[openModal,setOpenModal]=useState(false),[opening,setOpening]=useState(0),[openingNotes,setOpeningNotes]=useState('')
 const[movementOpen,setMovementOpen]=useState(false),[movementType,setMovementType]=useState<'cash_in'|'cash_out'|'expense'|'refund'>('cash_in'),[movementAmount,setMovementAmount]=useState(0),[movementDescription,setMovementDescription]=useState('')
 const[closeOpen,setCloseOpen]=useState(false),[closing,setClosing]=useState(0),[closeNotes,setCloseNotes]=useState(''),[busy,setBusy]=useState(false)
 const loadBase=async()=>{if(!store){setBranches([]);setBranch('');setSummary(null);setSessions([]);return};setLoading(true);setErr('');try{const [b,s]=await Promise.all([api<Branch[]>(`/branches?store_id=${store}`),api<CashSession[]>(`/cash/sessions?store_id=${store}`)]);setBranches(b.filter(x=>x.is_active));setSessions(s);const current=branch&&b.some(x=>x.id===branch)?branch:(b.find(x=>x.is_primary&&x.is_active)?.id||b.find(x=>x.is_active)?.id||'');setBranch(current);if(current)setSummary(await api<CashSummary>(`/cash/summary?store_id=${store}&branch_id=${current}`));else setSummary(null)}catch(e:any){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void loadBase()},[store])
 useEffect(()=>{if(!store||!branch)return;setLoading(true);api<CashSummary>(`/cash/summary?store_id=${store}&branch_id=${branch}`).then(setSummary).catch((e:any)=>setErr(e.message)).finally(()=>setLoading(false))},[branch])
 const refresh=async()=>{if(!store)return;const [s,h]=await Promise.all([api<CashSummary>(`/cash/summary?store_id=${store}&branch_id=${branch}`),api<CashSession[]>(`/cash/sessions?store_id=${store}`)]);setSummary(s);setSessions(h)}
 const openCash=async(e:React.FormEvent)=>{e.preventDefault();if(!branch)return;setBusy(true);setErr('');try{await api('/cash/sessions/open',{method:'POST',body:JSON.stringify({store_id:store,branch_id:branch,opening_amount:Number(opening||0),notes:openingNotes})});setOpenModal(false);setOpening(0);setOpeningNotes('');setMsg('Caja abierta correctamente.');await refresh()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const addMovement=async(e:React.FormEvent)=>{e.preventDefault();if(!summary?.session_id)return;setBusy(true);setErr('');try{await api(`/cash/sessions/${summary.session_id}/movements`,{method:'POST',body:JSON.stringify({store_id:store,type:movementType,amount:Number(movementAmount||0),description:movementDescription})});setMovementOpen(false);setMovementAmount(0);setMovementDescription('');setMsg('Movimiento registrado.');await refresh()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const closeCash=async(e:React.FormEvent)=>{e.preventDefault();if(!summary?.session_id)return;setBusy(true);setErr('');try{const r:any=await api(`/cash/sessions/${summary.session_id}/close`,{method:'POST',body:JSON.stringify({store_id:store,closing_amount:Number(closing||0),notes:closeNotes})});setCloseOpen(false);setCloseNotes('');setMsg(`Caja cerrada. Diferencia: ${money(r.difference)}.`);await refresh()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 const expected=Number(summary?.expected_amount||0)
 const movementCards=useMemo(()=>[
  {label:'Fondo inicial',value:Number(summary?.opening_amount||0),icon:WalletCards},
  {label:'Ventas efectivo',value:Number(summary?.sales_cash||0),icon:ReceiptText},
  {label:'Liquidaciones',value:Number(summary?.delivery_remittances||0),icon:Banknote},
  {label:'Entradas',value:Number(summary?.cash_in||0),icon:ArrowDownCircle},
  {label:'Retiros + gastos',value:Number(summary?.cash_out||0)+Number(summary?.expenses||0)+Number(summary?.refunds||0),icon:ArrowUpCircle},
 ],[summary])
 return <StoreShell title="Caja" subtitle="Aperturas, movimientos, cierres y efectivo de delivery" context={<StoreSelector value={store} onChange={setStore}/>} actions={summary?.open?<button className="btn-primary" onClick={()=>{setClosing(expected);setCloseOpen(true)}}><LockKeyhole className="h-4 w-4"/>Cerrar caja</button>:store&&branch?<button className="btn-primary" onClick={()=>setOpenModal(true)}><Plus className="h-4 w-4"/>Abrir caja</button>:null}>
  {!store?<PageEmpty title="Selecciona un negocio" detail="Elige el negocio para gestionar la caja."/>:loading&&!summary?<Loading/>:branches.length===0?<PageEmpty title="Crea una sucursal primero" detail="La caja se abre por sucursal para mantener cada operación separada." action={<a href="/branches" className="btn-primary">Ir a sucursales</a>}/>:<div className="space-y-5">{err&&<Alert text={err}/>} {msg&&<Alert text={msg} type="success"/>}<section className="card p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="section-kicker">SUCURSAL OPERATIVA</p><h2 className="mt-1 text-lg font-semibold">{summary?.branch_name||'Selecciona una sucursal'}</h2></div><select className="field max-w-sm" value={branch} onChange={e=>setBranch(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}{b.is_primary?' · Principal':''}</option>)}</select></div></section>
   {!summary?.open?<section className="rounded-[28px] border border-dashed border-[#d9e4de] bg-white p-10 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-brand-50 text-brand-700"><WalletCards className="h-7 w-7"/></span><h2 className="mt-4 text-xl font-semibold">Caja cerrada</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-[#8a918c]">Abre un turno antes de cobrar ventas en efectivo. WAMERCIO mantendrá el fondo, ventas, entradas, retiros, gastos y liquidaciones en un mismo cierre.</p><button className="btn-primary mt-5" onClick={()=>setOpenModal(true)}><Plus className="h-4 w-4"/>Abrir caja</button></section>:<>
    <section className="rounded-[28px] border border-brand-100 bg-brand-50/45 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end"><div className="min-w-0 flex-1"><p className="section-kicker">CAJA ABIERTA</p><h2 className="mt-1 text-2xl font-semibold">{money(expected)}</h2><p className="mt-1 text-sm text-[#738078]">Efectivo esperado en caja · abierta {summary.opened_at?dateTime(summary.opened_at):''}</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>{setMovementType('cash_in');setMovementOpen(true)}}><ArrowDownCircle className="h-4 w-4"/>Entrada</button><button className="btn-secondary" onClick={()=>{setMovementType('cash_out');setMovementOpen(true)}}><MinusCircle className="h-4 w-4"/>Retiro</button><button className="btn-secondary" onClick={()=>{setMovementType('expense');setMovementOpen(true)}}><ReceiptText className="h-4 w-4"/>Gasto</button></div></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{movementCards.map(({label,value,icon:I})=><div key={label} className="card p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-50 text-brand-700"><I className="h-4 w-4"/></span><div className="mt-3 text-xl font-semibold">{money(value)}</div><div className="mt-1 text-xs text-[#8d92aa]">{label}</div></div>)}</div>
    <section className="card overflow-hidden"><div className="flex items-center gap-3 border-b border-[#edf0f5] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><History className="h-4 w-4"/></span><div><h2 className="font-semibold">Movimientos del turno</h2><p className="mt-1 text-xs text-[#8d92aa]">Toda entrada o salida queda trazada antes del cierre.</p></div></div>{summary.movements?.length?<div className="divide-y divide-[#edf0f5]">{summary.movements.map(m=><div key={m.id} className="flex items-center gap-3 p-4"><span className={`grid h-9 w-9 place-items-center rounded-xl ${m.signed_amount>=0?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{m.signed_amount>=0?<ArrowDownCircle className="h-4 w-4"/>:<ArrowUpCircle className="h-4 w-4"/>}</span><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{movementLabels[m.type]||m.type}</div><div className="truncate text-[11px] text-[#9298ad]">{m.description||'Sin descripción'} · {dateTime(m.created_at)}</div></div><strong className={m.signed_amount>=0?'text-emerald-700':'text-rose-600'}>{m.signed_amount>=0?'+':'−'} {money(Math.abs(m.amount))}</strong></div>)}</div>:<div className="p-10 text-center text-sm text-[#9aa0b4]">Aún no hay movimientos en este turno.</div>}</section>
   </>}
   <section className="card overflow-hidden"><div className="border-b border-[#edf0f5] p-5"><h2 className="font-semibold">Historial de cierres</h2><p className="mt-1 text-sm text-[#8d92aa]">Revisa diferencias y montos contados de turnos anteriores.</p></div>{sessions.filter(s=>s.branch_id===branch&&s.status==='closed').length?<div className="divide-y divide-[#edf0f5]">{sessions.filter(s=>s.branch_id===branch&&s.status==='closed').slice(0,12).map(s=><div key={s.id} className="grid gap-2 p-4 sm:grid-cols-[1.2fr_1fr_1fr_1fr]"><div><div className="text-sm font-semibold">{dateTime(s.opened_at)}</div><div className="text-[11px] text-[#9399ab]">{s.opened_by}</div></div><div><span className="text-[10px] uppercase text-[#9ba0b2]">Esperado</span><div className="font-semibold">{money(s.expected_amount||0)}</div></div><div><span className="text-[10px] uppercase text-[#9ba0b2]">Contado</span><div className="font-semibold">{money(s.closing_amount||0)}</div></div><div><span className="text-[10px] uppercase text-[#9ba0b2]">Diferencia</span><div className={`font-semibold ${Number(s.difference||0)<0?'text-rose-600':Number(s.difference||0)>0?'text-amber-600':'text-emerald-700'}`}>{money(s.difference||0)}</div></div></div>)}</div>:<div className="p-8 text-center text-sm text-[#9aa0b4]">Todavía no hay cierres para esta sucursal.</div>}</section>
  </div>}
  <Modal open={openModal} onClose={()=>setOpenModal(false)} title="Abrir caja" subtitle="Indica cuánto efectivo hay físicamente al iniciar el turno."><form onSubmit={openCash} className="space-y-4"><div><label className="label">Fondo inicial</label><input autoFocus className="field" type="number" min="0" step="0.01" value={opening} onChange={e=>setOpening(Number(e.target.value))}/></div><div><label className="label">Nota</label><textarea className="field min-h-24" value={openingNotes} onChange={e=>setOpeningNotes(e.target.value)} placeholder="Opcional"/></div><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpenModal(false)}>Cancelar</button><button disabled={busy} className="btn-primary">{busy?'Abriendo...':'Abrir turno'}</button></div></form></Modal>
  <Modal open={movementOpen} onClose={()=>setMovementOpen(false)} title={movementType==='cash_in'?'Entrada de efectivo':movementType==='cash_out'?'Retiro de efectivo':movementType==='expense'?'Registrar gasto':'Registrar reembolso'} subtitle="El movimiento se aplicará al turno de caja actual."><form onSubmit={addMovement} className="space-y-4"><div><label className="label">Monto</label><input autoFocus className="field" type="number" min="0.01" step="0.01" required value={movementAmount||''} onChange={e=>setMovementAmount(Number(e.target.value))}/></div><div><label className="label">Descripción</label><input className="field" required value={movementDescription} onChange={e=>setMovementDescription(e.target.value)} placeholder="Motivo del movimiento"/></div><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setMovementOpen(false)}>Cancelar</button><button disabled={busy} className="btn-primary">Registrar</button></div></form></Modal>
  <Modal open={closeOpen} onClose={()=>setCloseOpen(false)} title="Cerrar caja" subtitle={`El sistema espera ${money(expected)}. Cuenta el efectivo antes de confirmar.`}><form onSubmit={closeCash} className="space-y-4"><div className="rounded-2xl bg-[#f8fafb] p-4"><div className="text-xs text-[#8d92aa]">Esperado</div><div className="mt-1 text-2xl font-semibold">{money(expected)}</div></div><div><label className="label">Efectivo contado</label><input autoFocus className="field" type="number" min="0" step="0.01" value={closing} onChange={e=>setClosing(Number(e.target.value))}/><p className={`mt-2 text-sm font-semibold ${closing-expected<0?'text-rose-600':closing-expected>0?'text-amber-600':'text-emerald-700'}`}>Diferencia: {money(closing-expected)}</p></div><div><label className="label">Nota de cierre</label><textarea className="field min-h-24" value={closeNotes} onChange={e=>setCloseNotes(e.target.value)} placeholder="Opcional"/></div><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setCloseOpen(false)}>Cancelar</button><button disabled={busy} className="btn-primary">Confirmar cierre</button></div></form></Modal>
 </StoreShell>
}
