'use client'
import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api} from '@/lib/api'
import {Alert,Loading,PageEmpty} from '@/components/ui'
import {Banknote,Landmark,CreditCard,Save,Truck,Store as StoreIcon,UtensilsCrossed,Check,Plus,Copy,Trash2,Pencil,Building2,X,FileCheck2} from 'lucide-react'

type PaymentMethod='cash'|'cash_on_delivery'|'bank_transfer'|'cheque'
type Fulfillment='delivery'|'pickup'|'dine_in'
type Rules=Record<Fulfillment,Record<PaymentMethod,boolean>>
const methods:PaymentMethod[]=['cash','cash_on_delivery','bank_transfer','cheque']
const methodMeta:Record<PaymentMethod,{label:string;detail:string;icon:any}>={cash:{label:'Efectivo',detail:'Pagar al recibir o retirar.',icon:Banknote},cash_on_delivery:{label:'Tarjeta en terminal',detail:'Cobro mediante terminal física.',icon:CreditCard},bank_transfer:{label:'Transferencia bancaria',detail:'Muestra las cuentas activas para elegir.',icon:Landmark},cheque:{label:'Cheque',detail:'Disponible únicamente cuando el negocio lo autoriza.',icon:FileCheck2}}
function normalizeRules(settings:any):Rules{const raw=settings?.payment_methods_by_fulfillment||{};const globals:any={cash:!!settings?.cash_enabled,cash_on_delivery:!!settings?.cash_on_delivery_enabled,bank_transfer:!!settings?.bank_transfer_enabled,cheque:!!settings?.cheque_enabled};const out:any={};for(const mode of ['delivery','pickup','dine_in'] as Fulfillment[]){out[mode]={};for(const method of methods)out[mode][method]=typeof raw?.[mode]?.[method]==='boolean'?raw[mode][method]:globals[method]}return out}

function Toggle({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void}){return <button type="button" aria-pressed={checked} onClick={()=>onChange(!checked)} className={`relative h-6 w-11 shrink-0 rounded-full transition ${checked?'bg-brand-500':'bg-slate-200'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition ${checked?'left-6':'left-1'}`}/></button>}

export default function PaymentMethods(){
 const[store,setStore]=useState(''),[tab,setTab]=useState<'methods'|'accounts'>('methods'),[data,setData]=useState<any>(null),[banks,setBanks]=useState<any[]>([]),[accounts,setAccounts]=useState<any[]>([]),[loading,setLoading]=useState(false),[err,setErr]=useState(''),[saved,setSaved]=useState(false),[modal,setModal]=useState(false),[editing,setEditing]=useState<any>(null),[account,setAccount]=useState<any>({bank_id:'',bank_name:'',account_type:'Corriente',account_number:'',account_holder:'',is_active:true})
 const load=async()=>{if(!store){setData(null);return};setLoading(true);setErr('');try{const[settings,bankRows,accountRows]=await Promise.all([api(`/stores/${store}/settings`),api<any[]>('/banks'),api<any[]>(`/bank-accounts?store_id=${store}`)]);setData({...settings,payment_methods_by_fulfillment:normalizeRules(settings)});setBanks(bankRows);setAccounts(accountRows)}catch(e:any){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[store])
 const globals=useMemo<any>(()=>({cash:!!data?.cash_enabled,cash_on_delivery:!!data?.cash_on_delivery_enabled,bank_transfer:!!data?.bank_transfer_enabled,cheque:!!data?.cheque_enabled}),[data])
 const fulfillments=useMemo(()=>data?([data.delivery_enabled?{key:'delivery' as Fulfillment,label:'Delivery',icon:Truck}:null,data.pickup_enabled?{key:'pickup' as Fulfillment,label:'Recoger',icon:StoreIcon}:null,data.dine_in_enabled?{key:'dine_in' as Fulfillment,label:'Mesa',icon:UtensilsCrossed}:null].filter(Boolean) as any[]):[],[data])
 const save=async()=>{setErr('');setSaved(false);try{await api(`/stores/${store}/settings`,{method:'PUT',body:JSON.stringify(data)});setSaved(true);await load();window.dispatchEvent(new CustomEvent('wamercio:store-settings-changed',{detail:{store_id:store}}))}catch(e:any){setErr(e.message)}}
 const toggleGlobal=(method:PaymentMethod,v:boolean)=>setData({...data,[method==='cash'?'cash_enabled':method==='cash_on_delivery'?'cash_on_delivery_enabled':method==='bank_transfer'?'bank_transfer_enabled':'cheque_enabled']:v})
 const setRule=(mode:Fulfillment,method:PaymentMethod,value:boolean)=>setData((current:any)=>({...current,payment_methods_by_fulfillment:{...normalizeRules(current),[mode]:{...normalizeRules(current)[mode],[method]:value}}}))
 const openAccount=(row?:any)=>{setEditing(row||null);setAccount(row?{...row}:{bank_id:'',bank_name:'',account_type:'Corriente',account_number:'',account_holder:'',is_active:true});setModal(true)}
 const saveAccount=async()=>{try{await api(editing?`/bank-accounts/${editing.id}?store_id=${store}`:`/bank-accounts?store_id=${store}`,{method:editing?'PUT':'POST',body:JSON.stringify(account)});setModal(false);await load()}catch(e:any){setErr(e.message)}}
 const delAccount=async(id:string)=>{if(!confirm('¿Eliminar esta cuenta bancaria?'))return;try{await api(`/bank-accounts/${id}?store_id=${store}`,{method:'DELETE'});await load()}catch(e:any){setErr(e.message)}}
 return <StoreShell title="Métodos de pago" subtitle="Configura las formas de pago y las cuentas para recibir el dinero de tu negocio" context={<StoreSelector value={store} onChange={setStore}/>} actions={tab==='accounts'?<button disabled={!store} onClick={()=>openAccount()} className="btn-primary"><Plus className="h-4 w-4"/> Registrar cuenta</button>:<button disabled={!store||!data} onClick={save} className="btn-primary"><Save className="h-4 w-4"/> Guardar cambios</button>}>
  {!store?<PageEmpty title="Selecciona un negocio" detail="Elige la tienda donde configurarás las formas de pago."/>:loading?<Loading/>:data&&<div className="space-y-5">{err&&<Alert text={err}/>} {saved&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-medium text-emerald-700">Configuración de pagos actualizada.</div>}
   <div className="flex justify-end"><div className="inline-flex rounded-2xl bg-[#f1f2f5] p-1"><button onClick={()=>setTab('methods')} className={`rounded-xl px-5 py-2.5 text-xs font-semibold ${tab==='methods'?'bg-brand-500 text-white shadow-sm':'text-[#747a92]'}`}><CreditCard className="mr-2 inline h-4 w-4"/>Métodos</button><button onClick={()=>setTab('accounts')} className={`rounded-xl px-5 py-2.5 text-xs font-semibold ${tab==='accounts'?'bg-brand-500 text-white shadow-sm':'text-[#747a92]'}`}><Building2 className="mr-2 inline h-4 w-4"/>Cuentas</button></div></div>
   {tab==='methods'?<>
    <section className="card overflow-hidden"><div className="border-b border-[#edf0f4] p-5"><h2 className="font-semibold">Métodos disponibles para el cliente</h2><p className="mt-1 text-xs text-[#8d92aa]">Los métodos activos se mostrarán al completar el pedido.</p></div><div className="grid gap-3 p-5 md:grid-cols-2">{methods.map(method=>{const m=methodMeta[method],I=m.icon;return <article key={method} className="flex items-start gap-4 rounded-2xl border border-[#edf0f4] p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#fafbfc] text-brand-600"><I className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{m.label}</h3>{method==='bank_transfer'&&accounts.length>0&&<span className="rounded-full bg-brand-50 px-2 py-1 text-[9px] font-semibold text-brand-700">{accounts.filter(a=>a.is_active).length} cuentas activas</span>}{method==='cheque'&&<span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-semibold text-amber-700">Requiere autorización</span>}</div><p className="mt-1 text-xs text-[#8d92aa]">{m.detail}</p></div><Toggle checked={globals[method]} onChange={v=>toggleGlobal(method,v)}/></article>})}</div></section>
    <section className="card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="section-kicker">Liquidación bancaria</p><h2 className="section-title">Cuentas asociadas a cobros</h2><p className="section-copy">Elige una cuenta principal para transferencias y otra para conciliar terminales.</p></div><button className="btn-secondary" onClick={()=>setTab('accounts')}>Administrar cuentas</button></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-[#edf0f4] p-4"><label className="label">Cuenta principal para transferencias</label><select className="field" value={data.transfer_account_id||''} onChange={e=>setData({...data,transfer_account_id:e.target.value})}><option value="">Sin cuenta principal</option>{accounts.filter(a=>a.is_active).map(a=><option key={a.id} value={a.id}>{a.bank_short_name||a.bank_name} · {a.account_number}</option>)}</select></div><div className="rounded-2xl border border-[#edf0f4] p-4"><label className="label">Cuenta vinculada a terminal</label><select className="field" value={data.terminal_account_id||''} onChange={e=>setData({...data,terminal_account_id:e.target.value})}><option value="">Sin cuenta vinculada</option>{accounts.filter(a=>a.is_active).map(a=><option key={a.id} value={a.id}>{a.bank_short_name||a.bank_name} · {a.account_number}</option>)}</select><div className="mt-3 grid grid-cols-2 gap-3"><div><label className="label">Comisión %</label><input type="number" min="0" step="0.01" className="field" value={data.terminal_percentage_fee||0} onChange={e=>setData({...data,terminal_percentage_fee:Number(e.target.value)})}/></div><div><label className="label">Fijo RD$</label><input type="number" min="0" step="0.01" className="field" value={data.terminal_fixed_fee||0} onChange={e=>setData({...data,terminal_fixed_fee:Number(e.target.value)})}/></div></div></div></div></section>
    <section className="card p-5"><h2 className="font-semibold">Disponibilidad por modalidad</h2><p className="mt-1 text-sm text-[#8d92aa]">Controla qué opciones aparecen en Delivery, Recoger y Mesa.</p>{fulfillments.length?<div className="mt-5 grid gap-4 xl:grid-cols-3">{fulfillments.map(mode=>{const I=mode.icon;const rules=normalizeRules(data)[mode.key];return <article key={mode.key} className="rounded-2xl border border-[#edf0f4] p-4"><div className="flex items-center gap-3"><I className="h-5 w-5 text-brand-600"/><h3 className="font-semibold">{mode.label}</h3></div><div className="mt-4 space-y-2">{methods.map(method=><button key={method} disabled={!globals[method]} onClick={()=>setRule(mode.key,method,!rules[method])} className={`flex w-full items-center gap-3 rounded-xl border px-3 py-2.5 text-left ${globals[method]?'bg-white':'cursor-not-allowed bg-slate-50 opacity-50'}`}><span className={`grid h-6 w-6 place-items-center rounded-lg border ${rules[method]&&globals[method]?'border-brand-500 bg-brand-500 text-white':'text-transparent'}`}><Check className="h-3.5 w-3.5"/></span><span className="text-sm font-medium">{methodMeta[method].label}</span></button>)}</div></article>})}</div>:null}</section>
   </>:<><div><h2 className="text-lg font-semibold">Cuentas bancarias</h2><p className="mt-1 text-sm text-[#8d92aa]">Configura todas las cuentas disponibles para pagos por transferencia.</p></div>{accounts.length?<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{accounts.map(a=><article key={a.id} className="card overflow-hidden"><div className="flex items-center gap-3 border-b border-[#edf0f4] p-4">{a.bank_logo_url?<img src={a.bank_logo_url} className="h-9 w-14 object-contain"/>:<span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-50 text-brand-600"><Building2 className="h-4 w-4"/></span>}<div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{a.bank_short_name||a.bank_name}</div></div><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${a.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{a.is_active?'ACTIVA':'INACTIVA'}</span></div><div className="p-4"><div className="text-[10px] font-semibold uppercase text-[#9ba0b4]">Número de cuenta</div><div className="mt-1 flex items-center justify-between gap-2"><strong className="break-all text-sm">{a.account_number}</strong><button onClick={()=>navigator.clipboard.writeText(a.account_number)} className="rounded-xl bg-[#f6f7f9] p-2"><Copy className="h-3.5 w-3.5"/></button></div><div className="mt-4 text-[10px] font-semibold uppercase text-[#9ba0b4]">Titular</div><div className="mt-1 text-xs font-semibold">{a.account_holder}</div><div className="mt-3 text-xs text-[#8d92aa]">{a.account_type}</div></div><div className="grid grid-cols-2 border-t border-[#edf0f4]"><button onClick={()=>openAccount(a)} className="flex items-center justify-center gap-2 p-3 text-xs font-semibold hover:bg-[#fafbfc]"><Pencil className="h-3.5 w-3.5"/>Editar</button><button onClick={()=>delAccount(a.id)} className="flex items-center justify-center gap-2 border-l border-[#edf0f4] p-3 text-xs font-semibold text-rose-600 hover:bg-rose-50"><Trash2 className="h-3.5 w-3.5"/>Eliminar</button></div></article>)}</section>:<PageEmpty title="Sin cuentas bancarias" detail="Registra la primera cuenta para mostrarla a clientes que paguen por transferencia."/>}</>}
  </div>}
  {modal&&<div className="fixed inset-0 z-[80] grid place-items-center bg-[#20233a]/40 p-3"><section className="w-full max-w-lg rounded-3xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-[#edf0f4] px-5 py-4"><h2 className="text-lg font-semibold">{editing?'Editar cuenta':'Nueva cuenta'}</h2><button className="rounded-xl bg-[#f6f7f9] p-2" onClick={()=>setModal(false)}><X className="h-5 w-5"/></button></header><div className="space-y-4 p-5"><div><label className="label">Banco</label><select className="field" value={account.bank_id||''} onChange={e=>setAccount({...account,bank_id:e.target.value})}><option value="">Selecciona un banco del catálogo</option>{banks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Tipo de cuenta</label><select className="field" value={account.account_type} onChange={e=>setAccount({...account,account_type:e.target.value})}><option>Corriente</option><option>Ahorros</option><option>Nómina</option></select></div><div className="flex items-end"><label className="flex w-full items-center gap-2 rounded-xl bg-[#f7f8fa] p-3 text-sm"><input type="checkbox" checked={!!account.is_active} onChange={e=>setAccount({...account,is_active:e.target.checked})}/> Activa</label></div></div><div><label className="label">Número de cuenta</label><input className="field" value={account.account_number} onChange={e=>setAccount({...account,account_number:e.target.value})}/></div><div><label className="label">Titular de la cuenta</label><input className="field" placeholder="Nombre como aparece en el banco" value={account.account_holder} onChange={e=>setAccount({...account,account_holder:e.target.value})}/></div></div><footer className="flex justify-end gap-2 border-t border-[#edf0f4] p-4"><button className="btn-secondary" onClick={()=>setModal(false)}>Cancelar</button><button className="btn-primary" onClick={saveAccount}>{editing?'Guardar cambios':'Registrar cuenta'}</button></footer></section></div>}
 </StoreShell>
}
