"use client";
import {useMemo,useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {api,money} from "@/lib/api";
import {Trash2,MapPinned,Loader2,ShieldCheck,Map,Plus} from "lucide-react";
import {GeofencePreview} from "@/components/geofence-preview";

export default function Delivery(){
 const qc=useQueryClient();const zones=useQuery({queryKey:['zones'],queryFn:()=>api<any>('/api/v1/dashboard/delivery-zones')});const geos=useQuery({queryKey:['geo-geofences'],queryFn:()=>api<any>('/api/v1/dashboard/geo/geofences?serviceType=delivery')});
 const[selected,setSelected]=useState('');const[detail,setDetail]=useState<any>(null);const[fee,setFee]=useState(0);const[priority,setPriority]=useState(100);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const available=useMemo(()=>{const used=new Set((zones.data?.zones||[]).map((z:any)=>z.GeoGeofenceID).filter(Boolean));return (geos.data?.geofences||[]).filter((g:any)=>!used.has(g.id)||g.id===selected)},[geos.data,zones.data,selected]);
 async function choose(id:string){setSelected(id);setDetail(null);setError('');if(!id)return;try{const d=await api<any>(`/api/v1/dashboard/geo/geofences/${encodeURIComponent(id)}`);setDetail(d.geofence)}catch(e:any){setError(e.message)}}
 async function save(){if(!selected)return;setSaving(true);setError('');try{await api('/api/v1/dashboard/delivery-zones/geofence',{method:'POST',body:JSON.stringify({geofence_id:selected,fee,priority})});setSelected('');setDetail(null);setFee(0);setPriority(100);await qc.invalidateQueries({queryKey:['zones']});await qc.invalidateQueries({queryKey:['geo-geofences']})}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function del(id:string){await api(`/api/v1/dashboard/delivery-zones/${id}`,{method:'DELETE'});qc.invalidateQueries({queryKey:['zones']})}
 return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">Delivery</h1><p className="mt-2 text-gray-500">Cobertura y tarifas enlazadas a geocercas reales de GEO RD MAP.</p></div><div className="rounded-2xl bg-green-50 px-4 py-3 text-xs font-bold text-green-700"><ShieldCheck size={16} className="mr-1 inline"/>La API Key geográfica permanece en el backend</div></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_390px]"><section className="rounded-3xl bg-white p-5 shadow-soft"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-orange-50 text-[#ff5400]"><MapPinned/></div><div><h2 className="font-black">Agregar zona de servicio</h2><p className="text-xs text-gray-500">Selecciona una geocerca administrada en GEO RD MAP y define la tarifa del negocio.</p></div></div><div className="mt-5 grid gap-3"><select className="field" value={selected} onChange={e=>choose(e.target.value)}><option value="">Seleccionar geocerca de delivery</option>{available.map((g:any)=><option key={g.id} value={g.id}>{g.name}{g.category?` · ${g.category}`:''}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-gray-600">Tarifa RD$<input className="field mt-1" type="number" min="0" step="0.01" value={fee} onChange={e=>setFee(Number(e.target.value))}/></label><label className="text-xs font-bold text-gray-600">Prioridad<input className="field mt-1" type="number" min="1" value={priority} onChange={e=>setPriority(Number(e.target.value))}/></label></div><button disabled={!selected||saving} onClick={save} className="btn btn-brand w-full">{saving?<Loader2 size={17} className="animate-spin"/>:<Plus size={17}/>} Vincular zona</button>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}</div>{detail&&<div className="mt-5"><GeofencePreview geometry={detail.geometry}/><div className="mt-3 rounded-2xl bg-slate-50 p-4 text-sm"><div className="font-black">{detail.name}</div>{detail.description&&<p className="mt-1 text-gray-500">{detail.description}</p>}<div className="mt-2 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white px-3 py-1 font-bold">{detail.category||'Sin categoría'}</span><span className="rounded-full bg-white px-3 py-1 font-bold">{detail.serviceType||'delivery'}</span><span className="rounded-full bg-green-100 px-3 py-1 font-bold text-green-700">Activa</span></div></div></div>}</section>
 <aside className="rounded-3xl bg-[#212529] p-5 text-white shadow-soft"><Map className="text-[#ff5400]"/><h2 className="mt-3 text-xl font-black">Cómo se calcula</h2><ol className="mt-4 space-y-4 text-sm text-white/70"><li><b className="text-white">1. Ubicación exacta.</b><br/>El cliente selecciona dirección o GPS.</li><li><b className="text-white">2. GEO RD MAP.</b><br/>Se consulta qué geocercas contienen el punto.</li><li><b className="text-white">3. wamercio.</b><br/>Se cruza la geocerca con las zonas habilitadas por este negocio.</li><li><b className="text-white">4. Routing.</b><br/>Se calcula distancia y ETA desde el negocio hasta el cliente.</li></ol></aside></div>
 <h2 className="mt-8 text-xl font-black">Zonas configuradas</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{zones.isLoading&&<div className="text-sm text-gray-400">Cargando...</div>}{(zones.data?.zones||[]).map((z:any)=><div key={z.ID} className="rounded-2xl bg-white p-5 shadow-soft"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-orange-50 text-[#ff5400]"><MapPinned size={20}/></div>{z.GeoGeofenceID&&<span className="rounded-full bg-green-50 px-3 py-1 text-[11px] font-black text-green-700">GEO RD MAP</span>}</div><h3 className="mt-3 font-black">{z.Name}</h3><div className="mt-1 text-2xl font-black">{money(z.Fee)}</div><div className="mt-2 text-xs text-gray-400">Prioridad {z.Priority||100} · {z.ServiceType||'delivery'}</div>{z.GeoGeofenceID&&<div className="mt-2 truncate text-[11px] text-gray-400">{z.GeoGeofenceID}</div>}<button onClick={()=>del(z.ID)} className="mt-4 flex items-center gap-2 text-sm font-bold text-red-600"><Trash2 size={16}/>Eliminar</button></div>)}</div>
 </div>
}
