'use client'
import {useEffect,useMemo,useState} from 'react'
import SuperAdminShell from '@/components/superadmin-shell'
import {Alert,Loading,Modal,PageEmpty,SearchBox,Status} from '@/components/ui'
import {api,dateTime} from '@/lib/api'
import type {SupportTicket,TicketMessage} from '@/lib/types'
import {Send} from 'lucide-react'
export default function AdminTickets(){
 const [rows,setRows]=useState<SupportTicket[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<SupportTicket|null>(null),[detail,setDetail]=useState<SupportTicket|null>(null),[reply,setReply]=useState(''),[error,setError]=useState('')
 const load=()=>{setLoading(true);api<SupportTicket[]>(`/admin/tickets?status=${status}`).then(setRows).finally(()=>setLoading(false))}
 useEffect(()=>{load()},[status])
 const filtered=useMemo(()=>rows.filter(x=>`${x.number} ${x.subject} ${x.user_name} ${x.user_email}`.toLowerCase().includes(q.toLowerCase())),[rows,q])
 const view=async(t:SupportTicket)=>{setSelected(t);setError('');setDetail(await api(`/admin/tickets/${t.id}`))}
 const send=async()=>{if(!selected||!reply.trim())return;try{await api(`/admin/tickets/${selected.id}/reply`,{method:'POST',body:JSON.stringify({message:reply})});setReply('');setDetail(await api(`/admin/tickets/${selected.id}`));load()}catch(e:any){setError(e.message)}}
 const changeStatus=async(v:string)=>{if(!selected)return;await api(`/admin/tickets/${selected.id}/status`,{method:'PATCH',body:JSON.stringify({status:v})});setDetail(await api(`/admin/tickets/${selected.id}`));load()}
 return <SuperAdminShell title="Tickets de soporte" subtitle="Centro de ayuda de propietarios WAMERCIO"><div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#f0f1f5] p-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-bold">Solicitudes</h2><p className="text-sm text-[#8d92aa]">Responde, organiza y cierra incidencias.</p></div><div className="flex flex-col gap-2 sm:flex-row"><select className="field" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos</option><option value="open">Abiertos</option><option value="answered">Respondidos</option><option value="closed">Cerrados</option></select><SearchBox value={q} onChange={setQ}/></div></div>{loading?<Loading/>:filtered.length===0?<PageEmpty title="Sin tickets" detail="No hay tickets para este filtro."/>:<div className="overflow-x-auto"><table className="table"><thead><tr><th>#</th><th>Usuario</th><th>Asunto</th><th>Prioridad</th><th>Estado</th><th>Actividad</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id} onClick={()=>view(t)} className="cursor-pointer hover:bg-[#fafbfe]"><td className="font-bold">#{t.number}</td><td><strong className="block">{t.user_name}</strong><span className="text-xs text-[#8d92aa]">{t.user_email}</span></td><td>{t.subject}</td><td>{priorityLabel(t.priority)}</td><td><Status value={t.status}/></td><td className="text-sm text-[#8d92aa]">{dateTime(t.last_reply_at)}</td></tr>)}</tbody></table></div>}</div>
 <Modal open={!!selected} onClose={()=>{setSelected(null);setDetail(null)}} title={detail?`Ticket #${detail.number} · ${detail.subject}`:'Ticket'} wide>{error&&<Alert text={error}/>} {!detail?<Loading/>:<div><div className="mb-4 grid gap-3 rounded-xl bg-[#fafbfe] p-4 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase text-[#a2a6b8]">Cliente</p><strong>{detail.user_name}</strong><p className="text-sm text-[#8d92aa]">{detail.user_email}</p></div><div className="sm:text-right"><Status value={detail.status}/><p className="mt-2 text-xs text-[#8d92aa]">Prioridad {priorityLabel(detail.priority)}</p></div></div><div className="space-y-3">{(detail.messages||[]).map((m:TicketMessage)=><div key={m.id} className={`flex ${m.sender_role==='superadmin'?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-lg px-4 py-3 ${m.sender_role==='superadmin'?'bg-brand-600 text-white':'bg-[#f1f2f6] text-slate-800'}`}><div className="mb-1 text-xs font-semibold opacity-70">{m.sender_role==='superadmin'?'Soporte WAMERCIO':m.sender_name}</div><div className="whitespace-pre-wrap text-sm">{m.message}</div><div className="mt-1 text-[10px] opacity-60">{dateTime(m.created_at)}</div></div></div>)}</div><div className="mt-5 border-t border-[#f0f1f5] pt-4"><textarea className="field min-h-24" placeholder="Responder al cliente..." value={reply} onChange={e=>setReply(e.target.value)}/><div className="mt-3 flex flex-wrap gap-2"><select className="field max-w-44" value={detail.status} onChange={e=>changeStatus(e.target.value)}><option value="open">Abierto</option><option value="answered">Respondido</option><option value="closed">Cerrado</option></select><button className="btn-primary ml-auto" onClick={send}><Send className="h-4 w-4"/> Responder</button></div></div></div>}</Modal></SuperAdminShell>
}
function priorityLabel(v:string){return ({low:'Baja',normal:'Normal',high:'Alta',urgent:'Urgente'} as any)[v]||v}
