'use client'
import {useEffect,useMemo,useState} from 'react'
import StoreShell,{StoreSelector} from '@/components/store-shell'
import {api,dateTime} from '@/lib/api'
import {Alert,Loading,PageEmpty,Switch} from '@/components/ui'
import {Gift,Save,Sparkles,UsersRound} from 'lucide-react'

type Program={is_active:boolean;points_per_currency:number;redemption_value:number;min_redeem:number;accounts:number;points_issued:number;points_redeemed:number}
type Account={id:string;global_customer_id:string;customer_name:string;phone:string;points_balance:number;total_earned:number;total_redeemed:number;updated_at:string}
const empty:Program={is_active:false,points_per_currency:.01,redemption_value:1,min_redeem:100,accounts:0,points_issued:0,points_redeemed:0}
export default function Loyalty(){
 const[store,setStore]=useState(''),[program,setProgram]=useState<Program>(empty),[accounts,setAccounts]=useState<Account[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[ok,setOk]=useState('')
 const load=()=>{if(!store){setAccounts([]);setProgram(empty);return};setLoading(true);setErr('');Promise.all([api<Program>(`/loyalty?store_id=${store}`),api<Account[]>(`/loyalty/accounts?store_id=${store}`)]).then(([p,a])=>{setProgram({...empty,...p});setAccounts(a)}).catch((e:any)=>setErr(e.message)).finally(()=>setLoading(false))}
 useEffect(load,[store])
 const points100=useMemo(()=>Number((program.points_per_currency*100).toFixed(2)),[program.points_per_currency])
 const save=async()=>{setBusy(true);setErr('');setOk('');try{await api('/loyalty',{method:'PUT',body:JSON.stringify({store_id:store,is_active:program.is_active,points_per_currency:program.points_per_currency,redemption_value:program.redemption_value,min_redeem:program.min_redeem})});setOk('Programa de fidelización actualizado.');load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 return <StoreShell title="Fidelización" subtitle="Puntos por compra con saldo auditable por cliente" context={<StoreSelector value={store} onChange={setStore}/>} actions={<button disabled={!store||busy} className="btn-primary" onClick={()=>void save()}><Save className="h-4 w-4"/>Guardar</button>}>
  {!store?<PageEmpty title="Selecciona una tienda" detail="Elige el negocio donde configurarás el programa de puntos."/>:loading?<Loading/>:<div className="space-y-5">{err&&<Alert text={err}/>} {ok&&<Alert text={ok} type="success"/>}
   <div className="grid gap-3 sm:grid-cols-3"><div className="card p-4"><p className="section-kicker">Clientes con puntos</p><p className="mt-1 text-2xl font-semibold">{program.accounts||accounts.length}</p></div><div className="card p-4"><p className="section-kicker">Puntos emitidos</p><p className="mt-1 text-2xl font-semibold">{Number(program.points_issued||0).toLocaleString('es-DO')}</p></div><div className="card p-4"><p className="section-kicker">Puntos canjeados</p><p className="mt-1 text-2xl font-semibold">{Number(program.points_redeemed||0).toLocaleString('es-DO')}</p></div></div>
   <div className="grid gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><section className="card p-5"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Gift className="h-5 w-5"/></span><div><p className="section-kicker">Configuración</p><h2 className="mt-1 text-lg font-semibold">Programa de puntos</h2></div></div><div className="mt-5 space-y-4"><Switch checked={program.is_active} onChange={v=>setProgram({...program,is_active:v})} label="Fidelización activa" detail="Los pedidos completados comenzarán a generar puntos automáticamente."/><div><label className="label">Puntos por cada RD$100</label><input className="field" type="number" min="0" step="0.1" value={points100} onChange={e=>setProgram({...program,points_per_currency:Number(e.target.value||0)/100})}/><p className="mt-1 text-xs text-[#969caf]">Ejemplo: 1 punto por RD$100 equivale a 0.01 punto por peso.</p></div><div><label className="label">Valor de cada punto (RD$)</label><input className="field" type="number" min="0" step="0.01" value={program.redemption_value} onChange={e=>setProgram({...program,redemption_value:Number(e.target.value||0)})}/></div><div><label className="label">Mínimo para canjear</label><input className="field" type="number" min="0" step="1" value={program.min_redeem} onChange={e=>setProgram({...program,min_redeem:Number(e.target.value||0)})}/></div><div className="rounded-2xl border border-brand-100 bg-brand-50/50 p-4 text-xs leading-5 text-brand-800"><Sparkles className="mb-2 h-4 w-4"/>Los puntos se acreditan una sola vez por pedido completado. Los canjes quedan ligados al pedido en un libro mayor que no se reescribe.</div></div></section>
    <section className="card overflow-hidden"><div className="border-b border-[#edf0f4] p-5"><div className="flex items-center gap-3"><UsersRound className="h-5 w-5 text-brand-600"/><div><p className="section-kicker">Clientes</p><h2 className="mt-1 text-lg font-semibold">Saldos de fidelización</h2></div></div></div>{accounts.length?<div className="overflow-x-auto"><table className="table"><thead><tr><th>Cliente</th><th>Saldo</th><th>Ganados</th><th>Canjeados</th><th>Actualizado</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><div className="font-semibold">{a.customer_name||'Cliente'}</div><div className="mt-1 text-xs text-[#969caf]">{a.phone?`+${a.phone}`:'Sin WhatsApp'}</div></td><td><strong className="text-brand-700">{a.points_balance.toLocaleString('es-DO')} pts</strong></td><td>{a.total_earned.toLocaleString('es-DO')}</td><td>{a.total_redeemed.toLocaleString('es-DO')}</td><td className="text-xs">{dateTime(a.updated_at)}</td></tr>)}</tbody></table></div>:<div className="p-12 text-center text-sm text-[#969caf]">Todavía no hay clientes con movimientos de puntos.</div>}</section>
   </div>
  </div>}
 </StoreShell>
}
